### ISSUE TITLE
Update notify hook on slack channel to new repo

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#1762]
#coreruleset-notify still listens to old archived repo.

We think that @fgsch has set this up. Thus assigning to him.

**Comment by dune73** [comment]
Update: It was @lifeforms.

**Comment by airween** [comment]
I [found](https://slack.com/intl/en-hu/help/articles/232289568-GitHub-for-Slack?eu_nc=1) a possible solution.

So these `Slack` commands on the channel should be enough?

```
/github unsubscribe SpiderLabs/owasp-modsecurity-crs issues,pulls,deployments,statuses,public,commits:all,releases,comments,branches,reviews
```
and
```
/github subscribe CoreRuleSet/coreruleset issues,pulls,deployments,statuses,public,commits:all,releases,comments,branches,reviews
```

**Comment by lifeforms** [comment]
Testing with a comment.

**Comment by lifeforms** [comment]
Testing with a comment.

**Comment by lifeforms** [comment]
Test!

**Comment by lifeforms** [comment]
I have added the GitHub app to the repo and used the commands from @airween to get all the notifications! Thanks!
