### ISSUE TITLE
False Positive with rule 932120

### ISSUE THREAD

**Issue by christiantreutler-avi** [coreruleset/coreruleset#1768]
### Description

False Positive with rule 932120

### Audit Logs / Triggered Rule Numbers

Rule 932120 blocks a request with 
args=asset-date-2020

Rule 932120 is looking for powershell commands. But it does not start at the beginning of a new word and so these false positives can happen, where it matches the powershell command set-date.

Would it make sense to match only on start of a new word here?

### Your Environment

* CRS version : 3.2.0
* Paranoia level setting: 1 (low)
* ModSecurity version (e.g., 2.9.3): 3.0.3
* Web Server and version (e.g., apache 2.4.41): Avi
* Operating System and version:

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by christiantreutler-avi** [comment]
Congrats for moving to the new repo! :)

**Comment by ckristhoff** [comment]
> Congrats for moving to the new repo! :)

https://github.com/coreruleset/coreruleset/issues/1775

**Comment by dune73** [comment]
We covered this issue in the [monthly issue chat](https://github.com/coreruleset/coreruleset/issues/1853#issuecomment-668226676). @emphazer volunteered to take this on.
