### ISSUE TITLE
Let's Encrypt SSL certificate generation

### ISSUE THREAD

**Issue by ShopixRo** [coreruleset/coreruleset#1773]
### Description
Output of modsec_audit.log

--dde07d07-A--
[18/May/2020:16:27:44 +0300] XsKNUBSLv@CtAoRchMQbWwAAAAU <<IP>> 54146 <<IP>> 80
--dde07d07-B--
GET /.well-known/acme-challenge/g0xtVr2JZjrCGgaXXH1xC8Fp-EXRRdiEAdL3Cm9B3QA HTTP/1.1
Accept-Encoding: identity
Host: autoconfig.domain.tld
Content-Type: application/jose+json
Connection: close
User-Agent: acme-tiny

--dde07d07-F--
HTTP/1.1 403 Forbidden
Content-Length: 272
Connection: close
Content-Type: text/html; charset=iso-8859-1

--dde07d07-E--

--dde07d07-H--
Message: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client <<IP>>] ModSecurity: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "autoconfig.domain.tld"] [uri "/.well-known/acme-challenge/g0xtVr2JZjrCGgaXXH1xC8Fp-EXRRdiEAdL3Cm9B3QA"] [unique_id "XsKNUBSLv@CtAoRchMQbWwAAAAU"]
Action: Intercepted (phase 2)
Stopwatch: 1589808464029236 20211 (- - -)
Stopwatch2: 1589808464029236 20211; combined=2753, p1=1779, p2=877, p3=0, p4=0, p5=97, sr=484, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.6
Engine-Mode: "ENABLED"

--dde07d07-Z--

### Audit Logs / Triggered Rule Numbers

Rule ID: 960015

### Your Environment

CentOS 7.8 + Apache + MariaDB + PHP

* CRS version (e.g., v3.2.0): 2.2.9
* Paranoia level setting: default
* ModSecurity version (e.g., 2.9.3): 2.9.2
* Web Server and version (e.g., apache 2.4.41): Apache 2.4.6
* Operating System and version: CentOS 7.8

### Confirmation

[ X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @ShopixRo,

thanks for your report.

Looks like this isn't a FP issue, but the LE client doesn't use `Accept` header.

You can add this chained rule to your exclusion set:
```
SecRule REQUEST_FILENAME "@beginsWith /.well-known/acme-challenge/" \
    "id:100101,\
    phase:2,\
    t:none,\
    pass,\
    nolog,\
    noauditlog,\
    chain"
    SecRule REQUEST_HEADERS:User-Agent "@strEq acme-tiny" \
        "ctl:ruleRemoveById=960015"
```

This will check the URI, and if that begins with `/.well-known/...` **and** if the `User-Agent` is `acme-tiny`, then the rule with `id` 960015 will skipped.

HTH.

ps: your rule set is a bit older... the current version of CRS is 3.2.0
