### ISSUE TITLE
Issues related to release matching IP

### ISSUE THREAD

**Issue by yuynagforhacker** [coreruleset/coreruleset#1780]
Hello, There is a question to ask:
I pass operation 
REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf 
SecRule REMOTE_ADDR "@ipMatch 192.168.0.0/16" "id:1000,phase:1,pass,nolog,ctl:ruleEngine=Off"
Release ip
But I can only release an ip or a single IP of a specified network segment. Once the ip is separated, such as 192.168.1.1 and 192.168.5.5, how to achieve a single secruleid? My current approach is to write two secruleid but it is not easy to maintain.
Thanks.

**Comment by fzipi** [comment]
Hi @yuynagforhacker !

I'm trying to decipher your problem here. More or less, what I'm reading is that you are trying to `exclude` some IP from the modsecurity rule engine, right?

**Comment by dune73** [comment]
Never got the necessary infos. Closing now.
