### ISSUE TITLE
Support CloudEvents content-types?

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [coreruleset/coreruleset#1803]
https://cloudevents.io/ is a fairly recent open source initiative to standardize a Webhooks schema. 

[See contributors](https://github.com/cloudevents/spec/blob/master/community/contributors.md)

Would you consider adding `application/cloudevents+json` and `application/cloudevents-batch+json` as an allowed `content-type`?

This is especially useful for those using shared hosting environments without access to modify any of the ModSecurity rules directly.

**Comment by dune73** [comment]
That sounds like a reasonable idea to me.

Opinions?

**Comment by lifeforms** [comment]
Sounds fair to me!

**Comment by lifeforms** [comment]
This issue was addressed in #1804 by your PR, which will be part of our next release at the end of the month. Thank you!

**Comment by Blackbaud-BobbyEarl** [comment]
Thank you @dune73 and @lifeforms for such a professional and prompt handling of my PR!  :-)
