### ISSUE TITLE
False positive in 920420

### ISSUE THREAD

**Issue by thi-baut** [coreruleset/coreruleset#1811]
### Description

Our Web Application Firewall, Azure Application Gateway, implementing CRS 3.1 is triggering rule 920420 (Request content type is not allowed by policy) under the rule set REQUEST-920-PROTOCOL-ENFORCEMENT when a request contains the content-type header **application/fhir+json**

**application/fhir+json** is the content-type (MIME-type) used to represent [JSON resources](https://www.hl7.org/fhir/json.html) used with the FHIR standard. Fast Healthcare Interoperability Resources (FHIR) is a standard describing data formats and elements and an application programming interface for exchanging electronic health records. More info on https://www.hl7.org/fhir. 

### Audit Logs / Triggered Rule Numbers

Rule triggered is 920420. Any request with a Content-Type header set to "application/fhir+json" would trigger the rule.

### Your Environment

* CRS version: 3.1
* Paranoia level setting: Unknown, managed by Azure Application Gateway
* ModSecurity version: Unknown, managed by Azure Application Gateway
* Web Server and version: Unknown, managed by Azure Application Gateway. Assumption is it is running NGINX. 
* Operating System and version: Unknown, managed by Azure Application Gateway

**Comment by fzipi** [comment]
Well, luckily this is configurable. You need to add this to the list of allowed_request_content_type.

Sadly, the solution you are using is managed. This might require contacting Azure support.

**Comment by thi-baut** [comment]
I don't have access to allowed_request_content_type (or any of the config. files). My only option is to disable the rule. My team reached out to MS support as we wanted to create a custom rule in AAG but it turns out that custom rules are rules "on top" of the CRS; if a custom rule is passed, all CRS rules will be bypassed.

Outside of MS products limitations, this content type is likely to be used by other teams and solutions as the FHIR standard becomes widely adopted in the health industry.

**Comment by fzipi** [comment]
Ouch... well... not much we can do for now then. Thanks for reaching us.

Will close this one.

**Comment by dune73** [comment]
@thi-baut : @lifeforms kind of agreed to provide a PR for the FIHR content-type for a future release. You are the first to report this shortcoming and you should really work on Azure to make sure they give you access to the items that the rule sets defines as configurable. The rule only makes sense when you can edit the parameter list.
