### ISSUE TITLE
Anomaly Score Blocking Mode

### ISSUE THREAD

**Issue by akefallonitis** [coreruleset/coreruleset#1814]
I am trying the latest ruleset with Modsecurity and use crs-setup.conf.example (https://github.com/coreruleset/coreruleset/blob/v3.3/dev/crs-setup.conf.example) as an example but it seems that blocking never triggers.

As in the documentation described https://www.modsecurity.org/CRS/Documentation/anomaly.html the section :

SecAction
"id:'900004',
phase:1,
nolog,
pass,
t:none,
setvar:tx.anomaly_score_blocking=on"

Need to be enabled but that not seem to be the case as in CRS 3.2 this section does not exists.

Is it something else need to be change to enable blocking ? Is it something enabled by default ?

Thanks in advanced.

**Comment by fzipi** [comment]
Hi @akefallonitis! Thanks for creating this one.

Sadly, that documentation is (really) outdated by now. We are trying to get the documentation up to speed now that we migrated our repo.

It is enabled by default by now, since some versions ago.

**Comment by lifeforms** [comment]
Do you find log entries in modsec_audit.log when you trigger a rule (e.g. try visiting a URL like https://yoursite/?img=/etc/passwd)? Or does no log turn up at all?

Do you have `SecRuleEngine On` somewhere in your configuration? If not, maybe ModSecurity in running in detection-only mode.

**Comment by dune73** [comment]
@akefallonitis : Could you solve your problem / understand the way this is running? Or do you still need assistance? If not, then please close the issue here.
