### ISSUE TITLE
False positive on 933160

### ISSUE THREAD

**Issue by Taiki-San** [coreruleset/coreruleset#1815]
### Description

This rule triggers incorrectly on the following pattern: `functional system (blabla) of this nature); - further blabla`.
Looks like the `.*` is a little bit too agressive there.
Because this rule is specific to PHP, we could customize it to require the blob in `system()` to either start with a quote or with `$`?
Would miss on constants but would also stop randomly triggering in blobs of text. 

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
Hi @Taiki-San 

thank you. Before checking the rule, it would be helpful if you can provide some way to reproduce it (request, logs, etc...). Also, can you send here info about your setup? Thank you!

**Comment by Taiki-San** [comment]
Hey,

We're running the patterns on their own, based from an import from PL1.
I know that our usage deviate a bit from modsecurity and that in the past, import errors introduced false positives.
However I'm not seeing what could be the issue here.

Unfortunately, I don't have a working modsecurity setup to provide a more precise reproduction scenario, I'm limited to inputs and specific patterns.

**Comment by theMiddleBlue** [comment]
I see, thanks. We can start from a request that is blocked by your WAF. If you can provide it (for example using curl) it would be really helpful.

**Comment by Taiki-San** [comment]
I suspect `curl http://localhost/ -d "functional system (blabla) of this nature); - further blabla"` is enough, but I will confirm tomorrow.
I also reproduced the false positive here https://regex101.com/r/l6SSnE/1 with the pattern.
