### ISSUE TITLE
SecAuditLogParts not working: mod_security keeps logging response body

### ISSUE THREAD

**Issue by adrelanos** [coreruleset/coreruleset#1819]
### Describe the bug

A lot rules use:

> ctl:auditLogParts=+E,\

This makes the log hard to read as response body is very lengthy. Would be useful to have at least one log without response body.

Could you please consider dropping `ctl:auditLogParts=+E,\` to make `SecAuditLogParts` configurable?

### Steps to reproduce

default:

    SecAuditLogParts ABIJDEFHZ

change to:

    SecAuditLogParts ABIJDFHZ

### Expected behaviour

response body not logged

### Actual behaviour

response body logged

### Additional context

similar description https://github.com/SpiderLabs/ModSecurity/issues/819 (but probably not ModSecurity bug)

### Your Environment

* CRS version (e.g., v3.2.0): v3.2.0
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3):  v1.0.1 
* Web Server and version (e.g., apache 2.4.41): nginx
* Operating System and version: Debian

**Comment by airween** [comment]
Hi @adrelanos,

thanks for feedback.

I'm afraid we have to investigate deeper your request.

Until then, if you want to remove this action from your config, you can use [msc_pyparser](https://github.com/digitalwave/msc_pyparser/), especially [this small script](https://github.com/digitalwave/msc_pyparser/blob/master/examples/example11_remove_auditlog.py) - for more information, see the [description](https://github.com/digitalwave/msc_pyparser/blob/master/examples/example11_remove_auditlog.txt) of that file. I made it for [v3.4/dev](https://github.com/coreruleset/coreruleset/tree/v3.4/dev) branch, but you can use it for any version (especially for v3.2 as you wrote).

[Here](https://github.com/coreruleset/coreruleset/compare/v3.4/dev...airween:v3.4/noauditlog) you can see the comparison of two branch.

Thanks for your patience.

**Comment by airween** [comment]
Hi @adrelanos, could you check the given solution? What do you think about that?

**Comment by adrelanos** [comment]
Looks fine to me. If this is fixed in 3.4, then awesome! :)

**Comment by airween** [comment]
Hi @adrelanos, thanks again your feedback.

We discussed this issue, and we think the `ctl=auditLogParts=+E` is important part of rule set, so we don't plan to remove it.

**Comment by dune73** [comment]
As a sidenote, I am currently writing a blogpost that is going to provide you with a way to get rid of this functionality (present in over 100 rules) for good. Give me a week or so to do this.
