### ISSUE TITLE
Get 920510 (Cache-Control Whitelist) into usable state for 3.3

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#1823]
### Describe the bug

Mark Nottingham (@mnot) from the IETF HTTP Working Group has contacted us to talk about our new Cache-Control whitelist. He has written two messages pointing out several issues with this rule:

* https://github.com/coreruleset/coreruleset/pull/1777#issuecomment-642449093
* https://github.com/coreruleset/coreruleset/pull/1777#issuecomment-646438206

In short, the rule is an example, where we are stricter than the RFC which in turn could force browsers to invent a new header instead of extending an existing. It seems browser vendors are very sensitive to new features being blocked by existing servers. The result is something they call _protocol ossification_. It means that the protocol can not longer be update, since too many things (WAF!) would break. So they add new features instead.

We have introduced a whitelist for the Cache-Control header and we enable it by default for v3.3 RC2 (-> PL1).

The idea of making the whitelist / the keywords configurable does not really solve the problem as it would still have bleeding edge / experimental browsers bump into the whitelist - and thousands of admins updating their configuration due to an
upcoming browser feature is not realistic.

@theMiddleBlue also proposed to make the configurable whitelist empty / permissive by default. That would solve the ossification problem, but then the rule only becomes active when an admin enables it by hand. And I think this is not in line with how we configure / developed the ruleset, namely PL1. (I admit, we have precedent in the form of the Anti-DoS rules, but it's a special case due to the need to have serverside sessions, which we rather don't want to enable by default).

I'm therefore coming back to my initial idea when we talked about this rule: Put it in PL3. It's a special rule for a special problem. It's a problem few people have faced so far, so I think protection at PL3 for those with an extra appetite for security would be useful.

I'm assigning @lifeforms, since he is the release manager and I think he should have the final say.

### Steps to reproduce

n/a

### Expected behaviour

Don't piss of the IETF HTTP Working Group.

### Actual behaviour

Could lead to protocol ossification.

### Additional context

n/a

**Comment by lifeforms** [comment]
I agree. Protocol ossification was not a concern we considered when creating this rule, but I find the arguments compelling and we should address them. Perhaps we should even mention it in the contributing guidelines after more discussion.

There is very little time for the release. For now, I'll create a PR to move the rule to PL3. I think this helps not only by lowering the number of installs which will run this strict check, but the characteristics of the admins on PL3 are likely different, where I'd expect PL3 users to be more proactive in upgrading their rules. So I think this mitigates the issue for now while we continue the debate for later.

Continue in #1825!

**Comment by dune73** [comment]
Thank you very much for your consideration.
