### ISSUE TITLE
Coreruleset (documentation) browser on project homepage

### ISSUE THREAD

**Issue by bittner** [coreruleset/coreruleset#1824]
### Motivation

As discussed at this evening's ModSecurity CRS Meetup Bern with @dune73, it might be beneficial to have a nicely browseable CRS documentation website. This could be similar to the [CRS list on the netnea website](https://www.netnea.com/cms/core-rule-set-inventory/), but hierarchical, split up into categories.

### Proposed solution

1. Build a hierarchical set of browseable HTML pages (static files) from the CRS repository content (rules). 
1. Deploy the freshly generated documentation automatically (on GitHub Pages) on every change on the main branch.

**Comment by dune73** [comment]
Thank you for creating this issue @bittner. 

### Additional ideas:
* Make it a different folder for different trees / tagged releases
* Start with a simple dump of the comments of a rule. Comments always start after the previous rule is done and they end before the SecRule.
* Link stricter siblings to their parents based on a 9xxxxx rule ID pattern. And vice versa
* Also link tests (if available)
* Also display tags of rule
* Also display severity and score
* Also display paranoia level


@bittner : If we give you a script that does a JSON structure, would you guys do the html/JS page?

**Comment by bittner** [comment]
I would suggest you directly create either Markdown, reStructuredText or AsciiDoc. There are static site generators for all of them that give us flexibility.

* reStructuredText would be the easiest if we want [Readthedocs](https://readthedocs.org/) to host the documentation. Versions are automatic, it's a feature that is built-in and is simply configured.
* Markdown would be straight-forward of you want to host the documentation with GitHub Pages. For the versioning I don't know a solution that does things out-of-the-box.
* With GitLab Pages there is full flexibility. We can host HTML generated from any static site generator.

**Comment by fzipi** [comment]
I did a first pass migrating the documentation to Hugo here: https://fzipi.github.io/coreruleset-documentation/. I did converted the original documentation with some updaes from rst to markdown. It uses Github Pages.

With Hugo you can use JSON, or even CSV to generate documentation. I've done some data templates and they work great (https://gohugo.io/templates/data-templates/).

**Comment by fzipi** [comment]
We did some discussion in Slack about this. So let's keep it open for now.

**Comment by dune73** [comment]
This is likely going to be closed by the bot very soon. I'm moving this to the new feature request library in the wiki: https://github.com/coreruleset/coreruleset/wiki/Feature-Request-Library
