### ISSUE TITLE
Move 932200 to PL1 after more user testing

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#1832]
### Motivation

In #1831, I temporarily moved new rule 932200 to PL2, in order to safely gather experience with its FP profile. The intention is to shift the rule back to PL1 on the next release (unless there are many FP reports).

### Proposed solution

Move the rule to PL1.

### Alternatives

In case of many FP, consider tightening the rule or create a sibling rule.

### Additional context

n/a

**Comment by dune73** [comment]
Removing the stale-issue label. This is a candidate for the incubator!
