### ISSUE TITLE
Wrong download link in download page

### ISSUE THREAD

**Issue by MonstreCharmant** [coreruleset/coreruleset#1837]
### Describe the bug

I found the Core Rule Set download link was still v3.2.0, while v3.3.0 should be shown instead. Please have a check if it's a typo.

### Steps to reproduce

Just open the [link](https://coreruleset.org/installation/)

### Expected behaviour

v3.3.0 should be shown here, instead of v3.2.0

### Actual behaviour

v3.2.0 is shown here, as in this screenshot ![screenshot](https://i.imgur.com/05zn9RR.png)

### Additional context

Nothing, cannot send mail to `security@coreruleset.org` so I paste it here.

### Your Environment

Firefox 78.0.1

**Comment by lifeforms** [comment]
Thank you so much for the bug report! I've updated the page with the correct link.
