### ISSUE TITLE
Simple Base64 Post Forbidden (continued)

### ISSUE THREAD

**Issue by guquesada** [coreruleset/coreruleset#1849]
What do the ARG: json.logo64? How to upload any file names?

_User spartantri commented on date 2018-03-19 16:19:33:_

Hi **luizbiazus**, at least add a rule to check `ARGS:json.logo_64` header to be a `PNG `file (and all other formats you support) add a `t:base64decode` and `PNG `file header is `\x89\x50\x4e\x47` if I have time this will be included soon but for files that are posted not encoded in arguments however if you modify `914240 ` from PR #994 as shown below you got the magic you need to do a partial positive validation and white list the affected argument.

Here you have a good starting point ;)
```
#Check if the file type matches the with the file signature
SecRule ARGS:json.logo_64 "@rx ^data:image/(?:jpeg|jpg|gif|png|bmp|image|ico);base64,(?:\x89\x50\x4e\x47|\xff\xd8\xff(?:\xe1|\xe0|\xfe)|\x47\x49\x46\x38(?:\x37|\x39)\x61|\x42\x4d(?:\xf8\xa9|\x62\x25|\x76\x03)|\x00\x00\x01\x00|\x52\x49\x46\x46)" \
    "id:914245,\
    phase:2,\
    pass,\
    log,\
    noauditlog,\
    msg:'Encoded image type match an image signature, white listing argument',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAMES}: %{MATCHED_VARS}',\
    t:none,t:base64decode,\
    tag:'application-multi',\
    tag:'platform-multi',\
    tag:'paranoia-level/1',\
    rev:'1',\
    ver:'OWASP_CRS/3.1.0',\
    severity:'NOTICE',\
    setvar:'tx.msg=%{rule.msg}',\
    ctl:ruleRemoveTargetById=941130;ARGS:json.logo_64"
```

Good luck, do security not holes and post/contribute feedback ;)

_Originally posted by @CRS-migration-bot in https://github.com/coreruleset/coreruleset/issues/1043#issuecomment-627999391_

**Comment by fzipi** [comment]
Hi @guquesada !

Sorry this one is a bit old, and we are trying to figure it out. Can you please explain a bit about your comment:`What do the ARG: json.logo64? How to upload any file names?` ?

**Comment by dune73** [comment]
No infos received. Closing this now.

**Comment by darmon77** [comment]
I am getting a false positive when loading images with the [cropperjs](https://fengyuanchen.github.io/cropperjs/) library 
This library processes edits with before loading them to png in data:image/jpeg;base64. 
momentarily deactivate the rule REQUEST-949-BLOCKING-EVALUATION.conf line 88 id "980130" obtaining the expected result loading the image. 
commenting rules is a bad practice NOT RECOMMENDED.
Is there a better way to remove that false positive only at runtime? if so; How do I create an exception? 

log 
[Log false positive](https://www.toptal.com/developers/hastebin/ojovefalox.md)
Back to the past............

**Comment by dune73** [comment]
Hey @darmon77, sorry for the inconvenience. The relevant alert ist no in 949xxx and also not 980130. Relevant is the first alert in your log, the rest is only reporting.

So you want to deactivate ARGS:pp_blob for rule "941170 NoScript XSS InjectionChecker: Attribute Injection".

The tutorials at netnea.com are a good introduction how to handle false positives. Speak up, if you need more help.
