### ISSUE TITLE
Want to check why the CRS need to block patch and put in ENFORCEMENT way

### ISSUE THREAD

**Issue by VampireDaniel** [coreruleset/coreruleset#1863]
Want to check why the CRS need to block patch and put in REQUEST-911-METHOD-ENFORCEMENT. and the rule name has ENFORCEMENT which means this rule have to be enabled, right?

This is real confusing me, why patch and put should be block in mandatory, can anyone share the thoughts.

**Comment by fzipi** [comment]
@VampireDaniel The file name is not the rule name. The rule is enabled in paranoia level 1, which should be your case.

As you can see in rule `id:911100`, the request methods should be within the `allowed_methods`. That is just configuration you set in your `crs-setup.conf`. See and read https://github.com/coreruleset/coreruleset/blob/50d11d7d34b26c788f7176fdc7ba9633849d817a/crs-setup.conf.example#L376 to get an insight on this settings.

Both `PATCH` and `PUT` methods are specific to some use cases (maybe API/WEBDAV related), and it is not used by most applications. But again, YMMV. If you need them, just uncomment the rule with `id:900200`, and add the ones you need.

**Comment by VampireDaniel** [comment]
@fzipi thanks a lot for your reply. 

I totally understand your point, its free for me to modify the rules based on the requirements. But, I think, once the Rule Set name has the `ENFORCEMENT`, then its more like a mandatory rule which have to be implmented and the SecTeam member in my company has same thoughts as well.

So what i want to say(purpose) is, the `ENFORCEMENT` in the name is inappropriate literally. and as long as the rule could be disabled, the the name shouldnt have like `ENFORCEMENT` or `Mandatory` or any words else.

This all my personal thoughts, feel free to discuss and comment. Again, thanks for your support.

**Comment by fzipi** [comment]
@VampireDaniel The rule set has the `ENFORCEMENT` in the file name because it contains the rules to enforce HTTP behaviour. One of the good things in the CRS is that it is configurable to your needs. Your reality might be different from others, so you can choose what is best for you.

So, if you want to enforce some particular setup for HTTP, you *need* to go to that file, and no other.
