### ISSUE TITLE
FP: 941120 (PL1) base64 encoded string in param

### ISSUE THREAD

**Issue by jamieburchell** [coreruleset/coreruleset#1867]
### Description

False positive when a POST contains a base64 encoded string in a parameter e.g. CAVV from a payment gateway.

```
Message: Warning. Pattern match "(?i)[\\s\"'`;\\/0-9=\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]on[a-zA-Z]+[\\s\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]*?=" at ARGS:CAVV. [file "/etc/httpd/modsecurity.d/owasp-crs-modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "108"] [id "941120"] [msg "XSS Filter - Category 2: Event Handler Vector"] [data "Matched Data: /OnCQMAAAA= found within ARGS:CAVV: xxxxxxxxxx/OnCQMAAAA="] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"]

```

* CRS version (e.g., v3.2.0): 3.3.0
* Paranoia level setting: PL2
* ModSecurity version (e.g., 2.9.3): 2.9.2
* Web Server and version (e.g., apache 2.4.41): 2.4.6
* Operating System and version: EL7

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
I just got FP with phpMyAdmin cookie string:
`REQUEST_COOKIES:pmaUser-25_https`

`pmaUser-25_https=%7B%22iv%22%3A%22JlC0JX%5C%2FTt%5C%2FaD%5C%2FoNNWpyRLQ%3D%3D%22%2C%22mac%22%3A%2224638a97cd776607e5a1473e7f221c60dabea1b3%22%2C%22payload%22%3A%2278KjYeS1l5kpOWoI0i7nXQ%3D%3D%22%7D`

**Comment by dune73** [comment]
Sorry for letting this go stale. It's part of a bigger problem with seemingly random input and we have a hard time fixing this for real. So I reckon the best bet for the time being is just to do a local rule exclusion following tutorial https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/.

**Comment by dune73** [comment]
#2006 brought an additional payload triggering 941120:

```
curl localhost -d "sig=AOq0QJ8wRgIhAKuxokAeHNKeYixGsoXSzp2xYuovnkpxAcu8PvHbz2BKAiEAiLgVhEmndw7P11FwbGA78pWwaaT8-K8J0L1k6ONDsRI="

```

**Comment by franbuehler** [comment]
Issue chat meeting Feb 15: We agree on moving this rule to PL2 as there is no good solution. @csanders-git will open a PR.

**Comment by dune73** [comment]
@csanders-git : Did you have time to work on this? If yes, could you share the status, please?

**Comment by dune73** [comment]
I guess we won't be hearing anything from @csanders-git about this anymore.

Unassigning him and adding the "good first issue" label.

All we need is a PR that moves rule 941120 from PL1 to PL2.
