### ISSUE TITLE
False positive for jazhosting.com/readstreetselfstorage

### ISSUE THREAD

**Issue by jazdesignco** [coreruleset/coreruleset#1890]
### Description
--
[Tue Sep 29 09:06:05.353814 2020] [:error] [pid 31015] [client 67.222.0.35:57986] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/readstreetselfstorage/wp-content/uploads/2016/06/verticalimage-150x150.png"] [unique_id "X3M-TdYQjRu2ttwVDmuv3QAAAAk"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:06:41.867459 2020] [:error] [pid 31336] [client 174.60.71.39:55435] [client 174.60.71.39] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/cgi-sys/ea-php74/readstreetselfstorage/wp-admin/admin-ajax.php"] [unique_id "X3M-cUaWlJwi6YLAKB35ngAAAAw"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/index.php
[Tue Sep 29 09:06:46.308255 2020] [:error] [pid 31412] [client 67.222.0.35:58038] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/cgi-sys/ea-php74/readstreetselfstorage/wp-admin/admin-ajax.php"] [unique_id "X3M-ddDRe3JdvAdTCUvAmAAAAAE"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:06:46.431290 2020] [:error] [pid 31412] [client 67.222.0.35:58038] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/readstreetselfstorage/wp-content/plugins/js_composer/assets/js/dist/edit-form.min.js"] [unique_id "X3M-dtDRe3JdvAdTCUvAmQAAAAE"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:06:53.258389 2020] [:error] [pid 30563] [client 67.222.0.35:58040] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/cgi-sys/ea-php74/readstreetselfstorage/wp-admin/admin-ajax.php"] [unique_id "X3M-fGZhNoDr0lywajQuFAAAAAU"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:06:53.361130 2020] [:error] [pid 30563] [client 67.222.0.35:58040] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/readstreetselfstorage/wp-content/plugins/js_composer/assets/js/dist/edit-form.min.js"] [unique_id "X3M-fWZhNoDr0lywajQuFQAAAAU"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:06:53.585202 2020] [:error] [pid 30455] [client 67.222.0.35:58042] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/readstreetselfstorage/wp-includes/js/tinymce/skins/lightgray/fonts/tinymce.woff"] [unique_id "X3M-fRUBsZKei08RJsfiBgAAABA"], referer: https://jazhosting.com/readstreetselfstorage/wp-includes/js/tinymce/skins/lightgray/skin.min.css?wp-mce-49100-20200624
[Tue Sep 29 09:07:04.112970 2020] [:error] [pid 31412] [client 67.222.0.35:58046] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/cgi-sys/ea-php74/readstreetselfstorage/wp-admin/admin-ajax.php"] [unique_id "X3M-h9DRe3JdvAdTCUvAmgAAAAE"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
[Tue Sep 29 09:07:14.157525 2020] [:error] [pid 29972] [client 67.222.0.35:58048] [client 67.222.0.35] ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied [hostname "jazhosting.com"] [uri "/readstreetselfstorage/wp-admin/post.php"] [unique_id "X3M-kpCrrAw5cE@3bQGi@wAAAAA"], referer: https://jazhosting.com/readstreetselfstorage/wp-admin/post.php?post=137&amp;action=edit
--

Did you recently implement new modsecurity rules? Or any changes related to that?

--
[root@host2 readstreetselfstorage]# cd /var/cpanel/secdatadir
[root@host2 secdatadir]# ls -lh
total 0
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 global.dir
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 global.pag
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 ip.dir
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 ip.pag
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 nobody-global.dir
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 nobody-global.pag
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 nobody-ip.dir
-rw-r----- 1 nobody nobody 0 Sep 29 08:00 nobody-ip.pag
--

### Your Environment

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
This issue is very unclear and i think it's related to some kind of misconfiguration of modsecurity:
`ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/jazhos-default_SESSION": Permission denied`

**Comment by azurit** [comment]
Can you provide more info?

**Comment by dune73** [comment]
Original submitter never gave us additional information. Closing this.
