### ISSUE TITLE
Bug in rules 980120 and 980150: TX:MONITOR_ANOMALY_SCORE does not exist

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#1897]
### Describe the bug

The [Rule 980120](https://github.com/coreruleset/coreruleset/blob/v3.3.0/rules/RESPONSE-980-CORRELATION.conf#L69) and [Rule 980150](https://github.com/coreruleset/coreruleset/blob/v3.3.0/rules/RESPONSE-980-CORRELATION.conf#L118) only match if the chained rule `SecRule TX:MONITOR_ANOMALY_SCORE "@gt 1"` matches. However, I could not find where that variable is set.

This basically breaks rules 980120 and 980150 as the chained condition is never satisfied.

Aside from these two rules, I could not find any other reference to or usage of the variable `TX:MONITOR_ANOMALY_SCORE`.

### Your Environment
* CRS version (e.g., v3.2.0): v3.3.0

**Comment by dune73** [comment]
Seems leggit. Thank you for reporting. Closing this in favor of PR #1898.
