### ISSUE TITLE
False positives from 931100, 931120, and 931130

### ISSUE THREAD

**Issue by KevinDyer-3DS** [coreruleset/coreruleset#1905]
A customer of mine is running Azure gateway with CRS v3.0.0 and is receiving multiple false positives for rules 931100, 931120, and 931130. 

request URL are of the form /ContextPath/RESTEndPoint?resource=https://RequestedResource/RestofURI%3fquerystring&RestofQueryString

For this particular app there are a number of cooperating/collaborating services (unique FQDN) that may be scattered across one or more TLD. Rules 931100 and 931120 do not allow for any exclusions. If IP address is used or if the embedded URL contains a querystring (?) the request is blocked. Only 931130 has an exclusion and it is only allowing the matches of the capture group to match the Host header of the request. 

Would it be unreasonable to create a whitelist to allow the capture group to be compared to in addition to the remote host for all three rules in this group? These rules are very similar to the controls required for CORS origin processing. The WAF/proxy/application needs to be able to control where the requests are either going to  or coming from.  But the target server should also be involved in the conversation once it  the request has been vetted by the WAF.

**Comment by azurit** [comment]
@fgsch Are you still working on this? Thank you for info.

**Comment by fgsch** [comment]
@azurit I'm planning to take a look at this tomorrow but feel free to take it if you want to work on it.

**Comment by dune73** [comment]
Any news on this front?

**Comment by joachimnielandt** [comment]
I am experiencing the same issue on my WAFv2 - OWASP 3.2: 

Excluded 'RequestArgValues contains santaclaus' for rule 931130, a request 'GET https://domain.com?target=https://santaclaus.com' results in a single match(931130)+blocked.

**Comment by RedXanadu** [comment]
Hi @joachimnielandt,

If you're happy for the parameter `target` to contain off-domain links then you will need to create a rule exclusion for it.

Assuming your WAFv2 is an Azure WAF, this page may be helpful:
https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-waf-configuration?tabs=portal

Otherwise, you should contact Microsoft Azure support if you need help beyond that. Microsoft use their own rule exclusion mechanisms, not the standard ones we're familiar with.

**Comment by joachimnielandt** [comment]
Hello @RedXanadu , thanks for the info. Sorry for thinking that this was Azure's tracker, my mistake. Indeed, I am using an Azure WAFv2 and the exclusion can indeed be made for parameter `target`, but not for value `contains santa`. 

I will continue my search on Azure's support instead :).
