### ISSUE TITLE
Use the upcoming version in 'ver' actions on our dev branch

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#1917]
### Motivation

Currently, we search-and-replace the `ver` actions before releasing. So while developing 3.4.0, our rules are still mentioning ver 3.3.0. This makes it harder to distinguish in logs whether a node is running the 3.3.0 release, or a 3.4.0 pre-release.

### Proposed solution

Change our release procedure to increase the `ver` actions on the dev branch right after a release.

And create a PR to increase them right now to 3.4.0 for the v3.4/dev branch.

### Alternatives

Don't do it and keep the old versions.

### Additional context

N/A

**Comment by dune73** [comment]
I agree this is a problem. What version would you do exactly? 

```
* 3.4.0pre
* 3.4.0dev
* 3.4.0a (for alpha)
```

**Comment by dune73** [comment]
@airween : Did you have time to work on this issue? What is the status?

**Comment by airween** [comment]
> @airween : Did you have time to work on this issue? What is the status?

No, I didn't - I'll make it at this weekend. Sorry guys.

**Comment by dune73** [comment]
No worries mate. And thank you!

**Comment by airween** [comment]
I have few questions:
* what about the file headers? Eg. I mean [this](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-901-INITIALIZATION.conf#L2) or [this](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf#L2)? I think I can change them too.
* what about the `SecComponentsSignature` variable in [this line](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-901-INITIALIZATION.conf#L28)? I also can change it.
* there are two files which already have the new version string in header: [this](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf#L2) and [this](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf#L2).

I thought I can check the old `ver` argument (eg. the `ver` will replaced only if the given pattern matches), but it can work only in case if `ver` actions, not for the comments.

Also it's a problem that `ver` uses the form `OWASP_CRS/x.y.z`, but the comment uses `Core Rule Set ver.x.y.z`.

The solution could be an extra argument for transform script - actually now it has 3 args:

```
./crs_change_ver.py "/path/to/coreruleset/rules/*.conf" /path/to/output "OWASP_CRS/3.4.0"
```
but it should be
```
./crs_change_ver.py "/path/to/coreruleset/rules/*.conf" /path/to/output "OWASP_CRS/3.4.0" "ver.3.4.0"
```

Any ideas are welcome.

**Comment by airween** [comment]
See the initial version of the Wiki page:

https://github.com/coreruleset/coreruleset/wiki/Change-version-in-CRS

**Comment by lifeforms** [comment]
Added the wiki page to the release procedure.

We settled on `3.4.0-dev` format for dev branch.

To be done: modify rule 900990 with a 'short version' of the version string (e.g. `340`) and create a PR applying the new scheme to the dev branch.

**Comment by dune73** [comment]
We talked about this in the [April issue chat](https://github.com/coreruleset/coreruleset/issues/2051#issuecomment-813570935). 

We were able to sort out all open questions for this issue and @airween will now proceed with his script and a PR.

**Comment by airween** [comment]
> We were able to sort out all open questions for this issue and @airween will now proceed with his script and a PR.

See PR #2085.

**Comment by dune73** [comment]
Closing this in favor of PR #2085.

**Comment by lifeforms** [comment]
Closing this in favor of PR #2100.

Thanks to Airween's version change utility added in #2085, version changes are now super easy and safe to make, which prevents bugs such as in #2009.
