### ISSUE TITLE
detected SQLi using libinjection with fingerprint

### ISSUE THREAD

**Issue by Aurel-NPS** [coreruleset/coreruleset#1921]
### Description

Hi all, I don't know why ModSecurity is blocking this request

[msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: no(no found within ARGS:r[3]: f/type/jahresberichte+(ausfuhrliche+version)"]

[942100_FP-logs.txt](https://github.com/coreruleset/coreruleset/files/5516372/942100_FP-logs.txt)

### Audit Logs / Triggered Rule Numbers

942100

### Your Environment

* CRS version (e.g., v3.2.0): 3.3.0
* Paranoia level setting: PL1
* ModSecurity version (e.g., 2.9.3): 2.9.2
* Web Server and version (e.g., apache 2.4.41): 2.4.29
* Operating System and version: Debian 10

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Sorry for the inconvenience and thank you for writing a detailed bug report.

This false positive happens in the libinject library that ModSecurity sources and that CRS leverages. There is very little we can do to help you here (outside of skipping the use of libinject). You are not the only one suffering here and unfortunately libinject is not actively maintained as of this writing.

I know this is bad news, sorry about that.

If you need help with writing a rule exclusion, then look at the CRS tutorial number 8 at netnea.com.

**Comment by fzipi** [comment]
@Aurel-NPS You can file a bug in the [new repository for the libinjection library](https://github.com/libinjection/libinjection), which might have more maintainance in the near future.

**Comment by Aurel-NPS** [comment]
Hi,

I'm trying to write a basic exclusion for this rule

SecRule REQUEST_URI "@beginsWith /fr/publications.html" \
        "id:1002,phase:1,pass,log, \
        ctl:ruleRemoveTargetById=942100"

But when I make some test, I've got a Secure Connection Failed from Firefox, and no logs in audit or debug file
The others URL still work fine

Regards
Aurelien

**Comment by airween** [comment]
@Aurel-NPS,

if the syntax is same as above, it might be wrong:
* you aren't using `\` at the end of the lines
* `ruleRemoveTargetById` expects a target at least - see [documentation](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#ctl).

I think the correct exclusion rule should be this:
```
SecRule REQUEST_URI "@beginswith /fr/publications.html" \
    "id:1002,phase:1,pass,log,\
    ctl:ruleRemoveById=942100"
```
Please note that your first example the URI begins with `/de...`, not with the `/fr...`.
