### ISSUE TITLE
RuleID 920120 and 920121 are triggering on Content-Disposition form-data as part of a multipart/form-data request

### ISSUE THREAD

**Issue by KevinDyer-3DS** [coreruleset/coreruleset#1927]
### Description

A normal multipart/form-data request is being blocked for the Content-Disposition header. Per RFCs 7578 and 6266 the content-disposition header is a mandatory header for multipart/form-data with the format of:

Content-Disposition: form-data; name="fileData"; filename="filename.jpg"

All of the semicolons, and quotes will be caught by these rules, even though they are required characters.

Audit log records:

11/11/2020,   1:39:17.106 PM | /internal/servlet/fcs/checkin | Attempted multipart/form-data   bypass | Warning. Pattern match   \"(?<!&(?:[aAoOuUyY]uml)\|&(?:[aAeEiIoOuU]circ)\|&(?:[eEiIoOuUyY]acute)\|&(?:[aAeEiIoOuU]grave)\|&(?:[cC]cedil)\|&(?:[aAnNoO]tilde)\|&(?:amp)\|&(?:apos));\|['\"=]\"   at FILES:fileData ....

11/11/2020,   1:39:17.106 PM | /internal/servlet/fcs/checkin | Attempted multipart/form-data   bypass | Warning. Pattern match   \"['\";=]\" at FILES:fileData ....

Input data:

POST https://3dspace.XXXXXXXXX/internal/servlet/fcs/checkin HTTP/1.1
Content-Type: multipart/form-data; boundary=mx1605094509
Accept: */*; q=.2
Accept-Language: en-us
x-MxEncoding: UTF8
Cache-Control: no-cache
Pragma: no-cache
fcsversion: FCS_1.fcs_14.R422
networkcheckinchecksum: true
User-Agent: MatrixOne
Host: 3dspace.XXXXXXXXX
Content-Length: 63474
Connection: Keep-Alive
Cookie: JSESSIONID=XXXXXXXXXXXXX; SERVERID=XXX.2

--mx1605094509
Content-Disposition: form-data; name="__fcs__jobTicket"

encrypted string base64 encoded......
--mx1605094509
Content-Disposition: form-data; name="fileData"; filename="somefileName''.1"
Content-Type: application/octet-stream

### Audit Logs / Triggered Rule Numbers

920120 and 920121

### Your Environment

* CRS version v3.1.0
* Paranoia level setting: PL2
* ModSecurity version: MS Azure App Gateway 
* Web Server and version (e.g., apache 2.4.41): N/A
* Operating System and version: N/A

### Confirmation

[x ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
Can you post the full log if it's possible? Rules 920120 and 920121 are not matching HTTP headers but uploaded files and file names. Thank you.

In your example, i see the problem in the file name which contains quotes characters (').

**Comment by azurit** [comment]
Can you provide more info?

**Comment by dune73** [comment]
@KevinDyer-3DS: Are you still interested to have us solve this issue? If yes, we need more infos. If we do not hear from you, we will have to close this issue.
