### ISSUE TITLE
Include IPv6 in Host Header Check

### ISSUE THREAD

**Issue by itsTheFae** [coreruleset/coreruleset#1928]
### Motivation

The CRS already contains rule ID 920350, which checks the `Host` header for IP address (and possible port) by using a digit-only check.  This rule works for IPv4 cases but fails (does not trigger) when IPv6 is used.  

The rule allows servers which only use name-based host configurations to detect possible invalid requests if they are made using the Server's IP address(es) instead of any configured host or domain name.

### Proposed solution

The rules should be modified to include IPv6 in the same check or via a new rule specific to IPv6 checking. 
The addition of an IPv6 check also deals with a bypass condition in that IPv4 in the `Host` will trigger rule-920350 but IPv6 will not.  

### Alternatives

Admin can certainly opt to configure Apache to deny access to requests having IP address as the `Host` portion of the request.  However this requires the addition of wildcard or `_default_` host configuration blocks in a specific order, or a per-virtual-host set of directives specific to the server addresses. 

The reason I suggest using ModSecurity is to avoid having to manually add new IPs when those are added to a server or double-checking that newly created host configuration files are not out-of-order with the wildcard/`_default_` host configurations.  

ModSecurity already provides the warning/check for IPv4 in the `Host` header, so why not just expand that to include IPv6 as well?

**Comment by airween** [comment]
@itsTheFae - #1929 is merged, and solved this issue. Can we close this ticket?

**Comment by itsTheFae** [comment]
Thanks for the quick response to this!  
Happy New Year!
