### ISSUE TITLE
MediaWiki redirects to the homepage after editing the post (with many external links)

### ISSUE THREAD

**Issue by ofmarconi** [coreruleset/coreruleset#1939]
**Describe the bug**

Hi, I don't have anything to do with security, I updated it as WHM sent it to "OWASP CRS v3.x for ModSec 2.9 (via RPM)"

It turns out that now I can't put many external links in a publication in MEDIAWIKI, would that have any solution besides disabling security?

Thanks!

**Logs and dumps**

https://imgur.com/a/mca3e7m

The interesting thing is that this is not my IP, so why does another IP appear?

Thank you for helping lay people like me.

**Comment by ofmarconi** [comment]
When I turn off Vendor OWASP CRS v3.x for ModSec 2.9

in WHM> ModSecurity vendors

My media wiki works again as expected, in the worst case, can I disable OWASP CRS by Htaccess only for this domain?

**Comment by azurit** [comment]
The reason why you don't see your IP is because you are using Cloudflare (it's a proxy, so their IPs are in logs).

I will need more info, are you able to upload full request log?

**Comment by ofmarconi** [comment]
Ahhh it makes sense,

I am already using the following security plugins in my installation

cPGuard Security
ConfigServer Security & Firewall
ImunifyAV

Can I disable any of them with this new update? Is it okay to get everyone connected?

As for cloudflare, would I have to put his ips so as not to block the connection of legitimate traffic? Does it happen automatically like Modsec?

About the LOG is the file really big or do you want me to leave only the data for the last few days? https://fromsmash.com/logmodsec (60MB)

**Comment by azurit** [comment]
> I am already using the following security plugins in my installation
> 
> cPGuard Security
> ConfigServer Security & Firewall
> ImunifyAV
> 
> Can I disable any of them with this new update? Is it okay to get everyone connected?


No, you don't have to.

 
> As for cloudflare, would I have to put his ips so as not to block the connection of legitimate traffic?

Definitely not! All of your visitors are connecting from Cloudflare IPs.


> About the LOG is the file really big or do you want me to leave only the data for the last few days? https://fromsmash.com/logmodsec (60MB)

It's ok but take it down ASAP, it contains lot's of sensitive information.

I'm checking the log, give me some time.

**Comment by ofmarconi** [comment]
Done

The mediawiki site is wiki.gugacast

**Comment by azurit** [comment]
Unfortunately, this issue can be handled only within exclusion rules package created especially for MediaWiki (which isn't available yet). If you know how, you can save this rule (from my pesonal collection) inside file `/etc/modsecurity/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`, it should resolve your issue :

```
SecRule REQUEST_FILENAME "@endsWith /api.php" \
    "id:9991900,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    chain"
    SecRule ARGS:action "@streq stashedit" \
        "t:none,\
        chain"
        SecRule &ARGS:action "@eq 1" \
            "t:none,\
            ctl:ruleRemoveTargetById=930120;ARGS:text,\
            ctl:ruleRemoveTargetById=932100;ARGS:text,\
            ctl:ruleRemoveTargetById=941100;ARGS:text,\
            ctl:ruleRemoveTargetById=941160;ARGS:text"

```

**Comment by ofmarconi** [comment]
Thank you @azurit!
I'll try to do that, if I can do an evaluation, is it a good setup for these plug-ins that I have installed on my WHM?

cPGuard Security
ConfigServer Security & Firewall
ImunifyAV
+ CRS

Does not leaving all these plug-ins running on my machine end up consuming more than necessary for security?

Does any cancel the other? Can I leave OWASP CRS v3.x for ModSec 2.9 (via RPM) off until this update to MediaWiki?

Sorry so many questions :)

**Comment by ofmarconi** [comment]
Is there an update forecast for MediaWiki? Hug!

**Comment by ofmarconi** [comment]
> Unfortunately, this issue can be handled only within exclusion rules package created especially for MediaWiki (which isn't available yet). If you know how, you can save this rule (from my pesonal collection) inside file `/etc/modsecurity/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`, it should resolve your issue :

I'm not finding this path, I found this file at:
/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example

That's right?
Just paste this command at the end of the file and remove the .example from the file name?

**Comment by ofmarconi** [comment]
I did it and it didn't work for me

**Comment by ofmarconi** [comment]
Updated log: https://pastebin.com/pUK2Dpr2

The password is your username.

_azurit_

**Comment by azurit** [comment]
Try renaming file:
`/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example`

To:
`/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`

**Comment by dune73** [comment]
@azurit: Do we have enough to incorporate the fixes for these FPs in our MediaWiki exclusion package?

Or do we close this issue here?

**Comment by fzipi** [comment]
We have dokuwiki exclusion, but nothing for mediawiki.

**Comment by dune73** [comment]
Closing this since we do not have a rule exclusion package for MediaWiki and the FPs are generic enough, so we can not simply remove them.
