### ISSUE TITLE
Rule 941120: false positive for the Russian language

### ISSUE THREAD

**Issue by ghost** [coreruleset/coreruleset#1943]
### Description

Caught a false positive on the words "употребляют наркотики"

941120 Matched Data: ;ONB = found within ARGS:json.description: #?>B@51;ONB =0@:>B8:8

```
ляют н
;ONB =
```

### Audit Logs / Triggered Rule Numbers

```
"response":{"body":"<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","http_code":403,"headers":{"Server":"","Server":"","Date":"Fri, 04 Dec 2020 15:21:01 GMT","Content-Length":"146","Content-Type":"text/html","Access-Control-Allow-Origin":"*","Connection":"close","Access-Control-Allow-Credentials":"true","Strict-Transport-Security":"max-age=15724800; includeSubDomains"}},"producer":{"modsecurity":"ModSecurity v3.0.4 (Linux)","connector":"ModSecurity-nginx v1.0.1","secrules_engine":"Enabled","components":["OWASP_CRS/3.3.0\""]},"messages":[{"message":"XSS Filter - Category 2: Event Handler Vector","details":{"match":"Matched \"Operator `Rx' with parameter `(?i)[\\s\\\"'`;\\/0-9=\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]on[a-zA-Z]+[\\s\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]*?=' against variable `ARGS:json.description' (Value: `\\xd1\\x83\\xd0\\xbf\\xd0\\xbe\\xd1\\x82\\xd1\\x80\\xd0\\xb5\\xd0\\xb1\\xd0\\xbb\\xd1\\x8f\\xd1\\x8e\\xd1\\x82 \\xd0\\xbd\\xd
(61 characters omitted)' )","reference":"o7,6v17,41t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls","ruleId":"941120","file":"/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf","lineNumber":"89","data":"Matched Data: ;ONB = found within ARGS:json.description: C?>B@51;ONB =0@:>B8:8","severity":"2","ver":"OWASP_CRS/3.3.0","rev":"","tags":["application-multi","language-multi","platform-multi","attack-xss","paranoia-level/1","OWASP_CRS","capec/1000/152/242"],"maturity":"0","accuracy":"0"}},{"message":"Inbound Anomaly Score Exceeded (Total Score: 5)","details":{"match":"Matched \"Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' )","reference":"","ruleId":"949110","file":"/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf","lineNumber":"80","data":"","severity":"2","ver":"OWASP_CRS/3.3.0","rev":"","tags":["application-multi","language-multi","platform-multi","attack-generic"],"maturity":"0","accuracy":"0"}}]}}
```

### Your Environment

* CRS version (e.g., v3.2.0): v3.3.0
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): v3.0.4
* Image: k8s.gcr.io/ingress-nginx/controller:v0.41.2

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by aiNeu0taip9ue** [comment]
Also https://github.com/coreruleset/coreruleset/issues/1867

**Comment by dune73** [comment]
@franbuehler, given you are covering #1942, would you mind taking on this issue here are well?

**Comment by azurit** [comment]
@franbuehler Did you have time to check if this is really related to 'your' issue https://github.com/coreruleset/coreruleset/issues/1942 ? Thanks for info!

**Comment by dune73** [comment]
Issue covered in the [September issue chat](https://github.com/coreruleset/coreruleset/issues/2185#issuecomment-913804183).

@theseion volunteered to take a look.

**Comment by theseion** [comment]
For reference, these are the characters in the expression:
\x0B: \v
\x09: \t
\x0C: form feed
\x3B: ;
\x2C: ,
\x28: (
\x3B: ;

The expression could be improved too, by removing the doubled `\x3B`.

**Comment by theseion** [comment]
I cannot reproduce this, not with Apache or NGiNX. After having spent some time trying to find a sequence of conversions that would lead to this it looks like there's maybe something fishy going on with the encoding of the web server. The "Matched Data" (`#?>B@51;ONB =0@:>B8:8`) looks similar to the US-ASCII XSS attack, where the 8-bit bytes are converted to 7-bit bytes, but it doesn't seem to work out.

I would need to know what encoding the server is using and a sample request would also help because it is unclear what the actual payload is (there are so many transformations in that rule, it could be a bunch of things).

Since OP is no longer around I suggest we close this and wait for another FP that we can actually work with.

**Comment by dune73** [comment]
We have not heard from original reporter, so I agree we close this until we get a better report that we can reproduce.

For the record: We are quite sure this or a similar problem exists. It's just that we can not fix it if we can not reproduce it.
