### ISSUE TITLE
Moving rules to the correct phases

### ISSUE THREAD

**Issue by airween** [coreruleset/coreruleset#1949]
### Motivation

There was a similar issue in #1941: we moved the rules to the previous phase if the used variables allowed. Now I reviewed the rules again, and checked the other direction - this issue lists the rules which contain a variable, which can't present in the used phase - spoiler: this is only the `ARGS` variable, and all rules are in `phase:1`.

**[9001182](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf#L284-L300)**:

rule in phase1, but (POST) ARGS avaliable in phase2
Note: there is an action at the end of the chain: `ctl:requestBodyAccess=Off`, this turns off the whole phase2 in modsec3

proposal: change the `ARGS:destination` by `ARGS_GET:destination` - any Drupal expert?
Or we can copy this rule but with `phase:2`, as is in case of 9004300 - see below.

**[9002141](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf#L107-L123)**:

rule in phase1, but (POST) ARGS avaliable in phase2

proposal: change the `ARGS:rest_route` by `ARGS_GET:rest_route` - any WP expert?
Or here we also can copy this rule but with `phase:2`, as is in case of 9004300 - see below.

**[9002143](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf#L136-L152)**:

rule in phase1, but (POST) ARGS avaliable in phase2

proposal: change the `ARGS:rest_route` by `ARGS_GET:rest_route` - any WP expert?
Or here we also can copy this rule but with `phase:2`, as is in case of 9004300 - see below.

**[9004300](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf#L166-L173)**:

rule in phase1, but (POST) ARGS avaliable in phase2
note: the next rule (9004310) is same but triggered in `phase:2` - any DokuWiki expert?

**[9006600](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf#L391-L408)**:

rule in phase1, but (POST) ARGS avaliable in phase2
proposal: change the `&ARGS` by `&ARGS_GET` - any XENFORO expert?
Or here we also can copy this rule but with `phase:2`, as is in case of 9004300 - see above.

Let's discuss about the possible solution.

**Comment by lifeforms** [comment]
- 9002141: can safely be changed to `ARGS_GET:rest_route`
- 9002143: can safely be changed to `ARGS_GET:rest_route`

As far as I know, these parameters are always passed as part of the URL.

**Comment by dune73** [comment]
We talked about this in the [April issue chat](https://github.com/coreruleset/coreruleset/issues/2051#issuecomment-813570935). 

We are now convinced that this can all be implemented by moving to phase 1 and replacing ARGS with ARGS_GET (for better readability). @airween will carry this out.
