### ISSUE TITLE
Monthly Chat Agendas January  (2021-01-04 and 2021-01-18)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#1953]
This is the Agenda for the Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, January 4th, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, January 4th. That's the 3rd Monday of the month.

Items on the Agenda:  (see previous meetings decisions: [here](https://github.com/coreruleset/coreruleset/issues/1944#issuecomment-740132322))

### Outside development
* [Video of Presentation](https://www.youtube.com/watch?v=nhiKnTBrAOI) at M0lecon from November by @theMiddleBlue has been put online
* [Blog post about ModSec / CRS Audit Log analysis with R](https://blog.stevens.club/2018/10/analyzing-owasp-mod-security-audit-log.html?m=1)
* [Detailed tutorial about ModSec / CRS at LinuxBabe](https://www.linuxbabe.com/security/modsecurity-apache-debian-ubuntu)

### PRs

* #1887: Eliminate FPs in 932100 by ignoring html decimal entities before dot sign and space or new line - **closed** in favor of #1954
* #1929: Fixed regex for match IPv6 addr syntax in 920350 - **merged**
* #1941: Shifting all rules to phase 1 where this is possible - **merged**
* #1946: Polishing NextCloud exclusion rules package - **merged**
* #1952: Better description for 920350 - **merged**
* #1954: Fix FP 932100 Issue #1886 - **merged**
* #1955: Introduction of blocking early feature - **merged**
* #1956: Fix blind SQLi detection at PL1 Issue 1904 - **merged**
* #1961: Update for scanners-user-agents.data - **merged**

## Open PRs

* [secrules_parsing: #7: Changed the acceptable argument for @\contains op](https://github.com/coreruleset/secrules_parsing/pull/7) - waiting for review
* #1962: New response body blocking: Web shells - waiting for secrules_parsing PR #6 (see above) and then there are ongoing discussions
* #1906: Fixing and improving environment for testing (docker/nginx) - We decided to split PR, but no feedback from original contributor
* #1911: Possible fix issue 1883 - can be replaced by #1966
* #1966: Rework pattern to fix false positive - replacing #1911 if we agree
* #1936: feat(ci): use relative paths in testing and other improvements - waiting for review
* #1951: phpMyAdmin exclusion rules package - waiting for review
* #1957: Fix false negative in rule 920480 - waiting for review
* #1958: Fix for issue #1922 - waiting for review
* #1960: Update for restricted-files.data - ready to be merged unless somebody objects to the file list.

## Open PRs marked "work in progress" / *needs action*

* #1938 V3.4/dev ftw main - **draft**
* #1934: feat(ci): upgrades ftw to python 3 supported version - tests are failing and PR needs more work
* #1930 feat(ci): add test plugin to annotate failures - **draft**
* #1868 Migrate PR: RE2 compatibility for 921120 - still waiting for @dune73's blog post about it
* #1845: Stop decoding things twice - It's basically ready for merging, but @fgsch will provide a better explanation of PR during the week
* #1817 Fix false positives with rule 942360 - **needs work**

## Other items

* Talking about the 3.3.1 release, namely in the light of #1963

## Open Issues - Separate Issues Meeting (Monday, January 18th)

*Special topic* : Blogpost about the ModSec3 security problem with disabling request body access.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #1864 FP: 930120 PL1
* Issue slot 2: #1969 NextCloud + YUM problem
* Issue slot 3: #1979 Better paranoia level setting
* Issue slot 4: #1950 FP 949110 - cookie with (*.)/(.*) in value
* Issue slot 5: #1949 Moving rules to the correct phases
* Issue slot 6: #1908 False Positive on valid JSON data for rule ID 942340
* Issue slot 7: 
* Issue slot 8: 
* Issue slot 9: 
* Issue slot 10: 

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp-slack.herokuapp.com/ .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions

## PRs

* [secrules_parsing #7](https://github.com/coreruleset/secrules_parsing/pull/7): Can be merged when @fzipi, @azurit and @airween think it's ready.
* #1962: New response body blocking: Web shells - waiting for secrules_parsing PR #6 (see above) and then there are ongoing discussions: @azurit tries to find something more unique for rule 955330. If this is not possible the rule should be moved to PL2.
* #1906: Fixing and improving environment for testing (docker/nginx) - We decided to split PR, but no feedback from original contributor
* #1911: Possible fix issue 1883 - can be replaced by #1966
* #1966: Rework pattern to fix false positive - replacing #1911 if we agree
* #1936: feat(ci): use relative paths in testing and other improvements - waiting for review
* #1951: phpMyAdmin exclusion rules package - waiting for review
* #1957: Fix false negative in rule 920480 - waiting for review
* #1958: Fix for issue #1922 - waiting for review
* #1960: Update for restricted-files.data - ready to be merged unless somebody objects to the file list.
