### ISSUE TITLE
ModSec regex not matching

### ISSUE THREAD

**Issue by scottbrannan** [coreruleset/coreruleset#1959]
Hi, we wanted to add an additional uri into our regex for one of our rule id's

 SecRule REQUEST_URI "@rx \/json/docs|\/json\/contact\/([0-9]+)|\/json\/abc" \
  "id:9989,phase:2,t:none,t:lowercase,nolog,pass,ctl:ruleRemoveTargetByID=932150;ARGS"

we tried with a regex as above, with the specific ID, with the uri minus the regex part, tried changing it from by id to by tag and tried just having the uri for the contact part on its own. None of these worked for the /json/contact uri. We ended up having to whitelist the whole id which then worked

  SecRuleRemoveById 932150

Any suggestions on what we could try so we arent removing by id?

Thanks

Scott

**Comment by dune73** [comment]
Hey Scott, I'm closing this as it's not a CRS issue, but rather a support request.

But now to your problem: The first things you should do is making sure your rule 9989 is placed before the CRS include. Then you could shift it from nolog to log o see if it triggers.
