### ISSUE TITLE
SecAction behaviour inconsistent

### ISSUE THREAD

**Issue by GieltjE** [coreruleset/coreruleset#1964]
### Motivation

For some specific vhosts we add tx.allowed_methods to some rules, but not all can be applied within the vhost (or even Directory/Location tags).

The following works within a vhost:
`SecAction "id:900200, phase:1, nolog, pass, t:none, setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE'"`

The following does not (and must be applied in crs-setup.conf thus affecting all vhosts):
`SecAction "id:91110, phase:1, nolog, pass, t:none, setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE'"`

### Proposed solution

Not sure as to the exact solution, but it would be preferable if both would work from within the vhost/Directory/Location tags.

### Alternatives

A better default list of tx.allowed_methods and where they can and cannot be applied (might be beneficial anyway).

**Comment by azurit** [comment]
I don't think you are doing this right.

First of all, you are assigning ID 900200, which is the ID of one of configuration parameters of CRS (see crs-setup.conf). The ID must be unique, you cannot assign the same ID to multiple SecRule/SecAction directives. You have, probably and luckilly for you, commented out that one SecRule in crs-setup.conf but if you decide in the future that you want to use it and uncoment it, your web server even won't start.

The proper solution would be uncommenting rule 900200 in crs-setup.conf and adding this to Directory/Location sections where needed:
`SecRuleUpdateActionById 900200 "setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE'"`

**Comment by azurit** [comment]
According to this https://github.com/coreruleset/coreruleset/issues/1963#issuecomment-753632559 my solution above will probably don't work for phase 1 rules. Please set your configuration always in VirtualHost sections.

**Comment by GieltjE** [comment]
The solution above doesn't work for e.g. 911100 in the vhost (within Directory statement) nor within the /etc/modsecurity/crs/crs-setup.conf file.
This creates issues for environments which host different sites with different requirements and creates potential security issues for them (e.g. having to whitelist tx.allowed_methods for all sites or the whole site where only some specific url might use it).

I think this is starting to overlap with #1963 a lot at this point.

**Comment by azurit** [comment]
Don't use Directory, put it directly into VirtualHost.

**Comment by GieltjE** [comment]
Could the SecWebAppId chain used in #1963 be used to do this too?

**Comment by azurit** [comment]
I think yes.
