### ISSUE TITLE
Not working link on coreruleset.org web site

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#1965]
Here:
https://coreruleset.org/faq/#sponsor

Link to sponsor page goes to https://owasp.org/index.php/Project_Sponsorship_Operational_Guidelines which is throwing 404.

**Comment by dune73** [comment]
Thank you for pointing this out. I'll take care of it.

**Comment by dune73** [comment]
Fixed. Thank you for reporting.
