### ISSUE TITLE
Conditional evaluation rules at phase:4

### ISSUE THREAD

**Issue by theMiddleBlue** [coreruleset/coreruleset#1967]
### Motivation

due to a modsec limit to "unzip" compressed response body, it would be nice to have a rule that skips all phase:4 rules when the response `Content-Encoding` header is present.

### Proposed solution

```
SecRule RESPONSE_HEADERS:Content-Encoding "@rx ^(?:gzip|compress|deflate|br)$" "id:123,phase:3,\
   nolog,\
   pass,\
   ... remove rules ..."
```

the problem is that due to v3 incompatibility, we can't use id range in ctl:ruleRemoveById and here can become useful what proposed in #1866

**Comment by azurit** [comment]
Guys, i'm working on alternative solution, stay tuned!

**Comment by azurit** [comment]
See PL #1968.

**Comment by azurit** [comment]
I integrated this idea into PR https://github.com/coreruleset/coreruleset/pull/1968.

**Comment by dune73** [comment]
Closing this in favor of #1968.
