### ISSUE TITLE
"949110": False positive

### ISSUE THREAD

**Issue by ashishkpal** [coreruleset/coreruleset#1977]
Hi,

I am observing Error. please help to resolve the same 

2021/01/12 11:04:00 [error] 3102#3102: *899 [client 127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/usr/local/coreruleset-3.3.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "127.0.0.1"] [uri "/"] [unique_id "1610449440"] [ref ""], client: 127.0.0.1, server: xxx.xxx.xxx, request: "PURGE / HTTP/1.1", host: "xxx.xxx.xxx.xxx"

CRS version - 3.3.0
Modsecurity 3.0.2
Nginx - 1.18.0

**Comment by dune73** [comment]
Hi there, sorry for the inconvenience. Hope we can sort this out.

You reported the blocking rule. However, there were other rules contributing to the anomaly score so the request has a score of 8 (and will be blocked).

Please report those as well.

As a quick remedy, you may want to look up the ModSecurity tutorials over at https://netnea.com.

**Comment by ashishkpal** [comment]
Dear @dune73 ,

i am not observing any other error apart from the above mention.

**Comment by dune73** [comment]
Hmm. This is off, but then you are running ModSec3, so you never know. There are several faults known with this version.

Can you reproduce the problem? If yes, could you share the exact request you are executing? I'd like to reproduce this. We used to have a rule back in the days that was silent, but that problem is fixed in 3.3.0, so I am a bit at a loss why you do not get the rule alerts.

**Comment by ashishkpal** [comment]
hi,
i am just to open my webpage and seeing this error on nginx error logs which are coming very frequently

2021/01/18 06:24:40 [error] 11683#11683: *693 [client 172.20.11.220] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/usr/local/coreruleset-3.3.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "xxx.xxx.xxx.xxx"] [uri "/.env"] [unique_id "1610951080"] [ref ""], client: 172.20.11.220, server: xxx.xxx, request: "GET /.env HTTP/1.1", host: "xxx.xxx.xxx.xxx"

**Comment by dune73** [comment]
OK. It's actually right in the alert: you do a request to /.env. Then I run this in my nginx installation, I get a rule alert on 930130 in addition to the 949110 that you get.

```
2021/01/18 11:24:11 [info] 6924#6924: *1 ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `restricted-files.data' against variable `REQUEST_FILENAME' (Value: `/.env' ) [file "/home/dune73/crs/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "105"] [id "930130"] [rev ""] [msg "Restricted File Access Attempt"] [data "Matched Data: /.env found within REQUEST_FILENAME: /.env"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "127.0.0.1"] [uri "/.env"] [unique_id "161096545191.204341"] [ref "o0,5v4,5t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"], client: 127.0.0.1, server: localhost, request: "GET /.env HTTP/1.1", host: "localhost"
2021/01/18 11:24:11 [warn] 6924#6924: *1 [client 127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/home/dune73/crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "138"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "127.0.0.1"] [uri "/.env"] [unique_id "161096545191.204341"] [ref ""], client: 127.0.0.1, server: localhost, request: "GET /.env HTTP/1.1", host: "localhost"

```

I get the feeling there is something wrong with your setup.

Could you please search for 930130 in your error log?

**Comment by ashishkpal** [comment]
sorry but ID - 930130 or any other ID is not there on any error logs except 949110 ID

**Comment by dune73** [comment]
Do you have the audit log enabled?  (You probably have).

Could you please confirm the 930130 is not in that log either? (The audit log can be set up in a way you get an individual file per request. So please make sure you are searching on the right log entry.

**Comment by ashishkpal** [comment]
able to find in the audit logs

ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `restricted-files.data' against variable `REQUEST_FILENAME' (Value: `/.env' ) [file "/usr/local/coreruleset-3.3.0/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "105"] [id "930130"] [rev ""] [msg "Restricted File Access Attempt"] [data "Matched Data: /.env found within REQUEST_FILENAME: /.env"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "xxx.xxx.xxx.xxx"] [uri "/.env"] [unique_id "1610951080"] [ref "o0,5v4,5t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]

**Comment by dune73** [comment]
OK. So we have the CRS alert that contributes to the anomaly score of 8 that 949110 reports. I have not the faintest idea, why you do not have it in the error log together with the 949110 rule alert. But I am confident, this is not a CRS issue, and I will therefore close this issue.

**Comment by jjarokergc** [comment]
Hello, I think that I have the same issue and would like to offer a possible explanation for the 949110 rule alert appearing without any other alerts.

My setup consists of an nginx reverse proxy to a nginx serving Dokuwiki.  When opening my Dokuwiki home page just now, a 403 error page appeared.  The nginx error logs show the 949110 alert, but no other alerts were present.

Looking at the modsec_audit.log, I see that the alert was triggered by the cookie:

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)[\s\"'`;\/0-9=\x0B\x09\x0C\x3B\x2C\x28\x3B]on[a-zA-Z]+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=' against variable `REQUEST_COOKIES:DW68700bfd16c2027de7de74a5a8202a6f' (Value: `amphcm9rZXJqbw%3D%3D%7C1%7CTlR9qy%2ByzBD3E9sb793rpG6FEYTSKx%2FonTwgxHHLnoo%3D' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "89"] [id "941120"] [rev ""] [msg "XSS Filter - Category 2: Event Handler Vector"] [data "Matched Data: /onTwgxHHLnoo= found within REQUEST_COOKIES:DW68700bfd16c2027de7de74a5a8202a6f: amphcm9rZXJqbw==|1|TlR9qy+yzBD3E9sb793rpG6FEYTSKx/onTwgxHHLnoo="] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "10.10.10.107"] [uri "/"] [unique_id "1641955754"] [ref "o49,14v582,77t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "10.10.10.107"] [uri "/"] [unique_id "1641955754"] [ref ""]
```
The 941120 rule alert does not appear in the nginx error log, which creates the mystery why the 949110 appears by itself.
