### ISSUE TITLE
High false positive rates for rule 932115

### ISSUE THREAD

**Issue by Taiki-San** [coreruleset/coreruleset#1987]
### Description

The rule is quite sensitive to URLs or code snippets.

The most common false positives are as follow:
- `url/bla?test=1&share=0`
- `url/bla?test=1&sort=0`
- `\n type x` (appears in free text)

### Your Environment

We run it in our custom runtime.

### Confirmation

[x I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thank you for reporing @Taiki-San. I'm closing this in favor of #1931 where the keyword sort appeares as well.
