### ISSUE TITLE
FP: Rule 930110 - Path Traversal Attack (/../) - triggered on ..

### ISSUE THREAD

**Issue by leroc274** [coreruleset/coreruleset#2005]
### Description

Rule 930110 - Path Traversal Attack (/../) - triggered on  .. (dot dot)

I think Rule should be triggered on 
../
/..
\\..
..\\
and not on
..

### Audit Logs

> --be180000-B--
> POST /servlets/servlet/SessionExample* HTTP/1.1
> 
> --be180000-C--
> dataname=..&datavalue=
> 
> --be180000-H--
> Message: Warning. Pattern match "(?:^|[\\/])\\.\\.(?:[\\/]|$)" at ARGS:dataname. [file "*/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "71"] [id "930110"] [msg "Path Traversal Attack (/../)"] [data "Matched Data: .. found within ARGS:dataname: .."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"]

### Environment

* CRS version: 3.3.0
* Paranoia level setting: 1
* ModSecurity version: 2.9.3
* Web Server and version: Apache 2.4.41
* Operating System and version: Windows

### Confirmation

[x ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
Thanks for the report. I will take this issue. We will ensure that `..` doesn't trigger anymore in the next release.

**Comment by lifeforms** [comment]
A change to fix this false positive is proposed in #2016. After review, it will be part of our next release. Thanks for reporting!
