### ISSUE TITLE
mod_security coreruleset: Block Request when Copy Text From MS Word Format

### ISSUE THREAD

**Issue by ahasanaki** [coreruleset/coreruleset#2015]
### Description

I'm using https://hub.docker.com/r/owasp/modsecurity + https://github.com/coreruleset/modsecurity-docker

Now in POST Request When user copy and paste text from ms word and send to server, the request will be blocked

`Feb 16 13:20:55 sap journal: 2021/02/16 13:20:55 [error] 22#22: *192440 [client IP] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator Ge' with parameter 5' against variable TX:ANOMALY_SCORE' (Value: 10' ) [file "/etc/modsecurity/crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "79"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "172.20.100.10"] [uri "/file/1209/referral/"] [unique_id "161346905556.327309"] [ref ""], client: IP, server: DOMAIN, request: "POST /file/1209/referral/ HTTP/1.1", host: "DOMAIN", referrer: " https://DOMAIN/file/1209/referral/"`

**Comment by fzipi** [comment]
Hi @ahasanaki , I'm sorry you got this false positive.

Sadly, we need more information from your logs because this is only the last part where the blocking evaluation is performed and we need to know the actual rules that matched, and why.

Can you provides us that (please sanitize any IPs/names also)?

**Comment by ahasanaki** [comment]
hi @fzipi, Thanks for following up
Domain: sub.domain.com
Modsec Docker IP & Port: 172.20.100.10:443
Client IP: 212.86.86.160
Users use Persian language and when they copy and paste the text in Word format (bold, font, heading, etc.) are blocked

logs from modsec_audit.log
`[06/Feb/2021:12:02:37 +0330] 161260035726.123842 212.86.86.160 49544 172.20.100.10 443
---nWLFI8t6---B--
POST /file/9173/referral/ HTTP/1.1
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Cache-Control: max-age=0
Content-Type: application/x-www-form-urlencoded
Origin: https://sub.domain.com
Upgrade-Insecure-Requests: 1
Content-Length: 300
Connection: keep-alive
Sec-Fetch-Mode: navigate
Host: sub.domain.com
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://sub.domain.com/file/9173/referral/
Accept-Encoding: gzip, deflate, br
Cookie: sid=e13540-d464-11e9-3a863awe; _ga=GA1.2.655140049.1568869371; __utmz=128786644.1589796093.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _      _utma=128786644.655140049.1568869371.1603705691.1608189134.3; PHPSESSID=ardoi2rks24fmdt4udi8oreg7; REMEMBERME=QXBwXEVudGl0eVxVc2VyOlltRnlaR2s9OjE2MTMyMDUwODI6MDcwNDhhZDcyZDdmY2Q2ZjM1ZTc      5ZmI3NGRmMjIyMTcyZDUzNTY3YmJmMTY1OTU5OTg4M2QzYWNiN2VjYjZkNw%3D%3D
Accept-Language: en-US,en;q=0.9

---nWLFI8t6---D--

---nWLFI8t6---E--
<!DOCTYPE html>\x0a<html>\x0a    <head>\x0a        <meta charset="UTF-8" />\x0a        <title>An Error Occurred: Internal Server Error</title>\x0a        <style>\x0a            body { ba      ckground-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }\x0a            .container { mar      gin: 30px; max-width: 600px; }\x0a            h1 { color: #dc3545; font-size: 24px; }\x0a            h2 { font-size: 18px; }\x0a        </style>\x0a    </head>\x0a    <body>\x0a        <      div class="container">\x0a            <h1>Oops! An Error Occurred</h1>\x0a            <h2>The server returned a "500 Internal Server Error".</h2>\x0a\x0a            <p>\x0a                      Something is broken. Please let us know what you were doing when this error occurred.\x0a                We will fix it as soon as possible. Sorry for any inconvenience caused.\x0a                  </p>\x0a        </div>\x0a    </body>\x0a</html>\x0a

---nWLFI8t6---F--
HTTP/1.1 500
Server: nginx
Date: Sat, 06 Feb 2021 08:32:38 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: max-age=0, must-revalidate, private
Expires: Sat, 06 Feb 2021 08:32:38 GMT
Content-Security-Policy: default-src 'self' http: https: data: blob: 'unsafe-inline'

---nWLFI8t6---H--

---nWLFI8t6---I--
                              `

**Comment by dune73** [comment]
Thank you for providing additional infos and the audit lot, @ahasanaki.

Unfortunately, we still do not have the request body. It is meant to be in the --C-- part, or the --I-- part. You do not have C configured (SecAuditLogParts directive), yet --I-- is there; and empty.

There can be multiple reasons and it's hard to pin down. It's probably easier to use the web developer options in the browser to extract the exact request body.

I am now closing this issue. Yet if you manage to get that information, then please re-open the issue submit said info. We are very interested, not the least because we are sure that Farsi support must be subpar.
