### ISSUE TITLE
Brotli detected as PHP leakage

### ISSUE THREAD

**Issue by i2dcarrasco** [coreruleset/coreruleset#2017]
### Description
```---4sUeZgau---F--
HTTP/1.1 200
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Strict-Transport-Security: max-age=31536000; preload
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
Connection: keep-alive
Content-Encoding: br
Content-Type: text/html; charset=UTF-8
Date: Mon, 22 Feb 2021 12:02:24 GMT
Server: nginx
Pragma: no-cache
Expires: -1
Accept-Ranges: bytes

---4sUeZgau---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\x1f\x8b\x08|\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\b|gif)|B(?:%pdf|\.ra)\b|^wOF(?:F|2))' against variable `RESPONSE_BODY' (Value: `\xc2\xd4\x9cYHM\xfa!\xa0\x198\xae\xc7:\xef?3\xb5\xfe\x9e\xaa\x1c\xee/H\xd2\x94br\x17\xb5P\x16\xbb\x1 (38762 characters omitted)' ) [file "/etc/nginx/modsec/crs/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "85"] [id "953120"] [rev ""] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: \xc2\xd4\x9cYHM\xfa!\xa0\x198\xae\xc7:\xef?3\xb5\xfe\x9e\xaa\x1c\xee/H\xd2\x94br\x17\xb5P\x16\xbb\x14Yv<#\xdbj\xcb\xee-J\xb1 \xe2I\x82\x03\x02l\x00\x94,\xbbU5\x97\xf3\xfc\xb5\x8f\x7f\xd9o\xcb\xea\xd3m\xfc\xef\xcd\xf4\xb36\xe3\x92+k"\x05\x91\x14*R\xba\xebS\x05\xa1\x92\x94\xe7\xde\xfb^\xe9u\xf7L\xd5\x0c\x06\xac\x9a\xc1\x00U\x03\x9ar\xeb@\xf7\xbf\xbf\xcft\x8f\x05<\xf9A\x90\xdf\xd8\xb5\xde$\x91\x8c\xf1\xa1J\x99\x92\xa4A9\x9f\xfdT\x99B=\x86\x8a\xf7\xae5\x1e\x82\x88 (13270 characters omitted)"] [severity "3"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "OWASP_CRS"] [tag "OWASP_CRS/LEAKAGE/SOURCE_CODE_PHP"] [tag "WASCTC/WASC-13"] [tag "OWASP_TOP_10/A6"] [tag "PCI/6.5.6"] [hostname "10.100.48.201"] [uri "/zapatillas/head.html"] [unique_id "161399534481.147069"] [ref "o3675,2v1566,13425v1566,13425"]
ModSecurity: Access denied with code 200 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `4' ) [file "/etc/nginx/modsec/crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "68"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "10.100.48.201"] [uri "/zapatillas/head.html"] [unique_id "161399534481.147069"] [ref ""]
```

After searching a bit, I've noticed that the rule is related with the "<?" php opening in response body, and looking into the raw response I've seen that is because maybe the modsecurity is not compatible with the brotli compression method and is detecting a part of the binary that contains those symbols:

`F?5<?<92>`

I've tried to disable the rule with `SecRuleRemoveById 953120` but the modsecurity is ignoring me and still giving me a false positive. I'm thinking on remove the entire modsecurity from the proxy part, and keep it just in the back side where the body is generated and where the body is not compressed.

EDIT: Rule disabled and now is working fine. The problem was that an nginx reload was ignoring the new config. After rebuild the image and deploy the new version seems to be working fine.

### Audit Logs / Triggered Rule Numbers
953120

### Your Environment
* CRS version (e.g., v3.2.0): v3.2.0
* Paranoia level setting: Default, I think that 4
* ModSecurity version (e.g., 2.9.3): v3.0.4
* Web Server and version (e.g., apache 2.4.41): Nginx 1.19.7
* Operating System and version: Debian 10

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thank you for reporting and good to see you were able to exclude this FP for your installation.

The rule in question - 953120 - is very sensitive. Yet it has a chained rule, that is meant to drop the FPs if there is binary data in the response. It does this by looking at file headers and Brotli is not part of the list.

Alternatively, we could also look into the content-encoding header of the response that indicates a binary brotli reponse.

I'd be happy to provide a PR, if you could provide me with the response that triggers this rule. Ideally the full audit log including the --E-- part or taken from the web developer tools in the browser. This because I do not have a brotli server ready and without the FP it would be tricky to construct a unit test to implement this.

In the meantime, I am closing this issue. But feel free to re-open if you can put your hands on said data.
