### ISSUE TITLE
Test WAF Bypass

### ISSUE THREAD

**Issue by kirana2507** [coreruleset/coreruleset#2026]
Hi, can ModSecurity prevent a SQL Injection if we send 1000 SQL injection in 1 attack? and do you know whats the command of that? Thanks before :)

**Comment by dune73** [comment]
Yes, it will.

You can compose your super-attack by picking a few of the tests in https://github.com/coreruleset/coreruleset/tree/v3.4/dev/tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI and assemble them into a curl command by hand.
