### ISSUE TITLE
Libinjection - XSS Detection Rule 94110 false/positive

### ISSUE THREAD

**Issue by MelleD** [coreruleset/coreruleset#2041]
### Description

If you use the following Json in the playload, the rule 94110 is triggered. The problem is the string "filter={AnyChar}"
`
"query":"filter=in(labels.name,"test")"`

Error message:

`"message":"XSS Attack Detected via libinjection","action":"Matched","site":"Global","details":{"message":"Warning. detected XSS using libinjection. ","data":"Matched Data: XSS data found within ARGS:query: filter=in(labels.name,\\x22test\\x22)"`

From my point of view, the rule should not be triggered by this payload

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
I agree. This a false positive. Yet it is not with CRS, but with Libinjection that provides this operator to ModSecurity and we have a rule that uses it.

I'm sorry, but I can only close this issue and tell you to visit https://github.com/client9/libinjection to submit your report.
