### ISSUE TITLE
modsecurity for Apache 2.9.3 - modsecurity CRS 3.2.0 - Apache-Error - PCRE limits exceeded

### ISSUE THREAD

**Issue by rudy500** [coreruleset/coreruleset#2042]
recusive error in Apache 2.4.41, PHP 7.4.16 fpm modsecurity 3.0.4-1bulid1, modsecurity CRS 3.2.0-1 and Ubuntu 20.04.2

don't see id code of rule and repeat this error everytime:

Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client XXX.XXX.XXX.XXX] ModSecurity: Rule 7fcb5152c980 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "89"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "xxxx.xxxx.xx"] [uri "/xxxx/xxxx/xxxx.php"] [unique_id "YFocJk5fc7dTaCi90TeixQAAAA8"]
Message: Rule 7fcb5152c980 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "89"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb51507e40 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "240"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514f8948 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "266"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514f2c28 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "317"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514e51f8 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "342"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514df840 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "367"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514d6e68 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "392"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514d1a80 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "417"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7fcb514c6950 [id "-"][file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "442"] - Execution error - PCRE limits exceeded (-8): (null).

modsecurity.conf
SecPcreMatchLimit 150000
SecPcreMatchLimitRecursion 150000

php.ini (fpm):

pcre.backtrack_limit = 1000000
pcre.recursion_limit = 100000

ulimit -a:
core file size (blocks, -c) 0
data seg size (kbytes, -d) unlimited
scheduling priority (-e) 0
file size (blocks, -f) unlimited
pending signals (-i) 63703
max locked memory (kbytes, -l) 65536
max memory size (kbytes, -m) unlimited
open files (-n) 1024
pipe size (512 bytes, -p) 8
POSIX message queues (bytes, -q) 819200
real-time priority (-r) 0
stack size (kbytes, -s) 8192
cpu time (seconds, -t) unlimited
max user processes (-u) 63703
virtual memory (kbytes, -v) unlimited
file locks (-x) unlimited

**Comment by noloader** [comment]
Also see https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/656 and the other similar issues.

**Comment by rudy500** [comment]
thank you for your answer it was very helpful

**Comment by azurit** [comment]
@rudy500 is this still an issue?

**Comment by rudy500** [comment]
Hi,

   Sorry for not responding before, I have been raising the parameters that you indicated to me and I managed to stabilize the platform and those messages at 5000000 to avoid these messages, thank you very much for your prompt response.

thank you and many blessings.

**Comment by dune73** [comment]
Great. Thank you for reporting back. Closing the issue then.
