### ISSUE TITLE
False Positive && BYPASS  phpBB 3.3.3 rules

### ISSUE THREAD

**Issue by diegaless** [coreruleset/coreruleset#2043]
### Description

It all started because a user notified me that creating a post always led to a 404, the problem was that the user tried to publish this fragment that breaks the rule ` --- advertise`

[line "86"] [id "200004"] [msg "Multipart parser detected a possible unmatched boundary."]

I suppose that this is an expected behavior, if not, tell me and I will fill in all the data that the form asks for.

**The real problem is the following (bypass)**: In phpBB there is the option to publish as a guest, activating it from the ACP [Guest posting phpBB](https://www.phpbb.com/community/viewtopic.php?t=2163297)
If this message is published as a guest, the rule does not jump, which makes me think that somehow this is not contemplated and no rule is being verified for guest posts. Any missing data I will be happy to add it

### Your Environment

* CRS version: 3.3.0
* Paranoia level setting: default
* ModSecurity version: 3.3.0
* Web Server and version: PHP 7.4.16 
* Operating System and version: Ubuntu Server 20.04

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by diegaless** [comment]
@azurit

**Comment by azurit** [comment]
@diegaless thank you for this report. Can you, please, upload full log from both requests?

**Comment by diegaless** [comment]
**Description**
User ( logued user) notified me that creating a post always led to a 404, the problem was that the user tried to publish this fragment that breaks the rule --- advertise

**Audit Logs / Triggered Rule Numbers**
POST /posting.php?mode=post&f=187
content-type: multipart/form-data;

**Triggered rules:**

-  [file "/etc/modsecurity/modsecurity.conf"] [line "86"] [id "200004"] -> [msg "Multipart parser detected a possible unmatched boundary."]
Action: Intercepted (phase 2)

There were rules that were repeated and eliminated by synthesizing.

**_FULL LOG in case it helps_**

`Message: Access denied with code 403 (phase 2). Match of "eq 0" against "MULTIPART_UNMATCHED_BOUNDARY" required. [file "/etc/modsecurity/modsecurity.conf"] [line "86"] [id "200004"] [msg "Multipart parser detected a possible unmatched boundary."]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 185.237.173.79] ModSecurity: Access denied with code 403 (phase 2). Match of "eq 0" against "MULTIPART_UNMATCHED_BOUNDARY" required. [file "/etc/modsecurity/modsecurity.conf"] [line "86"] [id "200004"] [msg "Multipart parser detected a possible unmatched boundary."] [hostname ""] [uri "/posting.php"] [unique_id ""]
Action: Intercepted (phase 2)
Apache-Handler: proxy:unix:/run/php/php7.4-fpm.sock|fcgi://localhost
Stopwatch: 1616624432969055 1839 (- - -)
Stopwatch2: 1616624432969055 1839; combined=688, p1=577, p2=10, p3=0, p4=0, p5=101, sr=78, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.3.0.
Server: Apache
Engine-Mode: "ENABLED"
`



**Description 2**
If the user comments in guest mode (without logging in) he can post perfectly --- advertise


**I do not know very well what you expect me to show you here, please tell me and I will provide it, but of course, when I can post it, no rule works and therefore there is no log to teach it**

**Audit Logs / Triggered Rule Numbers**
POST /posting.php?mode=post&f=187

**Triggered rules:**

- neither

Anything you need ask me @azurit . thanks for the help, have a nice day :)

**Your Environment**

- CRS version: 3.3.0
- Paranoia level setting: default (1)
- ModSecurity version: 2.9.2
- Web Server and version: Apache 2.4.29 | PHP 7.4.16
- Operating System and version: VPS Ubuntu 18.04

**Confirmation**
[x] I have removed any personal data (email addresses, IP addresses,
passwords, domain names) from any logs posted.

**Comment by diegaless** [comment]
Any news @azurit ?

I just had another report with exactly the same rules as the ones I mentioned above, this time it was because the user entered '->', it seems that whenever a user enters - regardless of what is preceded it sends it to a 404, I suppose it will detect it as an sql injection ... Use - is very typical on my platform. Change from -> to -> I solve it
