### ISSUE TITLE
PL 1 False Positive on Blacklist Keywords from Node-Validator

### ISSUE THREAD

**Issue by RubieV** [coreruleset/coreruleset#2060]
### Description
For several environments, the PL1 rule `Blacklist Keywords from Node-Validator (941180)` , is triggering on legitimate user's input, especially in customer feedback forms. 

The rule itself contains good signatures for the detection of actual attacks (i.e. `document.cookie`), however is mixed with the payload `-->`, which is causing the common false positives.

### Example
```
Look at this example --> https://example.com/
customer requested new e-mail adres  --­> john@example.com
```

### Substantiation

| Signature | False Positive Ratio | 
| --- | --- |
| document.cookie | Low |
| document.write | Low |
| .parentnode | Low | 
| .innerhtml | Low |
| window.location | Low | 
| -moz-binding | Low |
| ** | **High** |
| <![cdata[ | Low | 

### Proposal
Splitting this rule from a single PL1 rule into a PL1 and an PL2 rule.

### Your Environment

* CRS version (e.g., v3.2.0): v3.2.0
* Paranoia level setting: 2
* ModSecurity version (e.g., 2.9.3): 2.9.3
* Web Server and version (e.g., apache 2.4.41): Multiple
* Operating System and version: Multiple

### Original Rule

```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@pm document.cookie document.write .parentnode .innerhtml window.location -moz-binding <!-- -->
 <![cdata[" \
    "id:941180,\
    phase:2,\
    block,\
    capture,\
    t:none,t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:lowercase,t:removeNulls,\
    msg:'Node-Validator Blacklist Keywords',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-xss',\
    tag:'paranoia-level/1',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/152/242',\
    ctl:auditLogParts=+E,\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.xss_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"
```

### Confirmation

- [x] I have removed any personal data (email addresses, IP addresses, passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @RubieV,

thanks for your report. We will investigate this issue shortly, and will give a solution.

**Comment by lifeforms** [comment]
I remember some heated conversations about `-->` with you @RubieV and yes finally I can agree that we move this pattern to Paranoia Level 2.

This is a great first issue as it's basically copying the existing rule into the Paranoia Level 2 section of the file (remembering to give it a new ruleId and giving it the `paranoia-level/2` tag) and moving the `-->` to that new rule, so we will assign it to a new face on the CoreRuleSet scene and hope to raise a proud new contributor. :)

**Comment by dune73** [comment]
Closing this in favor of PR at #2082.

Thank you for reporting @RubieV.
