### ISSUE TITLE
OData queries and FetchXML queries result in a lot of false positives, even for Paranoia Level 1

### ISSUE THREAD

**Issue by edwinvandeburgt** [coreruleset/coreruleset#2073]
We're using Microsoft Application Gateway with WAF enabled and the CRS 3.2 and see a lot of false positives when OData queries of FetchXML queries are included in the QueryString.

Is there a recommendation to disable some (which?) rules for these use cases?

**Comment by lifeforms** [comment]
Hi @edwinvandeburgt , definitely it is possible to make a small exclusion rule in the CRS that disables some checks only at certain points.

If you can share some of the modsec audit logs, that would be helpful.

**Comment by edwinvandeburgt** [comment]
Hi @lifeforms ,

Thanks for your quick reply. 

Of course I could disable every FP that pops up, but I was looking for if someone already has a list for when OData and/or FetchXML is used.

I can't really share a modsec audit log, because I'm using Microsoft Application Gateway, which writes entries to LogAnalytics, containing the CRS rule and description and the url that triggered it, but nothing very verbose...

I'm afraid disabling checks at certain points is not possible, you could disable a rule but not change is so it ignores the querystring or something like that; on a per-rule basis it's all or nothing.

**Comment by dune73** [comment]
@edwinvandeburgt would you mind sharing a screen shot what the LogAnalytics is sharing with you exactly? It would help to put your explanation in perspective (and help other users in the future).

**Comment by edwinvandeburgt** [comment]
@dune73, sure.

The LogAnalytics query for an example request was:

`AzureDiagnostics
| where ResourceType == "APPLICATIONGATEWAYS" and OperationName == "ApplicationGatewayFirewall"
| where transactionId_g == "211809d7-1f01-8b99-c318-99556a620e25"    
| project requestUri_s, Message, ruleId_s, ruleGroup_s, details_message_s, action_s, transactionId_g, serverStatus_s
`

The returned results:

![afbeelding](https://user-images.githubusercontent.com/27497969/118641984-1734f700-b7db-11eb-928b-49220787e0af.png)


The URL contains an MS-Dynamics FetchXML query, which is the culprit and although it's very ugly, it's also valid FetchXML and no SQL or XSS:

/.../crmp_policyroles/?fetchXml=%3Cfetch%20version=%271.0%27%3E%3Centity%20name=%27crmp_policyrole%27%3E%3Cfilter%20type=%27and%27%3E%3Ccondition%20attribute=%27crmp_contactid%27%20operator=%27eq%27%20value=%2745cda833-f14d-e311-93f2-005056883d1e%27%20/%3E%3C/filter%3E%3Cattribute%20name=%27crmp_enddate%27%20/%3E%3Cattribute%20name=%27crmp_startdate%27%20/%3E%3Cattribute%20name=%27crmp_intermediaryid%27%20/%3E%3Cattribute%20name=%27crmp_coveragedifferentiation%27%20/%3E%3Cattribute%20name=%27crmp_coverageid%27%20/%3E%3Cattribute%20name=%27crmp_sourcesystemid%27%20/%3E%3Cattribute%20name=%27crmp_coveragetypecode%27%20/%3E%3Cattribute%20name=%27crmp_intermediaryname%27%20/%3E%3Cattribute%20name=%27crmp_iban%27%20/%3E%3Clink-entity%20name=%27crmp_role%27%20to=%27crmp_roleid%27%20from=%27crmp_roleid%27%20alias=%27rol%27%20link-type=%27outer%27%20%3E%3Cattribute%20name=%27crmp_name%27%20/%3E%3C/link-entity%3E%3Clink-entity%20name=%27crmp_producttype%27%20to=%27crmp_producttypeid%27%20from=%27crmp_producttypeid%27%20alias=%27typ%27%20link-type=%27outer%27%20%3E%3Cattribute%20name=%27crmp_code%27%20/%3E%3C/link-entity%3E%3Clink-entity%20name=%27crmp_policy%27%20to=%27crmp_policyid%27%20from=%27crmp_policyid%27%20alias=%27pol%27%20link-type=%27outer%27%20%3E%3Cattribute%20name=%27crmp_name%27%20/%3E%3Cattribute%20name=%27crmp_enddate%27%20/%3E%3Cattribute%20name=%27crmp_aanmaningscode%27%20/%3E%3Cattribute%20name=%27crmp_betaalperiode%27%20/%3E%3Cattribute%20name=%27crmp_periodepremie%27%20/%3E%3Cattribute%20name=%27crmp_actuelewaarde%27%20/%3E%3Cattribute%20name=%27crmp_kapitaal%27%20/%3E%3Cattribute%20name=%27crmp_saldo%27%20/%3E%3Cattribute%20name=%27crmp_startdate%27%20/%3E%3Cattribute%20name=%27crmp_kenmerk%27%20/%3E%3Clink-entity%20name=%27crmp_producttype%27%20to=%27crmp_productypeid%27%20from=%27crmp_producttypeid%27%20alias=%27ptyp%27%20link-type=%27outer%27%20%3E%3Cattribute%20name=%27crmp_name%27%20/%3E%3Cattribute%20name=%27crmp_code%27%20/%3E%3C/link-entity%3E%3C/link-entity%3E%3C/entity%3E%3C/fetch%3E

**Comment by edwinvandeburgt** [comment]
@dune73 , and we have the same false positives for OData queries:

![afbeelding](https://user-images.githubusercontent.com/27497969/118642501-b954df00-b7db-11eb-87cc-f03db3518d00.png)

/.../CustomerBankAccounts?%24filter=dataAreaId+eq+%27119%27+and+CustVendGuid+eq+d5115315-6385-eb11-a812-000d3adc5845+and+BankAccountId+eq+%270444285520%27

Are there some other recommendations for protecting API's instead of the full OWASP 3.2?

**Comment by edwinvandeburgt** [comment]
@dune73 , of course there is more data in the AzureDiagnostics table, referring to the Resource etc.

The following is a list of OWASP related fields:

![afbeelding](https://user-images.githubusercontent.com/27497969/118643570-05545380-b7dd-11eb-832b-62d71ef00d8d.png)

**Comment by dune73** [comment]
Thank you very much. This is very useful. You seem to be getting all the relevant infos about the request.

Conversion table:

| ModSec | Azure |
| -------|-------|
|    |     |
|    |     |
|    |     |
|    |     |

**Comment by edwinvandeburgt** [comment]
> Missing: Tags (like paranoia level or CAPEC) - Did you exclude them from your query or is it generally missing from Azure?

It's generally missing from Azure, unfortunately.

**Comment by dune73** [comment]
Thank you for the confirmation.

What a pity. I just wish these integrators, that charge money for their service (!), would do a better job at integrating CRS properly.

**Comment by dune73** [comment]
But now back to your initial question.

No, there is no general advice with regards to OData and FetchXML. At least not to our knowledge.

CRS can be used for API protection and it's maybe actually quite useful, yet the FP can be painful of course and on the native  ModSecurity engine, heavy API payloads can bring devastating performance numbers.

As you are aware, you are submitting XML in the query string. Unfortunately, ModSecurity (and I reckon also the engine that Azure is using these days) won't be able to treat query string XML as XML. That only works for POST bodies when you apply the XML Body Processor functionality. So instead you end up with a normal parameter with a lot of special characters and CRS hates that.

You will therefore have to disable at least the rules enforcing a limited number of special characters in a request. But given XML is kind of a computer code, there might be a lot of additional rules that are being triggered and you need to write rule exclusions for those. If this is not the central part of your application, but more or a side topic, then it may make sense to live with it and disable many or all rules for the FetchXml parameter.

If you are willing to invest a lot of time and you know which parts of the XML stuff are sensitive for your application, you could do a custom setup, where you extract those parts from the query string and feed them into CRS separately. That's quite a hack, but perfectly doable.

**Comment by dune73** [comment]
You're welcome. Happy to help, especially if it's a new or intriguing question.
