### ISSUE TITLE
Owasp crs 3.2 email validation request

### ISSUE THREAD

**Issue by Shajinraj** [coreruleset/coreruleset#2079]
### Motivation

Email validation for the login screen to improve the security and only the users with username as mail id should be able to login.

Email ID syntax should only be possible. 
Username with only name or number should be blocked.

### Proposed solution

When an user tries to login to a webpage, In front WAF should allow only the email ID users to login.

Application flow: Internet --> F5 LB --> WAF --> VIP -->Application login

### Alternatives

NA

### Additional context

Your Environment
CRS version (v3.2.0):
Paranoia level setting:
ModSecurity version (v2.9.3):
Web Server and version (httpd2.4.41):
Operating System and version: RHEL 7.9

**Comment by azurit** [comment]
Thank you very much for this feature request!

I think that login validation is work for an application, not a WAF.

Anyway, you can easily write such a rule and use it for your own. Check this:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#rx

**Comment by dune73** [comment]
This is a typical security rule that you write yourself (or implement in the application as input validation).

You may want to check out my ModSec tutorial at https://www.netnea.com/cms/apache-tutorial-6_embedding-modsecurity/#step_8_writing_simple_whitelist_rules. In step 8, I am developing a rule set that features a rule that checks a username for it's format, only allowing usernames of a certain format. Well in fact it does not enforce proper email addresses, but you get the idea and the text explains why I do it the way I do.
