### ISSUE TITLE
Replace references to blacklist and whitelist with denylist and allowlist respectively

### ISSUE THREAD

**Issue by 53cur3M3** [coreruleset/coreruleset#2083]
### Motivation

The terms blacklist and whitelist are no widely recognised as causing offence.

### Proposed solution

Replace references to blacklist and whitelist with denylist and allowlist respectively

### Additional context

If this request / change was approved I'd be happy to fix these, and submit a Pull Request
There are a handful of references to blacklist and whitelist, documented below:
`grep -Ri black | grep -vi blackberry | grep -vi blackhat | grep -vi "black\s*widow" | grep -vi "blackface" | grep -v "#define BLACK 0"
crs-setup.conf.example:# -- [[ Project Honey Pot HTTP Blacklist ]] ------------------------------------
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml:      desc: Node-validator blacklist keywords, ARGS
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml:      desc: Node-validator blacklist keywords, ARGS_NAMES
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml:      desc: Node-validator blacklist keywords, ARGS_NAMES
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941190.yaml:      desc: Node-validator blacklist keywords, ARGS
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941190.yaml:      desc: Node-validator blacklist keywords, ARGS_NAMES
tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941190.yaml:      desc: Node-validator blacklist keywords, COOKIES_NAMES
CHANGES: * Improves http blacklist checks (Walter Hop)
CHANGES:* Added PHP "call_user_func" to blacklist
rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf:# Comments blacklist and moderation list
rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf:                    ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:blacklist_keys,\
rules/REQUEST-910-IP-REPUTATION.conf:# been blacklisted by rules from previous requests.
rules/REQUEST-910-IP-REPUTATION.conf:# ModSecurity Rules from Trustwave SpiderLabs: IP Blacklist Alert
rules/REQUEST-910-IP-REPUTATION.conf:#SecRule TX:REAL_IP "@ipMatchFromFile ip_blacklist.data" \
rules/REQUEST-910-IP-REPUTATION.conf:#    msg:'Client IP in Trustwave SpiderLabs IP Reputation Blacklist',\
rules/REQUEST-910-IP-REPUTATION.conf:# Check Client IP against ProjectHoneypot's HTTP Blacklist
rules/REQUEST-910-IP-REPUTATION.conf:# To use the blacklist, you must register for an HttpBL API Key
rules/REQUEST-910-IP-REPUTATION.conf:# "Project Honey Pot HTTP Blacklist" in crs-setup.conf.
rules/REQUEST-910-IP-REPUTATION.conf:    msg:'HTTP Blacklist match for search engine IP',\
rules/REQUEST-910-IP-REPUTATION.conf:    msg:'HTTP Blacklist match for spammer IP',\
rules/REQUEST-910-IP-REPUTATION.conf:    msg:'HTTP Blacklist match for suspicious IP',\
rules/REQUEST-910-IP-REPUTATION.conf:    msg:'HTTP Blacklist match for harvester IP',\
rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf:# DR/**/OP/*bypass blacklisting*/sampletable
util/av-scanning/runAV/common.h:EXTERN char modsec_proxy_blacklist[1024];
util/av-scanning/runAV/common.c:	if ((idx = find_param_idx("MODSEC_PROXY_BLACKLIST",parameters,num_of_params)) >= 0)
util/av-scanning/runAV/common.c:		strcpy(modsec_proxy_blacklist,parameters[idx].value);
util/av-scanning/runAV/common.c:	strcpy(modsec_proxy_blacklist,"/opt/breach/etc/modsec_blacklist.conf");

grep -Ri white | grep -vi "white\s*space" | grep -vi "white\s*paper" | grep -vi "white_check_mark"
tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920510.yaml:    description: "Cache-Control directives whitelist"
tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913100.yaml:   desc: "YUM package manager whitelist"
tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913100.yaml:   desc: "eCairn whitelist"
CHANGES: * Resolve issue 1722 and fix content-type whitelisting (Franziska Bühler)
CHANGES:   whitelisting and rule exclusions (Christian Folini)
CHANGES:* Added Authorized Vulnerability Scanning (AVS) Whitelist rule set
CONTRIBUTING.md:* Check everything against RFC and white listed values for most popular elements
rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf:SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/* "@rx (?i)\b(?:s(?:e(?:t(?:_(?:e(?:xception|rror)_handler|magic_quotes_runtime|include_path)|defaultstub)|ssion_s(?:et_save_handler|tart))|qlite_(?:(?:(?:unbuffered|single|array)_)?query|create_(?:aggregate|function)|p?open|exec)|tr(?:eam_(?:context_create|socket_client)|ipc?slashes|rev)|implexml_load_(?:string|file)|ocket_c(?:onnect|reate)|h(?:ow_sourc|a1_fil)e|pl_autoload_register|ystem)|p(?:r(?:eg_(?:replace(?:_callback(?:_array)?)?|match(?:_all)?|split)|oc_(?:(?:terminat|clos|nic)e|get_status|open)|int_r)|o(?:six_(?:get(?:(?:e[gu]|g)id|login|pwnam)|mk(?:fifo|nod)|ttyname|kill)|pen)|hp(?:_(?:strip_whitespac|unam)e|version|info)|g_(?:(?:execut|prepar)e|connect|query)|a(?:rse_(?:ini_file|str)|ssthru)|utenv)|r(?:unkit_(?:function_(?:re(?:defin|nam)e|copy|add)|method_(?:re(?:defin|nam)e|copy|add)|constant_(?:redefine|add))|e(?:(?:gister_(?:shutdown|tick)|name)_function|ad(?:(?:gz)?file|_exif_data|dir))|awurl(?:de|en)code)|i(?:mage(?:createfrom(?:(?:jpe|pn)g|x[bp]m|wbmp|gif)|(?:jpe|pn)g|g(?:d2?|if)|2?wbmp|xbm)|s_(?:(?:(?:execut|write?|read)ab|fi)le|dir)|ni_(?:get(?:_all)?|set)|terator_apply|ptcembed)|g(?:et(?:_(?:c(?:urrent_use|fg_va)r|meta_tags)|my(?:[gpu]id|inode)|(?:lastmo|cw)d|imagesize|env)|z(?:(?:(?:defla|wri)t|encod|fil)e|compress|open|read)|lob)|a(?:rray_(?:u(?:intersect(?:_u?assoc)?|diff(?:_u?assoc)?)|intersect_u(?:assoc|key)|diff_u(?:assoc|key)|filter|reduce|map)|ssert(?:_options)?)|h(?:tml(?:specialchars(?:_decode)?|_entity_decode|entities)|(?:ash(?:_(?:update|hmac))?|ighlight)_file|e(?:ader_register_callback|x2bin))|f(?:i(?:le(?:(?:[acm]tim|inod)e|(?:_exist|perm)s|group)?|nfo_open)|tp_(?:nb_(?:ge|pu)|connec|ge|pu)t|(?:unction_exis|pu)ts|write|open)|o(?:b_(?:get_(?:c(?:ontents|lean)|flush)|end_(?:clean|flush)|clean|flush|start)|dbc_(?:result(?:_all)?|exec(?:ute)?|connect)|pendir)|m(?:b_(?:ereg(?:_(?:replace(?:_callback)?|match)|i(?:_replace)?)?|parse_str)|(?:ove_uploaded|d5)_file|ethod_exists|ysql_query|kdir)|e(?:x(?:if_(?:t(?:humbnail|agname)|imagetype|read_data)|ec)|scapeshell(?:arg|cmd)|rror_reporting|val)|c(?:url_(?:file_create|exec|init)|onvert_uuencode|reate_function|hr)|u(?:n(?:serialize|pack)|rl(?:de|en)code|[ak]?sort)|(?:json_(?:de|en)cod|debug_backtrac|tmpfil)e|b(?:(?:son_(?:de|en)|ase64_en)code|zopen)|var_dump)(?:\s|/\*.*\*/|//.*|#.*)*\(.*\)" \
rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example:# White-list ASV network block (no blocking or logging of AVS traffic) Update
rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example:# This rule illustrates that we can use tagging very effectively to whitelist a
rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf:# This provides generic whitelist protection against vulnerabilities like
rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf:# Cache-Control Request Header whitelist
rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf:# This rule aims to strictly whitelist the Cache-Control request header
rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf:    tag:'header-whitelist',\
rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf:# Session cookies whitelist
rules/REQUEST-913-SCANNER-DETECTION.conf:# Chained rule is doing whitelist for:
Binary file .git/objects/pack/pack-f7c2e4d6d40a4a820f511ae238c3bfdc6ca4a85c.pack matches
util/av-scanning/runAV/common.h:#define WHITE 1
util/av-scanning/runAV/common.h:EXTERN char modsec_proxy_whitelist[1024];
util/av-scanning/runAV/common.c:	if ((idx = find_param_idx("MODSEC_PROXY_WHITELIST",parameters,num_of_params)) >= 0)
util/av-scanning/runAV/common.c:		strcpy(modsec_proxy_whitelist,parameters[idx].value);
util/av-scanning/runAV/common.c:	strcpy(modsec_proxy_whitelist,"/opt/breach/etc/modsec_whitelist.conf");
`

**Comment by dune73** [comment]
We talked about this issue at our [recent project meeting](https://github.com/coreruleset/coreruleset/issues/2074#issuecomment-856173925).

Decision: @53cur3M3 will address this in a new PR, since the existing PR 2084 is too botched. Leaving this open until the new PR appears.

**Comment by dune73** [comment]
Closing this in favor of PR at #2137.
