### ISSUE TITLE
Request to add files under WEB-INF to restricted-files.data

### ISSUE THREAD

**Issue by vibhasethi** [coreruleset/coreruleset#2089]
Files under WEB-INF contain application configuration and files that should not be externally accessible. Creating this issue to request addition of following  in restricted-files.data.

WEB-INF/web.xml
WEB-INF/classes
WEB-INF/lib

**Comment by azurit** [comment]
Hi @vibhasethi,

thank you for bringing this to our attention, i've already created a pull request which fixes this issue.

**Comment by vibhasethi** [comment]
Thank you!
