### ISSUE TITLE
Rule: 913100 False Positive 0202

### ISSUE THREAD

**Issue by Shajinraj** [coreruleset/coreruleset#2093]
### Description

 [-:error] ********** client **********] ModSecurity: Warning. Match of "rx ^(?:urlgrabber/[0-9\\\\.]+ yum/[0-9\\\\.]+|mozilla/[0-9\\\\.]+ ecairn-grabber/[0-9\\\\.]+ \\\\(\\\\+http://ecairn.com/grabber\\\\))$" against "REQUEST_HEADERS:User-Agent" required. [file ../../coreruleset-3.4-dev/rules/REQUEST-913-SCANNER-DETECTION.conf"] [line "54"] [id "913100"] [msg "Found User-Agent associated with security scanner"] [data "Matched Data: zgrab found within REQUEST_HEADERS:User-Agent: mozilla/5.0 zgrab/0.x"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation-scanner"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/224/541/310"] [tag "PCI/6.5.10"] [hostname "******"] [uri "/"] [unique_id "*********"]

### Your Environment

*CRS version (e.g., v3.2.0):
Paranoia level setting: 1
ModSecurity version (e.g., 2.9.3):
Web Server and version (e.g., httpd 2.4.41):
Operating System and version: RHEL 7.9

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

Hi Team,

We could see the above issue in error logs , Could you please help how we can proceed with this?

**Comment by azurit** [comment]
Hi,

you are accessing your site using software which is associated with security scanners (zgrab). What software it is?

**Comment by Shajinraj** [comment]
Hi ,

We are accessing the site only through the browser!

**Comment by azurit** [comment]
This isn't a browser:
`User-Agent: mozilla/5.0 zgrab/0.x`

https://github.com/zmap/zgrab

**Comment by Shajinraj** [comment]
http-user-agent string
    	Set a custom HTTP user agent (default "Mozilla/5.0 zgrab/0.x")

We are using only the browsers to access, Could you please help with this and what changes we need to implement?

**Comment by 53cur3M3** [comment]
As the rule you reported is matching zgrab in the user-agent string you could just set http-user-agent to just "Mozilla/5.0" or pretty much anything else to avoid this rule being triggered.

**Comment by Shajinraj** [comment]
No , Am not sure what do you mean.

Is that I need to make some conf changes in crs.conf?

**Comment by dune73** [comment]
Have not heard from the reporter anymore with *need more infos* for over a month. Closing this.

If infos become available, then please re-open.
