### ISSUE TITLE
application/x-git-upload-pack-request - content type is not allowed by policy

### ISSUE THREAD

**Issue by ar-daniel** [coreruleset/coreruleset#2114]
### Description

Setup - gitea (git server running at localhost) behind nginx 
Tried to do git clone in command line - received 403 error
(works without modsecurity). 

From the audit log i believe the issue is - Request content type is not allowed by policy
application/x-git-upload-pack-request. 
Moreover I'm able to download the git repo from the gitea web interface as a zip file. (guess it might have different procedure to fetch)

Expected - to be able to do git command line operations on a git server running behind nginx with modsecurity 

### Audit Logs / Triggered Rule Numbers

---ASAWrFS5---A--
[05/Jun/2021:00:11:56 +0530] 162283211624.549894 xxx.xxx.xxx.xxx 34088 xxx.xxx.xxx.xxx 443
---ASAWrFS5---B--
POST /TestSampleOrg/test_repo_plain.git/git-upload-pack HTTP/2.0
host: zzzzz.xxxxx.tld
authorization: Basic < some hash string here >
user-agent: git/2.25.1
accept-encoding: deflate, gzip, br
content-type: application/x-git-upload-pack-request
accept: application/x-git-upload-pack-result
content-length: 165

---ASAWrFS5---D--

---ASAWrFS5---E--
 html <head><title>403 Forbidden</title></head> body  center  h1 403 Forbidden /h1 /center hr  center nginx /center  /body /html 

---ASAWrFS5---F--
HTTP/2.0 403
Server: nginx
Date: Fri, 04 Jun 2021 18:41:56 GMT
Content-Length: 146
Content-Type: text/html
Connection: close

---ASAWrFS5---H--
ModSecurity: Warning. Matched "Operator `Within' with parameter `|application/x-www-form-urlencoded| |multipart/form-data| |multipart/related| |text/xml| |application/xml| |application/soap+xml| |application/x-amf| |application/json| |application/cloudevents+json|  (134 characters omitted)' against variable `TX:content_type' (Value: `|application/x-git-upload-pack-request|' ) [file "/usr/local/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "937"] [id "920420"] [rev ""] [msg "Request content type is not allowed by policy"] [data "application/x-git-upload-pack-request"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153"] [tag "PCI/12.1"] [hostname "xxx.xxx.xxx.xxx"] [uri "/TestSampleOrg/test_repo_plain.git/git-upload-pack"] [unique_id "162283211624.549894"] [ref "o0,37v241,37t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "xxx.xxx.xxx.xxx"] [uri "/TestSampleOrg/test_repo_plain.git/git-upload-pack"] [unique_id "162283211624.549894"] [ref ""]

---ASAWrFS5---I--

---ASAWrFS5---J--

---ASAWrFS5---Z--

### Your Environment

* CRS version : v3.3.0
* Paranoia level setting: (how do i find this? i think its default )
* ModSecurity version : v3.0.4 (13 Jan 2020)
* ModSecurity- Nginx connector - used the latest git version as on 03rd June
* Web Server and version : nginx v1.21.0
* Gitea : v1.14.2
* Operating System and version: 
     server -  ubuntu server 20.04 LTS
     client - linux mint mate 20 ulyana
     user-agent: git/2.25.1  (same version in server)

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by fzipi** [comment]
Hi @ar-daniel !

Please take a look at your `crs-setup.conf` file. This is configurable for your reality. See [here in the example](https://github.com/coreruleset/coreruleset/blob/155d2294f373b03dcc1d379974914b876c1e09f1/crs-setup.conf.example#L421):
```
# Content-Types that a client is allowed to send in a request.
# Default: |application/x-www-form-urlencoded| |multipart/form-data| |multipart/related|
# |text/xml| |application/xml| |application/soap+xml| |application/x-amf| |application/json|
# |application/cloudevents+json| |application/cloudevents-batch+json| |application/octet-stream|
# |application/csp-report| |application/xss-auditor-report| |text/plain|
# Uncomment this rule to change the default.
#SecAction \
# "id:900220,\
#  phase:1,\
#  nolog,\
#  pass,\
#  t:none,\
#  setvar:'tx.allowed_request_content_type=|application/x-www-form-urlencoded| |multipart/form-data| |multipart/related| |text/xml| |application/xml| |application/soap+xml| |application/x-amf| |application/json| |application/cloudevents+json| |application/cloudevents-batch+json| |application/octet-stream| |application/csp-report| |application/xss-auditor-report| |text/plain|'"
```

So you just need to uncomment that line, and add your allowed content types.

**Comment by ar-daniel** [comment]
Thank you very much, this worked. 

I hadn't known the setting can be overridden, least how to override it. 
Is there docs on manual configuration you would suggest.?

with some search, I've found these 
https://www.netnea.com/cms/nginx-modsecurity-tutorials/
https://www.netnea.com/cms/nginx-tutorial-8_handling-false-positives-modsecurity-core-rule-set/
Are the above links the ones to look for reference. Please suggest.

**Comment by fzipi** [comment]
I'm glad it worked!

The above links are excellent as reference 🙂
