### ISSUE TITLE
PHPMyAdmin exclusion rules

### ISSUE THREAD

**Issue by aus-coder** [coreruleset/coreruleset#2134]
Exclusion rules defined for PHPMyAdmin in `REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf ` files are for 4.x branch of PHPMyAdmin but in latest 5.x branch URLs are in different format.

For example for SQL query page the URL is `/index.php?route=/server/sql`

All URLs in this version use routes instead of static page names.

Is there a plan to upgrade the exclusion file? Or is there one already?

**Comment by azurit** [comment]
Hi @aus-coder, we are already working on this!

**Comment by aus-coder** [comment]
Great, thank you! I wasn't aware of this, so reported it after encountering the problem today.

**Comment by dune73** [comment]
Thank you for reporting @aus-coder. We hope to deliver the update soon. Closing this in the meantime.
