### ISSUE TITLE
WordPress /wp-admin/site-health.php triggers

### ISSUE THREAD

**Issue by fancsali** [coreruleset/coreruleset#2142]
### Description

Trying to open `/wp-admin/site-health.php` triggers a `403` despite being a legit request; despite the WP exception rules being enabled in `/etc/modsecurity/crs/crs-setup.conf`:

```
SecAction  "id:900130,  phase:1,  nolog,  pass,  t:none,  setvar:tx.crs_exclusions_wordpress=1"
```

### Audit Logs / Triggered Rule Numbers

```
Message: Warning. Pattern match "(?i)(?:System\\.Data\\.OleDb\\.OleDbException|\\[Microsoft\\]\\[ODBC SQL Server Driver\\]|\\[Macromedia\\]\\[SQLServer JDBC Driver\\]|\\[SqlException|System\\.Data\\.SqlClient\\.SqlException|Unclosed quotation mark after the character string|'80040e14' ..." at RESPONSE_BODY. [file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "340"] [id "951220"] [msg "mssql SQL Information Leakage"] [data "Matched Data: SQL server is up to date\x22,\x22status\x22:\x22good\x22,\x22badge\x22:{\x22label\x22:\x22Performance\x22,\x22color\x22:\x22blue\x22},\x22description\x22:\x22<p>The SQL server is a required piece of software for the database WordPress uses to store all your site&#8217;s content and settings.<\x5c/p>\x22,\x22actions\x22:\x22<p><a href=\x5c\x22https:\x5c/\x5c/wordpress.org\x5c/about\x5c/requirements\x5c/\x5c\x22 target=\x5c\x22_blank\x5c\x22 rel=\x5c\x22noopener\x5c\x22>Learn more about what ..."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "applic
Message: Warning. Pattern match "(?:\\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|call_user_func)|\\$_(?:(?:pos|ge)t|session))\\b" at RESPONSE_BODY. [file "/usr/share/modsecurity-crs/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "72"] [id "953110"] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\x0a<html class=\x22wp-toolbar\x22\x0a\x09lang=\x22en-GB\x22>\x0a<head>\x0a<meta http-equiv=\x22Content-Type\x22 content=\x22text/html; charset=UTF-8\x22 />\x0a\x09<title>Site Health Status &lsaquo; mysite.com &#8212; WordPress</title>\x0a<script type=\x22text/javascript\x22>\x0aaddLoadEvent = function(func){if(typeof jQuery!=='undefined')jQuery(document).ready(func);else if(typeof wpOnload!=='function'){wpOnload=func;}else{var oldonload..."] [severity "ERROR"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "
Message: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/usr/share/modsecurity-crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "76"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 9)"] [ver "OWASP_CRS/3.3.0"] [tag "anomaly-evaluation"]
Message: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/usr/share/modsecurity-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "102"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 9): individual paranoia level scores: 9, 0, 0, 0"] [ver "OWASP_CRS/3.3.0"] [tag "event-correlation"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 2a0b:f4c2:1::1] ModSecurity: Warning. Pattern match "(?i)(?:System\\\\\\\\.Data\\\\\\\\.OleDb\\\\\\\\.OleDbException|\\\\\\\\[Microsoft\\\\\\\\]\\\\\\\\[ODBC SQL Server Driver\\\\\\\\]|\\\\\\\\[Macromedia\\\\\\\\]\\\\\\\\[SQLServer JDBC Driver\\\\\\\\]|\\\\\\\\[SqlException|System\\\\\\\\.Data\\\\\\\\.SqlClient\\\\\\\\.SqlException|Unclosed quotation mark after the character string|'80040e14' ..." at RESPONSE_BODY. [file "/usr/share/modsecurity-crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "340"] [id "951220"] [msg "mssql SQL Information Leakage"] [data "Matched Data: SQL server is up to date\\\\x22,\\\\x22status\\\\x22:\\\\x22good\\\\x22,\\\\x22badge\\\\x22:{\\\\x22label\\\\x22:\\\\x22Performance\\\\x22,\\\\x22color\\\\x22:\\\\x22blue\\\\x22},\\\\x22description\\\\x22:\\\\x22<p>The SQL server is a required piece of software for the database WordPress uses to store all your site&#8217;s content and settings.<\\\\x5c/p>\\\\x22,\\\\x22actions\\\\x22:\\\\x22<p><a href=\\\\x5c\\\\x22https:\\\\x5c/\\\\x5c/wordpress.org\\\\x5c/about\\\\x5c/requirements\\\\x5c/\\\\x5c\\\\x22 target=\\\\x5c\\\\x22_blank\\\\x5c\\\\x22 rel=\\\\x5c\\\\x22noopener\\\\x5c\\\\x22>Learn more about what ..."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "applic [hostname "mysite.com"] [uri "/wp-admin/site-health.php"] [unique_id "YNsA-Eye9KCGHwEDyWp6iAAAAAw"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 2a0b:f4c2:1::1] ModSecurity: Warning. Pattern match "(?:\\\\\\\\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|call_user_func)|\\\\\\\\$_(?:(?:pos|ge)t|session))\\\\\\\\b" at RESPONSE_BODY. [file "/usr/share/modsecurity-crs/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "72"] [id "953110"] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\\\\x0a<html class=\\\\x22wp-toolbar\\\\x22\\\\x0a\\\\x09lang=\\\\x22en-GB\\\\x22>\\\\x0a<head>\\\\x0a<meta http-equiv=\\\\x22Content-Type\\\\x22 content=\\\\x22text/html; charset=UTF-8\\\\x22 />\\\\x0a\\\\x09<title>Site Health Status &lsaquo; mysite.com &#8212; WordPress</title>\\\\x0a<script type=\\\\x22text/javascript\\\\x22>\\\\x0aaddLoadEvent = function(func){if(typeof jQuery!=='undefined')jQuery(document).ready(func);else if(typeof wpOnload!=='function'){wpOnload=func;}else{var oldonload..."] [severity "ERROR"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag " [hostname "mysite.com"] [uri "/wp-admin/site-health.php"] [unique_id "YNsA-Eye9KCGHwEDyWp6iAAAAAw"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 2a0b:f4c2:1::1] ModSecurity: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/usr/share/modsecurity-crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "76"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 9)"] [ver "OWASP_CRS/3.3.0"] [tag "anomaly-evaluation"] [hostname "mysite.com"] [uri "/wp-admin/site-health.php"] [unique_id "YNsA-Eye9KCGHwEDyWp6iAAAAAw"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 2a0b:f4c2:1::1] ModSecurity: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/usr/share/modsecurity-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "102"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 9): individual paranoia level scores: 9, 0, 0, 0"] [ver "OWASP_CRS/3.3.0"] [tag "event-correlation"] [hostname "mysite.com"] [uri "/wp-admin/site-health.php"] [unique_id "YNsA-Eye9KCGHwEDyWp6iAAAAAw"]
Action: Intercepted (phase 4)
Apache-Handler: application/x-httpd-php
Stopwatch: 1624965372200929 181340 (- - -)
Stopwatch2: 1624965372200929 181340; combined=40209, p1=3533, p2=8491, p3=103, p4=27833, p5=249, sr=320, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.3.0.
Server: Apache
Engine-Mode: "ENABLED"
```

### Your Environment

* CRS version (e.g., v3.2.0): v3.3.0
* Paranoia level setting: default
* ModSecurity version (e.g., 2.9.3): v2.9.3
* Web Server and version (e.g., apache 2.4.41): 2.4.38 (Debian)
* Operating System and version:  Debian 10.10 (buster)

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
Hi @fancsali!

Thank you for reporting this. Can you attach the output of such request if it isn't blocked?

**Comment by lifeforms** [comment]
I have actually just had a similar problem with a customer. The output of their Site Health page included `session_start()` which triggered a PHP leakage rule. 

Depending on the plugins used, this page may echo various "suspicious" strings about your PHP and database setup. I think it is quite safe to exclude this in our package, as the explicit purpose of the Site Health page is to report details on the PHP and MySQL installation.

Could you try adding the following rule to your configuration to see if this fixes your problem?

```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002830,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveById=951220,\
    ctl:ruleRemoveById=953110,\
    ver:'OWASP_CRS/3.4.0-dev'"
```

**Comment by dune73** [comment]
@fancsali : Did you have time to try this out? Did it fix your problem? If yes, we can make it part of our standard rule exclusion packages.

**Comment by fancsali** [comment]
Well, indeed, I've been playing around with this, and it seems, I've settled on this:

```
SecRule REQUEST_FILENAME "@beginsWith /wp-admin/" \
    "id:1000,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveById=941100,\
    ctl:ruleRemoveById=941110,\
    ctl:ruleRemoveById=941160,\
    ctl:ruleRemoveById=941180,\
    ctl:ruleRemoveById=951220,\
    ctl:ruleRemoveById=953100,\
    ctl:ruleRemoveById=953110,\
    ctl:ruleRemoveById=953120"
```

On one hand, this is quite a specific exception: it will apply to anything below `/wp-admin`, but not the login page at `/wp-login.php` itself, so it shouldn't compromise the security of the login system itself,

On the other hand, however, some of those rules would switch off PHP and MySQL information leak, and XSS rules: without that the embedded pop-up info window about the plugins in the plugin installer would not work, as those contain a tab for the support forums, which often has discussion about bugs, and error messages.

I am not sure, though, whether those are **acceptable risks** or ones that we **have to accept**.

Is an attack through the forums a feasible one?

**Comment by theMiddleBlue** [comment]
note from monthly issue chat: I'll try and check @lifeforms exclusion rules version to add it on WP RE file.

example:
```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002830,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveById=951220,\
    ctl:ruleRemoveById=953110,\
    ver:'OWASP_CRS/3.4.0-dev'"
```

**Comment by dune73** [comment]
Any update here @theMiddleBlue ?

**Comment by dune73** [comment]
Issue chat: We concluded that we will stick to the smaller original RE proposal. We're incorporating a pull request that implements this and will close the issue afterwards. If you insist on the longer list, we need logs to back that up.

**Comment by mackov83** [comment]
Hi, I am facing a very similar issue as discussed above, however with CRS 3.3.2. In my case the fix didn't work, I end up with a blank page. Browser debug shows: 'Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR'

Note: I also spotted that rule 9002830 already exists

``
---iNxqEvMX---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)(?:System\.Data\.OleDb\.OleDbException|\[Microsoft\]\[ODBC SQL Server Driver\]|\[Macromedia\]\[SQLServer JDBC Driver\]|\[SqlException|System\.Data\.SqlClient\.SqlException|Unclosed quotation mark  (641 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Cont (87088 characters omitted)' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "322"] [id "951220"] [rev ""] [msg "mssql SQL Information Leakage"] [data "Matched Data: accept-language found within TX:sql_error_match: 1"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-mssql"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116/54"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629213338"] [ref "o56805,25500v1209,82625"]
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|ca (43 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Cont (87088 characters omitted)' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "52"] [id "953110"] [rev ""] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\x0a\x09<title>Sit (82481 characters omitted)"] [severity "3"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116"] [tag "PCI/6.5.6"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629213338"] [ref "o56570,13v1209,82625"]
ModSecurity: Access denied with code 200 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `9' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "68"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 9)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629213338"] [ref ""]
``

**Comment by azurit** [comment]
> Note: I also spotted that rule 9002830 already exists

@mackov83 Change ID to `9002840` here:
`    "id:9002830,\`

**Comment by mackov83** [comment]
Thanks @azurit, that part I figured out for myself by using a new rule ID which wasn't a duplicate - something which I tested is checked when reloading nginx. 

However the recommended fix still triggers the same rules. Below is the code I inserted into REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf

```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002840,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveById=951220,\
    ctl:ruleRemoveById=953110,\
    ver:'OWASP_CRS/3.4.0-dev'"
```

**Comment by azurit** [comment]
Can you try changing phase to 4?

`    phase:4,\`

**Comment by mackov83** [comment]
Before I saw your message, I had changed the rule based on: https://github.com/coreruleset/coreruleset/blob/c6ea99c573564159aa4478d1231fa9534226fd6d/rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf

I switched from ```@endsWith``` to ```@rx```. This seemed to work as the page itself loads, however the usual checks performed on this page don't complete.

When I checked the audit log, I was seeing that the same rules 951220 and 953110 are triggering.

After seeing your message to change to phase 4, I reverted the config to get back to known fail scenario, however the page is still visible. I'm guessing there could be some form of caching happening now?

**Comment by azurit** [comment]
I don't know your setup but ModSecurity itself is not doing any cacheing.

Please use `@endsWith /wp-admin/site-health.php`, it's sufficient, `@rx` is regexp matching.

**Comment by azurit** [comment]
What about this?
```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002840,\
    phase:4,\
    pass,\
    t:none,\
    nolog,\
    ver:'OWASP_CRS/3.4.0-dev',\
    ctl:ruleRemoveTargetById=951220;TX:sql_error_match,\
    ctl:ruleRemoveTargetById=953110;TX:sql_error_match"
```

**Comment by mackov83** [comment]
Less errors in the audit log, but still not working. Only triggering 953110 now:

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|ca (43 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Cont (86178 characters omitted)' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "52"] [id "953110"] [rev ""] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\x0a\x09<title>Sit (81571 characters omitted)"] [severity "3"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116"] [tag "PCI/6.5.6"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629846326"] [ref "o56030,13v1579,81715"]
ModSecurity: Access denied with code 200 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `4' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "68"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629846326"] [ref ""]
```

**Comment by azurit** [comment]
Oh, sorry, there's a mistake in the last line:

```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002840,\
    phase:4,\
    pass,\
    t:none,\
    nolog,\
    ver:'OWASP_CRS/3.4.0-dev',\
    ctl:ruleRemoveTargetById=951220;TX:sql_error_match,\
    ctl:ruleRemoveTargetById=953110;RESPONSE_BODY"

```

**Comment by mackov83** [comment]
Doesn't look to have made any difference:

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|ca (43 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Cont (86110 characters omitted)' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "52"] [id "953110"] [rev ""] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-AU">\x0a<head>\x0a<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\x0a\x09<title>Sit (81503 characters omitted)"] [severity "3"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116"] [tag "PCI/6.5.6"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629890126"] [ref "o56030,13v1362,81647"]
ModSecurity: Access denied with code 200 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `4' ) [file "/usr/local/coreruleset-3.3.2/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "68"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "10.83.10.40"] [uri "/wp-admin/site-health.php"] [unique_id "1629890126"] [ref ""]
```

**Comment by azurit** [comment]
I don't see any other problem in that exclusion rule.

**Comment by azurit** [comment]
Can you provide full output from that page?

**Comment by mackov83** [comment]
[modsec_audit.log](https://github.com/coreruleset/coreruleset/files/7046603/modsec_audit.log)

**Comment by azurit** [comment]
Works ok for me (but i'm testing on Apache), please recheck you installed my exclusion rule correctly.

**Comment by mackov83** [comment]
Ok, I got it working with the following:

```
SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
    "id:9002840,\
    phase:4,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetById=951220;TX:sql_error_match,\
    ctl:ruleRemoveTargetById=953110;RESPONSE_BODY,\
    ver:'OWASP_CRS/3.4.0-dev'"
```

**Comment by azurit** [comment]
Do you mean by reordering actions?

**Comment by mackov83** [comment]
To be honest I am not 100% sure. 

When I read your message about rechecking the rule, I reordered things (ver: at the end) to ensure that all the syntax was in the correct place which worked.

I have now retested with ctl lines last which also worked. I have a feeling I might not have reloaded Nginx after making the change first time around.

**Comment by dune73** [comment]
Thank you for your support with testing this so intensively, @mackov83.

@azurit : Are you planning to provide a PR here, or should we look for a different volunteer?

**Comment by azurit** [comment]
Sorry, i was planning to get back to this.

I need to test solution (https://github.com/coreruleset/coreruleset/issues/2142#issuecomment-870534060) from @lifeforms because it should work (but it wasn't for @mackov83 ).

**Comment by dune73** [comment]
Nothing to be sorry for. But good to hear you are committed to this problem. I'm co-assigning you.

@lifeforms, if you want, feel free to unassign yourself, we have a new volunteer. :)

**Comment by dune73** [comment]
Issue covered in the [September issue chat](https://github.com/coreruleset/coreruleset/issues/2185#issuecomment-913804183).

@lifeforms will do a PR to address the PUT problem.

**Comment by dennismayr** [comment]
> Ok, I got it working with the following:
> 
> ```
> SecRule REQUEST_FILENAME "@endsWith /wp-admin/site-health.php" \
>     "id:9002840,\
>     phase:4,\
>     pass,\
>     t:none,\
>     nolog,\
>     ctl:ruleRemoveTargetById=951220;TX:sql_error_match,\
>     ctl:ruleRemoveTargetById=953110;RESPONSE_BODY,\
>     ver:'OWASP_CRS/3.4.0-dev'"
> ```

This did the trick for me!

**Comment by azurit** [comment]
@dennismayr Thanks for getting back to us! Can you be so kind and test it also with this little change?
`phase:1,\`

**Comment by dennismayr** [comment]
It worked as well.

You may have nailed a good workaround.

**Comment by dune73** [comment]
I doubt we will hear from @mackov83 again. 

@azurit do you have enough information to do a PR based on what we have (also including the welcome confirmation by @dennismayr)?

**Comment by dennismayr** [comment]
It works for me :)

**Comment by mackov83** [comment]
@dune73 was there something that you need from me?

I have to be honest, I stopped using the nginx and modsecurity solution as I managed to gain access to a commercially available solution under extremely cost effectively :)

**Comment by azurit** [comment]
I think this can be closed. Thanks to everyone involved!

**Comment by dune73** [comment]
Thanks for the heads up, @mackov83. Glad you found a solution.

I agree with closing.

**Comment by cmschlenke** [comment]
@azurit Am I understanding correctly that this fix will be deployed in CRS? Or no? I added the latest fix from @dennismayr to my server, but I want to know if/when I can remove redundant code if it is deployed as part of CRS. Thank you.

**Comment by azurit** [comment]
@cmschlenke It will be a part of next release (4.0) but in a form of a plugin, see:
https://github.com/coreruleset/wordpress-rule-exclusions-plugin
