### ISSUE TITLE
Rule 942100 is still triggered after setting ruleRemoveById

### ISSUE THREAD

**Issue by skwokie** [coreruleset/coreruleset#2145]
### Describe the bug
Hi, rule 942100 is triggered with audit log:
```
ModSecurity: Warning. detected SQLi using libinjection. [file "/usr/local/owasp-modsecurity-crs-3.0.2/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "43"] [id "942100"] [rev "1"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: 1o(1& found within ARGS:2dc05eb6: 220+(820||115 nF)"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [hostname "172.18.0.2"] [uri "/a/b/c/d"] [unique_id "162425608090.030571"] [ref "v73,17"]
ModSecurity: Access denied with code 404 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs-3.0.2/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "44"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "172.18.0.2"] [uri "/a/b/c/d"] [unique_id "162425608090.030571"] [ref ""]
```
I've tried to exclude it by creating this exclusion rule in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf; however, 942100 is still being triggered. 
```
SecRule REQUEST_URI "@streq /a/b/c/d" \
        "phase:2,log,pass,id:21506,ctl:ruleRemoveById=942100"
```

### Expected behaviour
I expect 942100 not to be triggered with the exclusion rule for the particular uri.

### Additional context
As suggested by someone on serverfault.com, I've also tried excluding the rule in phase 1 but to no avail.

### Your Environment
* CRS version (e.g., v3.2.0): 3.0.3
* Paranoia level setting: default
* ModSecurity version (e.g., 2.9.3): 3.0.3
* Web Server and version (e.g., apache 2.4.41): nginx 1.13.6
* Operating System and version: Ubuntu 18.04.3 LTS
* Container info: openresty/openresty:1.13.6.2-2-bionic

**Comment by dune73** [comment]
The alert message that you posted contains the URI without the query string. The variable REQUEST_URI contains the URI including the query string and then you continue with the streq operator. In rule exclusions, I usually use the beginsWith operator.

Other than that, this looks good to me.

**Comment by skwokie** [comment]
Hi, thanks so much for your prompt response. Just to make sure I understand correctly, you are saying that although my exclusion rule's URI matches the one in the audit log, the call actually has query string and so I need to use beginsWith instead. Thanks.

**Comment by dune73** [comment]
Yes, exactly. 

It is not obvious the audit log URI is stripped down, it's just ModSec trying to make you miserable.

beginsWith should do the job, if not, then please provide the original request and I can run a quick test.

**Comment by dune73** [comment]
Any update here, @skwokie? If not, we're going to close this issue soon.

**Comment by skwokie** [comment]
Thanks so much for your help!

**Comment by dune73** [comment]
You're most welcome.
