### ISSUE TITLE
Addressing requests to /proc and /sys

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2147]
### Description

We do not really cover requests to `/proc` as LFI attempts. I am not sure the whole tree can be blocked, but it has to be assessed what can be done about it.

### Your Environment

irrelevant

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
I think blocking `/proc` might cause too much FP in text like `/procedures` but we should do a thorough listing of our `/proc` filesystems to block as much as possible.

Note that we have already some proc entries in `lfi-os-files.data`. We have also `restricted-files.data`. I think the proc entries should be added to both (so they are blocked as REQUEST_FILENAME but also as form parameters).  

I think we can do away with doing a text match since these strings seem quite technical.

The following proc strings are from Ubuntu 18.04 and Ubuntu 20.4 systems. I turned the pids (e.g. `/proc/1234`) into a string that matches all pids. Does anyone have a Red Hat linux system? They may have some other additions, you can get them with `echo /proc/* | xargs -n 1 echo | sort`

```
/proc/0
/proc/1
/proc/2
/proc/3
/proc/4
/proc/5
/proc/6
/proc/7
/proc/8
/proc/9
/proc/acpi
/proc/buddyinfo
/proc/bus
/proc/cgroups
/proc/cmdline
/proc/config.gz
/proc/consoles
/proc/cpuinfo
/proc/crypto
/proc/devices
/proc/diskstats
/proc/dma
/proc/docker
/proc/driver
/proc/execdomains
/proc/fb
/proc/filesystems
/proc/fs
/proc/interrupts
/proc/iomem
/proc/ioports
/proc/ipmi
/proc/irq
/proc/kallsyms
/proc/kcore
/proc/key-users
/proc/keys
/proc/kmsg
/proc/kpagecgroup
/proc/kpagecount
/proc/kpageflags
/proc/latency_stats
/proc/loadavg
/proc/locks
/proc/mdstat
/proc/meminfo
/proc/misc
/proc/modules
/proc/mounts
/proc/mpt
/proc/mtrr
/proc/net
/proc/pagetypeinfo
/proc/partitions
/proc/sched_debug
/proc/schedstat
/proc/scsi
/proc/self
/proc/slabinfo
/proc/softirqs
/proc/stat
/proc/swaps
/proc/sys
/proc/sysrq-trigger
/proc/sysvipc
/proc/thread-self
/proc/timer_list
/proc/timer_stats
/proc/tty
/proc/uptime
/proc/version
/proc/version_signature
/proc/vmallocinfo
/proc/vmstat
/proc/zoneinfo
```

**Comment by airween** [comment]
>  Does anyone have a Red Hat linux system? They may have some other additions, you can get them with `echo /proc/* | xargs -n 1 echo | sort`
> 

On Debian 11 I've found these additions:

```
/proc/dynamic_debug
/proc/keys
/proc/pressure
```

RH 8.2 additions:
```
/proc/asound
```
Sles 15 contains mixed of items above.

**Comment by RedXanadu** [comment]
I could take a stab at this.

Arch brings to the table:
```
/proc/bootconfig
```

and CentOS 6.8 adds:
```
/proc/mtd
```

---

So, this long, amalgamated list is being added to both `lfi-os-files.data` and `restricted-files.data`, except maybe the `/proc/<digit>` entries?

Should the existing `/proc/...` entries from `lfi-os-files.data` also be added to `restricted-files.data`? For quick reference, those current, existing entries are:
```
proc/self/environ
proc/self/mounts
proc/self/stat
proc/self/status
proc/self/cmdline
proc/self/fd/0
proc/self/fd/1
proc/self/fd/2
proc/self/fd/3
proc/self/fd/4
proc/self/fd/5
proc/self/fd/6
proc/self/fd/7
proc/self/fd/8
proc/self/fd/9
proc/self/fd/10
proc/self/fd/11
proc/self/fd/12
proc/self/fd/13
proc/self/fd/14
proc/self/fd/15
proc/version
proc/devices
proc/cpuinfo
proc/meminfo
proc/net/tcp
proc/net/udp
```

**Comment by dune73** [comment]
I think this is the right approach, @RedXanadu. Thanks.

As for @lifeforms's question about the API's interested in `.../proc/1` and the like. I do see that as well as a possibility. But I would let it run and tackle it once people really report FPs.

**Comment by dune73** [comment]
Closing this after #2154 has been merged.
