### ISSUE TITLE
Could not block IP address of brute force attack using modsecurity & core rule set.

### ISSUE THREAD

**Issue by devikandixit** [coreruleset/coreruleset#2153]
We are using apache windows web server. When client hits our web URL we have a log in page (this is apache managed) that authenticates the user.
We need to take action for unsuccessful log in attempts by the user.
We wanted to delay log in process for the brute force attacker after 3 unsuccessful log in attempts.

For this we are experimenting the use of Mod Security module (ModSecurity 2.x) .
I have used the following configuration file in main apache config file (httpd.conf)
modsecurity-minimal.conf
crs-setup.conf
REQUEST-912-DOS-PROTECTION.conf

I have enabled the log and checked configuration statements are being executed. Logging is happening.

However even after 3 unsuccessful attempts the log in page is not delayed.

I have below settings in modsecurity-minimal.conf

SecRule RESPONSE_STATUS "403" "phase:4,id:4001,setvar:ip.block_script=+1,expirevar:ip.block_script=1800,msg:'Attack Detected'"
SecRule ip:block_script "@ge 2" "phase:1, deny, status:406, id:4002, msg:'Repetitive Attack from the same IP Address'"

Please help me how to fix this issue.

**Comment by dune73** [comment]
Hi there, thanks for writing in, yet I think you are using the wrong tool to fight this.

The DoS protection rules are not the strongest part of CRS and they are not useful for bruteforce attacks unless you know them by heart and tweak them to work.

What you should be looking into is mod_qos that is doing exactly what you want. 

I am closing this. If you are convinced this is a CRS malfunction, then please point out exactly where the error is.

**Comment by devikandixit** [comment]
Thank you. However I dont think mod_qos will fix our issue.

We are using Apache server on Windows. We do not have our own custom login page for our web server. We are relying on OS controlled(NTLM/Kerberos Authentication)log in page. However log in page do not prevent user log in (delayed log in for ex) after unsuccessful authentication. Hence we thought to use Mod Security to prevent it.

Also we used CRS Corerule sets like below. Still we are getting the issue stated above.

https://github.com/fabiocicerchia/OWASP-CRS/blob/master/experimental_rules/modsecurity_crs_11_brute_force.conf
