### ISSUE TITLE
blocking allowed content-type

### ISSUE THREAD

**Issue by dosfx** [coreruleset/coreruleset#2161]
### Description
```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^application/repository.jdbcDataSource+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-str (69 characters omitted)' against variable `TX:0' (Value: `application/repository.jdbcDataSource+json' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "894"] [id "920420"] [rev ""] [msg "Request content type is not allowed by policy"] [data "application/repository.jdbcDataSource+json"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"] [hostname "172.20.0.12"] [uri "/jasperserver/rest_v2/connections"] [unique_id "1626378869"] [ref "o0,42v468,42"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "79"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "172.20.0.12"] [uri "/jasperserver/rest_v2/connections"] [unique_id "1626378869"] [ref ""]
```

### Audit Logs / Triggered Rule Numbers

900220 I think?

### Your Environment

* CRS version (e.g., v3.2.0): 3.2.0
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): 3.2.0
* Web Server and version (e.g., apache 2.4.41): nginx 1.21.1
* Operating System and version: debian buster (in a docker container)

### Confirmation

[*] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

As you can see from the audit log we have already added `application/repository.jdbcDataSource+json` to the `tx.allowed_request_content_type` but it is still blocking.

Thanks!

**Comment by fzipi** [comment]
Thanks for the report, will be checking this one shortly.

**Comment by airween** [comment]
hi @dosfx,

> As you can see from the audit log we have already added `application/repository.jdbcDataSource+json` to the `tx.allowed_request_content_type` but it is still blocking.

I think you've missed to attach your audit log, but based on the info above I'm afraid you have added the CT with wrong format - eg. you forgot to escape the `+`?

See this [regex](https://regex101.com/r/f7RhKl/1)

**Comment by dosfx** [comment]
Thanks for the reply, @airween. We thought that might be the issue, but the default contains `application/soap+xml` without an escaped `+`, so we moved on.

I will give it a try and report back.

**Comment by dosfx** [comment]
@airween That worked! Thanks again for looking at it.

Someone might want to double check that the `application/soap+xml` in the default works.

**Comment by airween** [comment]
> @airween That worked! Thanks again for looking at it.

you're welcome!

> Someone might want to double check that the `application/soap+xml` in the default works.

I'll do that soon. Thanks for your help!

**Comment by airween** [comment]
Hi @dosfx,

sorry for the question, are you sure you use CRS 3.2?

The rule [920420](https://github.com/coreruleset/coreruleset/blob/v3.2/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L915) uses `@rx`. Now I've checked, and it works **without** escape sequence (you can see the escaped characters, but the reason is simple: the engine puts these sequences to there):

```
Rule 7fbc1c8681f0: SecRule "TX:content_type" "!@rx ^%{tx.allowed_request_content_type}$" "t:lowercase,setvar:tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}"
T (0) lowercase: "|application/repository.jdbcdatasource+json|"
Transformation completed in 7 usec.
Executing operator "!rx" with param "^%{tx.allowed_request_content_type}$" against TX:content_type.
Target value: "|application/repository.jdbcdatasource+json|"
Resolved macro %{tx.allowed_request_content_type} to: |application/x-www-form-urlencoded| |multipart/form-data| |multipart/related| |text/xml| |application/xml| |application/soap+xml| |application/x-amf| |application/json| |application/cloudevents+json| |application/cloudevents-batch+json| |application/octet-stream| |application/csp-report| |application/xss-auditor-report| |text/plain| |application/repository.jdbcDataSource+json| 
Escaping pattern [^|application\/x-www-form-urlencoded| |multipart\/form-data| |multipart\/related| |text\/xml| |application\/xml| |application\/soap\+xml| |application\/x-amf| |application\/json| |application\/cloudevents\+json| |application\/cloudevents-batch\+json| |application\/octet-stream| |application\/csp-report| |application\/xss-auditor-report| |text\/plain| |application\/repository\.jdbcDataSource\+json| $]
Operator completed in 164 usec.
Rule returned 0.
```

The operator has changed meantime, since the [3.3](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L957) we are using `@within` - and there your CT header does not work. More investigation needed, but first please help us to clarify the version.

**Comment by airween** [comment]
Okay, I found the reason of the false behavior: `@rx` uses case-insensitive, but `@within` doesn't.

I assume you put the new CT as you wrote: `application/repository.jdbcDataSource+json`, not `application/repository.jdbcdatasource+json`. If you use this one, it should have to work.

**Comment by fzipi** [comment]
@airween Maybe adding something to our documentation would help others also?

**Comment by airween** [comment]
> @airween Maybe adding something to our documentation would help others also?

Thanks @fzipi, PR #2164 is pending.

**Comment by dosfx** [comment]
Hi @airween

I'm fairly sure we are using v3.2, that is the version in the folder path inside the container. Also the audit log refers to the `Rx` operator and not the `within` operator.

Just for kicks I tried your advice of using all lowercase in the `tx.allowed_request_content_type`. but you can see in the audit log it is still blocking with that setup:

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^application/repository.jdbcdatasource+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-str (69 characters omitted)' against variable `TX:0' (Value: `application/repository.jdbcDataSource+json' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "894"] [id "920420"] [rev ""] [msg "Request content type is not allowed by policy"] [data "application/repository.jdbcDataSource+json"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"] [hostname "172.20.0.8"] [uri "/jasperserver/rest_v2/connections"] [unique_id "1626705802"] [ref "o0,42v468,42"]
```

Its got the all lowercase version of the content-type in the parameter, but the `[data "application/repository.jdbcDataSource+json"]` still has capitals. Is that bad? its case-insensitive regex... so it shouldn't really care you'd think. Unfortunately this is for a jasperreports server that we're just proxying through the nginx WAF so we have no control over the capitalization of the incoming content-type.

For reference and version checking here's the rule out of ` /usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf`:
```
# In case Content-Type header can be parsed, check the mime-type against
# the policy defined in the 'allowed_request_content_type' variable.
# To change your policy, edit crs-setup.conf and activate rule 900220.
SecRule REQUEST_HEADERS:Content-Type "@rx ^[^;\s]+" \
    "id:920420,\
    phase:2,\
    block,\
    capture,\
    t:none,\
    msg:'Request content type is not allowed by policy',\
    logdata:'%{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protocol',\
    tag:'OWASP_CRS',\
    tag:'OWASP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED',\
    tag:'WASCTC/WASC-20',\
    tag:'OWASP_TOP_10/A1',\
    tag:'OWASP_AppSensor/EE2',\
    tag:'PCI/12.1',\
    ver:'OWASP_CRS/3.2.0',\
    severity:'CRITICAL',\
    chain"
    SecRule TX:0 "!@rx ^%{tx.allowed_request_content_type}$" \
        "t:none,\
        ctl:forceRequestBodyVariable=On,\
        setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

```

**Comment by airween** [comment]
Hi @dosfx,

> I'm fairly sure we are using v3.2, that is the version in the folder path inside the container. Also the audit log refers to the `Rx` operator and not the `within` operator.

ah, sorry, you're right - it seems in your log.

And I have to apologize you - I was wrong, when I wrote that `@rx` is case **insensitive** - it's case **sensitive**.

So, in 3.2 you **must** add definitely the same string as your CT:

```
  setvar:'tx.allowed_request_content_type=application/repository.jdbcDataSource+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain'"
```

Now I have produced a ModSecurity + CRS 3.2 environment, and this works for me. My error.log is empty, and I can see this in my debug.log:

```
Executing operator "!rx" with param "^%{tx.allowed_request_content_type}$" against TX:0.
Target value: "application/repository.jdbcDataSource+json"
Resolved macro %{tx.allowed_request_content_type} to: application/repository.jdbcDataSource+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain
Escaping pattern [^application\/repository\.jdbcDataSource\+json|application\/x-www-form-urlencoded|multipart\/form-data|text\/xml|application\/xml|application\/soap\+xml|application\/x-amf|application\/json|application\/octet-stream|application\/csp-report|application\/xss-auditor-report|text\/plain$]
Operator completed in 144 usec.
Rule returned 0.
```
 
> Just for kicks I tried your advice of using all lowercase in the `tx.allowed_request_content_type`. but you can see in the audit log it is still blocking with that setup:

yes, but it works only if the rule has the `t:lowecase` transformation. I tried it too, it also works, if the whole custom added CT is with lowercase. 3.2 does not have this transformation (3.3 [has](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L958) it).

Sorry for my mistake, I really hope now everything is clear, and you can solve your issue.

**Comment by dosfx** [comment]
No worries @airween, I'm on the same page now.

The only way I can get it to work is to escape the + in the `allowed_request_content_type`, so in our `crs-setup.conf` we've got `setvar:'tx.allowed_request_content_type=application/repository.jdbcDataSource\+json|appli......`. Which is all fine, it works, but if you want to keep digging as to why you're able to make a request and I'm not, we can.
