### ISSUE TITLE
HTTP PUT being blocked in WordPress is a false positive

### ISSUE THREAD

**Issue by firasd** [coreruleset/coreruleset#2167]
### Description

It seems like PUT requests trigger the rule "911100: Method is not allowed by policy".
This is an increasingly common type of HTTP request in WordPress plugins

Request:	PUT /lmstest/wp-json/elementor/v1/site-editor/templates-conditions/263
Action Description:	Access denied with code 200 (phase 2).
Justification:	Test 'REQUEST_METHOD' against '!@within %{tx.allowed_methods}' is true.

Seems like this should be allowed using the WordPress exclusion rules

### Your Environment

OWASP ModSecurity 2.9 Core Rule Set v3.3.0

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
Please see rule ID 900200 in `crs-setup.conf` - does it helped you?

**Comment by azurit** [comment]
By the way, have you enabled WordPress exclusion package? See rule 900130.

**Comment by lifeforms** [comment]
I think you are using the Elementor plugin and we don't have support added for it yet.

If you could post the full error messages (perhaps cleaning your content from it), I can see if I can reproduce it, and add it to our WordPress exclusion package.

We are using Elementor also, it seems to become more popular, but haven't had this FP yet.

**Comment by firasd** [comment]
Looks like 900200 was already enabled

And yeah WORDPRESS-EXCLUSION-RULES.conf is enabled

I don't have direct shell/command line access so not able to examine crs-setup.conf.. will see if possible to access that and the the log

I believe PUT is a common method with the new WP REST API which is acccessed via the /wp-json URL, but yeah in this case the plugin in question was Elementor

**Comment by lifeforms** [comment]
It seems that elementor is trying to PUT to a wp-json url. Elementor is becoming a more and more popular “Site builder” plugin for WordPress that basically allows users to create very good looking complex pages with minimal administrator effort. I would not be against including support for it in the package.

I'm using it ourselves on a few pilot projects now, so I might as well contribute anything I find to CRS. I will work on this and also add bugs I find myself. Thanks for the report.

**Comment by dune73** [comment]
We'd still be interested to get your logs @firasd.

**Comment by lifeforms** [comment]
Note to self, this is also one exclusion I needed for Elementor that I want so include:

```
SecRule REQUEST_FILENAME "@endsWith /wp-json/elementor/v1/form-submissions" \
    "id:5100001,phase:1,t:none,nolog,pass,\
        ctl:ruleRemoveById=200001"
```

**Comment by azurit** [comment]
I have this one in my collection (but cannot provide example of the request):

```
# WordPress 5.0.6 / 5.2.3 / 5.2.4 / 5.4.4 / 5.7, plugin Elementor 2.6.8, added 5.9.2019, edited 16.4.2021
SecRule REQUEST_FILENAME "@endsWith /wp-admin/admin-ajax.php" \
    "id:9990134,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    chain"
    SecRule ARGS:action "@streq elementor_ajax" \
        "t:none,\
        chain"
        SecRule &ARGS:action "@eq 1" \
            "t:none,\
            ctl:ruleRemoveTargetByTag=attack-xss;ARGS:actions,\
            ctl:ruleRemoveTargetById=921130;ARGS:actions,\
            ctl:ruleRemoveTargetById=932115;ARGS:actions,\
            ctl:ruleRemoveTargetById=932150;ARGS:actions,\
            ctl:ruleRemoveTargetById=933160;ARGS:actions,\
            ctl:ruleRemoveTargetById=933180;ARGS:actions,\
            ctl:ruleRemoveTargetById=942230;ARGS:actions,\
            ctl:ruleRemoveTargetById=932110;ARGS:actions,\
            ctl:ruleRemoveTargetById=942190;ARGS:actions,\
            ctl:ruleRemoveTargetById=932100;ARGS:actions,\
            ctl:ruleRemoveTargetById=934100;ARGS:actions,\
            ctl:ruleRemoveTargetById=933210;ARGS:actions,\
            ctl:ruleRemoveTargetById=932140;ARGS:actions,\
            ctl:ruleRemoveTargetById=932105;ARGS:actions,\
            ctl:ruleRemoveTargetById=932130;ARGS:actions"

```

**Comment by lifeforms** [comment]
@azurit Haha, I also have that too. Although, I just did: 
````
ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:actions
````

**Comment by dune73** [comment]
So what do we do here. Add all this to the WP RE package?

**Comment by lifeforms** [comment]
In my opinion we should expand the scope of the WordPress package to bring in often-used plugins.

Plugins that we often use at work are: Advanced Custom Fields, Gravity Forms, WooCommerce, WPML (multi language). We have made proprietary exclusions for them, but they may need some polish to include them in CRS.

A good task for me during the CRS retreat?

**Comment by firasd** [comment]
I'd just like to underscore that PUT is a method used by WP-JSON (which is the URL for the WP API) in general.

So blocking all HTTP PUT requests (as mod_sec seems to do) is not really an Elementor problem per se, it will be a problem for anyone trying to use the WP API

**Comment by lifeforms** [comment]
The WordPress exclusion package could selectively allow PUT just on the necessary endpoints.

**Comment by dune73** [comment]
I think the expansion makes sense, but I am not sure it's a good task for the retreat. It's something that does not need a focused group of developers (unless we want to give the RE package a huge boost, yet if that's the case, I'd like to see a commitment from the WP community).

**Comment by dune73** [comment]
Issue covered in the [September issue chat](https://github.com/coreruleset/coreruleset/issues/2185#issuecomment-913804183).

@lifeforms will do a PR to address the PUT problem. The expansion idea comes afterwards.

**Comment by dune73** [comment]
The amount of @lifeforms assigned issues is staggering. We need to free you!

**Comment by azurit** [comment]
@firasd Can you post few examples of URLs for WP json API?

**Comment by firasd** [comment]
Looks like they're always prefixed with` /wp-json/`, or (if rewriting URLs is not available) the query string `?rest_route
`
eg.

http://example.com/wp-json/wp/v2/posts/123

http://example.com/?rest_route=/wp/v2/posts/123

Some docs: https://developer.wordpress.org/rest-api/extending-the-rest-api/routes-and-endpoints/

**Comment by firasd** [comment]
Interesting segment in that link about the HTTP methods

> HTTP methods are sometimes referred to as HTTP verbs. They are simply just different ways to communicate via HTTP. The main ones used by the WordPress REST API are:
> 
> * GET should be used for retrieving data from the API.
> * POST should be used for creating new resources (i.e users, posts, taxonomies).
> * PUT should be used for updating resources.
> * DELETE should be used for deleting resources.
> * OPTIONS should be used to provide context about our resources.
> 
> It is important to note that these methods are not supported by every client, as they were introduced in HTTP 1.1. Luckily, the API provides a workaround for these unfortunate cases. If you want to delete a resource but can’t send a `DELETE` request, then you can use the `_method` parameter or the` X-HTTP-Method-Override` header in your request. How this works is you will send a `POST` request to https://ourawesomesite.com/wp-json/my-shop/v1/products/1?_method=DELETE. Now you will have deleted product number 1, even though your client could not send the proper HTTP method in the request, or maybe there was a firewall in place that blocks out `DELETE` requests.

**Comment by azurit** [comment]
We are covering this in rules:
9002140
9002141
9002142
9002143

@lifeforms Should we allow PUT in all of them?

By the way, i think regexpes in 9002140 and 9002142 can be optimized by makeing them anchored (not sure about the URL syntax, correct me if it's wrong):
```
SecRule REQUEST_FILENAME "@rx /wp-json/wp/v[0-9]+/(?:posts|pages)(?:/[0-9]+)?$" \

SecRule REQUEST_FILENAME "@rx /wp-json/wp/v[0-9]+/media(?:/[0-9]+)?$" \

```
Will match URLs like:
```
/wp-json/wp/v2/posts
/wp-json/wp/v2/posts/123
/wp-json/wp/v2/pages
/wp-json/wp/v2/pages/123
/wp-json/wp/v2/media
/wp-json/wp/v2/media/123

```


Code for allowing PUT method:
`setvar:'tx.allowed_methods=%{tx.allowed_methods} PUT"`

**Comment by firasd** [comment]
Yeah a regex that matches the /wp-json/ endpoint makes sense.

**Comment by dune73** [comment]
Sorry for not getting to work on this. The team is currently swamped (see https://coreruleset.org/20220711/update-on-crs-4-0-release-delay/).

We're happy to accept pull requests for this though.

**Comment by ofmarconi** [comment]
I'm no expert, I don't even know if this is helpful, but no one has commented what the rule packs and line are that are preventing this script, if it's helpful, here it is:

REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "105"] [id "930130"]
REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"]

```
---dIW65o7G---H--
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `restricted-files.data' against variable `REQUEST_FILENAME' (Value: `/.env' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "105"] [id "930130"] [rev ""] [msg "Restricted File Access Attempt"] [data "Matched Data: /.env found within REQUEST_FILENAME: /.env"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "peoplebusiness.live"] [uri "/.env"] [unique_id "1667052995"] [ref "o0,5v4,5t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "peoplebusiness.live"] [uri "/.env"] [unique_id "1667052995"] [ref ""]
```

**Comment by ofmarconi** [comment]
I'm no expert, I don't even know if this is helpful, but no one has commented what the rule packs and line are that are preventing this script, if it's helpful, here it is:

REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "27"] [id "911100"]
REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"]

```
---7xzdJ1yl---H--
ModSecurity: Warning. Matched "Operator `Within' with parameter `GET HEAD POST OPTIONS' against variable `REQUEST_METHOD' (Value: `PUT' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "27"] [id "911100"] [rev ""] [msg "Method is not allowed by policy"] [data "PUT"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/274"] [tag "PCI/12.1"] [hostname "***.com.br"] [uri "/wp-json/elementor/v1/site-editor/templates-conditions/5402"] [unique_id "1667053184"] [ref "v0,3"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***.com.br"] [uri "/wp-json/elementor/v1/site-editor/templates-conditions/5402"] [unique_id "1667053184"] [ref ""]
```

**Comment by ofmarconi** [comment]
Disabling these 2 packages can be disastrous for security, right?

**Comment by ofmarconi** [comment]
Hello, is anyone watching this?

Thx

**Comment by dune73** [comment]
You should simply add PUT to the list of allowed methods in crs-setup.conf. That should make the 911100 alert disappear, until we update the WP rule exclusion package for good.

Making sure 911100 no longer triggers will also result in 949110 no longer blocking the request.

**Comment by theMiddleBlue** [comment]
@lifeforms should we add this to our WordPress exclusion plugin?

**Comment by lifeforms** [comment]
@theMiddleBlue I'm kind of weary of plugins altering basic settings, BUT we could add to them just on certain paths! Btw, I am sick now, but I have some local additions that I really want to have to WordPress plugin in 4.0. I have planned to do this on Friday. To prevent merge conflicts, could you do this before Friday, or after my PR is merged? It's not so big, just want to sync up the plugin with my local 3.3 fork.

**Comment by theMiddleBlue** [comment]
as you wish, if you want I can do this on https://github.com/coreruleset/wordpress-rule-exclusions-plugin/pull/8 or maybe we can wait to merge all PRs and then create a new one to address this

**Comment by fzipi** [comment]
@theMiddleBlue @lifeforms What's next here?

**Comment by lifeforms** [comment]
I have now planned to finish that PR on Wednesday, but I'm still a bit unreliable as I'm sick, but I will try. My biggest apologies for being so late lately...

**Comment by lifeforms** [comment]
I've made small necessary changes to https://github.com/coreruleset/wordpress-rule-exclusions-plugin/pull/8 and merged it.

**Comment by fzipi** [comment]
Closing this one then. Great work!
