### ISSUE TITLE
Monthly Chat Agenda August 2021 (2021-08-02 and 2021-08-16)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2169]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2021-08-02, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2021-08-16. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Items on the Agenda:  (see previous meetings decisions: [here](https://github.com/coreruleset/coreruleset/issues/2141#issuecomment-874288876))

### Outside development

* Google App Armor signed up as a silver sponsor for the CRS project and paid the invoice. This is now confirmed.
* A 2nd Gold sponsor has received the invoice, payment is expected in the first week of August.

### PRs that have been merged since the last meeting

* #2165
* #2164
* #2159
* #2158
* #2157
* #2155
* #2154
* #2152
* #2148
* #2107
* #2078

We merged 11 PRs since the last monthly project chat.

## Open PRs

* #2168 - in need of a quick review, maybe @airween 
* #2163 - replacing filenames lead to broken tests. Probably some ftw-fu needed here
* #2151 - adding more teeth to 932200 (uninitialized variables)
*  #2156
* #2149 - cleanup of regexp assembly script(s)
* #2067 - better integration needed, volunteer to finish this wanted
* #2050 - reviewer keen on ReDoS wanted
* #2049 - ModSec asks for input on their idea to introduce the expanded list of JSON CTs as a separate list
* #1993 - no agreement on plugin mechanics, @lifeforms and @dune73 disagree
* #1975 - Nextcloud REs update, volunteer wanted
 
## Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2136 - review by @franbuehler pending
* #2101 - review (tests) by @azurit pending
* #2070 - incomplete
* #2068 - still actively being updated

## Other items

* Status of Coraza WAF
* Status of dev retreat in October : 7 participants (full or partial), 2 tentative, at least 2 open
* What to do at the dev retreat: List of ideas: https://github.com/coreruleset/coreruleset/wiki/Dev-Retreat-Topics

### Status of issues covered last month

* Issue slot 1: #1991 - pending
* Issue slot 2: #2118 - pending
* Issue slot 3: #2135 - pending
* Issue slot 4: #2139 - pending
* Issue slot 5: #2140 - pending
* Issue slot 6: #2142 - pending
* Issue slot 7: #2150 - pending
* Issue slot 8: #2066 - pending

**Stats**

* Covered in chat: 8
* Closed: none
* Pending: 8

### This month's issues

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #2162 - new
* Issue slot 2: #2167 - new
* Issue slot 3: #2150 - pending
* Issue slot 4: #2142 - pending
* Issue slot 5: #2140 - pending
* Issue slot 6: #2139 - pending
* Issue slot 7: #2135 - pending
* Issue slot 8: #2118 - pending
* Issue slot 9: #2066 - pending
* Issue slot 10: #1991 - pending

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp-slack.herokuapp.com/ .

Everybody is welcome to join our community chat.

## Meeting Agenda Template

[Link](https://github.com/coreruleset/coreruleset/wiki/Monthly-Meeting-Agenda-Template)

**Comment by franbuehler** [comment]
# Decisions

## PRs

* #2168 - in need of a quick review - @airween
* #2163 - replacing filenames lead to broken tests. Probably some ftw-fu needed here - @fzipi 
* #2156 - review needed so we can remove `ctl:ruleEngine=Off`
* #2151 - adding more teeth to 932200 (uninitialized variables)
* #2149 - cleanup of regexp assembly script(s)
* #2067 - better integration needed, volunteer to finish this wanted
* #2050 - reviewer keen on ReDoS wanted
* #2049 - ModSec asks for input on their idea to introduce the expanded list of JSON CTs as a separate list
* #1993 - no agreement on plugin mechanics, @lifeforms and @dune73 disagree
* #1975 - Nextcloud REs update, volunteer wanted
 
## Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2136 - review by @franbuehler pending
* #2101 - review (tests) by @azurit pending
* #2070 - incomplete
* #2068 - still actively being updated


## Other items

* -

## Open Issues - Separate Issues Meeting (Monday, July 19)

* Issue slot 1: 
* Issue slot 2: 
* Issue slot 3: 
* Issue slot 4: 
* Issue slot 5: 
* Issue slot 6: 
* Issue slot 7: 
* Issue slot 8:  
* Issue slot 9:  
* Issue slot 10:
