### ISSUE TITLE
Suggestions on Effective monitoring in attacks with WAF 0202

### ISSUE THREAD

**Issue by Shajin02** [coreruleset/coreruleset#2175]
### Motivation

Hi Guys,

Could you please suggest how effective we can monitor the Mod security OWASP CRS for many attacks and how we can segregate them like false positives and attacks

### Proposed solution
I think we can monitor with error logs and mod sec audit logs, by taking the CRTICAL issues and check with them

Your Environment
CRS version (e.g., v3.2.0):
Paranoia level setting: 1
ModSecurity version (e.g., 2.9.3):
Web Server and version (e.g., httpd 2.4.41):
Operating System and version: RHEL 7.9

**Comment by Shajin02** [comment]
@airween , Could you please suggest here

**Comment by airween** [comment]
Hi @Shajin02,

thanks for your suggest.

I think [this](https://www.netnea.com/cms/apache-tutorial-11_visualizing-log-files/) is a good reference for starting.

Once I read on modsecurity-user-list or any other mailing list about a log parser tool (open source), but now I do not find it.

I think this topic is out of scope of this project, so I'm going to close this issue.

Thanks again.

**Comment by RubieV** [comment]
@Shajin02

I'm a developer for an off-the-shelf product that will give feedback on which rules affect customers, and generates configuration specific to each application. 

You can get in touch with me at ruben@securely.ai, so I can get to know more on your specific environment.
