### ISSUE TITLE
Prepare canned responses for dev-on-duty

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2187]
In order to avoid repeating ourselves, we ought to prepare a few canned responses that address 80-90% of the new issues.

Open question: What responses do we need?

- FP: Please provide missing information
- FP: Won't fix due to higher PL, please help yourself with a RE
- FP: Won't fix due to problem with libinjection beyond our reach, please help yourself with a RE
- FP: Have you activated rule exclusion package? If not, please do.

**Comment by fzipi** [comment]
I think we can start with these, that will cover probably 90% of the responses.

**Comment by dune73** [comment]
Issue covered in the [September issue chat](https://github.com/coreruleset/coreruleset/issues/2185#issuecomment-913804183).

@theseion volunteered to come up with a few drafts. @dune73 will refine and finish the texts afterwards.

**Comment by theseion** [comment]
# missing info
Hi! Thanks for submitting this issue.

Unfortunately, you did not include enough information for us to actually help you. Please provide the following if possible:
- audit log extract
- web server and version
- ModSecurity connector version
- CRS version

# won't fix higher PL
Hi! Thanks for submitting this issue.

Unfortunately, we cannot help you. With the few resources we have we strive to provide the best possible experience for paranoia level 1. Using higher paranoia levels requires much more work and is usually very specific to the environment CRS is deployed in.

One often used technique for dealing with such issues on higher paranoia levels is to use rule exclusions (RE). Look at the included RE packages to get an idea of how this can be done (see also [crs-setup.conf.example](https://github.com/coreruleset/coreruleset/blob/v3.3.2/crs-setup.conf.example)).

# won't fix libinjection
Hi! Thanks for submitting this issue.

Unfortunately, we cannot help you. The issue you've raised is actually specific to [libinjection](https://github.com/client9/libinjection) and we don't have the resources to fully investigate or fix such issues. If you have the skills to do so yourself though, that would be amazing!

One often used technique for dealing with issues in libinjection is to use rule exclusions (RE). Look at the included RE packages to get an idea of how this can be done (see also [crs-setup.conf.example](https://github.com/coreruleset/coreruleset/blob/v3.3.2/crs-setup.conf.example)).

# activate RE
Hi! Thanks for submitting this issue.

You should actually be covered by our standard suite of rule exclusion (RE) packages. Did you forget to enable the RE package for your case? Look at [crs-setup.conf.example](https://github.com/coreruleset/coreruleset/blob/v3.3.2/crs-setup.conf.example) to see how you would enable one of the RE packages.

**Comment by dune73** [comment]
Thank you very much @theseion. Perfect to get me started. I've taken your drafts and expanded on https://github.com/coreruleset/coreruleset/wiki/Dev-on-Duty:-Response-Templates. Please check.

**Comment by fzipi** [comment]
@theseion Do you think this one is ready to close?

**Comment by theseion** [comment]
Sure. @dune73?

**Comment by dune73** [comment]
Yes, I think we're done. Thanks.
