### ISSUE TITLE
something went wrong when i add new content-type to rule 900220

### ISSUE THREAD

**Issue by ChuongTran97** [coreruleset/coreruleset#2198]
### Description
i added new content-type (application/scim+json) to rule 900220 and uncomment this rule. But when i use this content-type in my request and Modsecurity block me. I get this log:

ModSecurity: Warning. Matched "Operator `Rx' with parameter `^application/scim+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-r (70 characters omitted)' against variable `TX:0' (Value: `application/scim+json' ) [file "/home/bwaf/modsec/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "894"] [id "920420"] [rev ""] [msg "Request content type is not allowed by policy"] [data "application/scim+json"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"] [hostname "192.168.201.20"] [uri "/scim2/Me"] [unique_id "1631266210"] [ref "o0,21v437,21"]

my content-type was added . But Mod still block this request. Please help me. i have to turn off this rule in my system
### Your Environment
i use:
* Core Rule Set ver.3.2.0
* nginx proxy (18.04)

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @ChuongTran97,

thank you for your report.

Can you provide a `curl` request and your modification to emulate this issue?

I switched back in my test environment to CRS 3.2 (3.2.1), activated the rule [900220](https://github.com/coreruleset/coreruleset/blob/v3.2/master/crs-setup.conf.example#L396-L402) and inserted your CT:

```diff
396,402c396,402
< #SecAction \
< # "id:900220,\
< #  phase:1,\
< #  nolog,\
< #  pass,\
< #  t:none,\
< #  setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain'"
---
> SecAction \
>  "id:900220,\
>   phase:1,\
>   nolog,\
>   pass,\
>   t:none,\
>   setvar:'tx.allowed_request_content_type=application/scim\+json|application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain'"
```

Please note, that I've used `application/scim\+json` instead of `application/scim+json`.

With my request, I couldn't reproduce your issue:

```
curl -v --request POST -d '{"username":"aaa","password":"bbb"}' -H "Content-Type: application/scim+json" http://localhost```
```

Please check your added extra CT - hope this helps your problem. If it does, please close this issue.

**Comment by ChuongTran97** [comment]
I used your configuration and it work. My problem was solved Thank you very much.
