### ISSUE TITLE
Add Windows triple dot to a PL1 rule

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2205]
### Description

Windows triple dot is a path traversal that we do not detect. See #1991.

I's probably best to add this to an existing rule.

**Comment by dune73** [comment]
Hey @franbuehler, do you have time to come up with a PR here?

**Comment by franbuehler** [comment]
I'll have a look at this now, @dune73.

**Comment by dune73** [comment]
Thank you. Sounds cool.

**Comment by franbuehler** [comment]
I would like to extend the rule [930100](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf#L66) that currently checks for two dots `{2}` with `{2,3}`.
See [source file of rule 930100](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/util/regexp-assemble/data/930100-dots.data#L44).

**Comment by dune73** [comment]
Would that catch `.../` or also `/.../`?

**Comment by franbuehler** [comment]
Only `.../`

**Comment by dune73** [comment]
I am not 100% sure, but I think we should cover `.../` in at least 1 rule I think.

**Comment by franbuehler** [comment]
What about this new regex

`(?:(?:^|[\\\\\/])\.{2,3}[\\\\\/]|[\\\\\/]\.{2,3}(?:[\\\\\/]|$))`

instead of the current one:

`(?:(?:^|[\\\\/])\.\.[\\\\/]|[\\\\/]\.\.(?:[\\\\/]|$))`

I propose to extend both rules 930100 and 930110.

**Comment by RedXanadu** [comment]
Auto-closed. Issue was resolved after merging #2309 and #2310.
