### ISSUE TITLE
Drop keyword not blocked for SQL injection

### ISSUE THREAD

**Issue by gudmundurp** [coreruleset/coreruleset#2211]
### Description

The following query is not blocked:

https://some.web.site/index.html?q='drop table users;--

But it is blocked if I replace drop with delete, update, etc. This feels inconsistent, so I thought I should report it just in case.

Interestingly, if I add a ";" character after the single quote, then it is blocked:

https://some.web.site/index.html?q='; drop table users;--

### Your Environment

* CRS version:  v3.3.2
* Paranoia level setting: 1
* ModSecurity version: v3.0.5
* Web Server: ingress-nginx on kubernetes v1.21.4 running on Docker Desktop version 4.0.1 with docker engine version v20.10.8

**Comment by azurit** [comment]
Hi @gudmundurp, thanks for reporting this! And sorry for the delay.
