### ISSUE TITLE
Assign attack type to as much rules as possible

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2224]
### Motivation

For our customers, we are drawing pie graphs from CRS logs for attack types, as this one:
![pie](https://user-images.githubusercontent.com/1083063/136538211-a0d67ee1-8b72-49d9-ac21-0dd2c7b1078e.png)

I would like to get rid of `OTHER` i.e. uncategorized attacks, which use to be quite high (see image above).

### Proposed solution

There are two types of rules:

1. Attack type can be set to one of existing types
 - set `HTTP` for rules in files `REQUEST-911-METHOD-ENFORCEMENT.conf`, `REQUEST-920-PROTOCOL-ENFORCEMENT.conf` and `REQUEST-921-PROTOCOL-ATTACK.conf`

2. New attack type needs to be created
I don't know if we want to create new attack types but if we do, i suggest this:
 - `IPR` for rules in `REQUEST-910-IP-REPUTATION.conf`
 - `SCAN` for rules in `REQUEST-913-SCANNER-DETECTION.conf`
 - `LEAK` for rules in files `RESPONSE-950-DATA-LEAKAGES*.conf`
 - `WEBS` for rules in file `RESPONSE-955-WEB-SHELLS.conf`

I can send a PR.

**Comment by fzipi** [comment]
Sounds good. What about the CAPEC information we added? Is that relevant for you?

**Comment by fzipi** [comment]
@azurit Do you think we can close this one in favor of what Christian commented?

**Comment by azurit** [comment]
Yes, thank you!
