### ISSUE TITLE
Fake Googlebot plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2227]
### Motivation

As we all know, many bots are fakeing `User-Agent` header to look like a Googlebot. In lots of cases, users are trusting this header and, for example, are not applying so high restrictions for such requests. Anyway, behavior where anyone is fakeing anything to get something more is considered bad (or should be). This plugin is able to detect and block such requests.

### Proposed solution

As Google is publishing all it's IP ranges, we are able to use this information to detect fake Googlebots (see https://www.gstatic.com/ipranges/goog.json ). Plugin consists of these parts:
 - blocking rule (using `@ipMatchFromFile`)
 - python script for updating local database of Google IP ranges

While running a prototype of this plugin for about a week, almost 2000 fake Googlebot requests were detected with zero false positives (list of IPs: https://pastebin.com/saGWuq5E ).

Plugin registry PR: https://github.com/coreruleset/plugin-registry/pull/4.

**Comment by lifeforms** [comment]
Decision: the approach of #2228 is more robust, it won't need Google IP address updates and could also cover other bots. So closing this one for now and continue in #2228.
