### ISSUE TITLE
Rule 942251 - Having - PL3

### ISSUE THREAD

**Issue by christiantreutler-avi** [coreruleset/coreruleset#2229]
### Description

Rule 942251 is causing very simple false positives with the **having** key word.
Especially since it does not have a word boundary \b like other rules with having.

Simple language like: **I like having a tea** is matching too
Or even **I like having123 tea**, which I saw triggered recently.

I understand that this rule in PL3, but even then I think this might be too generic.

### Audit Logs / Triggered Rule Numbers

Rule 942251

### Your Environment

* CRS version (e.g., v3.2.0): Avi CRS based on 3.3.0+
* Paranoia level setting: PL3

**Comment by fzipi** [comment]
Update: negative tests on the updated rule are failing, will triple check to see if this is expected.
