### ISSUE TITLE
 Monthly Chat Agenda November 2021 (2021-11-01 and 2021-11-15)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2239]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2021-11-01, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2021-01-15. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Items on the Agenda:  (see previous meetings decisions: [here](https://github.com/coreruleset/coreruleset/issues/2197#issuecomment-933754113))

### Outside development

* [Blog post about MySQL bug that is not being detected by AWS WAF, ModSec libjection but detected by CRS at PL2](https://www.gosecure.net/blog/2021/10/19/a-scientific-notation-bug-in-mysql-left-aws-waf-clients-vulnerable-to-sql-injection/)
* [Google Dork List for SQLi in 2021](https://gbhackers.com/latest-google-sql-dorks/)
* [Blog Post: Working with Paranoia Levels](https://coreruleset.org/20211028/working-with-paranoia-levels/)
* [Blog Post: Looking back at Dev Retreat](https://coreruleset.org/20211101/crs-developer-retreat-2021/)

**More about dev retreat in the wiki:** <br/>
* Retreat Infos: [Infos for Participants](https://github.com/coreruleset/coreruleset/wiki/Dev-Retreat-2021-Infos)
* Project: [Update CRS Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)
* Project: [Write Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts)
* Project: [CRS Demo / Sandbox Site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite)
* Project: [CRS Status Page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage)
* Project: [Coraza Integration](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration)
* Workshop: [How to Avoid CVEs in the Future](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21AvoidCVEs)
* Workshop: [Project Planning Workshop](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21PlanningWorkshop)
* Workshop: [Trustwave Announcement about ModSecurity](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21TrustwaveModSecurity)
* Workshop: [Creating a Template to Document CRS Rules](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21RuleDocTemplate)
* Workshop: [New rules to defend against Request Smuggling and Server Side Request Forgery](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21RequestSmugglingSSRF)
* Workshop: [What to do with ModSecurity Recommended Rules](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21ModSecRecommendedRules)

### PRs that have been merged since the last meeting

* #2050
* #2149
* #2183
* #2184
* #2201
* #2207
* #2208
* #2215
* #2218
* #2226
* #2231
* #2237
* #2238
* #2247
* #2249
* #2251
* #2252
* #2253
* #2254
* #2255
* #2257
* #2260
* #2263
* #2268
* #2269
* #2270
* #2271
* #2272
* #2273
* #2275
* #2276
* #2280
* #2281
* #2282
* #2283

We merged 35 PRs since the last monthly project chat. The number is exceptionally high due to the dev retreat, but also due to issue #2256 that aims to add tests for rules that are untested hitherto.

## Open PRs

* #2279
* #2277
* #2274
* #2258
* #2223
* #2222

# Open PRs related to issues 2256 (@2256)

* #2284
* #2267
* #2266
* #2265
* #2264
 
## Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2259
* #2248
* #2236
* #2217
* #2214
* #2193
* #2163
* #2070
* #2067
* #2049
* #1993
* #1975

## Other items

* Looking through projects started during the dev retreat and hear about their status.

### Intermediate Status:

* Documentation project: FIXME
* Technical blog posts project: FIXME
* Sandbox project: FIXME
* Status page project: FIXME

### Status of issues covered last month

none - we did not do an issue chat in October.

### This month's issues

There are 25 open issues at the beginning of the issue chat.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #2227 + #2228
* Issue slot 2: #2205
* Issue slot 3: #2240 - proposal for a dynamic PL based on reputation of request / IP (maybe via plugin)
* Issue slot 4: #2150 - we have a solution, but unsure about the impact. Let's discuss.
* Issue slot 5: #2206 - SMTP and friends should be covered. We have a proposal.
* Issue slot 6: #2127 - We need a volunteer for a rule exclusion set on OData.
* Issue slot 7: #2232 - Question of working OAuth2 FP workarounds into a plugin instead of blowing up rules with highly specific chains
* Issue slot 8: #2246 - plugin question
* Issue slot 9: #FIXME
* Issue slot 10: #FIXME

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp-slack.herokuapp.com/ .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions

## PRs

* #2279 - @franbuehler will review it
* #2277 - @franbuehler will review it
* #2274
* #2258
* #2223
* #2222


## Open PRs related to issues 2256 (@2256)

* #2284
* #2267
* #2266
* #2265
* #2264

## Other items
 

## Issues
