### ISSUE TITLE
Idea: Adaptive paranoia level

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2240]
### Motivation

I was thinking about doing paranoia level some kind of adaptive to the request so, for example, if the IP address is suspicious, paranoia level will be automatically raised. On the other hand, PL can be lowered for known IPs.

Paranoia level can be changed based on these parameters:
 - remote IP address (fixed IPs, ranges, geoip, reputation, tor exit nodes)
 - RBL
 - score from previous phases
 - ...

What do you think?

### Proposed solution

I have working prototype of the plugin which is able to change paranoia level based on geoip.

**Comment by dune73** [comment]
Have you tried out your implementation, @azurit? How did it go?

I'm covering this idea / concept in my blog post at https://coreruleset.org/20211028/working-with-paranoia-levels/. Do you think my concerns apply or would you use it nevertheless and add it to the list of official plugins?

**Comment by azurit** [comment]
I have a working plugin ready. It's able to set paranoia or executing paranoia level based on geoip (you can assing ISO codes to paranoia levels using configuration file).
I'm still thinking about not setting paranoia level directly based on request parameters but adding a score for every parameter and then, after all checks (i.e. geoip, ip reputation, ..) are done, setting paranoia level based on score.

I read your blog post and i think there are situations where this feature can be usefull but it must be used wisely.

**Comment by dune73** [comment]
Sounds good. This is scheduled for the chat tonight. I think it's worthwhile to do a plugin around this idea. What I am unsure is whether we want to make it an official plugin or a 3rd party plugin. Also has a bit to do with the GeoIP support in ModSec.

**Comment by azurit** [comment]
I found a way how to use also external source of geoip data (for example mod_geoip2 / mod_maxminddb).

**Comment by dune73** [comment]
@azurit, OK if we close this?

**Comment by azurit** [comment]
Yes, closing for now.
