### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2242]
This is an issue / project scheduled for the [CRS developer summit](https://github.com/coreruleset/coreruleset/wiki/Dev-Retreat-Topics#project-topics) in October 2021. This is supposed to take several days.

There is a separate wiki page for this project: [DevRetreat21UpdateDocumentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)

**Comment by RedXanadu** [comment]
The foundations have been laid for the new documentation system.

Most of the agreed-upon sections now exist, however a few still need to be created.

Some content needs to be moved. Much content still needs to be written. Much content needs to be checked and possibly reworked.
