### ISSUE TITLE
Write testcases for every rules so that we have a full coverage

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2256]
During the CRS Developer Summit we noticed that not all rules are covered with a test case. The following rules don't have at least one test.

Currently @airween and @franbuehler are writing test cases, but if anyone else wants to join in, here is the list and the status of the work.

Missing tests (tick means test exists now):

- [x] 913101 - @airween merged https://github.com/coreruleset/coreruleset/pull/2257
- [x] 913102 - @airween merged https://github.com/coreruleset/coreruleset/pull/2253
- [x] 920171 - @airween - merged PR: https://github.com/coreruleset/coreruleset/pull/2295
- [x] 920410 - @airween - merged PR: https://github.com/coreruleset/coreruleset/pull/2285
- [x] 920121- @53cur3M3 - merged PR:  https://github.com/coreruleset/coreruleset/pull/2264
- [x] 920341 - @jptosso - merged PR: https://github.com/coreruleset/coreruleset/pull/2266
- [x] 921151 - @53cur3M3 - merged PR: https://github.com/coreruleset/coreruleset/pull/2270
- [x] 921170 - rule can not be tested. Rule is a helper rule for 921180 and does not log by itself.
- [x] 921180 - @jptosso - merged submitted PR: https://github.com/coreruleset/coreruleset/pull/2308
- [x] 932105 - @airween - merged PR: https://github.com/coreruleset/coreruleset/pull/2286
- [x] 932110 - @airween - merged PR: https://github.com/coreruleset/coreruleset/pull/2287
- [x] 932120 - @53cur3M3 - merged PR: https://github.com/coreruleset/coreruleset/pull/2272
- [x] 932130 - @53cur3M3 - merged PR: https://github.com/coreruleset/coreruleset/pull/2273
- [x] 932150 - @53cur3M3 - merged PR: https://github.com/coreruleset/coreruleset/pull/2275
- [x] 932160 - @53cur3M3 - merged PR: https://github.com/coreruleset/coreruleset/pull/2276
- [x] 932170 - @franbuehler - merged https://github.com/coreruleset/coreruleset/pull/2283
- [x] 932171 - @franbuehler - merged https://github.com/coreruleset/coreruleset/pull/2284
- [x] 932180 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2280
- [x] 932106 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2269
- [x] 932190 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2268
- [x] 933200, @NiceYouKnow merged https://github.com/coreruleset/coreruleset/pull/2281
- [x] 933111, @NiceYouKnow merged https://github.com/coreruleset/coreruleset/pull/2281
- [x] 933190, @NiceYouKnow merged https://github.com/coreruleset/coreruleset/pull/2281
- [x] 942170 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2255
- [x] 942251 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2254
- [x] 942460 - @franbuehler merged https://github.com/coreruleset/coreruleset/pull/2252

**Comment by franbuehler** [comment]
> I think that means it's enough to add a new ENV variable to the tests/docker-compose.yaml file (and to the other sections, of course), with name COMBINED_FILE_SIZES. @franbuehler, can you confirm this?

Yes, I tested it to be really sure:

docker-compose.yaml:

```
services:
  modsec2-apache:
    container_name: modsec2-apache
    image: owasp/modsecurity-crs:3.3-apache
    environment:
      SERVERNAME: modsec2-apache
      ...
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.log"
      COMBINED_FILE_SIZES: "100"
```
When I have a look at the crs-setup.conf in the container, the activate-rules.sh seems to have done its job properly:

```
root@14c6c5eaa494:/usr/local/apache2# grep -B 10 combined_file_sizes /opt/owasp-crs/crs-setup.conf
# Block request if the total size of all combined uploaded files is too high
# Default: unlimited
# Example: 1048576
# Uncomment this rule to set a limit.
SecAction \
  "id:900350, \
   phase:1, \
   nolog, \
   pass, \
   t:none, \
   setvar:tx.combined_file_sizes=100"
```

I will open an issue to fix this missing documentation to the crs container.

**Comment by airween** [comment]
> ...
> And I just see that it's already documented.

Thank you for your help, I think I able to create the PR.

**Comment by dune73** [comment]
Dear all, thank you all for your support.

AFAICS everything listed above is now covered and we have tests for every request attack detection rule.

**Comment by franbuehler** [comment]
I'll rerun Ervin's script to check this.

**Comment by dune73** [comment]
Please do. 921170 is being reported, but that rule can not be tested, since it's a helper rule (of 921180) that does not write any logs.
