### ISSUE TITLE
Illegal Content-Type header (920470) for SOAP 1.2 action "attribute"

### ISSUE THREAD

**Issue by edwinvandeburgt** [coreruleset/coreruleset#2293]
### Description

A valid SOAP 1.2 call includes the SOAP action as part of the Content-Type, but when the Content-Type contains the valid action "attribute", the WAF will block it.

#### Example headers: 

application/soap+xml;charset=utf-8;action=xxx
application/soap+xml;charset=utf-8;action="xxx"

#### Log (Azure Log Analytics):

Message: Illegal Content-Type header
ruleSetVersion_s: 3.1.0
ruleId_s: 920470
action_s: Matched
details_message_s: Warning. Match of \"rx ^[\\\\w\\\\d/\\\\.\\\\-\\\\+]+(?:\\\\s?;\\\\s?(?:boundary|charset)\\\\s?=\\\\s?['\\\"\\\\w\\\\d_\\\\-]+)?$\" against \"REQUEST_HEADERS:Content-Type\" required. 
details_data_s: application/soap+xml;charset=utf-8;action=xxx
details_file_s: rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
details_line_s: 989

### Audit Logs / Triggered Rule Numbers
920470 for Content-Type header containing a SOAP action

### Your Environment
Azure Application Gateway with 3.1.0 Ruleset

### Confirmation

[X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Hello @edwinvandeburgt, sorry for inconvenience.

Unfortunately, you / Azure are running an outdated version of CRS. I can not reproduce this misbehavior on our supported versions. Please upgrade.

I'm closing this report now. If you get the same problem with a supported CRS version, then please upgrade.
