### ISSUE TITLE
Fix Matomo tracker on website

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2305]
### Motivation

We have a new Matomo tracker, but our WordPress website (using a random person's Matomo plugin) still refers to `piwik.js` instead of `matomo.js`. Therefore, tracking doesn't work. Docs does not have the tracker yet at all.

### Proposed solution

- [x] For WordPress, find another Matomo plugin that uses the new matomo.js URL.
- [x] For the docs site, put the Matomo tracking code somewhere in the theme.

### Alternatives

If we do not find a good Matomo WordPress plugin, I will have to create a "child theme" and insert the HTML manually in our theme.

### Additional context

N/A

**Comment by fzipi** [comment]
What about using https://wordpress.org/plugins/matomo/ ?

**Comment by lifeforms** [comment]
> What about using https://wordpress.org/plugins/matomo/ ?

If I'm correct, that plugin works with the Matomo SaaS offering. We use Matomo on-premise and that appears to require a different plugin, namely: https://wordpress.org/plugins/wp-piwik/

**Comment by lifeforms** [comment]
Tracking is now working for the main website and the documentation.
