### ISSUE TITLE
Add documentation for the sandbox

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2312]
### Motivation

Add documentation for the sandbox. I've started on it, but did not manage to finish. the README of the sandbox is nice, so I think I can manage this on my own, with a review.

### Proposed solution

- [x] An explanation
- [x] Example curl requests
- [x] Advanced usage (X-CRS-parameters)
- [x] Explain logging.
- [x] Maybe add a note that we are using Openresty as a proxy which might not be totally transparent - for instance it rejects some the Apache 2.4.49/50 path injections and these requests never reach our backend.

### Alternatives

None. Has to be there. :)

### Additional context

N/A

**Comment by lifeforms** [comment]
Decision: I will make a draft branch around Jan 7th and have fzipi and theMiddle review it.

**Comment by fzipi** [comment]
@lifeforms I think this one was already pushed, right?

**Comment by lifeforms** [comment]
Yep, it's live at https://coreruleset.org/docs/development/sandbox/

I thought it was important to have something there before the bug bounty started. But I forgot to ask you guys for a review, sorry about that.

Reviews appreciated. Do you have any comments or improvements, @fzipi @theMiddleBlue?

**Comment by fzipi** [comment]
Looks good to me. The only thing is that we still didn't made the repo available, so there is no way to create issues yet. Hopefully we can solve it soon!

**Comment by lifeforms** [comment]
Oh, that's right. I've fixed the URL to refer to the issues page on our public repo for now.

**Comment by fzipi** [comment]
Then if @theMiddleBlue has nothing to add, we can close this one!

Thanks for writing this!

**Comment by theMiddleBlue** [comment]
awesome work @lifeforms thanks!
for the "working on sandbox" we've just simplified the process to add a new backend, I'll explain it to you asap

**Comment by lifeforms** [comment]
Ok great, just message me and I'll update it. For now, I'll close this as it's ready from a user perspective.
