### ISSUE TITLE
Next notification push is blocked !

### ISSUE THREAD

**Issue by kennethlau** [coreruleset/coreruleset#2326]
### Description

Next notification push is blocked !

### Audit Logs / Triggered Rule Numbers

``
[error] 1216269#1216269: *2294 [client xx.xx.xx.xx] ModSecurity: Access denied with code 403 (phase 1). Matched "Operator `Eq' with parameter `1' against variable `IP:xx.xx.xx.xx_64c0f0d116fb71284a0e1cd2960c6675c0ea9372::::DOS_BLOCK' (Value: `1' ) [file "/etc/nginx/modsec/rules/REQUEST-912-DOS-PROTECTION.conf"] [line "130"] [id "912130"] [rev ""] [msg ""] [data ""] [severity "0"] [ver "OWASP_CRS/3.4.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "paranoia-level/1"] [tag "attack-dos"] [tag "OWASP_CRS"] [tag "capec/1000/210/227/469"] [hostname "xx.xx.xx.xx"] [uri "/ocs/v2.php/apps/notifications/api/v2/push"] [unique_id "1638104847"] [ref ""], client: xx.xx.xx.xx , server: xx.xx.xx.org , request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", host: "xx.xx.xx.xx.org"
``

### Your Environment

ubuntu 20.04

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:

### Confirmation

--- REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf.old
+++ REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf  
@@ -495,7 +495,7 @@
 # Nextcloud uses notifictions to inform the user of important new details.

 # Allows notifications to be deleted
-SecRule REQUEST_FILENAME "@rx /ocs/v[0-9]+\.php/apps/notifications/api/v2/notifications" \
+SecRule REQUEST_FILENAME "@rx /ocs/v[0-9]+\.php/apps/notifications/api/v2/(?:notifications|push)" \
     "id:9003701,\
     phase:1,\
     pass,\

**Comment by RedXanadu** [comment]
Hi @kennethlau, thanks for the report.

`[ver "OWASP_CRS/3.4.0-dev"]`
As a note, it looks like you're using our latest development branch. Please be aware that this changes often and is not stable. If you're looking for our latest stable release, which is appropriate to use in production, for example, then check out our [v3.3.2 release](https://github.com/coreruleset/coreruleset/releases/tag/v3.3.2).

`ModSecurity: Access denied with code 403... [file "/etc/nginx/modsec/rules/REQUEST-912-DOS-PROTECTION.conf"]... [id "912130"]`
It looks like your transaction was caught by the CRS DoS rules. Do you have the DoS rule enabled intentionally? They are enabled under the "Anti-Automation / DoS Protection" section of `crs-setup.conf`.

If you're looking for DoS protection, I would not rely on the CRS to perform this aspect of your security. There are much better places and ways to defend against DoS attacks, e.g. at the firewall level, or using a dedicated appliance.

I hope this helps.

**Comment by kennethlau** [comment]
Thanks !

**Comment by RedXanadu** [comment]
@kennethlau I'm going to close this issue now, but please feel free to reply here again if you need any further help with this.
