### ISSUE TITLE
Magento ver. 2.4.3

### ISSUE THREAD

**Issue by LINUXpos** [coreruleset/coreruleset#2329]
if i install latest update of mod_security_crs
Magento ver. 2.4.3 will not update product quantities from dashboard

redhat latest updates

**Comment by lifeforms** [comment]
Hi @LINUXpos , thanks for your issue. Unfortunately, we need a bit more information to help you fix it.

Do you have access to the ModSecurity audit log? (usually in `/var/log/modsec_audit.log`) Once the firewall blocks something, it should appear here. Can you re-try doing the request in Magento and paste the relevant entry here?

**Comment by LINUXpos** [comment]
Hello,  i recreated issue:  modesec log:

HTTP/1.0 500 Perl execution failed
Server: MiniServ/1.981
Date: Sat, 18 Dec 2021 08:27:21 GMT
Content-type: text/html; Charset=utf-8
Connection: close

<html>
<head>
<style data-err type="text/css">.err-head,.err-content,.err-body { font-family: Lucida Console, Courier, monospace;}.err-head { color: #f12b2b; font-size: 14px; font-weight: 500; padding: 5px 2.5px 0; text-transform: uppercase; transform: scale(1, 1.5); white-space: pre-wrap;}.err-content { padding-left: 2.5px; white-space: pre-wrap;}.err-content,.err-body { font-size: 12.5px;}.err-head[data-fatal-error-text] { padding: 0;}.err-stack caption,.err-stack > tbody > tr:first-child > td > b { color: #151515; font-weight: bold; text-align: left;}.err-stack > tbody > tr:first-child > td > b { border-bottom: 1px solid #151515;}.err-stack > tbody > tr:first-child>td { font-family: unset; font-size: 14px; height: 25px; text-transform: uppercase; transform: scale(1, 1.2); vertical-align: top;}.err-stack { border: 1px dashed #151515}.err-stack.captured { margin-left: 12px; width: auto}.err-stack tr td { font-family: Lucida Console, Courier, monospace; font-size: 13px; padding: 1px 10px; transform: scale(1, 1.15);}.err-stack tr:not(:first-child) td.captured { font-size: 90%;}.err-stack > tr:first-child > td.captured { font-size: 96%; padding-bottom: 7px; padding-top: 3px;}.err-stack caption.err-head { padding:0 0 10px 0;}.err-stack caption.err-head.captured { color: #222; font-size:98%;}</style>
<title>500 &mdash; Perl execution failed</title></head>
<body class="err-body"><h2 class="err-head">Error &mdash; Perl execution failed</h2>
<p class="err-content">can't open /var/log/httpd/log/httpd/modsec_audit.log: No such file or directory at /usr/libexec/webmin/filemin/download.cgi line 26.
</p>
</body></html>

= = = = = 

magento error if i try to change product stock quantity:
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Comment by LINUXpos** [comment]
[modsec_audit.log](https://github.com/coreruleset/coreruleset/files/7738984/modsec_audit.log)

**Comment by azurit** [comment]
@LINUXpos Look at this in the log above:
`can't open /var/log/httpd/log/httpd/modsec_audit.log: No such file or directory at /usr/libexec/webmin/filemin/download.cgi line 26`
Check if all directories in the path to the log file exists.

**Comment by azurit** [comment]
@LINUXpos Any news on this ?Thanks.
