### ISSUE TITLE
Dissassemble regexp for 920120 and extend matching

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2334]
### Describe the bug

While reviewing #2333, noticed two things:
- the 920120 regexp [is not "disassembled"](https://github.com/coreruleset/coreruleset/blob/5945066048cc8d4351af3600b4211a0e4d1e1224/util/regexp-assemble/data/920120.data#L25). We should disassemble it so it is easier to compare with the no-backtracking one. 
- Looks like the regexp is missing the `&aacute;` meta. It should match using`&[aeEiIoOuUyY]acute`. We should also review all these html metas so see if we are missing others, just in case.

### Steps to reproduce

Read the data files for regexp 920120.

### Expected behaviour

In PL1 html metas like `&aacute;` should not match.

### Actual behaviour

It is matching.

### Your Environment

* CRS version (e.g., v3.2.0): v3.4.0-dev

**Comment by fzipi** [comment]
On a first pass, we are matching this:
```
&[aAoOuUyY]uml
&[aAeEiIoOuU]circ
&[eEiIoOuUyY]acute
&[aAeEiIoOuU]grave
&[cC]cedil
&[aAnNoO]tilde
&amp|&apos
```

From [this table](https://dev.w3.org/html5/html-author/charref), looks like we left these out:

-  `[AEIOUaeiou]grave`
- `[aAcClLnNrRsSzZg]acute`
- `[iI]tilde`
- `[AUau]ring`
- `[Oo]slash`
-  `[gGkKlLnLrRsStT]cedil`
- `[eEiI]uml`
- `[cCgGhHjJsSwWyY]circ`
- `[cCdDeElLnNrRsStTzZ]caron`

**Comment by fzipi** [comment]
Dissasembled regexp should be similar to:

```
 ##!^ (?i)(?<!&
 ##!$ ;)['\"=]

 [aeiouy]uml
 [aeioucghjswy]circ
 [aeiouclnrszg]acute
 [aeiou]grave
 [cgklnrst]cedil
 [anoi]tilde
 [cdelnrstz]caron
 oslash
 amp
 apos
 [au]ring
```

But from previous @theseion comment, one problem we are facing is that lookbehind assertions need to be of fixed length. E.g.:
```
PCRE compilation failed at offset 155: lookbehind assertion is not fixed length
Stripped regex: '(?i)(?<!&(?:(?:[aeiouclnrszg]acut|[aeiou]grav|[anoi]tild)e|(?:[cgklnrst]cedi|[aeiouy]um)l|[aeioucghjswy]circ|[cdelnrstz]caron|a(?:pos|mp)|[au]ring|oslash);)['"=]'
```

**Comment by dune73** [comment]
Do we need to cover this tonight?

**Comment by fzipi** [comment]
If we have time, we should.

**Comment by fzipi** [comment]
So, because of perl Regexp::Assembly limitations, based on our construct, we cannot fully disassemble the regexp we use with lookbehind, and it must be used as one liner.

Despite this, the extended matching both for regular and non lookbehind are being handled in PR #2333.

So when that one is merged, we can close this one.
