### ISSUE TITLE
Take a closer look at https://github.com/mandiant/heyserial

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2336]
This might be of some use for CRS.

**Comment by dune73** [comment]
Also: https://twitter.com/ramen0x3f/status/1470952808434343944

**Comment by fzipi** [comment]
It would be good, when you have time, to create a list of requirements on what/how you foresee we use this one. It would help others to implement the feature. 😃

**Comment by azurit** [comment]
@dune73 Is this still relevant? Thank you for info.

**Comment by dune73** [comment]
I doubt anybody has the time for a through inspection, so I guess we can let it be closed.
