### ISSUE TITLE
Where can i find the corresponding relationship between the rule and attack protection?

### ISSUE THREAD

**Issue by StarryVae** [coreruleset/coreruleset#2342]
### Motivation

For example, if i just want to use the HTTPoxy protection , which rule or rulesets should i use ?

**Comment by azurit** [comment]
Try looking at the rules tags, for example rules for Microsoft IIS:
```
$ grep iis * | grep tag
REQUEST-920-PROTOCOL-ENFORCEMENT.conf:    tag:'platform-iis',\
RESPONSE-954-DATA-LEAKAGES-IIS.conf:    tag:'platform-iis',\
RESPONSE-954-DATA-LEAKAGES-IIS.conf:    tag:'platform-iis',\
RESPONSE-954-DATA-LEAKAGES-IIS.conf:    tag:'platform-iis',\
RESPONSE-954-DATA-LEAKAGES-IIS.conf:    tag:'platform-iis',\
```

**Comment by azurit** [comment]
Anyway, for support questions, please use one of these:
 - Channel #coreruleset on OWASP Slack (https://owasp.slack.com/).
 - Our Google Group (https://groups.google.com/a/owasp.org/g/modsecurity-core-rule-set-project).
 - https://stackoverflow.com or https://security.stackexchange.com (we are answering questions there on daily basis).
