### ISSUE TITLE
Rewrite the core CRS documentation

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2352]
### Motivation

As agreed at the 2021 Dev Retreat, we want to completely rewrite the CRS documentation.

### Proposed solution

The rewrite process is well underway, and several key pieces of content have already been completed.

We need to try and finish rewriting all of the **core** parts of the documentation _before_ the next CRS release.

## Progress tracker

We have an up-to-date progress tracker on the Dev Retreat documentation project wiki page, here:
https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation#where-do-we-want-to-go.

### Outstanding core documentation tasks

- ✔ Various engine options
- ✔ Various integrations (cloud and CDN)
  - [These are both complete](https://github.com/coreruleset/documentation/pull/27).
- ✔ Anomaly Scoring
  - [This is complete](https://github.com/coreruleset/documentation/pull/6).
- ✔ Sampling mode
  - [This is complete](https://coreruleset.org/docs/configuring/sampling_mode/).
- ✔ Dev info
  - [This is complete](https://github.com/coreruleset/documentation/pull/24).
- ✔ Get the install instructions re-write PR proofread and merged
  - [This is complete](https://github.com/coreruleset/documentation/pull/39/files).
- ✔ Tidy up
  - [This is complete](https://github.com/coreruleset/documentation/pull/51).
- Document the use of CRS in Apache VirtualHost and container contexts. @dune73 has agreed to write this as a blog post.

**Comment by RedXanadu** [comment]
Work on writing the "Developers info section" has started in earnest:
https://github.com/RedXanadu/documentation/tree/developers_section

**Comment by fzipi** [comment]
Looking good! Do you want me to help with verifying release artifacts?

**Comment by RedXanadu** [comment]
If you could, that would be excellent. Then I can concentrate on getting the import of CONTRIBUTORS.MD and the other "Development Info" bits finished.

**Comment by fzipi** [comment]
👍 I'll handle it

**Comment by fzipi** [comment]
Let me know what you need next here!

**Comment by RedXanadu** [comment]
Now just needs a tidy-up, which I will look to do this week.

All of the core documentation we wanted to finish is finished.

**Comment by RedXanadu** [comment]
I won't have time to look at this now until next week. I ended up spending time on other PRs instead.

**Comment by RedXanadu** [comment]
First pass of tidying up merged (https://github.com/coreruleset/documentation/pull/47).

Just a few more sharp corners to smooth out and then this is complete.

**Comment by dune73** [comment]
Awesome news.

One big spot we still need to cover is the use of CRS in VirtualHost and Container context. This really matters and it's more difficult with more detection rules in phase 1. You may want to add a separate checkbox for this. It's on my list.

**Comment by fzipi** [comment]
Is the _CRS in VirtualHost and Container context_ going to be a blog post? Should we close this one or is anything additional needed here that is not listed?

**Comment by dune73** [comment]
Yes, this is going to be a blog post. It's on my task list on a postit note on the wall in front of me as I write this. (And has been there for some months...) With CRS v4 being postponed, this is not super-urgent I think.

**Comment by RedXanadu** [comment]
I've added the Apache VirtualHost question to the [big list of documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation), which I am about to propose we have a re-runthrough of at the dev retreat. So, hopefully, we can discuss this very soon in person!

With that done, I think we can close this issue now. The one outstanding task has been moved and saved.
