### ISSUE TITLE
Possible False Positives with Nextcloud app Markdown Editor rule 949110

### ISSUE THREAD

**Issue by MrCybertux** [coreruleset/coreruleset#2367]
## Description
While working with the Nextcloud app Markdown Editor the connection to the document gets lost when it autosaves.
It only triggers when using one of the pre formatted Templates, i haven figuered out wich exact feature breaks it.
If i use a blank page i can work just fine.
The rule trigert has the id 941310

## Log output
```
[info] 164#164: *3297 ModSecurity: Warning. Matched "Operator `Rx' with parameter `\xbc[^\xbe>]*[\xbe>]|<[^\xbe]*\xbe' against variable `ARGS:json.autosaveContent' (Value: `\# company\x0a\x0a\## Logistik\x0a\x0a\### <Daten>\x0a\x0a\## Technik\x0a\x0a\### Netzwerk Gr\xc3\x (324 characters omitted)' ) [file "/opt/bunkerized-nginx/crs/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "527"] [id "941310"] [rev ""] [msg "US-ASCII Malformed Encoding XSS Filter - Attack Detected"] [data "Matched Data: \xbcnwald\x0a\x0a#### <daten> found within ARGS:json.autosaveContent: # company\x0a\x0a## logistik\x0a\x0a### <daten>\x0a\x0a## technik\x0a\x0a### netzwerk gr\xc3\xbcnwald\x0a\x0a#### <daten>\x0a\x0a### netzwerk noris\x0a\x0a#### <daten>\x0a\x0a### (153 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-tomcat"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "XXX.XXX.XXX.XXX"] [uri "/apps/text/session/sync"] [unique_id "164372592823.168891"] [ref "o66,20v21,298t:urlDecodeUni,t:lowercase,t:urlDecode,t:htmlEntityDecode,t:jsDecode"], client: XXX.XXX.XXX.XXX, server: nextcloud.example.io, request: "POST /apps/text/session/sync HTTP/2.0", host: "nextcloud.example.io"
```

**Comment by azurit** [comment]
Hello!

Thanks for submitting and sorry for your inconvenience. We will take a look into this soon.

**Comment by theseion** [comment]
Hi @MrCybertux

Thank you very much for your report. Your issue has already been addressed in the development branch. The update to the rule will be included in the next release (which will probably be towards summer).

If you have control over your CRS deployment you could update the rule manually with the change from the (v3.4/dev branch)[https://github.com/coreruleset/coreruleset/blob/f8be3a0e3df242f87be0cd9af7fbce66a72fca8e/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L537].
