### ISSUE TITLE
Update test User-Agent to "OWASP ModSecurity Core Rule Set Test"

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2368]
### Motivation

Per comments in #2362 , we should use an uniform User-Agent that doesn't depend on the version of CRS or others.

### Proposed solution

- Change the User-Agent in test to `OWASP ModSecurity Core Rule Set Test`
- When a particular User-Agent is required by the test itself, add it after a semicolon, example: `libwww-perl; OWASP ModSecurity Core Rule Set Test`
- Check what to do in the case of `encoded_request`: do we want to edit those also?

### Additional context

Linked PR.

**Comment by dune73** [comment]
Not sure I understand the issue. Did not implement #2362 this already. Or is the 3rd item in "Proposed solution" still open?

**Comment by airween** [comment]
> Did not implement #2362 this already.

No. #2362 has replaced the UA header by [ModSecurity CRS 3 Tests](https://github.com/coreruleset/coreruleset/pull/2362/files#diff-f1863c1dbc7ebf4c29fc24005a2038abea65c4a56999402bb4ef0571bd9e3bd0R15), which contains the CRS version.

[Here](https://github.com/coreruleset/coreruleset/pull/2362#issuecomment-1021938192) you wrote that _In fact I do not think we need any version in the test UA._

This issue asks we need to find a final solution.

**Comment by dune73** [comment]
Ah, gotcha. Thanks.

**Comment by airween** [comment]
>     * Change the User-Agent in test to `OWASP ModSecurity Core Rule Set Test`

Do we need to put the `ModSecurity`? I think it's already more than that. IMHO `OWASP Core Rule Set Test` would be enough.
 
>     * When a particular User-Agent is required by the test itself, add it after a semicolon, example: `libwww-perl; OWASP ModSecurity Core Rule Set Test`

Agree (but use `libwww-perl; OWASP Core Rule Set Test` here too).

>     * Check what to do in the case of `encoded_request`: do we want to edit those also?

I'd prefer that we use the same UA (and other headers too). I think it not just about "what is in the test", even more so "what we see in the log".

**Comment by dune73** [comment]
A UA is fairly official. So while this is not overly important to me, I still think we should use the official name of the project and that is _OWASP ModSecurity Core Rule Set_.

That does not rule out a name change in the future, but for the time being that's our name and there are good arguments to keep it that way for the time being.

**Comment by fzipi** [comment]
Changed UA to the official `OWASP ModSecurity Core Rule Set`. Luckily, this was an easy sed.
