### ISSUE TITLE
Rewrite Drupal exclusion rules package into plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2378]
As agreed, all exclusion rules packages needs to be moved into plugins.

**Comment by RedXanadu** [comment]
See: https://github.com/coreruleset/drupal-rule-exclusions-plugin.

Needs someone to review before sign-off on this issue.

**Comment by azurit** [comment]
@RedXanadu pls can you fix things above in all of your RE plugins? Then i will continue with review, thanks!

**Comment by RedXanadu** [comment]
That's a great idea! I forgot there was a 'Contributors' tab per-file. Perfect.

**Comment by RedXanadu** [comment]
Done. All RE plugins now have README content and a CONTRIBUTORS list sourced from the original file contributors.

**Comment by azurit** [comment]
Looks good!

Few things:
 - Missing 'Testing' section in the readme, copy it for example from https://github.com/coreruleset/phpbb-rule-exclusions-plugin (it was written in cooperation with dune).
 - Remove me from CONTRIBUTORS.md as i haven't contribute into this one.

**Comment by RedXanadu** [comment]
Thanks for reviewing this.

- Testing paragraph added.
- CONTRIBUTORS.md updated. (I originally added you to all of the plugins I committed because they all started as copies of your phpBB plugin files :smile: But I'll update them all to only ones where you were actually involved in writing the CRS rules.)

**Comment by RedXanadu** [comment]
All outstanding issues addressed. Once CRS 4 is live then the plugin repo can be made public.

Closing this issue (but can be reopened if anyone wanted to add any further comments).
