### ISSUE TITLE
Rewrite WordPress exclusion rules package into plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2379]
As agreed, all exclusion rules packages needs to be moved into plugins.

**Comment by RedXanadu** [comment]
@azurit Did this one get done or is it outstanding?

It would be ironic if the most important and widely used rule exclusion package we have got forgotten :sweat_smile:

**Comment by azurit** [comment]
No, i will get to it!

**Comment by azurit** [comment]
Needs review: https://github.com/coreruleset/wordpress-rule-exclusions-plugin

**Comment by RedXanadu** [comment]
@azurit I'll make this a priority to check this evening.

**Comment by RedXanadu** [comment]
@azurit Looks good! Great work.

**Comment by azurit** [comment]
Thanks!

**Comment by lifeforms** [comment]
Tested and working!
