### ISSUE TITLE
Rewrite Nextcloud exclusion rules package into plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2380]
As agreed, all exclusion rules packages needs to be moved into plugins.

**Comment by RedXanadu** [comment]
See: https://github.com/coreruleset/nextcloud-rule-exclusions-plugin.

Needs someone to review before sign-off on this issue.

**Comment by azurit** [comment]
Looks good!

Few things:
 - Rule 9508121 is missing `ver` action.
 - Missing 'Testing' section in the readme, copy it for example from https://github.com/coreruleset/phpbb-rule-exclusions-plugin (it was written in cooperation with dune).
 - Remove me from CONTRIBUTORS.md as i haven't contribute into this one.

**Comment by RedXanadu** [comment]
Thanks for reviewing this.

Good spot on the missing `ver` line.

- Missing `ver` line added.
- Testing paragraph added.
- CONTRIBUTORS.md updated.

**Comment by RedXanadu** [comment]
All outstanding issues addressed. Once CRS 4 is live then the plugin repo can be made public.

Closing this issue (but can be reopened if anyone wanted to add any further comments).
