### ISSUE TITLE
Rewrite phpBB exclusion rules package into plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2384]
As agreed, all exclusion rules packages needs to be moved into plugins.

**Comment by azurit** [comment]
Plugin registry PR: https://github.com/coreruleset/plugin-registry/pull/7

**Comment by azurit** [comment]
Needs review: https://github.com/coreruleset/phpbb-rule-exclusions-plugin

**Comment by RedXanadu** [comment]
Looks good to me!

**Comment by azurit** [comment]
Done, closing.
