### ISSUE TITLE
Rewrite phpMyAdmin exclusion rules package into plugin

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2385]
As agreed, all exclusion rules packages needs to be moved into plugins.

**Comment by azurit** [comment]
Needs review: https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin

**Comment by RedXanadu** [comment]
Looks good to me!

I noticed that you added in missing `ver` actions which are missing in the current CRS RE package. Well spotted :)

**Comment by azurit** [comment]
Done, closing.
