### ISSUE TITLE
Add workaround for expirevar on NGiNX for DOS rules as a plugin

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#2389]
As discussed during the [monthly chat in February 2022](#2350) and as requested in https://github.com/coreruleset/modsecurity-crs-docker/issues/59 we will add the workaround for `expirevar` on NGiNX for DOS rules. This will happen once #2373 is done.

It is not yet clear how we will implement the workaround. One idea is to add those rules as an additional plugin.

**Comment by theseion** [comment]
I've added an initial version of a plugin that implements the workaround: https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3. Still needs to be tested.

**Comment by fzipi** [comment]
@theseion I think this problem was solved, and we can close this one, right?

**Comment by theseion** [comment]
Very likely, yes. I haven't verified it though.

**Comment by theseion** [comment]
Confirmed.
