### ISSUE TITLE
Monthly Chat Agenda March 2022 (2022-03-07 and 2022-03-21) Meeting Agenda

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2401]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2022-03-07, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2022-03-21. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Items on the Agenda:  (see previous meetings decisions: [here](https://github.com/coreruleset/coreruleset/issues/2350#issuecomment-1031904666))

### Outside development

* CRS submitted several ideas to the Google Summer of Code [under the OWASP umbrella](https://owasp.org/www-community/initiatives/gsoc/gsoc2022ideas)
* WAF-Bypass.com carries a [blog post about bypassing CRS](https://waf-bypass.com/how-to-bypass-modsecurity-protection/) - the quality of this blog post is so low, it may warrant a response
* Thanks to @airween we're going to archive CRS chats very soon [**UPDATE**: Archive is [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md)]

### PRs that have been merged since the last meeting

* #2411
* #2414
* #2400
* #2399
* #2410
* #2402
* #2407
* #2404
* #2405
* #2259
* #2376
* #2391
* #2375
* #2393
* #2357
* #2347
* #2388
* #2372
* #2387
* #2371
* #2386
* #2351
* #2370
* #2377
* #2408
* #2420
* #2421

We merged 27 PRs since the last monthly project chat.

## Open PRs

* #2290 - no news from @spartantri on this PR marked as 4.0 milestone. What do we do?
* #2322 - I'm ready to merge this. What do you all think?
* #2349 - log4j stuff; let's talk about status and prospects
* #2406 - pre-commit tests coming to CRS
* #2417 - the refactoring of the scoring variables, contributed PR by @studersi
* #2422 - grand unified regex utils PR by @theseion
* #2423 - PR accompanying 2422

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2408
* #2420
* #2421
* #2417
* #2406
* #2322
* #1975
* #2217
* #2067
* #2290
* #2303
* #2349
* #2301
* #2302

## Dev retreat topics

* [Demo / Sandbox site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite): FIXME
* [Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation):
  - Issue tracking the outstanding documentation tasks for the 4.0 release:
  #2352
* [Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts): FIXME
* [Status page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage):
  - Around 15% of our tests fail on cloud mode. This means that it is blocking where it shouldn't.
  - There is a google Sheet being filled to track all failures.
  - :pen: Cloud providers won’t have support for latest versions of our ruleset. This will give us some problems.
  - :toolbox: Tools are being setup to repeat this process
  - Using the list we can start taking a look on what to modify on our tests to match the less amount of rules per test (if possible)
* [Coraza](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration): JP talks of two additional developers working on Coraza at the moment and a lot of demands from various businesses. Hard to prioritize - and setting limits to business demands.

## Other items
* Release Status and Planning
* Another player in the ModSecurity ecosystem touched on the idea to write down a ModSecurity SecLang specification. What do we think about this?
* Talk about `pre-commit` to fix problems before pushing ;)
* Budget 2022

### Various

* GSoC: We need to sort out the projects we can do and provide some guidance to applying students.
* The big anomaly scoring refactoring PR is ready for review, let's plan the review together: https://github.com/coreruleset/coreruleset/pull/2417
* We need to fill April and May dev-on-duty. See https://github.com/coreruleset/coreruleset/wiki/Dev-on-Duty

### Status of issues covered last month

* Issue slot 1: #2390 - still open
* Issue slot 2: #2319 - still open
* Issue slot 3: #2332 - still open
* Issue slot 4: #2318 - still open 
* Issue slot 5: #2329 - still open
* Issue slot 6: #2322 - merged
* Issue slot 7: #2109 - closed
* Issue slot 8: #2240 - closed
* Issue slot 9: #2367 - closed

**Stats**

* Covered in chat: 9
* Closed: 4
* Pending: 5

### This month's issues

There are FIXME open issues at the beginning of the issue chat.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #2438
* Issue slot 2: #2440 
* Issue slot 3: #2332
* Issue slot 4: #2334
* Issue slot 5: #2419
* Issue slot 6: #2394
* Issue slot 7: #FIXME
* Issue slot 8: #FIXME
* Issue slot 9: #FIXME

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions

## PRs

*

## Dev retreat topics

## Issues

* Issue slot 1:
