### ISSUE TITLE
False positive for Cyrillic

### ISSUE THREAD

**Issue by deniskonovalov64** [coreruleset/coreruleset#2409]
### Description

Hello, I have a mail server deployed on postfix and a roundcube web interface. When a letter is sent via the web interface, it is triggered in Cyrillic (ruleId: 942100). Because of what, some letters could not go through. I came across a similar topic on GitHub (SpiderLabs/owasp-modsecurity-crs#794), but as I understand it, there was no solution to this issue at that time. Can you tell me if there is a solution to the issue at the moment or what can be done in this case? Because the solution that is now does not suit me at all. I will be grateful for any help.

### Audit Logs / Triggered Rule Numbers
This is the data from the mail error log:

``2022/02/18 17:29:15 [error] 45721#45721: *199 [client 10.1.41.200] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/modsec/coreruleset-nightly/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.4.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "-"] [uri "/"] [unique_id "1645165755"] [ref ""], client: 10.1.41.200, server: -, request: "POST /?_task=mail&_unlock=loading1645165756247&_lang=ru&_framed=1 HTTP/1.1", host: "-", referrer: "https://-/?_task=mail&_action=compose&_id=1425376456620f3cab31e91"``

This is the data from the Mod Security audit log provided as JSON:

```
"transaction": {
      "host_ip": "-",
      "request": {
        "http_version": 1.1,
        "method": "POST",
        "uri": "/?_task=mail&_unlock=loading1645165756247&_lang=ru&_framed=1",
        "headers": {
          "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
          "Cache-Control": "max-age=0",
          "Referer": "https://-/?_task=mail&_action=compose&_id=1425376456620f3cab31e91",
          "Host": "-",
          "Connection": "keep-alive",
          "Accept-Encoding": "gzip, deflate, br",
          "Sec-Fetch-Site": "same-origin",
          "Sec-Fetch-Mode": "navigate",
          "Origin": "https://-",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
          "Cookie": "language=ru; roundcube_sessid=b0pe4udfghu0804fs2hhs2kv50; roundcube_sessauth=E7FmVXeqQGmpfC7cU6ODqD8Fg2-1645165500",
          "Sec-Fetch-Dest": "iframe",
          "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Google Chrome\";v=\"98\"",
          "Content-Length": "946",
          "sec-ch-ua-mobile": "?0",
          "sec-ch-ua-platform": "\"Windows\"",
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
          "Upgrade-Insecure-Requests": "1",
          "Content-Type": "application/x-www-form-urlencoded",
          "Sec-Fetch-User": "?1"
        }
      },
      "unique_id": "1645165755",
      "producer": {
        "modsecurity": "ModSecurity v3.0.6 (Linux)",
        "components": [
          "OWASP_CRS/3.4.0-dev\""
        ],
        "secrules_engine": "Enabled",
        "connector": "ModSecurity-nginx v1.0.2"
      },
      "client_port": 59674,
      "server_id": "6190d41d7ace5d863bfe1641802c119a1867c446",
      "response": {
        "headers": {
          "Content-Length": "555",
          "Connection": "keep-alive",
          "Server": "nginx/1.21.4",
          "Content-Type": "text/html",
          "Date": "Fri, 18 Feb 2022 06:29:15 GMT"
        },
        "http_code": 403
      },
      "client_ip": "-",
      "time_stamp": "Fri Feb 18 17:29:15 2022",
      "host_port": 443,
      "messages": [
        {
          "details": {
            "match": "detected SQLi using libinjection.",
            "severity": "2",
            "ruleId": "942100",
            "file": "/etc/nginx/modsec/coreruleset-nightly/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf",
            "lineNumber": "46",
            "data": "Matched Data: sos found within ARGS:_message: test\r\n\r\n-- \r\n________________\r\n! C2065=85<, \r\n\u0015235=89 \u001d>28:>2\r\n\u0018=65=5@ \u001e\u001e\u001e \"\u001f>A594>=\"\r\nB5;:  7(812)679-67-37 4>1.303;\r\n<>1:  7(999)790-12-28;\r\ne-mail: -",
            "accuracy": "0",
            "rev": "",
            "tags": [],
            "maturity": "0",
            "reference": "v1525,223t:urlDecodeUni",
            "ver": "OWASP_CRS/3.4.0-dev"
          },
          "message": "SQL Injection Attack Detected via libinjection"
        },
        {
          "details": {
            "ver": "OWASP_CRS/3.4.0-dev",
            "severity": "2",
            "ruleId": "949110",
            "file": "/etc/nginx/modsec/coreruleset-nightly/rules/REQUEST-949-BLOCKING-EVALUATION.conf",
            "data": "",
            "lineNumber": "139",
            "accuracy": "0",
            "rev": "",
            "tags": [
              "application-multi",
              "language-multi",
              "platform-multi",
              "attack-generic"
            ],
            "maturity": "0",
            "reference": "",
            "match": "Matched \"Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' )"
          },
          "message": "Inbound Anomaly Score Exceeded (Total Score: 5)"
        }
      ]
    }
```

### Your Environment

* CRS version (e.g., v3.2.0): OWASP_CRS/3.4.0-dev\
* Paranoia level setting: default
* ModSecurity version (e.g., 2.9.3): ModSecurity v3.0.6 (Linux)
* Web Server and version (e.g., apache 2.4.41): nginx/1.21.4
* Operating System and version: Ubuntu 18.04.6 LTS

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @deniskonovalov64,

it's sad to see that you ran into a false positive issue. Actually you can only do an exception to avoid the FP, something like this:

```
SecRule REQUEST_URI "@streq /" \
    "id:9909001,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetById=942100;ARGS:_message"
```

Put this rule into your vhost config, or to your CRS conf.

**Comment by deniskonovalov64** [comment]
Hello @airween, thanks for your response. I used a similar solution, but only in the nginx config and not the rules. I wonder if you know if there are any movements to solve such problems?

**Comment by deniskonovalov64** [comment]
It's just that you understand that such a decision is not entirely correct or even completely wrong.

**Comment by airween** [comment]
> Hello @airween, thanks for your response. I used a similar solution, but only in the nginx config and not the rules. I wonder if you know if there are any movements to solve such problems?

I'm afraid there are any other solution. As you can see, the mentioned rule ([942100](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L46-L47)) uses `@detectSQLi` operator, so the rule writer does not have any influence to the behavior (like - for eg. - in case of `@rx`).

> It's just that you understand that such a decision is not entirely correct or even completely wrong.

I agree, but as I explained above, rule uses a hard coded operator, it's very hard to avoid the FP's in these cases. We ran many similar cases especially in special character sets, like Cyrillic.

**Comment by deniskonovalov64** [comment]
Then is it possible to somehow reach the creators of SQLi, because the branch that I found was archived?

**Comment by airween** [comment]
> Then is it possible to somehow reach the creators of SQLi, because the branch that I found was archived?

I'm afraid not really. The [operator](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/detect_sqli.cc#L33) uses [libinjection](https://github.com/client9/libinjection).

As you can see, that repository is very old, and unmaintained. There are many other false positive issues, but the maintainer has left the project. So...

**Comment by deniskonovalov64** [comment]
It is very sad that such an important project is not supported :-( . Thanks for the clarification and your time. I close the question.
