### ISSUE TITLE
912 DOS PROTECTION blocks on 1 burst with `EXECUTING_PARANOIA_LEVEL=2` and `PARANOIA_LEVEL=1`

### ISSUE THREAD

**Issue by diablodale** [coreruleset/coreruleset#2413]
### Describe the bug

CRS v3.3.2 with 912 DOS PROTECTION will errantly block on one burst when `EXECUTING_PARANOIA_LEVEL=2` and `PARANOIA_LEVEL=1`.
This is partially due to code defect here

https://github.com/coreruleset/coreruleset/blob/8a7a8960c2721890054ec1f5d9e79f9dc62ac991/rules/REQUEST-912-DOS-PROTECTION.conf#L273-L275

With EPL=2, it will continue and then apply rule 912171 which causes immediate DOS block as if PL=2.
This is a discontinuity in the intention of EPL to get warnings at a given level but not apply blocks at that level.

### Steps to reproduce

1. Install CRS as per instructions for your platform.
2. Enable DOS protection, e.g. `tx.dos_burst_time_slice=60`, `tx.dos_counter_threshold=100`, `tx.dos_block_timeout=1800`
3. Set `EXECUTING_PARANOIA_LEVEL=2` and `PARANOIA_LEVEL=1`
4. Attack the server

### Expected behaviour

The attacker will be blocked after the second burst, i.e. after 200 requests

### Actual behaviour

The attacker will be blocked after the first burst, i.e. after 100 requests

### Your Environment

* CRS version: v3.3.2
* Paranoia level setting: 1
* Execution Paranoia level setting: 2
* ModSecurity version: 2.9.3 <detail redacted>
* Web Server and version: Apache <detail redacted>
* Operating System and version: <detail redacted>

**Comment by diablodale** [comment]
A quick fix with the current DOS codebase is to change those 3 lines to check the `PARANOIA_LEVEL`.
And naturally the rewrite for a plugin can include this topic within its test cases.

**Comment by diablodale** [comment]
Not stale.

**Comment by diablodale** [comment]
not stale

**Comment by fzipi** [comment]
I would say you can continue the discussion in the plugin repositories now.
- https://github.com/coreruleset/dos-protection-plugin-modsecurity-v2
- https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3

As we removed this from v4.

**Comment by diablodale** [comment]
🎺⚰️😁
