### ISSUE TITLE
Move IP reputation rules to separate plugin

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#2433]
### Motivation

The IP reputation rules could potentially be moved to a separate plugin instead of being part of standard CRS.

### Proposed solution

The 910 rules as well as the rule 949100 could be moved to a separate plugin.
In that case, rule 949100 could even become a 910 rule.
This would also affect the configuration and initialization variables associated with these rules.

The variables containing the necessary flags, would still need to be part of CRS as they are set by other CRS rules.

### Alternatives

Keep them in CRS but refactor these rules to better fit into CRS and add tests to ensure they are working properly.

### Additional context

* The IP reputation rules have GeoIP dependencies that are not required for the rest of CRS, particularly rule 910100.
* The IP reputation rules in general use a separate blocking mechanism in 949100 to do reputation-based blocking, which is turned off by default.
* The IP reputation rules 910100 and 910000 both also increase the anomaly score. However, in the case of rule 910000, this is useless as it is only increased in case `TX:DO_REPUT_BLOCK` is turned on, in which case regular CRS blocking based on the anomaly score is circumvented in favor of blocking immediately with rule 949100.
* There are no regression tests to verify these rules are working properly.

**Comment by dune73** [comment]
Totally in line with what we are aiming for. In fact the idea to move DoS rules away kind of included IP reputation in spirit.

**Comment by fzipi** [comment]
@dune73 We need someone to take on this one before feature freeze, right?

**Comment by dune73** [comment]
I'd say so, yes. In spirit ...

No honestly, the point is to cut away excess fat from CRS and concentrate on core functionality. This is not core functionality.

**Comment by studersi** [comment]
This would actually be more complicated than expected to move to a plugin.

Aside from the basic blocking mechanism and the variables used for that (i.e. `do_reput_block`, `reput_block_duration`), there are other variables set all over CRS (i.e. `reput_block_flag`, `reput_block_reason`).

Considering that the IP reputation flags are exclusively used in `REQUEST-913-SCANNER-DETECTION.conf`, the plugin could potentially update the actions of the scanner rules as follows using [SecRuleUpdateActionById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secruleupdateactionbyid), however I have never tried this:

```
SecRuleUpdateActionById 913000-913999 "'setvar:'ip.reput_block_flag=1',setvar:'ip.reput_block_reason=%{rule.msg}',expirevar:'ip.reput_block_flag=%{tx.reput_block_duration}'"
```

**Comment by studersi** [comment]
Yes, this uses the [IP collection](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#persistent-storage) which persists variables for an IP across requests.

If a scanner is detected, the `reput_block_flag` is set to 1 for a duration of `reput_block_duration` with an additional variable `reput_block_reason` providing context. If the `reput_block_flag` is set (and `DO_REPUT_BLOCK` is activated in the setup conf), rule `910000` skips forward to `BEGIN-REQUEST-BLOCKING-EVAL` where requests are blocked by `949100` instead of the normal CRS blocking rules. To me it is unclear why `910000` and `949100` run in phase 2, however.

Note that with the IP reputation rules there comes a whole other part as well. There are GeoIP rules and rules identifying specific IPs from a remote list using the [`@rbl`](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#rbl) operator with different handling depending on the type of RBL classification.

**Comment by dune73** [comment]
Thank you for the confirmation. So I read the architecture correctly.

I think the cleaner way of doing this would be to do a rule that adds a critical anomaly score if an IP has been marked as malicious (or scanner for limited scope).

That would be easy to do in a plugin and you do not need all this additional variables and rules and what not.

Also: When removing 949100, we could discuss moving 94911[01] to the new vacant position.

**Comment by studersi** [comment]
I am preparing a PR where I remove the IP reputation stuff.

> Also: When removing 949100, we could discuss moving 94911[01] to the new vacant position.

Personally, I would not change the Rule ID of existing rules. In particular rule `949110` could be monitored in the logs since it indicates that CRS has blocked a request. Changing the rule ID would likely cause problems with such setups.

**Comment by dune73** [comment]
You're probably right about sticking to existing rule IDs. It's just that removing 949100 will lead to an anomaly and given this is a major release...

**Comment by studersi** [comment]
I guess with the release of a new major version, it would be the best moment to do it.

On the other hand, if I remember correctly, modifications to rule IDs was one of the points criticized at the CRS Summit in Amsterdam (might have been @fzipi who brought it up at the time, if I remember correctly). The point was raised concerning rule exclusions, so it might be less problematic here, as it only affects monitoring and analysis.

**Comment by theseion** [comment]
I like the idea of moving all the things that rely on extra stuff, such as honeypot, RBL, GeoIP, to plugins.

I'm not sure about the idea of using the anomaly score instead of explicit blocking though. I don't have anything against it per se, but it occurs to me that there must be a reason that the DoS rules also block explicitly. Maybe those rules were conceived before anomaly scoring? Or maybe they idea is to drop everything in phase 1 which isn't possible with anomaly scoring?

**Comment by dune73** [comment]
In the case of DoS I see performance reasons. They do not apply with the rest of the stuff and I take it is more historical. CRS3 was the first version that really pushed anomaly scoring as default, but we did not really touch these rules for said release.

And there is nothing wrong with a plugin blocking directly, it's just that it does not integrate with CRS that much technically afterwards (which does not rule out it being a CRS plugin from my perspective).

**Comment by fzipi** [comment]
Nice discussion here, I agree on the idea of having three plugins. And blocking directly could be integrated with early blocking instead? That would give the same result, and will be more integrated with crs.

**Comment by dune73** [comment]
From my perspective difference between early blocking and a deny in the rule is the fact that the former can be controlled / relaxed with the anomaly threshold, while the latter can't. And there may be plugins where you want to block independently of the anomaly threshold. While I clearly prefer the latter.

DOS might be such a case (-> performance).

**Comment by lifeforms** [comment]
Merged and closed!

**Comment by studersi** [comment]
Question: When this was closed, did we create new issues to implement all removed features as plugins?

From https://github.com/coreruleset/coreruleset/issues/2433#issuecomment-1091862176:
> * IP reputation blocks based on previous CRS violations
> * Anomaly scoring based on GeoIP data
> * Anomaly scoring based on RBL lookups

As far as I see there are issues for the following:
* [ ] IP reputation blocks based on previous CRS violations -> ?
* [x] Anomaly scoring based on GeoIP data -> https://github.com/coreruleset/coreruleset/issues/2501
* [x] Anomaly scoring based on RBL lookups -> https://github.com/coreruleset/coreruleset/issues/2501

As far as I can tell there is no ticket for the reputation rules, where offending IPs are blocked entirely after repeated violations.

**Comment by fzipi** [comment]
There is not, thanks for catching this one. Can you create the ticket with what is needed?

**Comment by studersi** [comment]
Done: https://github.com/coreruleset/coreruleset/issues/2680.
