### ISSUE TITLE
add a rule with APPLICATION-ATTACK-JAVA.conf to defend jsp and jspx webshell

### ISSUE THREAD

**Issue by k4n5ha0** [coreruleset/coreruleset#2440]
### Motivation
like rule id:933110  "PHP Injection Attack: PHP Script File Upload Found"
block php app  upload php file

### Suggestion
i think REQUEST-944-APPLICATION-ATTACK-JAVA.conf need add a rule to block: upload jsp and jspx webshell

thx

**Comment by airween** [comment]
Hi @k4n5ha0,

thank you for your suggestion. We have to discuss this request, so I added this issue to the list of our monthly chat topics.

Btw, do you have any existing solution?

**Comment by azurit** [comment]
Do you have any examples of Java webshells? We can add it here: https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/RESPONSE-955-WEB-SHELLS.conf.

**Comment by k4n5ha0** [comment]
> Hi @k4n5ha0,
> 
> thank you for your suggestion. We have to discuss this request, so I added this issue to the list of our monthly chat topics.
> 
> Btw, do you have any existing solution?

Hi！@airween the hack usually find a url to upload jsp and jspx webshell like this pic
![image](https://user-images.githubusercontent.com/22064977/159159429-bf6060ed-f1bd-474c-8d39-65cc9acd2314.png)
so like  rule id:933110

```
SecRule FILES|REQUEST_HEADERS:X-Filename|REQUEST_HEADERS:X_Filename|REQUEST_HEADERS:X.Filename|REQUEST_HEADERS:X-File-Name "@rx .*\.(?:php\d*|phtml)\.*$" \
```
we can block file with @rx like "jsp?"

thx

**Comment by k4n5ha0** [comment]
> Do you have any examples of Java webshells? We can add it here: https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/RESPONSE-955-WEB-SHELLS.conf.

Hi！@azurit these two tools create webshell with jsp and jspx is very prowerful and low sign
https://github.com/rebeyond/Behinder
https://github.com/BeichenDream/Godzilla

thx

**Comment by k4n5ha0** [comment]
> Hi @k4n5ha0,
> 
> thank you for your suggestion. We have to discuss this request, so I added this issue to the list of our monthly chat topics.
> 
> Btw, do you have any existing solution?

and.with paranoia_level=2
![image](https://user-images.githubusercontent.com/22064977/159159841-14b4599d-8b57-4070-98a4-f328340a3590.png)
i can upload a file with ``` ../ or ..\ ```
![image](https://user-images.githubusercontent.com/22064977/159159866-62326386-9b7b-454a-b731-d2f18cbb3816.png)
and windows filename can not inclue ``` / \ : * ? " < > |   ```
![image](https://user-images.githubusercontent.com/22064977/159159888-848b00e4-9da2-4182-99c4-e5dc6613f7a6.png)

and i think it is owasp Path Traverser
thx again

**Comment by azurit** [comment]
> Hi！@azurit these two tools create webshell with jsp and jspx is very prowerful and low sign https://github.com/rebeyond/Behinder https://github.com/BeichenDream/Godzilla

Cool. Unfortunately, i'm not able to run those. Can you run them and post whole HTML output it produces? Thank you.

**Comment by k4n5ha0** [comment]
> > Hi！@azurit these two tools create webshell with jsp and jspx is very prowerful and low sign https://github.com/rebeyond/Behinder https://github.com/BeichenDream/Godzilla
> 
> Cool. Unfortunately, i'm not able to run those. Can you run them and post whole HTML output it produces? Thank you.

these tools create webshell without any html output , so these webshells can bypass many security check include clamav.

**Comment by lifeforms** [comment]
We are interested in blocking uploads of .jsp and .jspx files and we will work on blocking these in our next release.

**Comment by k4n5ha0** [comment]
> To @k4n5ha0: We are interested in blocking uploads of .jsp and .jspx filenames and we will work on blocking these in our next release.
> 
> If you want to continue the discussion about webshell detection, please do, it will be useful, but it's really a separate issue - so maybe it's better to create a separate GitHub issue for that.

ok! 3Q

**Comment by lifeforms** [comment]
A PR to block .jsp and .jspx uploads is in #2456.

**Comment by fzipi** [comment]
This was not merged yet, reopening.

**Comment by fzipi** [comment]
This one was merged, closing.
