### ISSUE TITLE
Prepare CRS 4.0 slide deck

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2443]
### Motivation

This would help us spread the word. But perhaps even more importantly, it forces us to describe the core new features that this release brings. Without that process it's just an endless Changelog.

**Comment by RedXanadu** [comment]
@dune73 This content could do double-duty as an "Introducing: CRS 4.0" blog post: "Headline Features:", "Other changes and bugfixes:", etc.

**Comment by dune73** [comment]
I'll self-assign the issue.

**Comment by fzipi** [comment]
Is this part of the Milestone? Or can be done afterwards?

**Comment by RedXanadu** [comment]
Ooh! Can we turn this into a video for the YouTube generation? :thinking: That might get some attention/views?

**Comment by dune73** [comment]
Honestly, I think it's part of the milestone. It has to be ready in time. And doing a video on top would certainly be helpful (and more work if done right).

**Comment by dune73** [comment]
We're getting there. So this is not stale. Just postponed. Also, there is a draft version by @fzipi.

**Comment by fzipi** [comment]
I say we just close this one now.
