### ISSUE TITLE
Additional plugins syncying between repos

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2452]
After doing a review on plugins, repos and related stuff (docker images), we need to see if the documentation on plugins match for the `documentation` project, the docker container that will map the plugins, and the plugins repos. 

- Are plugins “compatible” with older CRS versions? (I see `"Preparation for older installations"`) in the docs, e.g. https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin
- how is the proposed flow for installing plugins? using git? getting a zip file? none of the above?
- depending on the previous, things may vary. if we use git, we can’t clone everything to the same directory, so people will need to use a subdirectory on the `plugins` folder for each plugin.
- we can use the https://github.com/coreruleset/plugin-registry repo to create a yaml file with the list of plugins so it can be consumed by scripts. I foresee a script that gets the plugins, for example. Just simple bash + curl, but we need to verify things probably (gpg?).
- documentation should match the efforts in the crs docker container (https://github.com/coreruleset/modsecurity-crs-docker/pull/66). People should have a way of installing plugins there (even if using volume mount).

So, we need to check that:
- plugin registry
- plugins doc
- coreruleset documentation
- crs docker documentation
all matches and have the same description and usage.

Otherwise it is going to be caos.

**Comment by fzipi** [comment]
I'm tagging you both because you did most of the work on plugins setup @RedXanadu @azurit

**Comment by RedXanadu** [comment]
As far as I know, the latest and greatest documentation we have regarding plugins is here:
https://coreruleset.org/docs/configuring/plugins/

This is based on the CRS blog post announcing plugins and how to install them.

If we want to have a "single source of truth" for plugin documentation, I propose that should be it.

**Comment by dune73** [comment]
Plugin Installation: 

I have described two methods. The copy method or the symlink method. The symlink method would also work with separate git folders.

Providing a script that allows for easy plugin installation (-> like enabling / disabling apache modules) sounds like a plan. Maybe for the future once we are sure things have settled down (we also provided a CRS installation / update script back in the day and scrapped it again).

I think zero thought went into docker integration so far, so any useful method is welcome.

**Comment by fzipi** [comment]
So we agree on:
- source of truth: [coreruleset.org/docs.](https://coreruleset.org/docs/configuring/plugins/).
- every plugin has a small intro on what it does, and points ☝️ for installing/configuring
- we can adapt the containers based on the documentation

**Comment by dune73** [comment]
I agree.

**Comment by azurit** [comment]
@fzipi Is there anything more which needs to be done here?

**Comment by fzipi** [comment]
I think we need to do a massive review on the plugins and see if everything matches this:
> - every plugin has a small intro on what it does, and points ☝️ for installing/configuring
> - we can adapt the containers based on the documentation

**Comment by fzipi** [comment]
@RedXanadu @azurit Is there some text that can/should be copied to every plugin out there? Or we close and ignore this one?

**Comment by fzipi** [comment]
Based on previous answers from the team, we close this one.
