### ISSUE TITLE
Improve reporting level mechanism

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#2474]
### Motivation

https://github.com/coreruleset/coreruleset/pull/2417#issuecomment-1086926343 by @dune73 

> The rules employed now follow an architecture that checks the reporting value.
> 
>     * If the reporting value is lower than x1, the scores are reported and the executing skipts the rest of the reporting
> 
>     * If the reporting values is greater-equal x1, then nothing is reported for the moment and we advance to the next condition with x2.
> 
> 
> This is an elegant use of ModSecurity.
> 
> But it also results in a situation where the reporting is split over n rules. That means if you are interested to learn the scores of a given request, you may have to scan multiple rule ids to check whether you find something about the request. From an operation viewpoint, this is not very elegant.

### Proposed solution

https://github.com/coreruleset/coreruleset/pull/2417#issuecomment-1086926343 by @dune73 
 
> Let's discuss an alternative approach: A single reporting rule reporting incoming score, outgoing score, SQLi score and friends.
> 
> Yet the rule is skipped by default. However depending no the reporting value it is accessed.
> 
> This could look as follows:
> 
>     * check reporting value is = 0 : skip to end-marker (this is here for performance reasons)
> 
>     * check reporting value is ge 3: jump to reporting rule
> 
>     * check reporting value is ge 2 AND incoming anomaly score is >= threshold: jump to reporting rule
> 
>     * check reporting value is ge 2 AND outgoing anomaly score is >= threshold: jump to reporting rule
> 
>     * check reporting value is ge 1 AND incoming anomaly score is > 0 : jump to reporting rule
> 
>     * check reporting value is ge 1 AND outgoing anomaly score is > 0 : jump to reporting rule
> 
>     * Skip to end-marker
> 
>     * Reporting rule
> 
>     * end marker
> 
> 
> This is the more complicated ModSecurity construct, but it results in a more elegant output. And the first constraint allows to skip the entire group for those not interested in reporting.

### Additional context

https://github.com/coreruleset/coreruleset/pull/2417

**Comment by dune73** [comment]
Thanks for splitting this into a separate issue.

**Comment by lifeforms** [comment]
Thank you, the work has been done in separate PRs so closing this!
