### ISSUE TITLE
All CRS plugins are missing copyright notices

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2492]
### Describe the bug

All CRS plugins are missing copyright notices.

### Expected behaviour

For consistency, all CRS plugins should follow the main CRS style and have clear copyright notices.

### Additional context

I think this was missed out by accident originally and now all the plugins, which are clones of the original plugins / dummy plugin, are missing copyright notices.

I will sort this out.

**Comment by RedXanadu** [comment]
I worked on this last week but didn't update this issue…

Issue resolved in all repositories I have write access to. PRs opened to fix all repos I don't have write access to. Waiting on PRs to be merged, then this will be resolved.

**Comment by azurit** [comment]
PRs in all of plugins where i have write access are reviewed and merged. Thanks!

**Comment by RedXanadu** [comment]
Thank you @azurit!

@dune73 : Are you happy to merge the copyright notice PRs on:

https://github.com/coreruleset/dummy-plugin
https://github.com/coreruleset/auto-decoding-plugin
https://github.com/coreruleset/incubator-plugin

**Comment by lifeforms** [comment]
Merged!

**Comment by dune73** [comment]
For the record: Yes.

Also: Thank you for providing them - and for merging.
