### ISSUE TITLE
Make regexp-assemble.py support chained rules

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2496]
### Describe the bug

When updating a regex using `regexp-assemble.py`, the main rule is always updated. We have rules which are having regex in the chained rule (for example 951230) so this tool break such rules. I suggest to implement it using `offset` like in modsec `SecRuleUpdateActionById`.

### Steps to reproduce

`util/regexp-assemble/regexp-assemble.py update 951230`

**Comment by dune73** [comment]
Well spotted. Thank you.

@theseion : not sure you get notes for new issues.

**Comment by azurit** [comment]
Just to add: rule 951230 is currently not using data file but it's going to do, see https://github.com/coreruleset/coreruleset/pull/2490.

**Comment by azurit** [comment]
Just to add: rule 951230 is currently not using data file but it's going to do, see https://github.com/coreruleset/coreruleset/pull/2490.

**Comment by theseion** [comment]
Yes, this is a known limitation. I'm working on an improvement that will address updating chained rules.
