### ISSUE TITLE
I am getting a false positive data:image/jpeg;base64

### ISSUE THREAD

**Issue by darmon77** [coreruleset/coreruleset#2506]
I am getting a false positive when loading images with the [cropperjs](https://fengyuanchen.github.io/cropperjs/) library 
This library processes edits with before loading them to png in data:image/jpeg;base64. 
momentarily deactivate the rule REQUEST-949-BLOCKING-EVALUATION.conf line 88 id "980130" obtaining the expected result loading the image. 
commenting rules is a bad practice NOT RECOMMENDED.
Is there a better way to remove that false positive only at runtime? if so; How do I create an exception? 

log 
[Log false positive](https://www.toptal.com/developers/hastebin/ojovefalox.md)
Back to the past............

_Originally posted by @darmon77 in https://github.com/coreruleset/coreruleset/issues/1849#issuecomment-1104897263_

**Comment by dune73** [comment]
Closing in favor of response in #1849.
