### ISSUE TITLE
Review project Honeypot blacklists inclusion

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2508]
### Motivation

While rewriting documentation about our extended install procedure, we found out that we still point to [Project Honeypot](https://www.projecthoneypot.org/) blacklists. Per @theseion comments in https://github.com/coreruleset/documentation/pull/39:
> It seems to be operational still but there has been no development for a couple of years now. There are also some known issues (e.g. PHP dropped support for one of the functions they use, no IPv6 support, etc.).

### Proposed solution

We should maybe reassess whether we want to advertise the project as we do now.

**Comment by dune73** [comment]
I think the correct take is to drop this link, to reassess the situation in a holistic way and then propose a few links in the documentation. This could include crowdsec and maybe other honeypot projects or other options.
If we do the new IP reputation plugin, then a blog post could introduce said plugin and link it to various options for IP deny-lists.
