### ISSUE TITLE
Some plugins are still private.

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2516]
### Motivation

The XenForo plugin repository is still private. It cannot be used by users at this moment, except for me of course 😎 (Testing it now.)

### Proposed solution

Make all plugins public?

**Comment by RedXanadu** [comment]
This makes sense with the RC launch.

We should officially launch (un-private) the plugin repositories. Also we should add the release date for the plugins in the CHANGELOG.

**Comment by lifeforms** [comment]
Thank you! I will be available this afternoon as well.

**Comment by RedXanadu** [comment]
Done.

### Complete (given a release date and made public):

- [drupal-rule-exclusions-plugin](https://github.com/coreruleset/drupal-rule-exclusions-plugin)
- [nextcloud-rule-exclusions-plugin](https://github.com/coreruleset/nextcloud-rule-exclusions-plugin)
- [dokuwiki-rule-exclusions-plugin](https://github.com/coreruleset/dokuwiki-rule-exclusions-plugin)
- [cpanel-rule-exclusions-plugin](https://github.com/coreruleset/cpanel-rule-exclusions-plugin)
- [xenforo-rule-exclusions-plugin](https://github.com/coreruleset/xenforo-rule-exclusions-plugin)
- [dos-protection-plugin-modsecurity-v2](https://github.com/coreruleset/dos-protection-plugin-modsecurity-v2)

### Needs attention:

- [wordpress-rule-exclusions-plugin](https://github.com/coreruleset/wordpress-rule-exclusions-plugin) (no release date)
- [phpbb-rule-exclusions-plugin](https://github.com/coreruleset/phpbb-rule-exclusions-plugin) (no release date)
- [phpmyadmin-rule-exclusions-plugin](https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin) (no release date)
- [dos-protection-plugin-modsecurity-v3](https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3) (is a draft: not in a release-ready state?)

**Comment by lifeforms** [comment]
Added today as the release date, except for [dos-protection-plugin-modsecurity-v3](https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3).
