### ISSUE TITLE
SecCollectionTimeout still being set in crs-setup.conf

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2517]
### Describe the bug

```
#
# -- [[ Collection timeout ]] --------------------------------------------------
#
# Set the SecCollectionTimeout directive from the ModSecurity default (1 hour)
# to a lower setting which is appropriate to most sites.
# This increases performance by cleaning out stale collection (block) entries.
#
# This value should be greater than or equal to any block durations or timeouts
# set by plugins that make use of ModSecurity's persistent collections (e.g. the
# DoS protection and IP reputation plugins).
#
# Ref: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecCollectionTimeout

# Please keep this directive uncommented.
# Default: 600 (10 minutes)
SecCollectionTimeout 600

```

* CRS version (e.g., v3.2.0): 4.0.0-RC1
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:

**Comment by RedXanadu** [comment]
```
# This value should be greater than or equal to any block durations or timeouts
# set by plugins that make use of ModSecurity's persistent collections (e.g. the
# DoS protection and IP reputation plugins).
```

This is still the case with CRS 4, no?

If you have multiple plugins defined that use persistent collections, you don't want each plugin to define `SecCollectionTimeout` separately, you want it defined once in a central location, no?

**Comment by dune73** [comment]
Probably yes, but then we should at least comment it out and then document the plugin to enable this.

I do not think it's a good idea to mess with something just because some users might install a plugin that needs something.

**Comment by fzipi** [comment]
What is needed here now?

**Comment by fzipi** [comment]
@dune73 Ping?

**Comment by dune73** [comment]
A joint decision by the project. I'm adding it to the agenda for the next start of the month chat. In the hypothetical case RC comes out before that, we can always implement this for a subsequent RC or full release, I think.

**Comment by dune73** [comment]
Documentation PR: https://github.com/coreruleset/documentation/pull/113

crs-setup.conf PR: https://github.com/coreruleset/coreruleset/pull/3559

Closing this in favor of these PRs.

And this should have been labelled v4, not sure why it slipped my attention.
