### ISSUE TITLE
Convert CHANGES to markdown

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2529]
It's easier on the eyes.

Also fix references to it, for instance from the release blog and installation page, and probably documentation.

**Comment by fzipi** [comment]
Created https://github.com/coreruleset/documentation/pull/53 also to fix docs.

**Comment by fzipi** [comment]
Once we merge this one, the release blog can be updated.

**Comment by lifeforms** [comment]
> Once we merge this one, the release blog can be updated.

Done.
