### ISSUE TITLE
unix-shell.data: change usr/bin to bin

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2597]
### Motivation

Some distributions are moving towards a single /bin and getting rid of /usr/bin.

Also, if we blocklist bin/foo it will also trigger on usr/bin/foo so we won't lose coverage of existing commands.

### Proposed solution

Use simple bin instead of usr/bin in unix-shell.data

### Alternatives

N/A

### Additional context

N/A

**Comment by fzipi** [comment]
Also we commented with @airween about using just `/usr/local/bin` and maybe `/usr/local/sbin`. But we need to double check for FP, as this is PL1.

**Comment by theseion** [comment]
Makes sense. Removing the `usr/` prefix shouldn't have a big impact.

**Comment by dune73** [comment]
I agree with this idea and assessment. But it is still a bit unsettling to see this link to the first generation of UNIX systems disappear.
