### ISSUE TITLE
Certain PDF is blocked by the WAF rules

### ISSUE THREAD

**Issue by priyanka-raghavan-maersk** [coreruleset/coreruleset#2612]
### Steps to reproduce
1. If i upload a certain PDF the Azure WAF rule kicks in and blocks stating DefaultRuleSet-1.0-LFI-930100.
2. The pdf is not liked by the rule. If I open the pdf in chrome and save as pdf and upload file, the path traversal rule has no problem
3. The original pdf is produced by iText 2.1.7 by 1T3X and version 1.4. 

### Expected behaviour
The 

### Your Environment

This is the production environment

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:

I also have this from the logs

action | Block
-- | --
clientIP | 49.207.193.50
clientPort | 41099
details { |  
dataMatched Data: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10  found within InitialBodyContents: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 matches [0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | data | Matched Data: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10  found within InitialBodyContents: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | matches [ |   | 0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | 0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | 0 { |   | matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | matchVariableName | InitialBodyContents | matchVariableValue | ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10
data | Matched Data: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10  found within InitialBodyContents: ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10
matches [ |  
0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | 0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | 0 { |   | matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | matchVariableName | InitialBodyContents | matchVariableValue | ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10
0 {matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | 0 { |   | matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | matchVariableName | InitialBodyContents | matchVariableValue | ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10
0 { |  
matchVariableNameInitialBodyContentsmatchVariableValue------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10 | matchVariableName | InitialBodyContents | matchVariableValue | ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10
matchVariableName | InitialBodyContents
matchVariableValue | ------WebKitFormBoundaryfXJczxhuExBuEJNi Content-Disposition: form-data; name="DocumentType"  10

msg | Path Traversal Attack (/../)
-- | --

What part of the regex should we decipher to see why it is blocked?

**Comment by franbuehler** [comment]
Hi!

Thank you for reporting your false positive.

From your logs, I am not able to see why the PDF triggered the "Path Traversal Attack" rule 930100.
I don't see any ../ or so, not even encoded.

Are you able to reproduce your request with a `curl` request so that we could reproduce the request against https://sandbox.coreruleset.org/ for example?

**Comment by theseion** [comment]
A couple of things:
- The rule to state does not correlate with the data. The data fits rule 920470, which validates the `Content-Type` header, and as part of that, `multipart/form-data` boundaries
- It is possible that rule 930100 also triggered but that is not shown in this output
- The matched string is clearly a space separated concatenation of headers, which is why it is invalid
- The headers are part of a variable called `InitialBodyContents`, which we don't know where it comes from; it could be a query argument, a body parameter, header...

Is there any chance that you could share the PDF? Or is there some other way we could reproduce this?
Can you provide request logs for those failures?

**Comment by franbuehler** [comment]
Hi @priyanka-raghavan-maersk,

Could you please give us the needed information so that we can help you??

**Comment by priyanka-raghavan-maersk** [comment]
Hi I am not able to regenerate a document with the information like the one that is producing the problem.
However the InitialBodyContents comes from the multipart form body that is causing the issue. 
![image](https://user-images.githubusercontent.com/82929831/172124217-aed06e6a-55ce-4525-90cb-9bd5d743105c.png)


This is also a screenshot of the log 
![image](https://user-images.githubusercontent.com/82929831/172124523-5e3aa69b-247a-4823-9b98-d2a17e723810.png)

**Comment by dune73** [comment]
While I do see the `InitialBodyContents` in the screenshot, I am none the wiser. The rule IDs leave me equally puzzled.

You are using a paid service from Microsoft Azure. I think it's time for their support.

**Comment by dune73** [comment]
Good luck. I'm closing this now on our side. If you have additional information or find out that it's really our fault, then please re-open.
