### ISSUE TITLE
update file `iis-errors.data`

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2631]
There is no information on where this list comes from. We need to get some sources and update the list.

**Comment by fzipi** [comment]
One relevant information for this list is that "_VBScript errors are likely no longer emitted with default IIS installations which disable Classic ASP. Some details here:_ https://docs.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-script-error-messages-no-longer-shown-in-web-browser-by-default."

**Comment by fzipi** [comment]
@dune73 @lifeforms Well, I'm puzzled now. The file `iis-errors.data` is not mentioned in any rule in the `RESPONSE-954-DATA-LEAKAGES-IIS.conf` file. 🤔 

A quick blame gives me:
```
81c5f0671 base_rules/iis-errors.txt (Ryan Barnett 2014-03-04 14:44:24 -0500
```

What shall we do here? I've made an update to the list, but now I think we should have a rule that uses it, right?

**Comment by dune73** [comment]
I agree. That would be an improvement in terms of overall rule set quality.

**Comment by RedXanadu** [comment]
For context (this may or may not be helpful):
It looks like `iis-errors.txt` was originally just a range of lines in `base_rules/modsecurity_50_outbound.data` in 2.2.9. I guess the IIS-specific lines in that file were split off into their own file, but the new file was never referred to or used by any rules, it seems.

**Comment by dune73** [comment]
I feared for a long time there might be some dirty past in those response rules.
