### ISSUE TITLE
MS Edge triggers false positive on rule 920274

### ISSUE THREAD

**Issue by vandanrohatgi** [coreruleset/coreruleset#2633]
### Description

Request header `sec-ch-ua-mobile":"?0` used in MS Edge triggers false positive on Paranoia Level 4. This header is not present in browsers such as Firefox. 

This is a valid header according to: https://datatracker.ietf.org/doc/html/rfc8941#section-3.3.6
### Audit Logs / Triggered Rule Numbers

Rule Number: 920274

[logs.txt](https://github.com/coreruleset/coreruleset/files/8900508/logs.txt)

### Your Environment

* CRS version :  3.3.2
* Paranoia level setting: 4
* ModSecurity version: 2.9.5
* Web Server and version : apache 2.4.53
* Operating System and version: Linux crs-waf 5.10.16.3-microsoft-standard-WSL2

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thanks for reporting @vandanrohatgi.

We are usually reluctant to trune away FPs in PL4 (and also PL3), but here we are facing a situation where a header sent on every request is triggering. So tuning this away may be useful.

**Comment by azurit** [comment]
I wasn't able to reproduce this with current CRS version using:
`curl -s -H 'x-crs-paranoia-level: 4' -H 'x-backend: apache' -H 'x-format-output: txt-matched-rules' -H 'sec-ch-ua-mobile: ?0' https://sandbox.coreruleset.org/`

@vandanrohatgi Can you confirm this is already fixed?

**Comment by dune73** [comment]
We have an exclusion on this header in place.

https://github.com/coreruleset/coreruleset/commit/560da95da0f2cb4dba5fa6c09cd61c574b8d4491

Closing this.
