### ISSUE TITLE
update file `restricted-files.data`

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2643]
There is no information on where this list comes from. We need to get some sources and update the list.

We might get something useful from [PayloadAllTheThings](https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/File%20Inclusion).

**Comment by MutableLoss** [comment]
Just looking through this list, I can only guess this came from multiple lists, or is there ? Just seeing how it's a mix of sensitive files from user-land and sys/proc files, it seems this list was amended over time.

Most of these entries are sensitive files for various web-frameworks, CMS'es, Database servers and HTTP servers. It looks like the system-level files are specifically for the lfi-os-files.data file #2649 , which I guess explains the existence of the sys/proc files. The system files can be found in the PAT lists:

proc https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/File%20Inclusion/Intruders/LFI-FD-check.txt

I'm sure there is a .gitignore boilerplate that exists somewhere with the most common files listed, but I have yet to find it. Of course, we can at least link existing docs for each of these services for each section. 

Just to expand the list to similar popular services, would we want to include ELK stack files?

We also watch for Rails issues elsewhere, so maybe adding Rails-specific files to this list would be beneficial?

(pre-Rails 5)
config/local_env.yml
config/secrets.yml

([Rails 5+](https://guides.rubyonrails.org/configuring.html#rails-environment-settings))
config/master.key
config/credentials.yml.enc
config/credentials/production.yml.enc
config/credentials/production.key
config/credentials/staging.yml.enc
config/credentials/staging.key
config/credentials/development.yml.enc
config/credentials/development.key

**Comment by theseion** [comment]
@coreruleset/core-developers I started looking into `restricted-files.data` and it's a bit of a mess. The file references multiple _sections_ (not the entire file) of `lfi-os-files.data` and says to "keep them in sync". Then there are a bunch of references to various platforms and tools. I don't see that this is maintainable in any way unless we split the file up and / or add something like the `include` processor to process these lists as well.

From the documentation I gather that `@pmFromFile` takes a _list_ of files as argument, so one simple way to improve maintainability would be to split the file into multiple files and then pass all of them to `@pmFromFile`. Unfortunately, it looks like we would end up with a of additional files.

How would you feel about _generating_ these files? It wouldn't be something as complex as regex-assembly, but with the same ideas:
- fixed format (and linting)
- automatic updates
- better reuse
- comments

I'm not saying that we would need to do this right away. We should first focus on the release.

**Comment by theseion** [comment]
Think: `crs-toolchain lists update -a`

**Comment by dune73** [comment]
I agree this is a mess.

Thanks for the hint on `@pmFromFile` - that had slipped my memory completely. Most interesting.

The work on the UAs leads me into the same direction. I have a bash monster so far and would like to streamline it. An important feature I would need is a hook where I can run `sed` to make adjustments to the sourced list.

**Comment by theseion** [comment]
@fzipi I'm a bit at a loss here w.r.t. to the configuration and dotfiles. I can automate generating the file, I can document stuff etc. but I don't think there's a good source for the list of files. In fact, I think we are the best source... I've tried to trace the history of `lfi-os-files.data` and it seems to come from Trustwave. The original file looks to me very much like a collection of matches that they sourced from attack requests they observed: https://github.com/coreruleset/coreruleset/blob/0a035ccb79c12c2f0cea65e081b62777314dc399/base_rules/lfi_os_files.txt.

What's your feeling?

**Comment by fzipi** [comment]
I think we that we can add some of those to the generic extensions we block, in particular `.enc` and `.key` should be blocked in other rule at PL1 probably. So the effect would be the same. Can we do the same for other files/extensions?

The other part I need to think it better. We need to update it, for sure.

**Comment by dune73** [comment]
I am not surprise there is no other list. And maybe this is really something we have to maintain ourselves. I have quite a few hits here and I could contribute to the list, but I rarely do.

What I think is difficult is avoiding FPs. It's obvious that `.git` is bad, but there are a lot of URIs that are benign in one context and an obvious attack in a different one. (-> WP URIs)

**Comment by dune73** [comment]
Thinking a bit more about this, here is a potential source: https://github.com/mazen160/bfac/blob/master/bfac

@mazin160 did not update this for 2 years, but when I looked at it before the pandemic, it looked very extensive.

**Comment by fzipi** [comment]
If this is potentially a good source as an independent list, we can even create a new repo and project for it.
