### ISSUE TITLE
update file `php-variables.data`

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2651]
This is probably the most static list that we will have.

We can get all probably using https://www.php.net/get_defined_vars or similar?

Example:
```php
php -r 'print_r(array_keys(get_defined_vars()));'
Array
(
    [0] => _GET
    [1] => _POST
    [2] => _COOKIE
    [3] => _FILES
    [4] => argv
    [5] => argc
    [6] => _SERVER
)
```

Maybe we want to extend this list by using `php -r 'print_r(array_keys(get_defined_constants()));'`  or even `php -r 'print_r(get_declared_classes());'` 🤷

**Comment by fzipi** [comment]
@lifeforms @theMiddleBlue What do you think about this one?

**Comment by theMiddleBlue** [comment]
I think there're more constants/globals that we should add other than the ones on your list. For example:

[$GLOBALS](https://www.php.net/manual/en/reserved.variables.globals.php)
[$_SESSION](https://www.php.net/manual/en/reserved.variables.session.php)
[$_REQUEST](https://www.php.net/manual/en/reserved.variables.request.php)
[$_ENV](https://www.php.net/manual/en/reserved.variables.environment.php)

etc...

maybe we should parse the PHP documentation and get a list? we could also include a list of deprecated function/globals/constants

**Comment by fzipi** [comment]
Do we need to add also global constants? https://www.php.net/manual/en/reserved.constants.php

**Comment by theMiddleBlue** [comment]
it should be a good idea, except for booleans and nulls that could be prone to FPs
