### ISSUE TITLE
Remove un-necessary escapes from slashes in regexes

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2657]
### Motivation

See the discussion in #2622. 

- Forward slashes (`/`) do not require an escaping backslash. All manually created regular expressions should use `/` instead of `\/` (note that generated expressions may still include the escape character).
- Backslashes must be properly escaped, but there are differences in how engines parse input strings with multiple escape characters. We already consolidated all literal backslashes (i.e. `\\`) to `\x5c`, so backslashes don't need to be addressed.

**Comment by fzipi** [comment]
@dune73 Can you write some specification of what needs to be done here?

**Comment by dune73** [comment]
I'd rather have @RedXanadu or @fgsch define that.

**Comment by RedXanadu** [comment]
Ah, yes. So, we now just need to enforce our policy on [forward slash representation](https://coreruleset.org/docs/development/contribution_guidelines/#forward-slash-representation).

**Comment by RedXanadu** [comment]
Only one instance of an unnecessary forward slash escape was found in the rule set :sweat_smile:

Lots of the compiled regex patterns have escaped forward slashes, but we're leaving those alone.

Once #2805 is merged, I believe we can close this issue!

**Comment by RedXanadu** [comment]
The associated PR has now been merged.

This issue is now resolved.
