### ISSUE TITLE
XSS in javascript context using `setTimeout`

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2661]
### Describe the bug

This one comes from BB 4A9UJH6G.

There is a XSS problem when using `setTimeout` in a javascript context  (e.g. in a string or json).

The proposed example shows that `setTimeout(name, 1)` is not detected:

```
x";setTimeout(name, 1)//

<script>
var reflection = "INPUT";
</script>
<script>
var reflection = "x";setTimeout(name, 1)//";
</script>
```

### Steps to reproduce

A full XSS would look like this on the attackers website: 

```
window.open("https://vulnwebsite.tld?x=x%22;setTimeout(name, 1)//","alert(document.cookies)")
```

### Expected behaviour

Request should be blocked.

### Your Environment

* CRS version (e.g., v3.2.0): v4.0/dev
* Paranoia level setting: PL3
* ModSecurity version (e.g., 2.9.3): 2.9.6
* Web Server and version (e.g., apache 2.4.41): apache latest
* Operating System and version:

**Comment by lifeforms** [comment]
Related PR is merged, awesome!!
