### ISSUE TITLE
Split rules that use pm data lists into two: one for unversioned files/paths, and a new sibling with a regexp to match versioned paths/files

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2665]
### Motivation

While reviewing lists, we are being extremely static on our detection. Also, it is not scalable as versions are (of course) being constantly upgraded. So getting behind on protection is way too easy. If we don't react quick enough, things like matching `python3.11` or others might take us time.

Example,
```
etc/php/php4/php.ini
etc/php4.4/fcgi/php.ini
etc/php4/apache/php.ini
etc/php4/apache2/php.ini
etc/php4/cgi/php.ini
etc/php5/apache/php.ini
etc/php5/apache2/php.ini
etc/php5/cgi/php.ini
```

### Proposed solution

Why not use a small subset of regular expressions for those variable strings? We remove them from our pm data files, and move them to a new sibling rule that uses a regexp-assembly generated one.

Split rules like 930120 in two:
- one will remain using pm aho-corasick matches
- a new regexp-assembled file in a new sibling rule with version matching

For the previous example, move it to something like:
```
etc/php(\d+)?(\.\d+){0,2}/apache2/php.ini
```

Maybe we don't want this for all files we have listed, but really important files like the php.ini example above might be a real win.

**Comment by RedXanadu** [comment]
@fzipi Does this still need to be done? We still have the issue of versioning in some data files, right?

**Comment by fzipi** [comment]
No, we can leave this one closed, thanks for pointing this out.
