### ISSUE TITLE
Monthly Chat Agenda July (2022-07-04 and 2022-07-18)

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2675]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2022-07-04, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2022-07-18. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* [Kubernetes / Ingress ModSecurity writeup](https://vuln.be/post/kubernetes-modsecurity/)

### Declogging our project - We're somewhat stuck with too many bug bounty findings

* How is the situation?
* How can we get out of it?

### Project Marketing

* Any alternative proposals to the one we shared via the dev channel?

### PRs that have been merged since the last meeting

* #2587
* #2664
* #2660
* #2596
* #2662
* #2583
* #2656
* #2555
* #2552
* #2567
* #2609
* #2635
* #2564
* #2599
* #2627
* #2524
* #2566
* #2538
* #2624
* #2623
* #2603
* #2604
We merged 22 PRs since the last monthly project chat.
### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2557
* #2573
* #2575
* #2578
* #2581
* #2584
* #2591
* #2594
* #2595
* #2637
* #2663
* #2666
* #2668
* #2669
* #2676
* #2677

## Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2590
* #2572
* #2562
* #2478
* #2301
* #2302
* #2303
* #2290
* #2217
* #2067
* #1975

## Dev retreat topics

* **[Demo / Sandbox site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite)**: Fixed 1-2 bugs
* **[Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)**:
  * New page: [Operation: Kubernetes Ingress Controllers](https://coreruleset.org/docs/operation/kubernetes_ingress/) (thank you @fzipi)
  * New page: [Development: regexp-assemble](https://coreruleset.org/docs/development/regexp_assemble/) (thank you @theseion)
  * Updated / new content: [Development: Contribution Guidelines](https://coreruleset.org/docs/development/contribution_guidelines/) (thanks again to @theseion)
* **[Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts)**: nothing
* **[Status page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage)**: on hold
* **[Coraza](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration)**: some progress, but no GSoC student could be found, developers needed...

## Other items

* Dev on Duty with empty positions for July and August

### Status of issues covered last month

* Issue slots last meeting were internally discussed about the ones from BB.

**Stats**

* Covered in chat: FIXME
* Closed: FIXME
* Pending: FIXME

### This month's issues

There are FIXME open issues at the beginning of the issue chat.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #2562
(Needs a decision: New rule or extension of existing `restricted_extensions` rule?)
* Issue slot 2: #2621 
* Issue slot 3: #2680
* Issue slot 4: #2676
* Issue slot 5: #2625
* Issue slot 6: #FIXME
* Issue slot 7: #FIXME
* Issue slot 8: #FIXME
* Issue slot 9: #FIXME
* Issue slot 10: #FIXME

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions

## Declogging our project (bug bounty)

2-phases-plan to fight against overwhelming bug bounty work:

**Idea phase 1:**

One thing is, it’s hard to develop rules without good tests. So we were thinking to organize a “special project”, which would have a budget of 5K, to create test files for all findings. This is an important task as it will give us more velocity on developing rules.
This can be somebody or a small team that divides the tasks.
The idea is to have everything very clear in ftw-yaml format and thus almost curl-ready when we start to create a PR to fix it.
We could put the tests in a repo by their vendor ID.

Idea by Max:
We should / could write a script to convert between tests and curl...
-> https://github.com/coreruleset/coreruleset/issues/2678
Ervin would like to work on this script.

Azurit thinks he can do part of idea 1 work but not sure if he can handle it all.
Will discuss more about it with Christian.

Idea phase 2:
We've been productive during retreat. So Walter was thinking of a virtual hackathon somewhere in the summer where we take some days off and fully concentrate on closing vulns as a team.

Proposal: Aug 1 to Aug 4.

Who can attend?

* Walter
* Franziska: Monday maybe, Wednesday yes.
* Ervin: not the whole day, but partially
* Emphazer
* Max
* Xanadu: might be moving the house, but if not: yes!

## PR / Marketing

Proposal accepted

**Comment by fzipi** [comment]
## Issues Meeting

- #2562 - Create a new rule for PL2 targeting the new restricted_extensions_archives (@RedXanadu )
- #2621 - @fzipi will do a second pass on more files needing update, and consolidating if they are similar for using the `include` directive in regexp-assemble
- #2621 - involved Simon to see if he wants to take the lead on this one
- #2676 - PR to show how is the update process, and making an example on what is expected for the update in general
- #2625 - @emphazer will take a look
