### ISSUE TITLE
 Create IP reputation plugin

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#2680]
### Motivation
The reputation rules have been removed from the core.

### Proposed solution
Create an optional plugin for IP reputation blocks based on previous CRS violations.

### Additional context
https://github.com/coreruleset/coreruleset/issues/2433

**Comment by fzipi** [comment]
Thanks for creating this one! 🚀 

Do you want to take the lead on a proposal?

**Comment by studersi** [comment]
Not sure to be honest. I don't really have any time to work on these plugins at the moment.

The functionality of this plugin could be to keep an IP reputation score that accumulates and persists across requests.

We already have separate DDoS and RBL plugins (or they are planned at least). They could take care of burst requests and externally provided IP reputation.

This plugin could simply add the anomaly scores of each request to the persistent IP collection and block requests if they reach a certain limit. or just add the accumulated score back to the regular anomaly score variables on subsequent requests from the same IP.

**Comment by fzipi** [comment]
No worries! 😄 

Thanks for the extended description, I guess it simplifies the task for whoever is taking this.

**Comment by dune73** [comment]
I agree. There is nothing wrong with release CRSv4 without this functionality. If there is a pressing need somebody will write a plugin from scratch, or people use something that is better suited than ModSec for this task.
