### ISSUE TITLE
Detect `$ {` PHP injection

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2686]
### Description

In #2668, it was shown that PHP variables can be accessed by `$ {` (note the space between the chars).

As @theMiddleBlue found, PL1 can be bypassed for example:

```
print_r($ {'_SER'.'VER'});
```

We have a rule 932130, which fires on `${` to detect unix shell snippets. I checked but in the shell, adding a space between `$` and `{` doesn't work:

```
# testy=123
# echo ${testy}
123
# echo $ {testy}
$ {testy}
```

But in PHP it works. So the right place to detect this, is not the rule 932130, but a new rule, with a different attack class: PHP code injection. 

### Your Environment

* CRS version (e.g., v3.2.0): nightly
* Paranoia level setting: 2
* ModSecurity version (e.g., 2.9.3): 2.9.3
* Web Server and version (e.g., apache 2.4.41): apache
* Operating System and version: n/a

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
Notta di Stale!

**Comment by fzipi** [comment]
@azurit Can you take this one, provided you have experience with PHP? Thanks!

**Comment by azurit** [comment]
@fzipi Should we match also `${` (without a space) by a new rule? It is valid PHP syntax, too, but it's already matched by rule `932130` (which has nothing to do with PHP).

**Comment by fzipi** [comment]
> So the right place to detect this, is not the rule 932130, but a new rule, with a different attack class: PHP code injection.

I think that is exactly hat is noted here by Walter. So a new rule to covers that case.

**Comment by fzipi** [comment]
After the discussion in the meeting in June, any news on this one @azurit ?

**Comment by fzipi** [comment]
Ping @azurit.

**Comment by fzipi** [comment]
Hey @azurit, do you think you can follow up on this one?

**Comment by azurit** [comment]
@fzipi Here you are.
