### ISSUE TITLE
Monthly Chat Agenda August 2022 (2022-08-01 and 2022-08-15)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2690]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2022-08-01, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2022-08-15. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* [Blog post explaining the delay](https://coreruleset.org/20220711/update-on-crs-4-0-release-delay/)
* The CRS project entered an agreement with a PR company to help us with project marketing. The goal is the promote the project and participating as developer (we are not doing marketing to bring CRS to users, we do marketing to bring developers to our project!). This is paid for by our sponsors.
* The CRS project has started to pay Christian Folini / @dune73 a small monthly sum for project coordination and various administration work. This is paid for by our sponsors.
* There is a virtual hackathon running from Aug 1 to Aug 5 where CRS developers will write PRs to fix the remaining open bug bounty reports. This is happening in the private dev slack channel.
* The 2022 CRS developer retreat will happen from Saturday Oct 29 to Saturday November 5, 2022. We'll stay in the Villa Cagnola near Varese, Italy. That's 20-30 min from Milano airport.

### PRs that have been merged since the last meeting

* #2700
* #2696
* #2667
* #2687
* #2590
* #2669
* #2668
* #2594
* #2578
* #2557

We merged 10 PRs since the last monthly project chat.

## Open PRs

* #2702
* #2677
* #2676
* #2666
* #2663
* #2637
* #2595
* #2591
* #2584
* #2581
* #2575
* #2573

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2701
* #2572
* #2562
* #2478
* #2303
* #2302
* #2301
* #2290
* #2217
* #2067
* #1975 

## Sub projects

* **[Demo / Sandbox site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite)**: There is a new sandbox mode that triggers a blockade / 403 if the anomaly score is above the treshold. This can be configured via a HTTP header.
* **[Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)**: no change
* **[Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts)**:
  * @RedXanadu is slowly :turtle: :snail: working on a blog post idea: "A quantitative approach to false positives": Testing our regular expressions against large bodies of examples of natural language and seeing how different PLs compare for FPs (inspired by a Bug Bounty submission).
* **[Status page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage)**: no change
* **[Coraza](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration)**: no news

* **GSoC**: 2 midterm evaluations submitted: CVE: pass / ML: pass but with addition "I have some reservations about passing the contributor".

## Other items

* Sandbox: Should blocking with 403 be the new default behavior?
* Restricted file types: We removed `.axd` from the restricted extensions list, but there's talk of adding it back. Should we leave it off the list? (Re: #2562)
* #2591 is at an impasse. Need to make a tough decision about the direction we are taking here.

## Open Issues - Separate Issues Meeting (Monday, 2022-08-15)

* First item on agenda: Status of the bug bounty findings
* The turning to open PRs, namely bug bounty
* Looking through bug bounty findings and how to attack the remaining open ones
* Sandbox with different results than a local CRS installation

### This month's issues

There are FIXME open issues at the beginning of the issue chat.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #FIXME
* Issue slot 2: #FIXME
* Issue slot 3: #FIXME
* Issue slot 4: #FIXME
* Issue slot 5: #FIXME
* Issue slot 6: #FIXME
* Issue slot 7: #FIXME
* Issue slot 8: #FIXME
* Issue slot 9: #FIXME
* Issue slot 10: #FIXME

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Meeting decisions

## Other Items

* Sandbox: Should blocking with 403 be the new default behavior? -> Unless @fzipi  and maybe @theMiddleBlue bring some cutting arguments in favor of 200 we'll change to 403 by default during the week.
* Restricted file types: We removed `.axd` from the restricted extensions list, but there's talk of adding it back. Should we leave it off the list? (https://github.com/coreruleset/coreruleset/pull/2562) -> If we removed `.axd` in 7 Dec 2020 and no one has noticed or complained… maybe we keep it simple and take it out for good. Assuming there are no objections or good reasons to add it back in. And if somebody has hard feelings we're open for a PR that adds a commented out variant with `.axd` to `crs-setup.conf`.
* https://github.com/coreruleset/coreruleset/pull/2591 is at an impasse. Need to make a tough decision about the direction we are taking here.

**Comment by azurit** [comment]
Can i close this?

**Comment by dune73** [comment]
Absolutely. Thank you for cleaning up.
