### ISSUE TITLE
Review the `user-agentt` adding from #2048

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2695]
### Describe the bug

I would like to revisit https://github.com/coreruleset/coreruleset/pull/2048.

Taking a look at the config file and example, there is no documentation there stating why that `user-agentt` is needed or why to block it.

Even the discussion in the PR is reasonable. 

The problem was detected and reverted the same day (see https://github.com/php/php-src/commit/2b0f239b211c7544ebc7a4cd2c977a5b7a11ed8a?branch=2b0f239b211c7544ebc7a4cd2c977a5b7a11ed8a&diff=unified#diff-a35f2ee9e1d2d3983a3270ee10ec70bf86349c53febdeabdf104f88cb2167961R368-R370 and https://github.com/php/php-src/commit/8d743d5281c29e9750e183804b7ba02e1ff82f0b).

No PHP versions were created that could contain this code. And an extensive review of the PHP code was made afterward.

So IMHO we are good to remove it from our protections.

**Comment by lifeforms** [comment]
I agree, this vuln was not out in the wild, there were no supply chain issues, and I'm fine with removing the check.
