### ISSUE TITLE
Duplicated tests: 942290-3 and 942290-4

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#2697]
### Describe the bug

Tests `942290-3` and `942290-4` are the same:
https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942290.yaml

Merged here:
https://github.com/coreruleset/coreruleset/pull/2579

### Solution

1. Contact PR author (@rekter0) and ask him to fix the test as probably only he knows how it should look like.
2. If first step doesn't work, remove test `942290-4` and fix `test_title`s of tests below it.

**Comment by fzipi** [comment]
Per comments on the tests, they should come from https://blog.securelayer7.net/mongodb-security-injection-attacks-with-php. So the first five tests should replicated the ones there.

**Comment by fzipi** [comment]
@azurit Do you want to take this one?

**Comment by azurit** [comment]
@fzipi Sure.

**Comment by fzipi** [comment]
We can close this one.
