### ISSUE TITLE
Review XSS rules for inclusion of REQUEST_URI in variables to match

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2699]
### Description

BB: EOJQZ6XX

The report received mentioned the usage of the following XSS technique on paths `/index.php/%3Csvg/onload=alert()`

👉 We should review all XSS rules to see if/where we need to include the `REQUEST_URI` or similar to overcome this.

**Comment by lifeforms** [comment]
I created a PR in #2730. Please continue the discussion over there!
