### ISSUE TITLE
Detect `' notnull --` in SQLi rules

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2703]
### Description

BB Finding 7MV2I59X

`email=' notnull --`

`curl -v localhost/?email=%27%20notnull%20--`

**Comment by franbuehler** [comment]
`notnull` was added to the PL2 rule 942120 by Karelogin on May 15:

https://github.com/coreruleset/coreruleset/commit/66f1529068770ab789d8084b39e4bd6c644be64d

**Comment by lifeforms** [comment]
The linked PR is merged, thank you! 🥳
