### ISSUE TITLE
Detect `' is not?--` in SQLi rules

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2704]
## Description

BB Finding 7NLGEWUC

email=`' is not?--`

`curl -v localhost/?email=%27%20is%20not%3F--`

**Comment by franbuehler** [comment]
`' is not?--` is detected by terjang's new PL2 rule 943520 which was added on Jun 4:
https://github.com/coreruleset/coreruleset/pull/2568/files
`[id "942520"] [msg "Detects basic SQL authentication bypass attempts 4.0/4"] [data "Matched Data: ' is not found within ARGS:email: ' is not?--"]`

PL2 rule 942110 should match as well, but the rule only has `severity "WARNING"` and adds a score of `3`:
`[id "942110"] [msg "SQL Injection Attack: Common Injection Testing Detected"] [data "Matched Data: ' found within ARGS:email: ' is not?--"]`

**Comment by lifeforms** [comment]
Looks good, linked PR with test is merged!
