### ISSUE TITLE
Detect `admin%40juice-sh.op\'and%20likely%20(id)--` in SQLi rules

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2707]
BB case 5XJH0GXM

`admin%40juice-sh.op\'and%20likely%20(id)--`

`curl -v localhost/?admin%2540juice-sh.op%5C%27and%2520likely%2520%28id%29--`

**Comment by franbuehler** [comment]
Already detected by terjanq's new rules 942151 and 942522 (May 24):
https://github.com/coreruleset/coreruleset/commit/cb076a4139af7345ad701d51f7a6b07352c438b8

`[id "942151"] [msg "SQL Injection Attack"] [data "Matched Data: likely ( found within ARGS_NAMES:admin%40juice-sh.op\\x5c\\x5c'and%20likely%20(id)--: admin@juice-sh.op\\x5c'and likely (id)--"]`

[id "942521"] [msg "Detects basic SQL authentication bypass attempts 4.1/4"] [data "Matched Data: admin@juice-sh.op\\x5c'and found within TX:942521_lhs: and"]

[id "942522"] [msg "Detects basic SQL authentication bypass attempts 4.1/4"] [data "Matched Data: admin@juice-sh.op\\x5c'and found within ARGS_NAMES:admin%40juice-sh.op\\x5c\\x5c'and%20likely%20(id)--: admin@juice-sh.op\\x5c'and likely (id)--"]

**Comment by lifeforms** [comment]
Thanks for adding the tests! Merged the linked PR.
