### ISSUE TITLE
Detect `admin%40juice-sh.op'%20and%20password%20glob%20password;` in sqli rules

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2709]
BB cases 5PESYSYC and 7WPA04FK

* `admin%40juice-sh.op'%20and%20password%20glob%20password;`
* SQL bypass using glob

`curl -v localhost/?admin%2540juice-sh.op%27%2520and%2520password%2520glob%2520password%3B`

**Comment by franbuehler** [comment]
Detected by terjanq's new rule 942521:

`[id "942521"] [msg "Detects basic SQL authentication bypass attempts 4.1/4"] [data "Matched Data: admin@juice-sh.op' and found within TX:942521_lhs: and"]`

**Comment by franbuehler** [comment]
The expression `glob` is partially detected in the new PL2 rule [942520](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1386). But only `glob` does not match, only the string `"not glob` matches.
I first thought about extending this rule 942520. But removing the `[\"'`]\s*?`at the beginning of the rule could probably lead to false positives.

So I was thinking about extending the PL2 rule [942130](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L615) which checks for [# - 942130 targets tautologies using equalities (e.g. 1 = 1)](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L604). And I think this is exactly what `GLOB` does.

So I'll propose a PR that will add `glob` to the 942130.data like that:
`[\w]+\s*glob[\s'\"`()]*?[\w?*]+\b`

https://www.tutorialspoint.com/sqlite/sqlite_glob_clause.htm

**Comment by lifeforms** [comment]
Looks good, merged! 🥳
