### ISSUE TITLE
Add new test for SQLite command

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2713]
## Description

Relates to **1DQC0CU3**

Associated PR: #2714

---

The issue was that we didn't pick up the SQLite function `sqlite_compileoption_used`, allowing things like:

```
curl --data-binary 'email=admin%40juice-sh.op\'%20or%20sqlite_compileoption_used%20(id)--' ...
```

We now _do_ pick up the `sqlite_compileoption_used` function (in rule 942151), which was added already in #2570.

Now let's just add a test for 1DQC0CU3 and get that marked as complete.

**Comment by lifeforms** [comment]
Test is succeeding, PR is merged! 🥳
