### ISSUE TITLE
Detect ksh (KornShell)

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2720]
## Description

Relates to **PFK4711C**

Associated PR: #2721

---

We have various rules to detect popular Unix shells, including bash, dash, csh, and zsh, but we do not detect ksh in all of them (it's missing in some rules).

- Add detection for `ksh`
  - 932100(/932105) - already present
  - 932150 :heavy_check_mark:
  - unix-shell.data - already present
- Add an associated test :heavy_check_mark:

**Comment by lifeforms** [comment]
PR looks good and has been merged!
