### ISSUE TITLE
More missing PHP wrappers

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2724]
### Describe the bug

Following on from #2722, it looks like we may be missing some additional PHP wrappers, specifically the `ssh2.*` family.

**Source**: https://www.php.net/manual/en/wrappers.ssh2.php

### Expected behaviour

We should cover these additional PHP wrappers:

- `ssh2.shell://`
- `ssh2.exec://`
- `ssh2.tunnel://`
- `ssh2.sftp://`
- `ssh2.scp://`

### Actual behaviour

We currently only match against `ssh2://`

### Your Environment

* CRS version (e.g., v3.2.0): v4.0/dev

### TODO

- [x] Update rule 933200's data file to add the additional `ssh2.*` patterns
- [x] Add a note to rule 933200 and its associated data list to link to where the wrappers are originally documented (https://www.php.net/manual/en/wrappers.php)

**Comment by fzipi** [comment]
Just in case, we have moved all wrappers to this file now: https://github.com/coreruleset/coreruleset/blob/v4.0/dev/util/regexp-assemble/data/include/url-schemes.data

**Comment by fzipi** [comment]
That way we can just include it in the corresponding regex using the regexp-assemble `include` directive.

**Comment by RedXanadu** [comment]
@fzipi But what about rule 933200?

I've just updated rule 933200 where the wrappers are. See: #2723

**Comment by fzipi** [comment]
Awesome.

I think we should take a note in the data file where the wrappers come from (https://www.php.net/manual/en/wrappers.php), and [add it to the issue](https://github.com/coreruleset/coreruleset/issues/2621) that tracks the list of files to update whenever we do the list updating process.

**Comment by fzipi** [comment]
Added to the list that tracks updates. Closing.
