### ISSUE TITLE
ModSecurity rules 949110 and 930110

### ISSUE THREAD

**Issue by zhoueysun** [coreruleset/coreruleset#2745]
### Description

I am on a shared hosting with Namecheap.com. I don't have any access to modsec logs. When I upload certain images into my **webtrees** program installed with Softaculous sponsored by Namecheap, I will get **SyntaxError: Unexpected token < in JSON at position 0**

Namecheap customer support white listed ModSecurity rules 949110 and 930110 and things work well now. 

The programmer of **webstrees** expressed an interest of what is in those certain media files which trigger modsec to activate.

Based on the rules number above, can you provide that information so I may forward the answer to him?

**Comment by dune73** [comment]
By "whitelisting" 949110 the support has effectively disabled all blocking of malicious requests. 949110 is the rule that blocks a request after a detection rule like 930110 has detected an anomaly.

930110 checks for the following regular expression: `(?:(?:^|[\x5c/])\.{2,3}[\x5c/]|[\x5c/]\.{2,3}(?:[\x5c/]|$))` on the following parameters: `REQUEST_URI|ARGS|REQUEST_HEADERS|!REQUEST_HEADERS:Referer|FILES|XML:/*`

I'm closing this issue now as this is not per se a CRS issue. If you want to learn more, I suggest you join the coreruleset channel on the OWASP slack via https://owasp.org/slack/invite.

**Comment by jjarokergc** [comment]
Hello, 

I encountered this block just now performing the same media upload on webtrees as the original poster.  Thank you @airween, I appreciate the advice to not exclude 949110, which I was going to add to my webtrees instance.  Instead, I excluded the following two rules:

```
SecRuleRemoveById 930110
SecRuleRemoveById 930120
```
Excluding these rules allowed me to upload media to webtrees.  Here is the original log message:
```
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `lfi-os-files.data' against variable `ARGS:unused' (Value: `.htaccess' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "78"] [id "930120"] [rev ""] [msg "OS File Access Attempt"] [data "Matched Data: .htaccess found within ARGS:unused: .htaccess"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "10.10.10.107"] [uri "/tree/Kolik/create-media-object"] [unique_id "1691795643"] [ref "o0,9v209616,9t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "10.10.10.107"] [uri "/tree/Kolik/create-media-object"] [unique_id "1691795643"] [ref ""]
```
Please let me know if you have comments on my excluding both of these rules.

**Comment by dune73** [comment]
I do not see an alert for 930110, but if you are sure that `unused=.htaccess` is innocent, then this is OK. You may want to use a more granular rule exclusion here. The way you do it, the rule is completely removed. Alternatives: Disable for the URI or disable for the parameter in question or a combination thereof. See documentation at coreruleset.org/docs.
