### ISSUE TITLE
feat(LFI): Detect Windows style filepaths

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2749]
### Description

Bug Bounty issue: U8Z0MSCP

Earlier pull request: https://github.com/coreruleset/coreruleset/pull/2595

This issue may be harder than it looks (or maybe not). I am confused because as far as I know, we should have detected this technique also in earlier releases. So I think we may have to fix an existing rule as well, and that rule is really complex. I closed the hacker PR for now, but may use it as a reference.

It's also possible we had a problem with the sandbox leading to a false result.

In any case, it will need a good look and some concentration.

**Comment by theMiddleBlue** [comment]
by sending the reported payload to the sandbox nightly, it seems that we already block this at PL1:

![image](https://user-images.githubusercontent.com/4454961/199198127-5dcff326-9406-4429-aebd-5019ea3d7c57.png)

I'm going to close this for the moment, feel free to reopen if I missed something
