### ISSUE TITLE
getting FP with paranoia level 1

### ISSUE THREAD

**Issue by ludique** [coreruleset/coreruleset#2752]
Filing this issue cause I get a 403 Forbidden on some post request from a system I'm working with.
CRS version is 3.3.2 and paranoia level 1
relevant modsec_audit.log:
[audit.log](https://github.com/coreruleset/coreruleset/files/9377419/audit.log)
offending headers:
[request.txt](https://github.com/coreruleset/coreruleset/files/9377455/request.txt)
Hope someone can take a look at it.

**Comment by dune73** [comment]
Wow, this is stunning. I only looked at this for 5 mins and multipart format is hard, but the request looks really innocent, namely the request line and the content-length. So I can not see how the request documented in your attachments could trigger these alerts.

Are sure the rest of the server runs OK?

**Comment by azurit** [comment]
Hi @ludique! Those logs looks really weired. How was that request done? Using a browser or a script?

**Comment by ludique** [comment]
Hi, the server is running multiple websites without an issue, this in
particular is an electron app called adminjs.
The request was made on firefox and headers were captured in dev tools as
raw and the audit log was taken from /var/log/modsec_audit.log in a ubuntu
server 22.04 running nginx.
I believe it's a weird issue since protocol enforcement warning rules are
getting triggered by well formed headers, this adds up in anomaly score so
finally rule 949110 gets triggered and a 403 error is responded.
Maybe I could try reproduce this issue on a different os/web server
versions.
Fernando Casar L.
Director Operaciones
Ludique Comunicaciones
+56996755039

**Comment by azurit** [comment]
Can you try different browser?

**Comment by RedXanadu** [comment]
That request works fine for me. Tested successfully against ModSecurity2 on Apache and ModSecurity3 on nginx.

This:

``
Operator `Rx' with parameter `^\d+$' against variable `REQUEST_HEADERS:Content-Length' (Value: `542' ) [msg "Content-Length HTTP header is not numeric"] [data "542"]
``

is extremely strange. That rule uses a simple regular expression: it should absolutely pass with the input `542`…

Incidentally, the three rules that matched in your audit log report:

- 920160
- 920470
- 920100

all use an operator of the form `!@rx ...`. They are also the only atomic (non-chain) rules using the negation (`!`) operator. It's like the negation is not being respected.

A regular expression library problem? A weird engine bug?

@ludique Did you compile the WAF components yourself or are you using pre-compiled binaries?

**Comment by ludique** [comment]
Hi, it was compiled from source and using nginx from ppa:ondrej/nginx. did
the install according to this tutorial:
https://www.linuxcapable.com/how-to-install-nginx-with-modsecurity-3-on-ubuntu-22-04-lts/
thanks!

Fernando Casar L.
Director Operaciones
Ludique Comunicaciones
+56996755039

**Comment by airween** [comment]
I installed Nginx + libmodsecurity3 + libnginx-mod-http-modsecurity module from [here](https://modsecurity.digitalwave.hu), onto my Ubuntu 2204 system.

Your request.txt contains only the headers, so I couldn't check your request exactly, therefore I used this:

```
$ curl -v -F person=anonymous -F attachment=@data.txt http://localhost
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 316
> Content-Type: multipart/form-data; boundary=------------------------fdd8cd9d3254e3a4
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Tue, 23 Aug 2022 07:52:22 GMT
< Content-Type: text/html
< Content-Length: 10671
< Last-Modified: Wed, 03 Aug 2022 16:00:36 GMT
< Connection: keep-alive
< ETag: "62ea9ba4-29af"
< Accept-Ranges: bytes
< 
```

The mentioned rules weren't triggered (only 920170, but I think it's correct in case of Nginx), so I wasn't able to reproduce your issue.

I think the components (what @RedXanadu mentioned), eg. pcre, libmodsecurity... are right.

**Comment by iammattmartin** [comment]
We're running the same version of Nginx, although on Ubu 20.04.

Similar errors too. Are you using the [lazy-loading patch out](https://github.com/SpiderLabs/ModSecurity-nginx/pull/277) of interest to help wth the nginx crashes?

**Comment by EECOLOR** [comment]
We had the same problem. It turned out that we did not supply `--with-pcre2` during configuration.

The correct line to configure ModSecurity for compilation: `./configure --with-pcre2`

Output using that setting:

```
ModSecurity -  for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-46-gbfba51f
   + SecLang tests                                 ....a3d4405
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (MaxMind) v
         /usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/
      * (GeoIP) v1.6.12
         -lGeoIP, -I/usr/include/
   + LibCURL                                       ....found v7.68.0 
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl, -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.10
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found 
      -lfuzzy -L/usr/lib/x86_64-linux-gnu/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_3 -I/usr/include/lua5.3
   + PCRE2                                          ....found 
      -lpcre2-8, -DWITH_PCRE2 -I/usr/include
```

If we leave out the flag the PCRE2 would look like this:

```
  + PCRE2                                          ....disabled
```

**Comment by dune73** [comment]
Time to close this as stale?

**Comment by oerdnj** [comment]
@ludique Make sure that you compile ModSecurity with PCRE2 (`--with-pcre2`) and only PCRE2. I would be interested in hearing the results then.

**Comment by ludique** [comment]
@oerdnj compiled with PCRE2 only, and it worked correctly. Thanks!
