### ISSUE TITLE
Add optional list of block-able archive extensions as a comment

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2757]
## Description

Relates to **JW2SU88A**

Associated PR: #2758 

---

Following on from #2562, we decided to have a list of block-able archive file extensions as an *optional* feature, presented as a comment.

Users can then choose to block archive files if they wish to do so by adding the optional list to their `tx.restricted_extensions` variable.

**Comment by fzipi** [comment]
We can close this one, as associated PR was merged, right?

**Comment by dune73** [comment]
I agree. @RedXanadu ?

**Comment by RedXanadu** [comment]
Yes, all done. Thank you.
