### ISSUE TITLE
Rule 921150 blocking multipart/form-data content type with JSON data

### ISSUE THREAD

**Issue by Absal1706** [coreruleset/coreruleset#2759]
### Description

For our application, we have configured GCP WAF security policies. While sending POST request with JSON data and Content-Type: multipart/form-data, error **body_denied_by_security_policy** is occurring due to owasp-crs-v030001-id921150-protocolattack(rule not added in evaluatePreconfiguredExpr() command)

### Audit Logs / Triggered Rule Numbers

![image](https://user-images.githubusercontent.com/111952943/186377945-cb534bc9-c718-44f2-8e18-0499bf587bcc.png)

owasp-crs-**v030001-id921150**-protocolattack is triggered with 403 error for above POST request with **JSON**

### Your Environment

* CRS version : 3.0
* Paranoia level setting: PL1
* Spring Boot Version: 2.7.1
* Web Server and version (e.g., apache 2.4.41): NA
* Operating System and version: NA

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Hey @Absal1706, sorry for the inconvenience, let's try to sort this out.

Am I right that GCP WAF means Google Cloud Armor?

Are you a paying customer? What did their support say?

CRS is technically not supporting v3.0 anymore, yet 921150 is a relatively simple rule and I presume it did not change since v3.0 (you may want to check that out here on GH yourself, though).

The rule checks for header injections via empty headers. I do not readily see that in your submitted screenshot. So I am a bit troubled to see the problem in your request.

Can you reproduce your request / the blockade via curl? If yes, please share and I can give it a shot here, if it need be on a v3.0.

And finally, I can not really make sense of _(rule not added in evaluatePreconfiguredExpr() command)_. Is that part of an error message? As Google uses their own non-ModSecurity engine, it's very hard for us to test issues as this, namely because this is not a ModSecurity error message and we do not have access to Google's engine.

**Comment by Absal1706** [comment]
Hi @dune73 ,

Thank you for your swift reply.
>Am I right that GCP WAF means Google Cloud Armor?

Yes

>Are you a paying customer? What did their support say?

Yes, paying customer. So far we didn't contact them. Please let me know regarding the details so that I can ask for their support.

>I do not readily see that in your submitted screenshot

Sorry for the inconvenience. Problem is, through FormData from client  side, I am sending a JSON object. While doing so, it throws protocol attack error even for EMPTY JSON object.

>I can not really make sense of (rule not added in evaluatePreconfiguredExpr() command)

Again sorry. This command generally used to disable the signatures. If we disabled the signatures in cloud armor policy, operations working fine.
So I have disable the rule like below
evaluatePreconfiguredExpr('protocolattack-stable', ['owasp-crs-v030001-id921150-protocolattack'])

Ref : https://cloud.google.com/armor/docs/rule-tuning#protocol_attack

![image](https://user-images.githubusercontent.com/111952943/186356045-e95641ca-3184-4857-9467-a634f1f02617.png)



>As Google uses their own non-ModSecurity engine, it's very hard for us to test issues as this, namely because this is not a ModSecurity error message and we do not have access to Google's engine.

In [link](https://cloud.google.com/armor/docs/rule-tuning#crs-3.0_8), it is mentioned that cloud armor are preconfigured based on https://github.com/coreruleset/coreruleset/releases/tag/v3.3.2. So only, I raised this request for more information.

**Comment by dune73** [comment]
> Thank you for your swift reply.

Glad to be of assistance.

> > Are you a paying customer? What did their support say?
> 
> Yes, paying customer. So far we didn't contact them. Please let me know regarding the details so that I can ask for their support.

Generally, we would prefer if you could address the paid support first before you ask for free support. But no worries, let's see if I can help.

> > I do not readily see that in your submitted screenshot
> 
> Sorry for the inconvenience. Problem is, through FormData from client side, I am sending a JSON object. While doing so, it throws protocol attack error even for EMPTY JSON object.

The rule in question is looking at argument names and LF+CR as part of the argument names AFAICS. Now I do not see that in your screenshot, so I reckon something else is amiss here. And given I do not have access to the engine GCF uses to execute our rules - or more exactly the GCF rule derived from the original CRS rule to run on the custom GCF rule engine - there is very little I can do.

> Again sorry. This command generally used to disable the signatures. If we disabled the signatures in cloud armor policy, operations working fine. So I have disable the rule like below evaluatePreconfiguredExpr('protocolattack-stable', ['owasp-crs-v030001-id921150-protocolattack'])

Got you. That is likely to be a viable workaround at a reasonable cost of security when all the rest is intact.
> In [link](https://cloud.google.com/armor/docs/rule-tuning#crs-3.0_8), it is mentioned that cloud armor are preconfigured based on https://github.com/coreruleset/coreruleset/releases/tag/v3.3.2. So only, I raised this request for more information.

Sure thing. GCF is a custom rule engine running a selection of rules originally based on CRS. So we are a good place to ask for help, but in this particular case, I either fail to see the obvious or GCF / the engine is to blame here.

If you come to the same conclusion, I ask you to close this issue and address it to the paid GCF support.

**Comment by RedXanadu** [comment]
This would have auto-closed with either the old or the new auto-close policies, but I think because the auto-close policy has been messed with recently this issue will stay open forever…

Closing.
