### ISSUE TITLE
v3.3.4: Rule 921422 is in paranoia-level 2 but uses tx.anomaly_score_pl1 

### ISSUE THREAD

**Issue by mirkodziadzka-avi** [coreruleset/coreruleset#2799]
In v3.3.4, rule 921422 is in paranoia-level 2 but uses tx.anomaly_score_pl1 

See https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/REQUEST-921-PROTOCOL-ATTACK.conf#L337

**Comment by lifeforms** [comment]
Thanks for the report. It is currently fixed in our development branch. We are currently busy adding a CI step to validate the scoring logic. But you were faster than us.
