### ISSUE TITLE
URL-encoded google maps 

### ISSUE THREAD

**Issue by DrGriff** [coreruleset/coreruleset#2822]
### Description

If we take a Google Map URL, e.g,
> https://www.google.com/maps/place/Emirates+Stadium/@51.5548918,-0.1106267,17z/data=!3m1!4b1!4m5!3m4!1s0x48761b7645295e3b:0x3600713c8382cf90!8m2!3d51.5548885!4d-0.108438

And then URL encode this to get:
> https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FEmirates%2BStadium%2F%4051.5548918%2C-0.1106267%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x48761b7645295e3b%3A0x3600713c8382cf90!8m2!3d51.5548885!4d-0.108438

And then embed this as a parameter in a URL, e.g.
> https://SomeAzureWebsite/linkhandler.ashx?p1={encoded link}&p2=BlahBlah

So we have:
> https://SomeAzureWebsite/linkhandler.ashx?p1=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FEmirates%2BStadium%2F%4051.5548918%2C-0.1106267%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x48761b7645295e3b%3A0x3600713c8382cf90!8m2!3d51.5548885!4d-0.108438&p2=BlahBlah

Then our Azure Application Gateway firewall blocks this.

We're currently using OWASP 3.1 and the rules that stop it are:
- 942430 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)
- 942431 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
- 942432 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)
- 942450 - SQL Hex Encoding Identified

### Your Environment

Azure App Gateway
 - Tier = WAF V2
 - OWASP 3.1

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Hey @DrGriff, I am sorry for the inconvenience - and thank you for reporting.

You state using OWASP CRS 3.1. This is a version we stopped supporting years ago. But furthermore, all your alerts happen at higher paranoia levels:

```
942430 PL2 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)
942431 PL3 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
942432 PL4 - Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)
942450 PL2 - SQL Hex Encoding Identified
```

It is likely the Hex Encoding finding will be gone in the upcoming CRS 4.0 release. The other ones are best fought by reducing the Paranoia Level to a more sane value of PL1 or PL 2. That leaves you with 942430 which is probably not enough to block the request. But it may still make sense to remove the false positive via rule exclusion. If you are not familiar with the concept, please look up the tutorials at https://netnea.com.

**Comment by dune73** [comment]
Closing this, since we are assuming PL2-4 users are able to handle FPs themselves - outside of PL2 FPs that affect a lot of users.
