### ISSUE TITLE
DATA LEAKAGE rules for popular passwords

### ISSUE THREAD

**Issue by iosetek** [coreruleset/coreruleset#2839]
### Motivation

DATA LEAKAGE rules are great from preventing tragic events of bypassed unknown attacks.
As plenty hackers try to obtain list of user's passwords it would be a good idea to block password leakages.

### Proposed solution

From the 2nd paranoia level I would simply block responses which contain some popular password phrases such as "qwerty123", "0123456789" etc. along with their hashes.
This list could be customizable in order to disable certain phrases that are actually occurring within application's flow (for some reason application may send 0123456789 as a subset of available characters).

For the 1st paranoia level there could be an additional requirement that at least 2-3 different popular passwords must be found within the response.

### Additional context

I strongly believe that there were some discussions on this topic but I didn't find anything in the current issues and I don't see such rules. That is why I wanted to share such thought.

**Comment by airween** [comment]
Hi @iosetek,

thanks for your idea.

Personally, I do not like this generic solutions in the core, but I can imagine this feature as a [plugin](https://github.com/coreruleset/plugin-registry).

What do you think about?

Btw: I appended this issue to our next chat [meeting](https://github.com/coreruleset/coreruleset/issues/2823).

**Comment by iosetek** [comment]
Hi @airween 

Thank you for such a quick reply!
I personally didn't have any experience with plugin-registry so I need to take a look into this.
I agree that it may be a bit too generic, although in the perspective of constant password leakages it would bring a value to add at least some popular passwords into standard rules to detect some leakages.

It's not a perfect solution as an experienced attacker, who is aware of this project, will simply try to exclude these popular passwords from the response payload to bypass the firewall but even with that there is a big chance that he won't do that in the first place and the administrator will be notified of such action occuring in the system.

Thank you for adding this topic on the chat!

**Comment by fzipi** [comment]
This is an interesting proposal. I have more doubts than certainties now 🤔 😄 
- How do we know something is a real password and not something like test data? You mention something similar in your proposal, but I think it is key.
- How big the size of the dictionary with passwords to check you think should be? Of course, the larger it is, the best for catching passwords.
- If the user is already using a bad password in a leakage, what prevents attackers to just use the most common dictionaries and brute forcing them? Probably only knowing the username?
- I saw things like this in some providers, but they target the other side of the moon: they leverage a query to haveibeenpwned using the api to see if you are using a password already in the wild
- this could be used in forms (needs to be configurable) so in the user creation form we can catch bad passwords (I reckon this might sound like backend work)

Really an interesting topic.

**Comment by iosetek** [comment]
Thank you for interest!

1. Well, I don't think that the test data is the main concern here - more that some passwords may be used in different context. For example password "1234567890" can be returned as a list of possible numeric characters. "qwerty" may be just a listing of keyboard characters. Unfortunately, plenty of common passwords may be used in different context.
What makes response suspicious is the amount of occurrences of these phrases. My suggestions would be
* within a single response at least 2-3 DIFFERENT popular passwords must appear
* within a single response at least 5-10 popular passwords must be detected
This would trigger the rule if the response contains, for example 6 occurrences of "qwerty123" and 4 occurrences of "1234567890" (if someone steals an entire password table we can assume at least multiple users will have these common passwords).

The "password" word itself may be another point of suspicion as it may be a SQL column name.

2. I don't think we should go with the big database. We need to pick just a few passwords, which make us completely sure that AT LEAST few users use these passwords.

3. We cannot prevent attacker from trying common passwords on every user, he has information about. This is anomaly detection and could be a part of different discussion. For us, personally, this whole idea could work thankfully to these users, who use bad passwords :D That way we can prevent leakage of good passwords and direct mapping between certain user and his password (if an attacker learns what password is associated with certain email, he will definitely try the same password on different sites).

4. haveibeenpwned won't be good for this scenario. It is just a database of random phrases, that were used by certain users. Using such a big database will generate enormous amount of false-positive detections. The goal of this solution is to use the fact that some users use the most dumb passwords, which are not that common in normal traffic.

5. Yeah, I was thinking about making it customizable. I think that we could use 901-INITIALIZATION rules to create variables such as tx.password_database, where we specify our default password list but allow the user to write his own list. Also create variables for how many password occurrences should trigger the violation.

To sum up:

This can work thanks to users who constantly use common passwords. This way, if someone downloads an entire user database, the occurrences of well known phrases used as passwords can alarm us that the response is suspicious.

I would go with a database similar to this ["123456", "qwerty123", "1234567890", "1111111111", "2222222222", ... , "999999999", "abc123"]. All of them should be case insensitive.

To decrease the number of false positives we should set a number of different passwords from the database which needs to occur (it depends on how big the database is).

To reduce it even more we should also add a variable for how many total passwords occurred in a single response (this value needs to be equal or greater than the above one).

This is not that common (at least I hope so...) to keep passwords in a plain text in the database nowadays. That's why we need all passwords from the database above in a hashed form (all popular algorithms - MD5, SHA1, SHA2) etc.

Such occurrences are much more suspicious - 1234567890 may be used in many contexts but the hash of this is not that common. It means that we could have lower values for minimal occurrences to report a violation.

This entire solution won't detect all password leakages. The good practice for storing passwords is to use hash of the password with salt and pepper - which makes it impossible for us to detect with the approach above. For such servers a good approach would be to create a dummy user with a non private password, which could be used as a marker to detect the leakage - but this is also a part of different topic :)

Even though it won't detect properly maintained password databases  it would be great if we could prevent at least one password leakage.

**Comment by dune73** [comment]
@fzipi Why the "awaiting feedback" label?

**Comment by fzipi** [comment]
🤦 That way it will auto close. Unless someone asks or comments on the issue. I guess one year without activity qualifies, right?

**Comment by dune73** [comment]
OK.

Thank you for your proposal @iosetek. It is interesting, but namely your more detailed description makes clear that this is relatively hard to do with CRS (counting the number of hits in a response). So you would probably have to do a complex rule recipe that is unlikely to fit into the mainline rule set.

But as @airween explained above, this would be interesting as a plugin. We could then see adoption and think about mainlining on the long run.
