### ISSUE TITLE
Add CI pipeline linting + sanity tests to plugins

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2842]
### Motivation

After moving subset of rules to plugins, we are not running basic linting and sanity checks on each subrepo.

### Proposed solution

Add pipeline check to test for:
- rule linting
- sanity checks: rules can be used, plugin works when starting up, etc.
- any other test we think will help
- add the tests to the plugin template so new tests will start with reasonable basics

**Comment by theMiddleBlue** [comment]
I'm going to setup a github action for the wp plugin following your requirements and fi everything goes well I'll copy it to the template

**Comment by fzipi** [comment]
@theMiddleBlue You have a working version already, right?

**Comment by theMiddleBlue** [comment]
Yep, but just for Apache. If it's enough we can start using it

**Comment by fzipi** [comment]
I'm wondering if we can include a workflow for every plugin. That should simplify a lot.

**Comment by dune73** [comment]
That sounds very sweet.

**Comment by fzipi** [comment]
@theMiddleBlue Managed to make it work.

Take this workflow for example: https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin/actions/runs/3307700942/jobs/5459522658. In this case, only the tests are failing (I didn't check the why yet).

Actions are based on https://github.com/coreruleset/crs-plugin-test-action, and the good thing is that for testing the plugin, you need:
- your tests, stored in the `tests/regression/<your plugin>/<the files.yaml>`
- including the files and config like this: https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin/pull/6/files.

There is some problem with the nginx workflow and I think it might be something in the base docker container, so I'll take a second look.

**Comment by fzipi** [comment]
This is going to be continued in #3051.
