### ISSUE TITLE
NoSQL (BB RQ1R4RCP)

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2845]
### Description

There is a bypass for NoSQL using `'||1==1|'` as payload.

This comes from BB RQ1R4RCP.

**Comment by theMiddleBlue** [comment]
this could be detected by
`942110 PL2 SQL Injection Attack: Common Injection Testing Detected`

adding `REQUEST_FILENAME` to the list of variables.

I'm going to open a draft PR for this
