### ISSUE TITLE
Forbidden possesive quantifiers in rule 920600

### ISSUE THREAD

**Issue by fzipi360** [coreruleset/coreruleset#2848]
### Describe the bug

Rule 920600 has possessive quantifiers that prevent it to work with other regexp engines like re2.

Here we are using them twice: https://github.com/coreruleset/coreruleset/blob/40b0e528d61d8eeb18b96435516ed23bb76e1d3e/util/regexp-assemble/data/920600.data#L46-L48.

### Expected behaviour

We need compatibility with other engines.

**Comment by airween** [comment]
Agenda chat's result: we will add some extra checks to [rules-check.py](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/util/crs-rules-check) and [secrules-parser.py](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/.github/workflows/lint.yaml#L36) with help of [google-re2](https://pypi.org/project/google-re2/) module.
