### ISSUE TITLE
Why is there an empty space instead of a variable in after MULTIPART_PART_HEADERS:_charset_ ?

### ISSUE THREAD

**Issue by bleedingAyush** [coreruleset/coreruleset#2849]
### Describe the bug

I am configuring ModSecurity using Nginx by following this [https://www.linode.com/docs/guides/securing-nginx-with-modsecurity/#configuring-modsecurity](url) on Linode by hackersploit. I have done everything said but when I run the command `sudo nginx -t` after adding `modsecurity_rules_file` it is giving an error which says 
`nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/modsecurity-crs/rules/REQUEST-922-MULTIPART-ATTACK.conf. Line: 27. Column: 53. Expecting a variable, got:  :  MULTIPART_PART_HEADERS:_charset_ "!@eq 0" \ in /etc/nginx/sites-enabled/nodeApp:3`

### Steps to reproduce

Adding `modsecurity_rules_file` variable in nginx conf file.

### Your Environment

* CRS version (latest):
* Paranoia level setting:
* ModSecurity version (latest):
* Web Server and version (e.g., nginx 1.18.0:
* Operating System and version: Ubuntu 20.04 (LTS)

**Comment by dune73** [comment]
You may want to look up https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/ where this is covered. Also the idea to remove said rule file if you can not upgrade.

Closing this now.
