### ISSUE TITLE
Add scalaj-http/... user-agent to scripting-user-agents.data

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2873]
### Description

User-Agent encountered: scalaj-http/2.4.2

Website: https://index.scala-lang.org/scalaj/scalaj-http

We're currently not detecting this as scripting user agent. So it should be added to `scripting-user-agents.data`.

**Comment by fzipi** [comment]
@dune73 Can we close this one?

**Comment by dune73** [comment]
Given we gave up on the matching of UAs outside the most dangerous ones, yes. Let's close this.
