### ISSUE TITLE
BB YL5ZAHD1 - `file:%2F%2F`

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2882]
### Description

Fix BB finding YL5ZAHD1

path traversal: `file://` is blocked, `file:%2F%2F` is not.

### Your Environment

Todo: Add transformation function `t:urlDecodeUni` to existing rule [931130](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf#L116).

**Comment by emphazer** [comment]
it's also necessary to add REQUEST_URI to match 
```
curl http://localhost/file:%2f%2fetc/passwd
```

**Comment by theMiddleBlue** [comment]
it turns out that we've a problem with Apache phase:2 and REQUEST_(FILENAME|URI|etc...). I don't want to share too much on public issue.

**Comment by emphazer** [comment]
fix is merged
