### ISSUE TITLE
BB C1GOPFSX - compressed response body in modsec3 - add documentation

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2884]
### Description

Finding: request a compressed response body -> bypassess us. in modsec3 the library does not make modifications

Comment: We need disable compression in ModSec3, given SecDisableBackendCompression has not been implemented on ModSec3/NGINX, the only way is to remove this via the Accept header

### Todo

This has to be fixed in the engine, which will probably not happen.

What we can do: add documentation on how to configure this in NGINX.

**Comment by RedXanadu** [comment]
I would suggest adding this content here:

https://coreruleset.org/docs/operation/known_issues/

> There are some known issues with CRS and some of its compatible WAF engines…

Who knows the answer, though? Can an nginx user write this content?

**Comment by airween** [comment]
> Who knows the answer, though? Can someone who is an nginx WAF operator write this content?

I can take a look it soon.

**Comment by dune73** [comment]
@airween, are you still aware of this. If you do not have the time, then maybe @themiddle can give a hand.

**Comment by airween** [comment]
> @airween, are you still aware of this.

yes, sure.

Is there any _final_ deadline? I try to schedule it by then...

**Comment by RedXanadu** [comment]
For anyone who is curious: the ModSecurity v2 `SecDisableBackendCompression` option removes both the `Accept-Encoding` and `TE` headers (https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/mod_security2.c#L1103).

**Comment by dune73** [comment]
Thank you for pointing this out. I was not aware it was touching on TE as well. Makes sense of course.

**Comment by airween** [comment]
See PR [#77](https://github.com/coreruleset/documentation/pull/77) for CRS docs.

**Comment by RedXanadu** [comment]
Thank you @airween for providing the necessary instructions for Nginx. These have now been merged into the live documentation.

Another bug bounty straggler resolved!
