### ISSUE TITLE
Unused transaction variables

### ISSUE THREAD

**Issue by airween** [coreruleset/coreruleset#2891]
### Describe the bug

CRS 3.3/dev includes some unused `TX` variables. The existence of these variables does not have any effect, but but we could investigate them.

The affected variables:
* [executing_anomaly_score](https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/RESPONSE-980-CORRELATION.conf#L65-L68), [another place](https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/RESPONSE-980-CORRELATION.conf#L65-L68)
* [/LEAKAGE\\\\\\/ERRORS/](https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/RESPONSE-980-CORRELATION.conf#L25)
* [/WEB_ATTACK/](https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/RESPONSE-980-CORRELATION.conf#L54)
* [/AVAILABILITY\\\\\\/APP_NOT_AVAIL/](https://github.com/coreruleset/coreruleset/blob/v3.3/dev/rules/RESPONSE-980-CORRELATION.conf#L42)

### Your Environment

* CRS version: v3.3/dev

**Comment by fzipi** [comment]
@airween Can we close this one?

**Comment by fzipi** [comment]
@airween ping
