### ISSUE TITLE
Rule 941170 have wrong syntax regex and long processing

### ISSUE THREAD

**Issue by namnh43** [coreruleset/coreruleset#2909]
### Describe the bug

Issue 1: Please verify the format of regex content of rule 941170.
Issue 2: Processing time is too long

### Steps to reproduce

Issue 1: Copy and paste regex content to regex101 to verify the syntax. It reports the error "pattern error" notify in red mark.
Please verify fix if it is incorrect.
Issue 2: Check processing time with python script below (save as regex_check.py):
```
import pcre as re #using pcre lib (version 8.45) to parse regex as modsecurity engine
import sys
import random
import string

regex_941170 = ""
def check_processing_time():
r2=re.compile(regex_941170)
letters = string.ascii_lowercase
body=''.join(random.choice(letters) for i in range(100000)) #test with 100KB random string
m = r2.search(body)
if m:
print("Match regex\n")
else:
print ("No match")

check_processing_time()
```
From terminal, run: time python regex_check.py
The result time ~ 14s
### Expected behaviour

Issue 1: Correct format
Issue 2: Processing time ~ 2s

### Actual behaviour
Issue 2: Processing time ~ 14s

### Your Environment

* CRS version (e.g., v3.2.0): v4.0.0.-rc1
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): v3
* Operating System and version: Linux

**Comment by airween** [comment]
Hi @namnh43,

thanks for your notes.

> Issue 1: Copy and paste regex content to regex101 to verify the syntax. It reports the error "pattern error" notify in red mark. Please verify fix if it is incorrect.

You can check and verify any regular expression from CRS with regex101, but please be careful. Regex101 needs escapes before the special characters.

CRS team checks and verifies all regular expression before we add it to any rule. If it were wrong, the engines (Apache, Nginx with libmodsecurity3) wouldn't start correctly.

Issue 2: Check processing time with python script below (save as regex_check.py):

sorry, but the indentations are missing from the attached file. My other note it that the mentioned regex in your code is empty.

Let me show you two tools which can help you to check the regular expressions (syntax and runtime).

1. [msc_retest](https://github.com/digitalwave/msc_retest)

I checked your issue now, but I think the mentions regex is find:
```
$ echo "javascript:\\\\\\\\u0020" | src/pcre4msc2 -j -n 100 regexes/941170_1.txt
regexes/941170_1.txt - time elapsed: 0.000011436, match value: SUBJECT MATCHED 1 TIME
regexes/941170_1.txt - time elapsed: 0.000000972, match value: SUBJECT MATCHED 1 TIME
regexes/941170_1.txt - time elapsed: 0.000000425, match value: SUBJECT MATCHED 1 TIME
regexes/941170_1.txt - time elapsed: 0.000000319, match value: SUBJECT MATCHED 1 TIME
...
regexes/941170_1.txt - time elapsed: 0.000000811, match value: SUBJECT MATCHED 1 TIME
regexes/941170_1.txt - time elapsed: 0.000000677, match value: SUBJECT MATCHED 1 TIME
Num of values: 100
         Mean: 000.000000656
       Median: 000.000000544
          Min: 000.000000313
          Max: 000.000011436
        Range: 000.000011123
Std deviation: 000.000001112
```
As you can see, the total time (compilation and pattern matching) is below 11usecs (values are microsecond).

(Note: the subject comes from the rule's [test file](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941170.yaml#L62).)

2. if you want to use Python and `pcre` library, you can take a look one of my my [gist](https://gist.github.com/airween/8c5bfd5be011359edd918e964ca86178#file-pcreffi-py).

Here is how it works:

```
$ time ./pcreffi.py ../../src/msc_retest/regexes/941170_1.txt 
Using pattern: b'(?i)(?:\\W|^)(?:javascript:(?:[\\s\\S]+[=\\x5c\\(\\[\\.<]|[\\s\\S]*?(?:\\bname\\b|\\x5c[ux]\\d))|data:(?:(?:[a-z]\\w+/\\w[\\w+-]+\\w)?[;,]|[\\s\\S]*?;[\\s\\S]*?\\b(?:base64|charset=)|[\\s\\S]*?,[\\s\\S]*?<[\\s\\S]*?\\w[\\s\\S]*?>))|@\\W*?i\\W*?m\\W*?p\\W*?o\\W*?r\\W*?t\\W*?(?:/\\*[\\s\\S]*?)?(?:[\\"\']|\\W*?u\\W*?r\\W*?l[\\s\\S]*?\\()|[^-]*?-\\W*?m\\W*?o\\W*?z\\W*?-\\W*?b\\W*?i\\W*?n\\W*?d\\W*?i\\W*?n\\W*?g[^:]*?:\\W*?u\\W*?r\\W*?l[\\s\\S]*?\\('
Using subject: b'111111111111111111111111111111'...
Time elapsed: 0.001003
Time elapsed: 0.000955
Time elapsed: 0.000999
Time elapsed: 0.000970
Time elapsed: 0.000989
Time elapsed: 0.000966
Time elapsed: 0.001013
Time elapsed: 0.000970
Time elapsed: 0.000984
Time elapsed: 0.001029

real	0m0,162s
user	0m0,107s
sys	0m0,008s

```

Now times are in milliseconds, but please note that cffi is a bit slower.

Summary: I think everything is fine with the regex at rule 941170.

I'm going to close this issue. If you have any question, please let me know.
