### ISSUE TITLE
Rule 942540 has wrong paranoia level related info

### ISSUE THREAD

**Issue by airween** [coreruleset/coreruleset#2961]
### Describe the bug

Rule [942540](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L540) has wrong paranoia level information.

The rule has came with 288eae7cc, and the issue is

* `setvar` sets the [anomaly_score_pl1](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L559) which is no longer used; the expected variable is `inbound_anomaly_score_pl1`

### Additional info:

* CRS version: v4.0/dev

**Comment by lifeforms** [comment]
Good find! PR created, please continue discussion there.
