### ISSUE TITLE
BB Finding ULYKOFYK-4 not detected despite fix

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2977]
### Description

The following curl call is not triggering any rules.

```$ curl "http://localhost/rest/products/2499999||this.product/reviews"```

I am not 100% sure it should trigger, but a pipe in an URI is rather exotic.

**Comment by RedXanadu** [comment]
@dune73 I've been looking at ULYKOFYK.

If we want to match against things like
`localhost/rest/products/2499999||this.product/reviews`
then we probably want to match against the `||` operator.

We already have rule 942120 at PL 2: _SQL Injection Attack: SQL Operator Detected_. That rule matches against `ARGS_NAMES|ARGS|XML:/*`.

Maybe we also need to go SQL operator hunting in the `REQUEST_FILENAME`? Maybe at a higher PL?

We would risk hitting FPs against paths like:

/docs/operators/**isnull**/index.html
/docs/operators/**xor**/index.html
/docs/operators/**rlike**/index.html

**Comment by dune73** [comment]
This seems to do the trick.

I am not overly concerned about false positives as these in filenames. And the rule is already at PL2. So I think we could do such a PR. Thank you for investigating it.

**Comment by RedXanadu** [comment]
Okay, great. PR to make these changes and fully resolve ULYKOFYK: #3057

**Comment by RedXanadu** [comment]
Resolved by #3057. Closing.
