### ISSUE TITLE
Syncing our list of bad user agents with apache-ultimate-bad-bot-blocker list

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2982]
### Description

We are currently covering 6% of the bad bots listed at https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/Apache_2.4/custom.d/globalblacklist.conf.

```
$ cat globalblacklist.conf. | grep bad_bot | cut -d")" -f2 | cut -d"(" -f1 | while read UA; do curl localhost?XXX10 -H "User-Agent: $UA"; done
...
$ cat /apache/logs/access.log | grep XXX10 | grep -v "Require not" | alscorein | sucspercent
                         Entry        Count Percent
---------------------------------------------------
                             5           38   5.97%
                             0          599  94.03%
---------------------------------------------------
                         Total          637 100.00%

```

Not quite sure in which file the would fit or how to split the list.

**Comment by fzipi** [comment]
We have at least these issues created:
- #2638
- #2645 
- #2648
- #2646
Probably you can add this information to any of those, and maybe close this one?

**Comment by dune73** [comment]
Happy to do so. But let's first decide how to handle this. I think this bad bot list is super extensive and not really categorized very well. Its grouping does not match ours. And our rules / data files are somewhat arbitrary on top.

So how do we want to approach this?

**Comment by fzipi** [comment]
Well, I have questions also, but no answers:
- where is the line between a crawler, a bot, or a scanner? once we draw that line, we can move things around.
- there are some comments around this in https://github.com/coreruleset/coreruleset/issues/2638 that might want to explore.

My general answer on how to approach this will be:
- systematic and repeatable.
- and, most importantly, scriptable.

**Comment by fzipi** [comment]
@dune73 Any news here?

**Comment by dune73** [comment]
Getting there.

**Comment by dune73** [comment]
We decided to drop most UA detection for CRSv4. So I'm closing this.
