### ISSUE TITLE
wp-admin/site-health.php in native install triggers

### ISSUE THREAD

**Issue by crankedguy** [coreruleset/coreruleset#3004]
Hi,

in a native WP install, latest version, calling wp-admin/site-health, logged in as admin, triggers
953110, 959100 and 980140

modsec 2.9.6, latest ruleset

**Comment by franbuehler** [comment]
Hello!

Thanks for submitting and sorry for your inconvenience.

The false positive you are reporting should actually be covered by one of our standard rule exclusion packages. In the latest released version, they can be activated by editing `crs-setup.conf` (see here: https://github.com/coreruleset/coreruleset/blob/v3.3/master/crs-setup.conf.example#L350).

If the problem persists, then please speak up.

CRS Dev-on-Duty

**Comment by crankedguy** [comment]
This is already enabled of course
SecAction \
 "id:900130,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.crs_exclusions_wordpress=1

**Comment by franbuehler** [comment]
I just realized that the new Wordpress rule exclusion plugin contains more exclusions than the latest released version. 

So, I think it would be best if you activated the [wordpress-rule-exclusion-plugin](https://github.com/coreruleset/wordpress-rule-exclusions-plugin) like described in our [docs](https://coreruleset.org/docs/concepts/plugins/). There is a rule for 953110 and the path wp-admin/site-health.

Does that help?

**Comment by crankedguy** [comment]
I can confirm that with the plugin rules the manual rules for this issue can be removed, so site-health works with the plugin rules but not with the latest 2.9.6 release rules

The issue mentioned https://github.com/coreruleset/coreruleset/issues/3003 here still stays also with the plugin enabled

**Comment by franbuehler** [comment]
I do not understand what is working and what no. Are your false positives for `953110` gone? They should be gone when I have a look at this rule here: https://github.com/coreruleset/wordpress-rule-exclusions-plugin/blob/master/plugins/wordpress-rule-exclusions-before.conf#L724

**Comment by crankedguy** [comment]
Like I said, if you use the plugin everything is ok, if you use the 3.3.4 ruleset without the plugin it is not
