### ISSUE TITLE
Error with latest nightly build

### ISSUE THREAD

**Issue by fesarlis** [coreruleset/coreruleset#3006]
Modsecurity 2.9.6

AH00526: Syntax error on line 43 of /opt/apache/conf/rules/owasp/REQUEST-922-MULTIPART-ATTACK.conf:
Error creating rule: Unknown variable: &MULTIPART_PART_HEADERS

**Comment by franbuehler** [comment]
According to our [FAQ (at the bottom)](https://coreruleset.org/faq/), it seems that you don't have the latest ModSecurity version installed. Could you please verify if you really use ModSecurity 2.9.6?

**Comment by fzipi** [comment]
Closing.
