### ISSUE TITLE
Monthly Chat Agenda January 2023 (2023-01-02 and 2022-01-16)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3037]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2023-01-02, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2023-01-16. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* Setup tutorial for [caddy&coraza](https://commandwp.com/posts/2022-12-26-caddy-as-a-reverse-proxy/)
* Separate ModSecurity rule set for WordPress usage [WPRS](https://www.linuxcapable.com/how-to-install-wordpress-modsecurity-rule-set-wprs/) (by our very own @theMiddleBlue, somewhat outdated, but never reported here before) 

#### Rules

* The biggest task / roadblocker is the overhaul of 932150 in PR #3061. @theseion will work on this during the week and we will try to review / merge afterwards.
* We are not getting any traction with the [keyword list updates](https://github.com/coreruleset/coreruleset/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Azap%3A+list+update%22). It's not quite clear why, but the BB still being open is certainly a problem. There is also the idea to pay somebody to get this done, but we would rather avoid this. But if anybody is interested in that, then please speak up. 

#### CRS Sandbox

* @theMiddleBlue is currently creating a new challenge for the SQL in JSON bypass technique, in order to ask to try to bypass the new related rule

#### CRS Bug Bounty and Security

* The PR to solve the 2nd list of bypass findings by  Shivam Bathla's is not merged yet (#2926). But close.
* Bug Bounty Findings stats: Coverage at PL1: 78.13% (up from 76.86%), PL2: 94.27% (92.57%), PL3: 94.69% (92.99%), PL4 98.94% (98.51%). Currently, 25 tests fail at PL3. We assume most of these will be fixed by the updated 932150. See above.

#### Plugins

* **New task:** Now that tests can be added to plugins, add tests to **all** plugins (#3051).
  * Moved this lengthy item to project discussions (see below).
* WordPress plugin needs to be update with all new FPs found in the latest WP version.
  * Remove FPs for the top installed WP plugins (SEO, Woocommerce, etc...)
  * Convert/refactor WPRS project into a CRS plugin (https://github.com/Rev3rseSecurity/wordpress-modsecurity-ruleset)

#### Documentation and Public Relations

* There is an effort on trying to get a release notes in #3072
* The INSTALL document needs attention. We currently have _four different install guides_ (INSTALL, 'Quick Start Guide', 'Extended Install', and coreruleset.org/installation/). We should not maintain four guides: we should squash them into a single source of truth for install documentation. @RedXanadu has agreed to look at this some time in the new year; it's a lot of work…
* The next developer portrait is going to be released coming weeks

#### Project Administration and Sponsor relationships

* All payments for CRS have been issues, not sure everything arrived before the end of the year.
* CRS sponsoring newsletter 2022.Q4 is pending
* CRS finances for 2022 not completed; once done 2023 budget has to be drafted

#### Tools

* no news

#### Testing incl. Seaweed and many future plans

* @vandanrohatgi is around again 🎉 . He offered to help with additional Seaweed plans. @fzipi will be working with him in getting additional features and see what he wants to help with.

#### Containers

* There is an outstanding problem with the certificate generation in issue https://github.com/coreruleset/modsecurity-crs-docker/issues/106.

#### CRS Status Page

* A few more 'missing PL 1 test cases' investigated and resolved.

## Project discussions and decisions

* Should we **remove** response body audit logging from **all** rules? (I.e. remove `ctl:auditLogParts=+E` everywhere.) 
  * We need to be consistent with our rules. We need to implement and document a CRS project policy on this:
    * CRS rules _never_ audit log responses?
    * CRS rules _sometimes_ audit log responses? If so, when?
  * Response bodies can contain sensitive data, so maybe CRS shouldn't ever trigger them to be logged and stored.
  * Would we need to provide a config item to (re-)activate response body audit logging for users who must keep it enabled?
  * What about users/integrators who might have a setting of their own?
  * Associated PR: #3034 (@fzipi note: all four people involved in this PR were in sync that this was needed, so I went there and merged it).

* We talked about this in our retreat, but looks like we need a broader discussion, so let's have it: #2948

* Now that tests can be added to plugins, add tests to **all** plugins (#3051).
  * Realistically, **who is going to do this work?**
    This task needs a person responsible for it or it won't get done. It looks like an enormous amount of work. Should we pay someone to do this project? Last year we had budgeted money for 'projects' that we did not use. _Open for discussion._
  * What is needed?
  * Step 1: Copy the [template-plugin github actions workflow](https://github.com/coreruleset/template-plugin/tree/main/.github/workflows) directory to the destination plugin.
  * Step 2: Create the tests subdirectory 👉 `tests/regression/<the plugin name>`
  * Step 3: Create a test file for at least one rule. What are we testing? That the plugin works. **Meaning**? If this is for an exclusion rule, then use any REQUEST_URI that we are removing rules from, and then see that after GET/POST ing to that url with whatever the rule is targeting, `no_log_contains` the rule we are excluding.
  * **Is there any example of this crazy magic?** Yes, please see the one in the [phpmyadmin-rule-exclusions-plugin](https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin/blob/master/tests/regression/phpmyadmin-plugin/9513370.yaml)
  * But wait a minute, do we need to add a test for **all rules** also? 👉 @fzipi suggests we delay doing this. We need to test that the plugin itself is working, we don't need 100% coverage now. We are testing that our decoupling from the core still makes the plugin work.
  * So it is just copying that `.workflows` directory then, and writing ONE TEST FILE with ONE TEST INSIDE then? Pretty much, yes.
  * And what about complex plugins that require Lua extensions? We cannot cover those now. That's future work. As we are using the "regular" CRS docker, for that we will need to extend it to have the new lua files, etc. This is future work.

### PRs that have been merged since the last meeting

* #3034
* #3026
* #3048
* #3043
* #3067
* #3063
* #3066
* #3052
* #3055
* #3058
* #3057
* #3020
* #3053
* #2946
* #3041
* #3050
* #2573

We merged 17 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2933
* #3059
* #3040
* #3056
* #3045
* #3019
* #3029
* #2954
* #2878
* #2948
* #2637
* #2666

### Open issues and PRs

* As of Monday, we have FIXME open issues.
* As of Monday, we have FIXME open pull requests.

## Separate 2nd Meeting (Monday, 2023-01-16)

* BB Status of refactoring of rule 932150 and friends is the final showstopper. @theseion is working on this, with @fzipi and @dune73 waiting for a PR they volunteered to review.
* #3079
  Unless there is someone who is keen to fix a corner case bug with the IP reputation rules in CRS 3.x, I think this issue will realistically become a *'Won't fix'* issue.
* #3087
  @anuraaga from Coraza proposed a feature request which replaces `ARGS`/`ARGS_NAMES` with `ARGS_GET`/`ARGS_GET_NAMES` and `ARGS_POST`/`ARGS_POST_NAMES`. We need to think deeply about the consequences.
* Initialization of collections (see https://github.com/coreruleset/coreruleset/issues/3068)
   * CRS no longer needs collections, but plugins may want to work with collections
   * So either CRS initializes them for the plugins, or plugins need to coordinate themselves
   * If it's CRS, it should be off by default, but an prepared config item
* CRS Community Summit in Dublin Feb 14: Participation, staying (AirBnB?), program
* We stated we want to get serious about Coraza on NGINX in 2023. Is it time to start?

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions Jan 2

**Comment by franbuehler** [comment]
# Decisions Jan 16 (issue chat meeting)

* BB Status of refactoring of rule 932150 and friends is the final showstopper. @theseion is working on this, with @fzipi and @dune73 waiting for a PR they volunteered to review.
* #3079 -> 
  Unless there is someone who is keen to fix a corner case bug with the IP reputation rules in CRS 3.x, I think this issue will realistically become a *'Won't fix'* issue. 
**-> Decision**: Wont Fix' and we flag it in the future if someone writes a plugin for IP reputation.
* #3087
  @anuraaga from Coraza proposed a feature request which replaces `ARGS`/`ARGS_NAMES` with `ARGS_GET`/`ARGS_GET_NAMES` and `ARGS_POST`/`ARGS_POST_NAMES`. We need to think deeply about the consequences.
* Initialization of collections (see https://github.com/coreruleset/coreruleset/issues/3068)
   * CRS no longer needs collections, but plugins may want to work with collections
   ** -> Decisions**: CRS initializes them for the plugins, off by default
* CRS Community Summit in Dublin Feb 14: Participation, staying (AirBnB?), program
* We stated we want to get serious about Coraza on NGINX in 2023. Is it time to start?

we provide a collection initialization plugin, we need to find a way to make sure it runs before the plugins that need it.
[20:42 Uhr](https://owasp.slack.com/archives/CBKGH8A5P/p1673898150129109)
And - besides - we defined that plugins should try to live independently, this not interfering with one another.
[20:42 Uhr](https://owasp.slack.com/archives/CBKGH8A5P/p1673898179911939)
With that being said, I personally lean somewhat in the direction of CRS doing the initialization, if an optional variable is set (off by default).
