### ISSUE TITLE
Error REQUEST-922-MULTIPART-ATTACK

### ISSUE THREAD

**Issue by ahlandapu** [coreruleset/coreruleset#3042]
Hi all, I am a new user of ModSecurity I have an error message related to REQUEST-922-MULTIPART-ATTACK while running apache web server. In the folder /usr/share/modsecurity-crs/rules/ already using ModSecurity CRS version 4(new version). Please help me resolve this error

**Comment by airween** [comment]
Hi @ahlandapu, thanks for reaching us!

Unfortunately this is not enough information to help you. Based on your description I assume you have a "false positive" issue, which means the WAF blocks a request, what - in your opinion - shouldn't be blocking.

Please review again our [issue template](https://github.com/coreruleset/coreruleset/issues/new?assignees=&labels=False+Positive&template=01_false-positive.md&title=), and please provide these information:

* Description - a bit more detailed description about the issue
* Audit Logs / Triggered Rule Numbers - Everything you can provide about a blocked request/response or, at least, a list of triggered CRS rule numbers
* Your Environment
  * CRS version: **4.0/dev**
  * Paranoia level setting:
  * ModSecurity version (e.g., 2.9.3):
  * Web Server and version (e.g., apache 2.4.41):

**Comment by fzipi** [comment]
> Hi all, I am a new user of ModSecurity I have an error message related to REQUEST-922-MULTIPART-ATTACK while running apache web server. In the folder /usr/share/modsecurity-crs/rules/ already using ModSecurity CRS version 4(new version). Please help me resolve this error

Are you using ModSecurity version 2.9.6 or up, right?
