### ISSUE TITLE
REQUEST-912-DOS-PROTECTION.conf dont block ddos 

### ISSUE THREAD

**Issue by selemene112** [coreruleset/coreruleset#3047]
### Describe the bug

I used loic and hping3 to try simulating a ddos ​​attack with modsecurity V3 installed but modsecurity couldn't block **ddos.**

### Steps to reproduce
i am using the REQUEST-912-DOS-PROTECTION.conf rule which i downloaded from https://github.com/coreruleset/coreruleset i am using it for simulating blocking ddos ​​attack on nginx server.

### Expected behaviour
I hope you provide a way to block a ddos ​​attack that I simulated on my own server

### Your Environment

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 3...):
* Web Server and version (e.g., nginx 1.18.0):
* Operating System and version: ubuntu 22.04 LTS

**Comment by theseion** [comment]
This is a known issue with libmodsecurity on nginx. There is a workaround for it documented here: https://github.com/SpiderLabs/ModSecurity/issues/1803#issuecomment-474884652.

We're also working on a plugin for v4 that will apply the mentioned workaround but it still needs some testing.

**Comment by theseion** [comment]
BTW, you mention DDoS: neither ModSecurity nor CRS will ever be able to protect you from DDoS. DoS protection is possible (although other tools are better equipped for this) but DDoS by its nature, can't be reliably detected because we can't pin down IP addresses.

**Comment by selemene112** [comment]
> This is a known issue with libmodsecurity on nginx. There is a workaround for it documented here: [SpiderLabs/ModSecurity#1803 (comment)](https://github.com/SpiderLabs/ModSecurity/issues/1803#issuecomment-474884652).
> 
> We're also working on a plugin for v4 that will apply the mentioned workaround but it still needs some testing.

can modsecurity on the apache version block dos attacks?

thank you sir

**Comment by theseion** [comment]
Sorry, that was unclear. Unfortunately, no. See here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#expirevar.

**Comment by RedXanadu** [comment]
@selemene112 I'll +1 to what @theseion said. I wouldn't recommend even _trying_ to use CRS or ModSecurity for any type of DoS or DDoS protection. _They are simply the wrong tools for the job._ Find a better tool :slightly_smiling_face:

More information and suggestions/alternatives here: https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3#plugin-expectations-suitability-and-scale

P.S. If you can throw a proxy into the mix, HAProxy is good at this sort of thing (read about using its [stick table functionality](https://www.haproxy.com/blog/introduction-to-haproxy-stick-tables/).)
