### ISSUE TITLE
Add tests to plugins

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#3051]
### Motivation

After merging the generic test runner for the plugins, we need to add at least base tests for every plugin that we officially support.

### Procedure

* Step 1: Copy the [template-plugin github actions workflow](https://github.com/coreruleset/template-plugin/tree/main/.github/workflows) directory to the destination plugin.
* Step 2: Create the tests subdirectory 👉 tests/regression/<the plugin name>
* Step 3: Create a test file for at least one rule. What are we testing? That the plugin works. Meaning? If this is for an exclusion rule, then use any REQUEST_URI that we are removing rules from, and then see that after GET/POST ing to that url with whatever the rule is targeting, no_log_contains the rule we are excluding.
Is there any example of this crazy magic? Yes, please see the one in the [phpmyadmin-rule-exclusions-plugin](https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin/blob/master/tests/regression/phpmyadmin-plugin/9513370.yaml)

Wait a minute, do we need to add a test for all rules also? 👉 @fzipi suggests we delay doing this. We need to test that the plugin itself is working, we don't need 100% coverage now. We are testing that our decoupling from the core still makes the plugin work.

**So it is just copying that .workflows directory then, and writing ONE TEST FILE with ONE TEST INSIDE then? Pretty much, yes.**

Let's divide this list in _must have_ for v4 and _nice to have_.

This is the list of plugins from https://github.com/coreruleset/plugin-registry:

## Must have

- [x] #3094
- [x] #3095
- [x] #3096
- [x] #3097
- [x] #3098
- [x] #3099
- [x] #3100
- [x] #3101

## Nice to have

- [ ] add tests for auto-decoding plugin                  https://github.com/coreruleset/auto-decoding-plugin
- [ ] add tests for antivirus plugin                      https://github.com/coreruleset/antivirus-plugin
- [ ] add tests for body-decompress plugin                https://github.com/coreruleset/body-decompress-plugin
- [ ] add tests for fake-bot plugin                       https://github.com/coreruleset/fake-bot-plugin
- [x] add tests for google-oauth2 plugin                  https://github.com/coreruleset/google-oauth2-plugin
- [ ] add tests for dos-protection-modsecurity-v2 plugin  https://github.com/coreruleset/dos-protection-plugin
- [ ] add tests for dos-protection-modsecurity-v3 plugin  https://github.com/coreruleset/dos-protection-plugin
- [ ] add tests for machine-learning-integration-plugin plugin
- [ ] add tests for performance-plugin plugin
- [ ] add tests for incubator plugin                      https://github.com/coreruleset/incubator-plugin

### Alternatives

- For plugins that need extra modules or additional setup, we should check on a case-by-case basis.

**Comment by dune73** [comment]
Thank you very much @fzipi.

**Comment by fzipi** [comment]
Added required tests as planned. Sadly no one else picked this simple task 🤷 

Considering the above, I'm closing this as the nice to have won't probably be done.
