### ISSUE TITLE
JSON-Based SQL Injection

### ISSUE THREAD

**Issue by tmoehle** [coreruleset/coreruleset#3062]
### Motivation

Apparently it is possible to abuse JSON syntax in many database servers (like mysql or mariadb) to bypass protection from SQL injectons.
https://claroty.com/team82/research/js-on-security-off-abusing-json-based-sql-to-bypass-waf

### Proposed solution

Add checks for sql injections via JSON.

**Comment by airween** [comment]
Hi @tmoehle,

thanks for reaching us.

The idea is not new - please see the PR #3055. If you have any perception related to that feature, please let us know.

**Comment by fzipi** [comment]
Duplicate.
