### ISSUE TITLE
Test 920340-2 seems to not test any rules

### ISSUE THREAD

**Issue by anuraaga** [coreruleset/coreruleset#3070]
I was looking at slowdown in running FTW tests with latest CRS and found that 920340-2 is always running to timeout. The test has a content-length, no payload and no content-type. Rule 920340 is checking for a request with a content-length but no content-type.

Content-length without sending a payload on HTTP1 is basically a hung request as the server is waiting for the payload, hence running to timeout. This doesn't seem to be related to rule 920340 or CRS in general - is it a test that can be removed?

On the flip side, there doesn't seem to be a negative test in the file, sending a content-length and a content-type not triggering a log message. Perhaps that's the test that should be there?

**Comment by fzipi** [comment]
I think while the test would not match the rule, it is sane. It depends 100% on the webserver implementation. And of course, it will go up to the timeout configured, because the server is expecting 50 bytes that will never come.

Because CRS should be independent of the Web Server, I think this test should remain. Right now the Apache web server, which is the base for our tests, reacts with an error to this. But what about others? Nginx, Caddy, etc?

Taking a look at the file, I think that tests 1 and 3 are the same. One is somehow using GET, while the other is using the POST we should be checking.

**Comment by anuraaga** [comment]
> And of course, it will go up to the timeout configured, because the server is expecting 50 bytes that will never come.

This is a test of HTTP standard though isn't it? Is it related to CRS or ModSec? If we want tests to verify HTTP behavior I think it could make sense but I would probably actually label them in some way then. Currently the test is labeled for 920340 which seems unrelated. And also before we didn't have any tests that required timeout but now it was added - perhaps it's ok but I think we should be clear while also understanding test stability in slower environments which require higher timeouts.

**Comment by fzipi** [comment]
The whole 920XXX is about that. If you take a look at the comments in the file, it clearly says: 
```
# The purpose of this rules file is to enforce HTTP RFC requirements that state how
# the client is supposed to interact with the server.
# https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html
```
So now I'm not following what you're not following. 🤷

**Comment by anuraaga** [comment]
Sorry got that the file is for helping with http semantics. But still this specific test seems to be problematic

- No other test in that file times out
- 920340 does not test for payload presence or absence. The rule is not the cause of timeouts
- Timeouts slow down tests which affects productivity to some degree

If a slow test is providing value then it's ok but it's not clear what this test is verifying. If it really was to check a request fails when there is no payload with a content length wouldn't it be a separate test independent of 920340?

**Comment by dune73** [comment]
I think I'm leaning on the side of @anuraaga here.

The rule is meant to check if a rule without a content-type carries a content-length header and if it is yes, if it is 0. While test 1 and 3 test exactly this, the test 2 does not test this, but simply trigger a timeout (error). I do not see why we need this inforation nor test.

I am not 100% sure, but as of this writing, I think the test can be kicked.

**Comment by theseion** [comment]
I agree with @anuraaga, the test has nothing to do with 920340. I also think that we shouldn't test web server behavior but rule behavior, so instead, we should have a rule that blocks requests that have a Content-Length header but no body. In either case, I don't think this test is very helpful as it is now.

**Comment by fzipi** [comment]
@anuraaga @dune73 @theseion Can someone provide a PR?

**Comment by dune73** [comment]
Sure. See #3089.

**Comment by fzipi** [comment]
Closing after merge.
