### ISSUE TITLE
Project Honeypot queries do not lead to blocking

### ISSUE THREAD

**Issue by ne20002** [coreruleset/coreruleset#3082]
### Description
I have a modsecurity-crs-docker installed and enabled rules for querying Project Honeypot but there is no blocking.
Looking into the dns logs (pi-hole) I see that the httpbl is queried with e.g.

```
<mycode>.199.116.42.192.dnsbl.httpbl.org  giving 127.8.30.5
<mycode>.207.99.22.46.dnsbl.httpbl.org    giving 127.19.4.1
```

In crs-setup.conf it is configured as in the documentation (plus search ips):

```
SecHttpBlKey <mycode>
SecAction "id:900500,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.block_search_ip=1,\
  setvar:tx.block_suspicious_ip=1,\
  setvar:tx.block_harvester_ip=1,\
  setvar:tx.block_spammer_ip=1"
```
As I get the queries in the dns log and I see it is getting results, I assume that the ModSecurity rules are processed.

So why is there no blocking? What may be the cause?

* CRS version (e.g., v3.3.4): 3.3.4
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.4): current modsecurity-crs-docker 
* Web Server and version (e.g., apache 2.4.41): current modsecurity-crs-docker
* Operating System and version: Debian Bullseye

### Confirmation

[ x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theseion** [comment]
Can you turn on debug logging for ModSecurity? Then you'll see what happens with the rule by looking at the logs.

**Comment by theseion** [comment]
Sorry, I somehow missed your comment.

There appears to be a mismatch between the response and the expected message. Actual response:
```
[167412788247.060653] [/] [4] RBL lookup of 62.204.66.10 succeeded. %s: 30 days since last activity, threat score 34. Case: Suspicious harvester comment spammer IP
```
Expected response, used to determine the type of threat:
```
[167412788247.060653] [/] [4] (Rule: 0) Executing operator "Rx" with param "RBL lookup of .*?.dnsbl.httpbl.org succeeded at TX:checkip. (.*?): .*" against TX:httpbl_msg.
```

As you can see, the regular expression expects `.*?.dnsbl.httpbl.org` in place of the IP address in the response. I don't know how the strings are processed in the engine exactly, but from the log you an see that `TX:httpbl_msg` has the value `62.204.66.10`, when it should hold something like `Suspicious harvester comment spammer IP`, which is what is checked by the following rules.

@dune73 @fzipi any ideas to what's going on here?

**Comment by dune73** [comment]
I guess httpbl changed the format of the response and nobody noticed before @ne20002, since very few people use these rules. Which in turn is why we removed them for CRS4.

They are likely coming back as a plugin, I hope with tests and in a more robust form.

Personally, I am not overly keen to provide a PR here.

**Comment by theseion** [comment]
Thank you @dune73. @ne20002 You will need figure out, what the exact response is and then adjust the rules to match. We can guide you, of course.

**Comment by ne20002** [comment]
Hi @theseion 
I moved away from Project Honeyot and set up blockin using @rbl by using xbl.spamhaus.org (this is less email spammers which I usually won't need to block). This is working well for me.
