### ISSUE TITLE
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^0?$' against variable `REQUEST_HEADERS:Content-Length' (Value: `206' )

### ISSUE THREAD

**Issue by bsbudhwar** [coreruleset/coreruleset#3125]
```
---BpvUOiJ1---A--
[08/Feb/2023:22:25:57 +0530] 167587535755.526256 xx.xx.xx.xx 43638 xx.xx.xx.xx 443
---BpvUOiJ1---B--
GET /Microsoft-Server-ActiveSync?Cmd=Ping&User=user%40domain.com&DeviceId=androidc0000675677&DeviceType=Android HTTP/1.1
Authorization: Basic Zm5ibWFya2V0aW5nQGZhbWlseXdvcmxkLmNvLmluOlJlc2V0QDEyMw==
Host: activesync.domain.com
User-Agent: Android-Mail/2023.01.08.501398065.Release
Accept-Encoding: gzip
MS-ASProtocolVersion: 14.0
Content-Type: application/vnd.ms-sync.wbxml
Content-Length: 206
Connection: Keep-Alive

---BpvUOiJ1---D--

---BpvUOiJ1---E--
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\x0a<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>\x0a    <title>404 &mdash; Not Found</title>\x0a    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\x0a    <meta name="description" content="Sorry, page not found"/>\x0a    <style type="text/css">\x0a        body {font-size:14px; color:#777777; font-family:arial; text-align:center;}\x0a        h1 {font-size:180px; color:#99A7AF; margin: 70px 0 0 0;}\x0a        h2 {color: #DE6C5D; font-family: arial; font-size: 20px; font-weight: bold; letter-spacing: -1px; margin: -3px 0 39px;}\x0a        p {width:320px; text-align:center; margin-left:auto;margin-right:auto; margin-top: 30px }\x0a        div {width:320px; text-align:center; margin-left:auto;margin-right:auto;}\x0a        a:link {color: #34536A;}\x0a        a:visited {color: #34536A;}\x0a        a:active {color: #34536A;}\x0a        a:hover {color: #34536A;}\x0a    </style>\x0a</head>\x0a\x0a<body>\x0a    <p><a href="http://activesync.domain.com/">activesync.domain.com</a></p>\x0a    <h1>404</h1>\x0a    <h2>Page Not Found</h2>\x0a    <div>\x0a        It seems that the page you were trying to reach does not exist anymore, or maybe it has just moved.\x0a        You can start again from the <a href="http://activesync.domain.com/">home</a> or go back to <a href="javascript:%20history.go(-1)">previous page</a>.\x0a    </div>\x0a</body>\x0a</html>\x0a

---BpvUOiJ1---F--
HTTP/1.1 403
Server: jupiter
server: jupiter
Date: Wed, 08 Feb 2023 16:55:57 GMT
Content-Length: 1450
Content-Type: text/html
Last-Modified: Tue, 19 Feb 2019 11:35:21 GMT
Keep-Alive: timeout=60
Connection: keep-alive
X-XSS-Protection: 0; mode=block
ETag: "5c6be9f9-5aa"

---BpvUOiJ1---H--
```
``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^0?$' against variable `REQUEST_HEADERS:Content-Length' (Value: `206' ) [file "/etc/nginx/modsec/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "162"] [id "920170"] [rev ""] [msg "GET or HEAD Request with Body Content"] [data "GET"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "xx.xx.xx.xx"] [uri "/Microsoft-Server-ActiveSync"] [unique_id "167587535755.526256"] [ref "o0,3v0,3v377,3"]
``

``
ModSecurity: Warning. Matched "Operator `Within' with parameter `|application/x-www-form-urlencoded| |multipart/form-data| |multipart/related| |text/xml| |application/xml| |application/soap+xml| |application/json| |application/cloudevents+json| |application/cloudev (16 characters omitted)' against variable `TX:content_type' (Value: `|application/vnd.ms-sync.wbxml|' ) [file "/etc/nginx/modsec/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "938"] [id "920420"] [rev ""] [msg "Request content type is not allowed by policy"] [data "application/vnd.ms-sync.wbxml"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153"] [tag "PCI/12.1"] [hostname "xx.xx.xx.xx"] [uri "/Microsoft-Server-ActiveSync"] [unique_id "167587535755.526256"] [ref "o0,29v331,29t:lowercase"]
``

``
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `10' ) [file "/etc/nginx/modsec/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "xx.xx.xx.xx"] [uri "/Microsoft-Server-ActiveSync"] [unique_id "167587535755.526256"] [ref ""]
``
```
---BpvUOiJ1---I--

---BpvUOiJ1---J--

---BpvUOiJ1---Z--
```

We are using Z-Push Opensource ActiveSync solution without mod Secuity its working fine but after enabling the mod security it's not working.

Please help what changes to be done to rules file.

**Comment by RedXanadu** [comment]
Hi @bsbudhwar,

I'm going to close out this issue now. Feel free to reply and re-open if you have any further questions.
