### ISSUE TITLE
Learn more about nature of alerts pointing to "Accept-Charset" header

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3140]
We need to talk about the Accept-Charset header. It is deprecated and clients should not use it anymore. 

In the CRS v4 dev tree we no longer accept requests with that header.

Yet I see this header a lot. I see it on like 0.2% of all requests, mostly User-Agents pointing to browsers. IP distribution relatively even (some scheduled agents and many more clients with 1-2 requests over the course of 30 days); 1443 requests, 379 IPs in my sample.

One thing that puzzles me though is that none of the IP addresses are in the MaxMind GeoIP country database. 3% of the requests I am looking at can not be assigned to a country code and somehow all 379 IPs in question fall into this category. This is somewhat unlikely.

Based on my very limited data, this allows for two interpretations: 

1. The header is much more frequent than it should be and we produce a ton of FPs 
1. The header is an exceptionally strong indicator of suspicious activity and we should be very lucky to have it.Can anybody shed more light onto this.

**Comment by KramNamez** [comment]
In my experience, that header comes up, but it is never legitimate. It comes from bots and from "browsers" in countries that we don't have clients in (probably). I say "browsers", because it's UAs like Chrome 58 or Chromium 61, both from 2017, and similarly old browsers - when they're even mainstream browsers. Occasionally a strange mobile browser pops up, but given that it is very rare, and essentially never the same one twice, they don't seem like legitimate uses either.

**Comment by dune73** [comment]
GitHub query for the header: https://github.com/search?q=%22accept-charset%22&type=Code

**Comment by dune73** [comment]
More References: 
* https://hsivonen.fi/accept-charset/

**Comment by azurit** [comment]
After short research and traffic analysis i was able to detect some FPs related to blocking of this header. It wasn't much though.

Legitimate requests using this header were coming from some smart TVs and also Thunderbird e-mail client. Here are UAs:
```
Mozilla/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1

Mozilla/5.0 (SAMSUNG; SAMSUNG-GT-S8600/S8600XXKJC; U; Bada/2.0; en-us) AppleWebKit/534.20 (KHTML, like Gecko) Dolfin/3.0 Mobile WVGA SMM-MMS/1.2.0 OPN-B

Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.33 Safari/537.31 SmartTV/5.0

Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaC5-00/062.001; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.6.2 3gpp-gba

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Thunderbird/102.8.0
```

**Comment by dune73** [comment]
Can you share just how many of these FPs you got or would get in let's say 1 million requests?

**Comment by azurit** [comment]
Would be about 31000 FPs per milion requests.

**Comment by dune73** [comment]
Wow. That's a lot. Thank you very much.

**Comment by dune73** [comment]
Closing this now.

We'll deal with the situation in issue #3148.
