### ISSUE TITLE
GSoC 2023 Ideas

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#3160]
## GSoC 2023 Ideas

We need to propose our ideas for the upcoming GSoC.

They need to be added here: https://owasp.org/www-community/initiatives/gsoc/gsoc2023ideas

**Comment by RedXanadu** [comment]
There's a sheet/diagram of ideas from Varese, somewhere…

**Comment by dune73** [comment]
I have it on photo but need to find it and transcribe.

**Comment by RedXanadu** [comment]
Here are the ideas from Varese:

- Joint project with [OWASP Honeypot](https://owasp.org/www-project-honeypot/)
- Design a usable report with CRS CAPEC tags, and link it to the OWASP Top 10
- Performance measurement of targets in rules
- Regex assemble "debugger"
  - Block/line step
  - Terminal colours / syntax highlighting
- Regex-only tests with [crs-toolchain](https://coreruleset.org/docs/development/crs_toolchain/), YAML

**Comment by RedXanadu** [comment]
We should consider re-submitting the ModSecurity transformation operators investigation idea from last year:

https://github.com/OWASP/www-community/blob/master/pages/initiatives/gsoc/gsoc2022ideas.md#crs-transformations-review

**Comment by dune73** [comment]
It's worth a try.

**Comment by dune73** [comment]
Schedule: https://developers.google.com/open-source/gsoc/timeline

It seems we are really behind schedule.

**Comment by fzipi** [comment]
Created https://github.com/OWASP/www-community/pull/752.

Can someone expand on what is needed in the previous points listed https://github.com/coreruleset/coreruleset/issues/3160#issuecomment-1479868893 ?

**Comment by dune73** [comment]
![tmp](https://user-images.githubusercontent.com/618722/230071734-4b1a5377-08db-473e-89b0-401db1e13ce5.jpeg)

**Comment by dune73** [comment]
We're behind schedule, but maybe it's worth adding:
* Design usable report with CRS CAPEC tags (for use with OWASP Top 10 for example, or for management)
* Regex assemble "debugger": line stepping, term colors, etc.
* Regex-only tests (with crs-toolchain YAML / *.ra files)

The joint honeypot project is far too late. We would need to coordinate this in advance.

**Comment by fzipi** [comment]
```The GSoC 2023 contributor proposal submission period has now closed. We had 5,704 contributors submit 7,723 proposals for GSoC 2023.```

I would say let's add an extended description in the same format as the others to the file, so when copied to 2024 we get that from the start?

**Comment by dune73** [comment]
Sounds leggit. Sorry I let this slip. I think it's my mistake.

**Comment by fzipi** [comment]
Closing this one.
