### ISSUE TITLE
It does not allow almost any requests. Even the fonts

### ISSUE THREAD

**Issue by blackmold9** [coreruleset/coreruleset#3181]
* CRS version - v3.3.4:
* Paranoia level - 1:
* ModSecurity version 3:
* Web Server - nginx/1.22.0:
* Operating System - Ubuntu 22.10:

Why it does not pass a simple query like 
curl --location '192.168.0.100/api/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{"any":"param","i":"post"}'

``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^\d+$' against variable `REQUEST_HEADERS:Content-Length' (Value: `26' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "128"] [id "920160"] [rev ""] [msg "Content-Length HTTP header is not numeric"] [data "26"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "192.168.0.100"] [uri "/api/"] [unique_id "168018524010.980622"] [ref "v256,2"]
``

``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\w/.+-]+(?:\s?;\s?(?:action|boundary|charset|type|start(?:-info)?)\s?=\s?['\"\w.()+,/:=?<>@-]+)*$' against variable `REQUEST_HEADERS:Content-Type' (Value: `application/json' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "916"] [id "920470"] [rev ""] [msg "Illegal Content-Type header"] [data "application/json"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153"] [tag "PCI/12.1"] [hostname "192.168.0.100"] [uri "/api/"] [unique_id "168018524010.980622"] [ref "v34,16t:lowercase"]
``

``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:Accept' (Value: `application/json' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "920600"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "application/json"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "192.168.0.100"] [uri "/api/"] [unique_id "168018524010.980622"] [ref "v59,16t:lowercase"]
``

``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?i:(?:[a-z]{3,10}\s+(?:\w{3,7}?://[\w\-\./]*(?::\d+)?)?/[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?|connect (?:\d{1,3}\.){3}\d{1,3}\.?(?::\d+)?|options \*)\s+[\w\./]+|get /[^?#]*(?:\?[^#\s]*)?(?:#[\S]*)?)$' against variable `REQUEST_LINE' (Value: `POST /api/ HTTP/1.1' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "48"] [id "920100"] [rev ""] [msg "Invalid HTTP Request Line"] [data "POST /api/ HTTP/1.1"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "192.168.0.100"] [uri "/api/"] [unique_id "168018524010.980622"] [ref "v0,19"]
``

``
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `15' against variable `TX:ANOMALY_SCORE' (Value: `18' ) [file "/etc/nginx/modsec/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 18)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.0.100"] [uri "/api/"] [unique_id "168018524010.980622"] [ref ""]
``

**Comment by azurit** [comment]
Hi @blackmold9, probably a known problem, see this: https://github.com/coreruleset/coreruleset/issues/3117

**Comment by RedXanadu** [comment]
+1 to @azurit's comment.

Where are you building nginx from, @blackmold9?

**Comment by blackmold9** [comment]
hi, @azurit's, from https://nginx.org/download

**Comment by blackmold9** [comment]
After building nginx from https://modsecurity.digitalwave.hu/, everything functions correctly
