### ISSUE TITLE
Fix C9K-230327

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3191]
The security finding is documented in private repository as https://github.com/coreruleset/security-tracker-private/issues/7

The decision to fix this was taken in the last CRS chat: https://github.com/coreruleset/coreruleset/issues/3159#issuecomment-1494812544

It would be a good first rule if it was not for a confidential security finding. :)

**Comment by EkiXu** [comment]
Hi there,I'm the reporter of issue, could I join this security-tracker-private? Or how can I dissucss with you.

**Comment by dune73** [comment]
Hello @EkiXu. Thanks for writing in. Nothing important in the tracker. But you can reach us via security // coreruleset.org

**Comment by dune73** [comment]
@theMiddleBlue volunteered to provide a PR ASAP.

**Comment by fzipi** [comment]
@theMiddleBlue we are still pending the fix for this one.
