### ISSUE TITLE
False positive response to Cyrillic characters in a string

### ISSUE THREAD

**Issue by flexstat** [coreruleset/coreruleset#3193]
### Description

Hello again. Again faced with the problem of Cyrillic characters and triggering rules. this time the rule worked on the combination of characters: "T!T"

### Logs

``
mybunker_1  | 2023/04/07 07:57:06 [warn] 637#637: *55 ModSecurity: Warning. detected SQLi using libinjection. [file "/opt/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "45"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: sos found within ARGS:message: \x1a>>@48=0BK =0 D>B>\x0d\x0a\x0d\x0a\x11 \x1e, \x1e\x11/\x17\x10"\x15\x1b,\x1d\x1e \x1a \x1f \x1e'"\x15\x1d\x18.!\x0d\x0a\x0d\x0a-B> ?@8:>?, 53> 3;C18=0 2-4 A<, =5 =C6=> CAB@0820BL  0@E5>;>38G5A:85 @0A:>?:8. \x1f>A;5 CA?5H=KE ?>8A:> (298 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [hostname "192.168.240.2"] [uri "/mail.php"] [unique_id "168085422563.651517"] [ref "v1286,812t:urlDecodeUni"], client: 192.168.240.3, server: www.example.com, request: "POST /mail.php HTTP/1.1", host: "site.ru", referrer: "http://site.ru/"
``

### Your Environment

OWASP_CRS/3.3.2
(tag:'paranoia-level/1',)
ModSecurity version (e.g., 2.9.6):
Operating System and version: ubuntu 22.04

**Comment by azurit** [comment]
Hi @flexstat. Have you tried hints presented to you by @RedXanadu here https://github.com/coreruleset/coreruleset/issues/3178 ?

**Comment by flexstat** [comment]
> Hi @flexstat. Have you tried hints presented to you by @RedXanadu here #3178 ?


hi @azurit . here another rule 942100 is triggered, I don't quite understand what exactly and whether it will be safe to add this rule to the exception.

**Comment by azurit** [comment]
Yes, add it. The whole rule may look like this:
```
SecRule REQUEST_FILENAME "@streq /mail.php" \
    "id:100,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetById=941310;ARGS:message,\
    ctl:ruleRemoveTargetById=942100;ARGS:message"

```

**Comment by azurit** [comment]
To make it even tightier, you can tie it to a specific URL:
```
SecRule SERVER_NAME "@streq www.example.com" \
    "id:100,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    chain"
    SecRule REQUEST_FILENAME "@streq /mail.php" \
        "t:none,\
        ctl:ruleRemoveTargetById=941310;ARGS:message,\
        ctl:ruleRemoveTargetById=942100;ARGS:message"
```

**Comment by flexstat** [comment]
I have a lot of different form handlers on my site. is it possible to make some more universal rule?

**Comment by azurit** [comment]
It's up to you how big holes in the firewall you are willing to create. I recommend to always tie it to `REQUEST_FILENAME`.

**Comment by flexstat** [comment]
and is it possible to change the current rule so that it does not work on the arguments specified in the logs. it seems to me that it is not normal that this phrase works on this rule

**Comment by azurit** [comment]
Unfortunately it's not possible. The problem is exactly how @RedXanadu described it [here](https://github.com/coreruleset/coreruleset/issues/3178#issuecomment-1485639424).

**Comment by flexstat** [comment]
how critical will it be if I completely disable this rule ?

**Comment by azurit** [comment]
I don't understand why you want to do that - simply create an exclusion rule as i recommended above, it's the safest way how to resolve false positives.

**Comment by flexstat** [comment]
> I don't understand why you want to do that - simply create an exclusion rule as i recommended above, it's the safest way how to resolve false positives.


I have a lot of different handlers used mail.php, form.php, callme.php and others, more than 50 pieces in the project of different handlers, it is very inconvenient to add a deviation for each

**Comment by azurit** [comment]
Are really all those scripts accepting user input? Anyway, 50 isn't so much, i would simply add it as a regex:
```
SecRule REQUEST_FILENAME "@rx ^/(?:mail|form|callme)\.php$" \
...
```

**Comment by flexstat** [comment]
there may be more handlers in the project and they can be added. Tell me, what exactly does rule 942100 affect, what will happen if I disable it, what are the consequences?

**Comment by azurit** [comment]
You can modify that rule everytime you add more handlers, this is how security works - it's a process, not a state.

Rule `942100` is searching for SQL injection patterns using `libinjection` library.

**Comment by flexstat** [comment]
can you then explain why this rule specifically triggers Cancel COOKIE REQUEST|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/ * "@detectSQLi" \ it doesn't look like what we see in the logs at all

**Comment by azurit** [comment]
It is using [@detectSQLi](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#detectsqli) action.

**Comment by flexstat** [comment]
that is , you do not recommend disabling this rule completely ?

**Comment by azurit** [comment]
I cannot recommend it.

**Comment by flexstat** [comment]
but the same rule checks the forms, and if I disable them for all my forms, then it turns out there will be no sense from this rule at all

**Comment by azurit** [comment]
Are really all of your forms used only for taking text input from users? That is a very rare use-case. Also, that rule is searching for patterns also in other parts of the request.

Anyway, i'm closing this issue. If you need more info, feel free to join our Slack channel a chat there. Thanks.

**Comment by lifeforms** [comment]
I want to add that rule 942100 is really powerful and it's definitely one of those that I would not recommend to disable completely, I'd recommmend to just do it for your text fields. It is a very useful rule that catches a LOT of attacks. Unfortunately, the logics of what happens in this rule is completely controlled by a different project (libinjection) so we cannot modify anything about it (although we can submit issues, but there is not so much development activity on it) and there are known issues with different languages 😞

**Comment by flexstat** [comment]
> I want to add that rule 942100 is really powerful and it's definitely one of those that I would not recommend to disable completely, I'd recommmend to just do it for your text fields. It is a very useful rule that catches a LOT of attacks. Unfortunately, the logics of what happens in this rule is completely controlled by a different project written in C (libinjection) so we cannot modify anything about it (although we can submit issues, but there is not so much development activity on it) and there are known issues with different languages disappointed

thx !
