### ISSUE TITLE
False positive response to Cyrillic characters in a string (setting up exceptions)

### ISSUE THREAD

**Issue by flexstat** [coreruleset/coreruleset#3194]
### Description
Hello again. I'm from this ticket  https://github.com/coreruleset/coreruleset/issues/3193 

it turned out that my forms use parameters, for example my forms in the project have these urls:

`/path/name_form?param1=111`

_param1_ this is a variable part and it can change

how can I add similar urls `/forms/name_form?param1=111` to an exception: 

```
SecRule REQUEST_URI "@beginsWith /url/form.php " \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveTargetById=942100;ARGS:message"
```

### Logs

``
mybunker_1  | 2023/04/07 07:57:06 [warn] 637#637: *55 ModSecurity: Warning. detected SQLi using libinjection. [file "/opt/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "45"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: sos found within ARGS:message: \x1a>>@48=0BK =0 D>B>\x0d\x0a\x0d\x0a\x11 \x1e, \x1e\x11/\x17\x10"\x15\x1b,\x1d\x1e \x1a \x1f \x1e'"\x15\x1d\x18.!\x0d\x0a\x0d\x0a-B> ?@8:>?, 53> 3;C18=0 2-4 A<, =5 =C6=> CAB@0820BL  0@E5>;>38G5A:85 @0A:>?:8. \x1f>A;5 CA?5H=KE ?>8A:> (298 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [hostname "192.168.240.2"] [uri "/forms/name_form?param1=111"] [unique_id "168085422563.651517"] [ref "v1286,812t:urlDecodeUni"], client: 192.168.240.3, server: www.example.com, request: "POST /forms/name_form?param1=111" HTTP/1.1", host: "site.ru", referrer: "http://site.ru/"
``

### Your Environment

OWASP_CRS/3.3.2
(tag:'paranoia-level/1',)
ModSecurity version (e.g., 2.9.6):
Operating System and version: ubuntu 22.04

**Comment by airween** [comment]
Hi @flexstat,

thanks for your report.

As there is in previous [comment](https://github.com/coreruleset/coreruleset/issues/3193#issuecomment-1500420305), [@detectSQLi](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L46) can trigger many FP's. I'm afraid you can't do anything than make an exclusion.

**Comment by flexstat** [comment]
> As there is in previous [comment](https://github.com/coreruleset/coreruleset/issues/3193#issuecomment-1500420305), [@detectSQLi](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L46) can trigger many FP's. I'm afraid you can't do anything than make an exclusion.

Hi @airween. Thank you, I understand that exceptions need to be made.

tell me how to correctly add exceptions for my form page ?

**Comment by flexstat** [comment]
Hi @RedXanadu, 
Can you help me with my question, how can I add an exception for my url

**Comment by lifeforms** [comment]
By the way, for long text fields, where people enter arbitrary input, it is not uncommon to do something like:

```
SecRule REQUEST_URI "@beginsWith /forms/name_form" \
    "id:10001,\
    phase:1,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:message"
```

In this way, you _completely_ deactivate all CRS rules for the `message` parameter. Of course, this should only be done if you are reasonably sure that the application handles the parameter in a secure way. But for long text fields, for instance webmail, I do it sometimes, otherwise you keep returning into a loop of one rule, another rule, then another rule triggering.

**Comment by flexstat** [comment]
don't close the ticket yet, I need time to figure it out

**Comment by flexstat** [comment]
Such a question can I disable all the coreruleset rules for the url ? How can this be done ?

> Hi @flexstat,
> 
> > tell me how to correctly add exceptions for my form page ?
> 
> Sure.
> 
> I can imagine something like this:
> 
> ```
> SecRule REQUEST_URI "@beginsWith /forms/name_form" \
>     "id:10001,\
>     phase:1,\
>     t:none,\
>     nolog,\
>     ctl:ruleRemoveTargetById=942100;ARGS:message"
> ```
> 
> How this rule works:
> 
>     * rule looks the request URI; if it begins with `/forms/name_form`, then activated
> 
>     * rule executed in 1st phase
> 
>     * excludes the `message` argument in case of rule 942100
> 
> 
> You should place this rule **BEFORE** your rule set, eg. into the file `REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`.

Such a question can I disable all the coreruleset rules for the url ? How can this be done ?

**Comment by azurit** [comment]
See [here](https://github.com/coreruleset/coreruleset/issues/3194#issuecomment-1502052019).

**Comment by flexstat** [comment]
> See [here](https://github.com/coreruleset/coreruleset/issues/3194#issuecomment-1502052019).

thank you very much, I understand. Can I ask you one more question? How do I disable the rule for all form fields at once?

**Comment by lifeforms** [comment]
```
SecRule REQUEST_URI "@beginsWith /forms/name_form" \
    "id:10001,\
    phase:1,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetById=1234567;ARGS"
```

Will do that.

**Comment by flexstat** [comment]
> ```
> SecRule REQUEST_URI "@streq /forms/name_form" \
>     "id:10001,\
>     phase:1,\
>     t:none,\
>     nolog,\
>     ctl:ruleRemoveTargetById=1234567;ARGS"
> ```
> 
> Will stop processing the rule on everything in ARGS for this particular URL.

Very strange, but it does not work in Laravel. Created a test form, an exception is triggered, but Laravel, a rule is also triggered.

**Comment by azurit** [comment]
Can you show your exact rule and audit message?

**Comment by dankegel** [comment]
I wanted to create a curl command to reproduce against the CRS sandbox, but it's hard to reconstruct from that error message.  Is there a tool that makes that easier?

**Comment by flexstat** [comment]
> Can you show your exact rule and audit message?
`
2023/05/03 06:07:43 [warn] 216341#216341: *406961 ModSecurity: Warning. detected SQLi using libinjection. [file "/opt/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "45"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: vos found within ARGS:message: \x24! "K !@> <19BA:85 ?@64=9:2! \x370;>2 6IE :<?;M "] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [hostname "10.10.10.3"] [uri "/profile/sends/342345/message"] [unique_id "168309406369.188135"] [ref "v1752,90t:urlDecodeUni"], client: 10.11.12.28, server: www.example.com, request: "POST /profile/sends/342345/message HTTP/2.0", host: "site.com", referrer: "https://site.com/"`

**Comment by theseion** [comment]
@flexstat, you did not respond to our request for more information. Please reopen if this is still relevant to you.
