### ISSUE TITLE
Honey Pot HTTP Blacklist missing in ver.4.0.0-rc1 config

### ISSUE THREAD

**Issue by JohnFarl** [coreruleset/coreruleset#3195]
Before the latest release the crs-setup-config file included a section Honey Pot HTTP Blacklist, now that section has been removed.

Not sure if this is an intended omission or a mistake.

**Comment by airween** [comment]
Hi @JohnFarl,

thanks for reporting.

I'm not sure if this was a bug, more of a deliberate action. As far as I know, TrustWave has stopped supporting these, so they are no longer needed.

I found only this reference:

https://owasp.slack.com/archives/CBKGH8A5P/p1624448131474000

@dune73 - please confirm.

**Comment by dune73** [comment]
Confirm.

It's non-mainstream functionality (-> \@rbl operator) that we stripped from CRS for 4.0. Ideal plugin material, but somebody has to do the job.
