### ISSUE TITLE
Monthly Chat Agenda May 2023 (2023-05-01 and 2023-05-15)

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#3204]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2023-05-01, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2023-05-15. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* :sunny: Google Summer of Code (GSoC): We have 1 qualified applicant who is going to work on a performance testing framework for CRS rules. Ranking took place last week and we hope Google agrees.
* OWASP Podcast ran a [Coraza Episode "Rethinking WAFs"](https://soundcloud.com/owasp-podcast/2023-04-rethinking-wafs-owasp-coraza)

#### Rules

* FIXME: Please fill in

#### CRS Sandbox

Todo:
- GitHub bot: add PR container when "sandbox-readt" label is present
- Dismiss Elasticsearch log?
- Coraza httpbin 

#### CRS Bug Bounty and Security

* Bug Bounty blog post had to be reviewed by our partners. This took more than a month. But it's ready now.
* We're currently tracking two open security issues. None of them is new.

#### Plugins

* Lots of updates with the NextCloud / OwnCloud rule exclusion plugin (https://github.com/coreruleset/nextcloud-rule-exclusions-plugin)
* 3rd party contribution RedMail / RoundCube rule exclusion plugin currently under review (https://github.com/coreruleset/plugin-registry/pull/13)

#### Documentation and Public Relations

* :arrows_counterclockwise: New issue to review the correctness of our template "gold standard" tests.
  If you're good with the test system and you can help review, please see: https://github.com/coreruleset/documentation/issues/85. We need to get this right!
* 3 blog posts in the queue, all almost ready to be published: Community Summit, new CRS youtube channel, Bug Bounty rundown
* 2 additional dev portraits currently in the making

#### Project Administration and Sponsor relationships

* Dev-on-duty payments for 2023.Q1 not issued yet, all a bit behind here

#### Tools

* FIXME: Please fill in

#### Testing incl. Seaweed and many future plans

* No development here.

#### Containers

* Assorted updates: modsecurity-3.0.9 and apache 2.4.57.

#### CRS Status Page

* On hold until CRS v4 is out

## Project discussions and decisions

* _Item from previous meeting: agreed to formally add to the agenda for discussion at the first May meeting._
  **Coraza/libcoraza:** Should the CRS project pay for someone to build an Nginx connector?
* Scanner overhaul: License question for one of the sources, also we need reviewers. (https://github.com/coreruleset/coreruleset/pulls)

### PRs that have been merged since the last meeting

* #3206
* #3186
* #3196
* #3167
* #3029
* #3141
* #3158
* #3187
* #3192
* #3207
 
We merged 10 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #3202
* #3170
* #3201
* #3190
* #3203
* #2302
* #3184
* #2637
* #2666

### Open issues and PRs

* As of Monday, we have 109 open issues.
* As of Monday, we have 14 open pull requests.

# Separate 2nd Meeting (Monday, 2023-05-15)

* PR #3202
  * Is this really what we want?
  * How to maintain this - fix future FPs?
  * Do we do a tag? Which one?
* https://github.com/coreruleset/secrules_parsing/issues/43

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by RedXanadu** [comment]
# Decisions 2023-05-01

**Comment by franbuehler** [comment]
# Decisions separate 2nd Meeting (Monday, 2023-05-15)

* PR #3202
  * Is this really what we want?
  * How to maintain this - fix future FPs?
  * Do we do a tag? Which one?
* https://github.com/coreruleset/secrules_parsing/issues/43 -> @airween will check it out and work with **jit** to get it merged.
