### ISSUE TITLE
94113 False positive when performing WordPress Search

### ISSUE THREAD

**Issue by talktomedia-rob** [coreruleset/coreruleset#3217]
Perform a search on the front or backend of a WordPress website with WooCommerce, the search phrase contains "pattern"

"http_method": "GET",
      "meta_file": "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf",
      "timestamp": "2023-05-19 15:41:15",
      "handler": null,
      "meta_logdata": "Matched Data: +Pattern found within https://domain.com/?s=Oak+Pattern&post_type=product: https://domain.com/?s=Oak+Pattern&post_type=product",
      "meta_line": "58",
      "http_status": 403,
      "meta_offset": 0,
      "host": null,
      "meta_id": 941130,
      "path": "/?s=Oak+Pattern&post_type=product",
      "meta_severity": "CRITICAL",
      "id": 489306,
      "justification": "Test 'REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|ARGS_NAMES|ARGS|XML:/*' against '(?i)[\\s\\S](?:x(?:link:href|html|mlns)|!ENTITY.*?SYSTEM|data:text\\/html|pattern(?=.*?=)|formaction|\\@import|base64)\\b' is true.",
      "meta_rev": "2",
      "meta_msg": "XSS Filter - Category 3: Attribute Vector",
      "meta_uri": null,
      "action_desc": "Access denied with code 403 (phase 2).",
      "http_version": "HTTP/1.1",
      "timezone": 60,

**Comment by azurit** [comment]
Hi @talktomedia-rob. This is already fixed in current development version of CRS.

**Comment by talktomedia-rob** [comment]
@azurit is there an ETA on the next release?

**Comment by azurit** [comment]
Not sure but you can copy the new rule from here:
https://github.com/coreruleset/coreruleset/blob/483630449e176cbd4e22571511acefaab5e5a870/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L134

**Comment by azurit** [comment]
@talktomedia-rob Feel free to close this issue if new rule works ok for you.

**Comment by fzipi** [comment]
@talktomedia-rob This is two months old now. Please reopen if this didn't work for you.
