### ISSUE TITLE
920420 False positive application/merge-patch+json

### ISSUE THREAD

**Issue by HappyWarbird** [coreruleset/coreruleset#3224]
### Description

As described in RFC 7396 (https://datatracker.ietf.org/doc/html/rfc7396), the content type application/merge-patch+json is a proposed standart, but isn't added to the tx.allowed_request_content_type in 901162.

### How to reproduce the misbehavior (-> curl call)

curl -H "x-format-output: txt-matched-rules" -H "Content-Type: application/merge-patch+json" https://sandbox.coreruleset.org

### Logs

``
[Mon May 22 16:24:24.764147 2023] [error] [client REDACTED] ModSecurity: Warning. Match of "within %{tx.allowed_request_content_type}" against "TX:content_type" required. [file "REDACTED/modsecurity-rules/owasp-crs/3.3.2/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1085"] [id "920420"] [msg "Request content type is not allowed by policy"] [data "|application/merge-patch+json|"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.2"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153"] [tag "PCI/12.1"] [tag "REQUEST-920-PROTOCOL-ENFORCEMENT"] [hostname "REDACTED"] [uri "REDACTED"] [unique_id "REDACTED"] rc=REDACTED uri="REDACTED" #3895(4010)
``

### Your Environment

* CRS version (e.g., v3.3.4): 3.3.2
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6): 2.8.0
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): Apache httpd 2.4.54
* Operating System and version: USP Secure Entry Server

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by franbuehler** [comment]
Thank you for your report. As we don't allow the HTTP method PATCH by default, I think we won't add this content-type as allowed content-type. Therefore I suggest that you uncomment this rule https://github.com/coreruleset/coreruleset/blob/483630449e176cbd4e22571511acefaab5e5a870/crs-setup.conf.example#L486 in your crs-setup.conf and you add the content-type there.

**Comment by HappyWarbird** [comment]
Thanks, yes i edit 901162 and add the content-type there.
Issue closed
