### ISSUE TITLE
[QUESTION]Why owasp crs rule 942200 contain "space" keyword?

### ISSUE THREAD

**Issue by leveryd** [coreruleset/coreruleset#3243]
```
# Regexp generated from util/regexp-assemble/regexp-942200.data using Regexp::Assemble.
# To rebuild the regexp:
#   cd util/regexp-assemble
#   ./regexp-assemble.pl regexp-942200.data
# Note that after assemble an outer bracket with an ignore case flag is added
# to the Regexp::Assemble output:
#   (?i:ASSEMBLE_OUTPUT)
#
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i:(?:(?:(?:(?:trunc|cre|upd)at|renam)e|(?:inser|selec)t|de(?:lete|sc)|alter|load)\s*?\(\s*?space\s*?\(|,.*?[)\da-f\"'`][\"'`](?:[\"'`].*?[\"'`]|(?:\r?\n)?\z|[^\"'`]+)|\Wselect.+\W*?from))" \
    "id:942200,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni,\
    msg:'Detects MySQL comment-/space-obfuscated injections and backtick termination',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/152/248/66',\
    tag:'PCI/6.5.2',\
    tag:'paranoia-level/2',\
    ver:'OWASP_CRS/3.3.2',\
    severity:'CRITICAL',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"
```

the rule contains "space" keyword, but why need this keyword instead of "\s"?

[![image][1]][1]

  [1]: https://i.stack.imgur.com/U5IPn.png

**Comment by airween** [comment]
Hi @leveryd,

thanks for your report.

You should take a look to the data file of the generated [regex](https://github.com/coreruleset/coreruleset/blob/v3.3/master/util/regexp-assemble/regexp-942200.data), which contains the keyword `space` (plus the `\s` too).

The reason is unknown why is it there, so we have to investigate this.

**Comment by leveryd** [comment]
Yeah, i have looked the generated [regex](https://github.com/coreruleset/coreruleset/blob/v3.3/master/util/regexp-assemble/regexp-942200.data), but the question is the same.

**Comment by dune73** [comment]
@franbuehler Do you have something to add here?

**Comment by airween** [comment]
Quote from @theseion:

_‘space’ is the ‘space()’ function. It’s used for obfuscation since space in the query string is just ignored. https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_space_

I think we can close this issue, if you don't have any question.

**Comment by leveryd** [comment]
@airween

I can understand what space() can do, but i can not understand how it is used for obfuscation, can u give a complete payload example?

**Comment by theseion** [comment]
Two (not very good) examples:

```mysql
SET @query=CONCAT(SPACE(1), 'SELECT ', 'id ', 'FROM ', 'test');
PREPARE stmt FROM @query;
EXECUTE stmt;
```

```mysql
INSERT INTO test (id) VALUES (SPACE(1));
```

Unfortunately, we don't know what this particular expression is supposed to catch. As you can see, neither of the two examples is matched by that part of the regular expression. I suspect that there is a way to use `space` that I haven't found. What's telling about the regex is the leading parenthesis before `space` and that it must apparently follow one of `select|create|rename|truncate|load|alter|delete|update|insert|desc`.

**Comment by leveryd** [comment]
Ok, so this regex is expected to find some interesting unknow payload.

**Comment by leveryd** [comment]
By the way, i have some similar question about what's the rule is to expected to catch. Although i can guess somewhat by "rule msg", but it is not so clear.

Should i ask by issue, or some other better way? any suggestion?

@airween @theseion

**Comment by airween** [comment]
> By the way, i have some similar question about what's the rule is to expected to catch. 

See [@theseion's](https://github.com/coreruleset/coreruleset/issues/3243#issuecomment-1612443857) comment.

**Comment by leveryd** [comment]
@theseion 

Below regex (in regexp-942200.data file too) detect what payload?
```
,.*?[)\da-f\"'`][\"'`][\"'`].*?[\"'`]
,.*?[)\da-f\"'`][\"'`](?:\r?\n)?\z
,.*?[)\da-f\"'`][\"'`][^\"'`]+
```

**Comment by theseion** [comment]
We did not write these expressions, they were compiled by Trustwave years ago and no one knows where they came from anymore or what they are supposed to match. There's hardly any documentation. 
That being said, I've looked around a bit and here are a couple of examples:

```mysql
SELECT RTRIM(XMLAGG(XMLELEMENT(e, table_name || ',')).EXTRACT('//text()').EXTRACT('//text()') ,',') FROM all_tables;

SELECT (@) FROM (SELECT(@:=0x00),(SELECT (@) FROM (information_schema.columns) WHERE (table_schema>=@) AND (@)IN (@:=CONCAT(@,0x0a,' [ ',table_schema,' ] >',table_name,' > ',column_name))))x

SELECT * FROM Users WHERE id = '1' AND MID(VERSION(),1,1) = '5';

SELECT CONCAT_WS('', 'a', 'd', 'm', 'i', 'n');

(IF(MID(version(),1,1) LIKE 5, BENCHMARK(100000,SHA1('true')), false))

UNION(SELECT(column)FROM(table))
```

I found all of these here: https://www.websec.ca/kb/sql_injection. Note that some of the matches may be accidental, the expression is far from perfect.

**Comment by fzipi** [comment]
@leveryd What we (or I) have in plans for future CRS releases is to clean up this mess. Every line in a regexp data file should have clear comments on what is that we are matching, and why.

This huge job will require everyone to take a deep and found matching attack... or just clean that part from a rule.
