### ISSUE TITLE
403 error message with nginx proxy manager

### ISSUE THREAD

**Issue by OpenK54** [coreruleset/coreruleset#3245]
I have several servers behinde the proxy. I can access them from the web and browse the servers gui. But it is not possible to access any file. Debbuging the browser I see 403 forbidden responses in the browser, but these are not present in the servers log. Deactivating coreruleset solved the problem. See: https://github.com/ZoeyVid/nginx-proxy-manager/discussions/315

**Comment by airween** [comment]
Hi @OpenK54,

thanks for your feedback.

Unfortunately the available information is is not enough, I'm afraid we can't help you based on it.

Please see the [template](https://github.com/coreruleset/coreruleset/issues/new?assignees=&labels=%3Aheavy_plus_sign%3A+False+Positive&projects=&template=01_false-positive.md&title=), and fill it as well. You can modify your first comment, or feel free to close this one and open a new issue.

**Comment by theseion** [comment]
If CRS did block you should see messages in the error log of the web server and in the ModSecurity audit log. Those will tell you which rules triggered and then you can work from there to tune your setup. CRS isn't a turn key solution. If you want to make the most out of it you'll have to get your hands dirty.

**Comment by azurit** [comment]
@OpenK54 Ping.

**Comment by theseion** [comment]
@OpenK54, please reopen if you have more information to share.
