### ISSUE TITLE
[QUESTION] what payload the rule 941340 to prevent?

### ISSUE THREAD

**Issue by leveryd** [coreruleset/coreruleset#3250]
Hello,  941340 rule is here

https://github.com/coreruleset/coreruleset/blob/8b1d673fdd7adb41a6e685d4f88f54bb721ccd45/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L963

I have read the test case, but still can not understand what payload it want to prevent.

https://github.com/coreruleset/coreruleset/blob/v3.3.0/tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941340.yaml

If u want to prevent "assign variable operation", why it must obey 'xxx.yyy' such pattern?

![image](https://github.com/coreruleset/coreruleset/assets/1846319/2377ce90-1470-47a7-97d6-b16749f1c86e)

And why there is keyword "in" ?
![image](https://github.com/coreruleset/coreruleset/assets/1846319/84e6e29a-486e-4dd8-9174-e59433d419ae)

**Comment by azurit** [comment]
@leveryd Hi. Second test is based on [this](https://github.com/PortSwigger/xss-cheatsheet-data/blob/f9c45f99948bc4c57ee315103c655d2885c04398/json/classic.json#L28), does it helps to you to understand this rule?

**Comment by azurit** [comment]
@leveryd I'm not JavaScript expert but `JScript.Encode` seems to be supported only by Microsoft web browsers.

**Comment by leveryd** [comment]
> @leveryd I'm not JavaScript expert but `JScript.Encode` seems to be supported only by Microsoft web browsers.

I tried to reproduce on microsoft edge browser, it still is the same.

**Comment by azurit** [comment]
@leveryd Edge is based on Chrome, try Internet Explorer.

**Comment by leveryd** [comment]
Fine, i think this rule should be deleted because the attack it want to prevent can not work nowadays.

refer: https://github.com/PortSwigger/xss-cheatsheet-data/issues/48

> Those payloads are in the classic section which means they are old vectors that no longer work. JScript.Encode was specific to older versions of Internet Explorer.
