### ISSUE TITLE
Bring the v4 branch release notes up to date (CHANGES.MD)

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#3260]
### Describe the bug

Once v3.3.5 is out, we should update the v4 branch with all of the missing CHANGES.MD changes. It currently doesn't cover the most recent few v3.3 release change notes.

### Expected behaviour

The v4 release line should include all of the v3 change notes, too.

### Actual behaviour

The v3.3 branch has some release notes that are missing in the v4 branch, because we added the change notes there for the v3.3.x releases.

**Comment by airween** [comment]
Did #3338 solves this issue?

**Comment by dune73** [comment]
Not sure with regards to 3.3. And the v4 RC1 changelog has not been up to the RC2 standard. Let's keep this open until we are really, really sure everything is done.

**Comment by azurit** [comment]
@dune73 Are we sure now or not yet?

**Comment by dune73** [comment]
Yes, most definitely. Thanks for the ping. Closing now.
