### ISSUE TITLE
Add more user agents to scanner user agent list

### ISSUE THREAD

**Issue by jfeng-league** [coreruleset/coreruleset#3285]
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list

I'd like to add these user agents into the scanner detection list. It will greatly improve all the downstream systems (GCP Cloud Armor) that utilize these lists

**Comment by RedXanadu** [comment]
Hi @jfeng-league,

Please use our issue templates when opening an issue, e.g. the 'Feature Request' template. This ensures we have the information required and in a standard format, making these issues easier and quicker to triage.

Your idea is a good one, but we have [recently decided](https://github.com/coreruleset/coreruleset/pull/3202#issuecomment-1582312003) against continuing to do much blocking based on User Agent:

> We agreed in the June meeting, that [overhauling the User Agent detection rules] would not work and we are now stripping the UA based scanner detection to the most malicious scanners announcing themselves in the UA in a PL1 rule. All the rest is being kicked out since we are not able to draw a line between benign, annoying and not so benign scanners and bots. Creating a plugin to provide this for those who really want it, would be an option though, but that is not a priority / depends on a volunteer.

The plan was to use the "apache-ultimate-bad-bot-blocker", so very similar to your suggestion!

This type of User Agent block/spam detection could be turned into a plugin in the future, but at the moment the decision is that it will not live as part of the core/default CRS rules.

I'm going to close this issue as we've already decided as a project not to move in this direction of UA scanning/blocking, but feel free to follow up if you have any further questions or points to make.
