### ISSUE TITLE
Incorrect Regex in Rule 942440 Chained Matchvar

### ISSUE THREAD

**Issue by theMiddleBlue** [coreruleset/coreruleset#3287]
https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1362

I've realized that there's an oversight in the regex used for the chained matchvar. At the time of implementation, I incorrectly set the range as written, but it should actually be A-Za-z to accurately capture the intended pattern.

I think the rx is working as expected just because the "-" between the two ranges is interpreted as literal hyphen. Am I wrong?

I'm going to assign this to me as a reminder for opening a PR to fix this.

**Comment by dune73** [comment]
You are talking about `A-Z-a-z`? That's indeed wrong. But you repeat the `-` later in the regex so I think it gets ignored. Not 100% sure you can write `-_, though. Should not it be `_-`?

Also, when doing a PR, could you add a comment why we need the chained rule with the `ey` prefix.

**Comment by theMiddleBlue** [comment]
fixed here: #3290

**Comment by theseion** [comment]
This issue has been fixed in #3290.
