### ISSUE TITLE
Rule 920600 is blocking all kinds of Java HttpUrlConnection

### ISSUE THREAD

**Issue by bussef** [coreruleset/coreruleset#3289]
### Description

For many Java projects the class HttpUrlConnection is used. It is using a fixed Accept-Header: `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2`
Source: https://github.com/JetBrains/jdk8u_jdk/blob/94318f9185757cc33d2b8d527d36be26ac6b7582/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L290
(It is still the same in Java 17)

This implementation does not include a charset parameter which is perfectly fine according to the HTTP 1.1 spec. However Rule 920600 explicitly enforces the charset parameter and blocks requests where this parameter is missing per default. In my opinion the charset-parameter should not be enforced in the Accept-Header, unless there is a very important reason for it.

### How to reproduce the misbehavior (-> curl call)

Apologies, Java is not Curl :)

### Logs

```
-OOO- A.B.C.D - - [29/Aug/2023:16:37:19 +0000] "GET /redacted HTTP/1.1" 403 146 "-" "Java/11.0.19" 415 0.000 [-] [] - - - - 76cb2cd7f5bebe57890d52fff2aa40f2
---VvL2tRta---A--
[29/Aug/2023:16:37:19 +0000] 169332703979.310293 A.B.C.D 0 172.17.34.23 443
---VvL2tRta---B--
GET /redacted HTTP/1.1
Host: redacted.host
X-Request-ID: 76cb2cd7f5bebe57890d52fff2aa40f2
X-Forwarded-Port: 443
X-Forwarded-Scheme: https
X-Real-IP: A.B.C.D
X-Forwarded-For: A.B.C.D
X-Forwarded-Host: redacted.host
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
X-Forwarded-Proto: https
X-Scheme: https
User-Agent: Java/11.0.19

---VvL2tRta---D--

---VvL2tRta---E--
<html>\x0d\x0a<head><title>403 Forbidden</title></head>\x0d\x0a<body>\x0d\x0a<center><h1>403 Forbidden</h1></center>\x0d\x0a<hr><center>nginx</center>\x0d\x0a</body>\x0d\x0a</html>\x0d\x0a

---VvL2tRta---F--
HTTP/1.1 403
Server: 
Server: 
Date: Tue, 29 Aug 2023 16:37:19 GMT
Content-Length: 146
Content-Type: text/html
Connection: keep-alive
Content-Security-Policy: default-src 'self'; img-src 'self' data:

---VvL2tRta---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^(?:(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+)\/(?:\*|[^\"(),\/:;<=>?![\x5c\]{}]+))(?:\s*+;\s*+(?:(?:charset\s*+=\s*+(?:\"?(?:iso-8859-15?|windows-1252|utf-8)\b\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\"(),\/:;<=> (714 characters omitted)' against variable `REQUEST_HEADERS:Accept' (Value: `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' ) [file "/etc/nginx/owasp-modsecu
rity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1147"] [id "920600"] [rev ""] [msg "Illegal Accept header: charset parameter"] [data "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [hostname "172.
17.34.23"] [uri "/redacted"] [unique_id "169332703979.310293"] [ref "v348,52t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [
tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "172.17.34.23"] [uri "/redacted"] [unique_id "169332703979.310293"] [ref ""]

---VvL2tRta---I--

---VvL2tRta---J--

---VvL2tRta---Z--
```

### Your Environment

* CRS version (e.g., v3.3.4): v3.3.4
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6):
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): kubernetes nginx ingress controller 1.6.0
* Operating System and version:

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @bussef,

thank your for your report.

Yes, CRS 3.3 follows the explained behavior above. The "good news" for you is that in CRS4, this behavior has changed. CRS4 allows the `Accept` header without `charset` value.

I understand that you can't change the rule set now, so the only option is that you make an exclusion. If you do not want always to exclude this rule, you can check the `User-Agent` header, and if it's the `Java/11.0.19` or something that you want to allow, then you can make a condition in the exclusion.

Let me know, if I can help you.
