### ISSUE TITLE
False positive on 932110 with Dutch text

### ISSUE THREAD

**Issue by janvanuytrecht** [coreruleset/coreruleset#3321]
### Description

This Dutch text triggers 932110, while it is valid json text.

### How to reproduce the misbehavior (-> curl call)

ErrorMessage:

``
Pattern match (?i)(?:;|\{|\||\|\||&|&&|\n|\r|`)\s*[\(,@\'"\s]*(?:[\w'"\./]+/|[\\'"\^]*\w[\\'"\^]*:.*\\|[\^\.\w '"/\\]*\\)?["\^]*(?:m["\^]*(?:y["\^]*s["\^]*q["\^]*l(?:["\^]*(?:d["\^]*u["\^]*m["\^]*p(?:["\^]*s["\^]*l["\^]*o["\^]*w)?|h["\^]*o["\^]*t["\^]*c["\^]*o["\^]*p["\^]*y|a["\^]*d["\^]*m["\^]*i["\^]*n|s["\^]*h["\^]*o["\^]*w))?|s["\^]*(?:i["\^]*(?:n["\^]*f["\^]*o["\^]*3["\^]*2|e["\^]*x["\^]*e["\^]*c)|c["\^]*o["\^]*n["\^]*f["\^]*i["\^]*g|g["\^]*(?:[\s,;]|\.|/|<|>).*|t["\^]*s["\^]*c)|o["\^]*(?:u["\^]*n["\^]*t["\^]*(?:(?:[\s,;]|\.|/|<|>).*|v["\^]*o["\^]*l)|v["\^]*e["\^]*u["\^]*s["\^]*e["\^]*r|[dr]["\^]*e["\^]*(?:[\s,;]|\.|/|<|>).*)|k["\^]*(?:d["\^]*i["\^]*r["\^]*(?:[\s,;]|\.|/|<|>).*|l["\^]*i["\^]*n["\^]*k)|d["\^]*(?:s["\^]*c["\^]*h["\^]*e["\^]*d|(?:[\s,;]|\.|/|<|>).*)|a["\^]*p["\^]*i["\^]*s["\^]*e["\^]*n["\^]*d|b["\^]*s["\^]*a["\^]*c["\^]*l["\^]*i|e["\^]*a["\^]*s["\^]*u["\^]*r["\^]*e|m["\^]*s["\^]*y["\^]*s)|d["\^]*(?:i["\^]*(?:s["\^]*k["\^]*(?:(?:m["\^]*g["\^]*m|p["\^]*a["\^]*r)["\^]*t|s["\^]*h["\^]*a["\^]*d["\^]*o["\^]*w)|r["\^]*(?:(?:[\s,;]|\.|/|<|>).*|u["\^]*s["\^]*e)|f["\^]*f["\^]*(?:[\s,;]|\.|/|<|>).*)|e["\^]*(?:l["\^]*(?:p["\^]*r["\^]*o["\^]*f|t["\^]*r["\^]*e["\^]*e|(?:[\s,;]|\.|/|<|>).*)|v["\^]*(?:m["\^]*g["\^]*m["\^]*t|c["\^]*o["\^]*n)|(?:f["\^]*r["\^]*a|b["\^]*u)["\^]*g)|s["\^]*(?:a["\^]*(?:c["\^]*l["\^]*s|d["\^]*d)|q["\^]*u["\^]*e["\^]*r["\^]*y|m["\^]*o["\^]*(?:v["\^]*e|d)|g["\^]*e["\^]*t|r["\^]*m)|(?:r["\^]*i["\^]*v["\^]*e["\^]*r["\^]*q["\^]*u["\^]*e["\^]*r|o["\^]*s["\^]*k["\^]*e)["\^]*y|(?:c["\^]*o["\^]*m["\^]*c["\^]*n["\^]*f|x["\^]*d["\^]*i["\^]*a)["\^]*g|a["\^]*t["\^]*e["\^]*(?:[\s,;]|\.|/|<|>).*|n["\^]*s["\^]*s["\^]*t["\^]*a["\^]*t)|c["\^]*(?:o["\^]*(?:m["\^]*(?:p["\^]*(?:(?:a["\^]*c["\^]*t["\^]*)?(?:[\s,;]|\.|/|<|>).*|m["\^]*g["\^]*m["\^]*t)|e["\^]*x["\^]*p)|n["\^]*(?:2["\^]*p|v["\^]*e)["\^]*r["\^]*t|p["\^]*y)|l["\^]*(?:e["\^]*a["\^]*(?:n["\^]*m["\^]*g["\^]*r|r["\^]*m["\^]*e["\^]*m)|u["\^]*s["\^]*t["\^]*e["\^]*r)|h["\^]*(?:k["\^]*(?:n["\^]*t["\^]*f["\^]*s|d["\^]*s["\^]*k)|d["\^]*i["\^]*r["\^]*(?:[\s,;]|\.|/|<|>).*)|s["\^]*(?:c["\^]*(?:r["\^]*i["\^]*p["\^]*t|c["\^]*m["\^]*d)|v["\^]*d["\^]*e)|e["\^]*r["\^]*t["\^]*(?:u["\^]*t["\^]*i["\^]*l|r["\^]*e["\^]*q)|a["\^]*(?:l["\^]*l["\^]*(?:[\s,;]|\.|/|<|>).*|c["\^]*l["\^]*s)|m["\^]*d(?:["\^]*k["\^]*e["\^]*y)?|i["\^]*p["\^]*h["\^]*e["\^]*r|u["\^]*r["\^]*l)|f["\^]*(?:o["\^]*r["\^]*(?:m["\^]*a["\^]*t["\^]*(?:[\s,;]|\.|/|<|>).*|f["\^]*i["\^]*l["\^]*e["\^]*s|e["\^]*a["\^]*c["\^]*h)|i["\^]*n["\^]*d["\^]*(?:(?:[\s,;]|\.|/|<|>).*|s["\^]*t["\^]*r)|s["\^]*(?:m["\^]*g["\^]*m["\^]*t|u["\^]*t["\^]*i["\^]*l)|t["\^]*(?:p["\^]*(?:[\s,;]|\.|/|<|>).*|y["\^]*p["\^]*e)|r["\^]*e["\^]*e["\^]*d["\^]*i["\^]*s["\^]*k|c["\^]*(?:[\s,;]|\.|/|<|>).*|g["\^]*r["\^]*e["\^]*p)|n["\^]*(?:e["\^]*t["\^]*(?:s["\^]*(?:t["\^]*a["\^]*t|v["\^]*c|h)|(?:[\s,;]|\.|/|<|>).*|c["\^]*a["\^]*t|d["\^]*o["\^]*m)|t["\^]*(?:b["\^]*a["\^]*c["\^]*k["\^]*u["\^]*p|r["\^]*i["\^]*g["\^]*h["\^]*t["\^]*s)|(?:s["\^]*l["\^]*o["\^]*o["\^]*k["\^]*u|m["\^]*a)["\^]*p|c["\^]*(?:(?:[\s,;]|\.|/|<|>).*|a["\^]*t)|b["\^]*t["\^]*s["\^]*t["\^]*a["\^]*t)|e["\^]*(?:x["\^]*p["\^]*(?:a["\^]*n["\^]*d["\^]*(?:[\s,;]|\.|/|<|>).*|l["\^]*o["\^]*r["\^]*e["\^]*r)|v["\^]*e["\^]*n["\^]*t["\^]*(?:c["\^]*r["\^]*e["\^]*a["\^]*t["\^]*e|v["\^]*w["\^]*r)|n["\^]*d["\^]*l["\^]*o["\^]*c["\^]*a["\^]*l|g["\^]*r["\^]*e["\^]*p|r["\^]*a["\^]*s["\^]*e|c["\^]*h["\^]*o)|g["\^]*(?:a["\^]*t["\^]*h["\^]*e["\^]*r["\^]*n["\^]*e["\^]*t["\^]*w["\^]*o["\^]*r["\^]*k["\^]*i["\^]*n["\^]*f["\^]*o|p["\^]*(?:(?:r["\^]*e["\^]*s["\^]*u["\^]*l|e["\^]*d["\^]*i)["\^]*t|u["\^]*p["\^]*d["\^]*a["\^]*t["\^]*e)|i["\^]*t["\^]*(?:[\s,;]|\.|/|<|>).*|e["\^]*t["\^]*m["\^]*a["\^]*c)|i["\^]*(?:r["\^]*b(?:["\^]*(?:1(?:["\^]*[89])?|2["\^]*[012]))?|f["\^]*m["\^]*e["\^]*m["\^]*b["\^]*e["\^]*r|p["\^]*c["\^]*o["\^]*n["\^]*f["\^]*i["\^]*g|n["\^]*e["\^]*t["\^]*c["\^]*p["\^]*l|c["\^]*a["\^]*c["\^]*l["\^]*s)|a["\^]*(?:d["\^]*(?:d["\^]*u["\^]*s["\^]*e["\^]*r["\^]*s|m["\^]*o["\^]*d["\^]*c["\^]*m["\^]*d)|r["\^]*p["\^]*(?:[\s,;]|\.|/|<|>).*|t["\^]*t["\^]*r["\^]*i["\^]*b|s["\^]*s["\^]*o["\^]*c|z["\^]*m["\^]*a["\^]*n)|l["\^]*(?:o["\^]*g["\^]*(?:e["\^]*v["\^]*e["\^]*n["\^]*t|t["\^]*i["\^]*m["\^]*e|m["\^]*a["\^]*n|o["\^]*f["\^]*f)|a["\^]*b["\^]*e["\^]*l["\^]*(?:[\s,;]|\.|/|<|>).*|u["\^]*s["\^]*r["\^]*m["\^]*g["\^]*r)|b["\^]*(?:(?:c["\^]*d["\^]*(?:b["\^]*o["\^]*o|e["\^]*d["\^]*i)|r["\^]*o["\^]*w["\^]*s["\^]*t["\^]*a)["\^]*t|i["\^]*t["\^]*s["\^]*a["\^]*d["\^]*m["\^]*i["\^]*n|o["\^]*o["\^]*t["\^]*c["\^]*f["\^]*g)|h["\^]*(?:o["\^]*s["\^]*t["\^]*n["\^]*a["\^]*m["\^]*e|d["\^]*w["\^]*w["\^]*i["\^]*z)|j["\^]*a["\^]*v["\^]*a["\^]*(?:[\s,;]|\.|/|<|>).*|7["\^]*z(?:["\^]*[ar])?)(?:\.["\^]*\w+)?\b at ARGS.
``

Input:

``
{
Net zoals voor de cultuursector wordt ook voor de jeugdsector de huidige regelgeving aangepast in functie van een snellere afbouw van de subsidiëring en de overdracht van de middelen naar het nieuwe Jeugddecreet.
De kredieten op dit artikel dienen om de loonkost of de opzegvergoeding te subsidiëren. Of het nu om de subsidiëring van de lonen of van de opzegvergoeding gaat, in beide gevallen is het niet exact in te schatten hoe hoog de effectieve subsidiëringskost zal zijn. Dit kan variëren op basis...
``

###

I assume the issue is 'net zoals', while net is just the dutch translation for 'just like'

### Your Environment

* CRS version: 3.2

### Confirmation

[ x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theseion** [comment]
Thanks for reporting @janvanuytrecht. This particular FP (`net`) has been addressed in v4.0.

What was the content type of the request? The input isn't JSON, even though it starts with an opening brace. For JSON (or more freeform content like the input you provided) it is usually necessary to create an exclusion rule because the request can contain arbitrary data (see https://coreruleset.org/docs/concepts/false_positives_tuning/#directly-modifying-crs-rules).

**Comment by theseion** [comment]
Closing as stale.
