### ISSUE TITLE
gpg key missing for release v4.0.0-rc2

### ISSUE THREAD

**Issue by m-si** [coreruleset/coreruleset#3345]
### Describe the bug

First of all: Thank you all for your great work. Maybe I miss something obvious. I can't fetch coreruleset-4.0.0-rc2.tar.gz.asc as it seems not to be published. Or is it intended to stop signing releases?

### Steps to reproduce

curl -SL https://github.com/coreruleset/coreruleset/releases/download/v4.0.0-rc2/coreruleset-4.0.0-rc2.tar.gz.asc

### Expected behaviour

key file should be downloadable

### Actual behaviour

it's not there so it can't be downloaded

**Comment by airween** [comment]
Sorry for the inconvenience, meanwhile we already uploaded the signatures:

https://github.com/coreruleset/coreruleset/releases/tag/v4.0.0-rc2

And your mentioned command above returns with it.
