### ISSUE TITLE
Rule 941330 denies multipart upload with filename

### ISSUE THREAD

**Issue by maround95** [coreruleset/coreruleset#3348]
### Description
When uploading a file in a multipart body, the rule '941330' denies the request.
The regex defined matches the "Content-Disposition" header in the body of the request in case it also defines the "filename" directive.

An example of a decoded body, with an empty file:
```
------WebKitFormBoundaryJVNIdp0GIXR9yHpA
Content-Disposition: form-data; name="file"; filename="myimage.png"
Content-Type: image/png

------WebKitFormBoundaryJVNIdp0GIXR9yHpA--
```
```
Content-Disposition: form-data; name="file"; filename="myimage.png"
------------------------------------------^^^^^^^^^^^^ (regex matches across the name and filename directives)
```
### How to reproduce the misbehavior (-> curl call)
Any multipart upload with the "filename" directive defined.

`curl -X POST $URL --form 'file=@"/path/to/file"'`

### Your Environment

CRS v3.3 using Google Cloud Armor.
This also should apply to the current '4.0/dev' branch.

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by M4tteoP** [comment]
Hi @maround95, thanks for the report.
I'm trying to reproduce your issue. I'm not succeeding doing it by uploading a multipart body with the following request:
- `curl -X POST localhost:80/anything -v --form 'file=@"/tmp/myimage.png";filename="myimage.png"'`

Performed against some different configurations:
   - `CRS v4.0.0-rc2 loaded in Modsec v2 with Apache`
   - `CRS v3.3.5 loaded in Modsec v2 with Apache`
   - `CRS v4.0.0-rc1 loaded in Coraza with Envoy`

The body contains the elements that you mentioned:
```
"data": "--------------------------7b26b9aae617c947\r\nContent-Disposition: form-data; name=\"file\"; filename=\"myimage.png\"\r\nContent-Type: image/png\r\n\r\n\r\n--------------------------7b26b9aae617c947--\r\n"
```
But no rules are matched.

I managed to reproduce it by directly sending that content as part of a payload with: ``curl "http://localhost:80/anything" --data 'Content-Disposition: form-data; name="file"; filename="myimage.png"' -v``
Here are the logs:
- CRS 3.3.5:
```
[Tue Oct 31 17:33:19.630628 2023] [security2:error] [pid 33:tid 281471671587200] [client 172.20.0.1:46806] [client 172.20.0.1] ModSecurity: Warning. Pattern match "(?i:[\\"'][ ]*(?:[^a-z0-9~_:' ]|in).*?(?:(?:l|\\\\\\\\u006C)(?:o|\\\\\\\\u006F)(?:c|\\\\\\\\u0063)(?:a|\\\\\\\\u0061)(?:t|\\\\\\\\u0074)(?:i|\\\\\\\\u0069)(?:o|\\\\\\\\u006F)(?:n|\\\\\\\\u006E)|(?:n|\\\\\\\\u006E)(?:a|\\\\\\\\u0061)(?:m|\\\\\\\\u006D)(?:e|\\\\\\\\u0065)|(?:o|\\\\\\\\u006F)(?:n|\\\\\\\\u006E) ..." at ARGS:Content-Disposition: form-data; name. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "805"] [id "941330"] [msg "IE XSS Filters - Attack Detected"] [data "Matched Data: \\x22; filename= found within ARGS:Content-Disposition: form-data; name: \\x22file\\x22; filename=\\x22myimage.png\\x22"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.5"] [tag "modsecurity"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [tag "PCI/6.5.1"] [tag "paranoia-level/2"] [hostname "localhost"] [uri "/anything"] [unique_id "ZUE6X_pYHThGyy0MaYqlMwAAABY"]
```

- CRS 4.0.0-rc2:
```
[Tue Oct 31 17:40:24.303506 2023] [security2:error] [pid 35:tid 281472947368320] [client 172.21.0.1:57416] [client 172.21.0.1] ModSecurity: Warning. Pattern match "(?i:[\\"'][ ]*(?:[^a-z0-9~_:' ]|in).*?(?:(?:l|\\\\x5cu006C)(?:o|\\\\x5cu006F)(?:c|\\\\x5cu0063)(?:a|\\\\x5cu0061)(?:t|\\\\x5cu0074)(?:i|\\\\x5cu0069)(?:o|\\\\x5cu006F)(?:n|\\\\x5cu006E)|(?:n|\\\\x5cu006E)(?:a|\\\\x5cu0061)(?:m|\\\\x5cu006D)(?:e|\\\\x5cu0065)|(?:o|\\\\x5cu006F)(? ..." at ARGS:Content-Disposition: form-data; name. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "958"] [id "941330"] [msg "IE XSS Filters - Attack Detected"] [data "Matched Data: \\x22; filename= found within ARGS:Content-Disposition: form-data; name: \\x22file\\x22; filename=\\x22myimage.png\\x22"] [severity "CRITICAL"] [ver "OWASP_CRS/4.0.0-rc2"] [tag "modsecurity"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [tag "PCI/6.5.1"] [tag "paranoia-level/2"] [hostname "localhost"] [uri "/anything"] [unique_id "ZUE8CIwgTu6QGo0BYEbUiQAAAIE"]
```

I'm wondering:
1. Did you manage to reproduce it when uploading a file in a multipart body against a Modsecurity container or the test environment that comes inside the CRS repo (`docker-compose -f tests/docker-compose.yml up -d modsec2-apache`? Mind that it logs PL4 rules, but no actions are enforced, running in `DetectionOnly` by default).
2. Would you have some more logs coming from the matched rule (e.g. showing the internal variable that matched)?
3. If you did not manage to reproduce it outside Google Cloud Armor, did you try to reach their support?

I'm currently thinking that Google WAF Engine is behaving in a different way compared to ModSecurity and Coraza in regards to processing the multipart request. ModSecurity and Coraza come with a dedicated body processor that deals with it.

**Comment by maround95** [comment]
Hello @M4tteoP,
Thank you for your reply.

1. I have tried with the following test environment `CRS v4.0.0-rc2 loaded in Modsec v2 with Apache` and my findings are the same as yours, i.e. it doesn't get reproduced with the file upload, but the explicit content does trigger it.
2. Yes, the internal variable matched is `ARG_VALUES` and the matched value is `"; filename=` as described earlier.
Also matched field name might be of interest: `--a-random-boundary-string Content-Disposition: form-data; name`
3. I have not. It seems plausible that there might be some discrepancies in how the Google WAF Engine processes body data given our results. I'll reach out to them.

**Comment by dune73** [comment]
Good plan. We'd be interested in the response.

**Comment by maround95** [comment]
Basically their response was to ignore the problematic rule and/or create a modified copy where the regex is different.
In any case, it seems like the problem does not apply to the reference implementations.

Thank you both for your help.

**Comment by dune73** [comment]
Thank you for the heads up @maround95. If there is anything else we can do for you, please let us know.
