### ISSUE TITLE
Set up automation for changelog comments

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3368]

**Comment by dune73** [comment]
See https://github.com/coreruleset/coreruleset/wiki/DevRetreat23DiscussionChangelogUpdates

**Comment by theseion** [comment]
> What we could think about is working via a label. So the moment we merge, the PR has to carry a label. The label could be "Changelog approved". That means somebody does a proposal and somebody approves that. We can then search for the label as a nice side-effect.
