### ISSUE TITLE
934130 and 934131: not required base64 tfunc

### ISSUE THREAD

**Issue by theMiddleBlue** [coreruleset/coreruleset#3376]
Rules 934130 and 934131, created in https://github.com/coreruleset/coreruleset/pull/2411, currently utilize the `t:base64Decode` tfunc. However, we spot some issues during "make regression tests works for nginx", revealing some problems with attempting to decode the payload from a base64 string.

Additionally:
1. ModSecurity v2 and v3 uses different libraries for base64 decoding, leading to divergent behaviors.
2. The use of the base64 encoding approach is inconsistent on CRS, it specifically focused on matching a prototype pollution payload base64 encoded, and we're not following this approach elsewhere. Why only here?
3. Testing has shown that base64 decoding can fail, even with the "ext" version, resulting in an empty variable that essentially equals to a bypass.

Proposal:
Considering the aforementioned issues, I propose the following actions:
1. Remove the `t:base64Decode` Tfunc from Rules 934130 and 934131.
2. Eliminate all related tests associated with the base64 decoding approach.

Opinions?

**Comment by RedXanadu** [comment]
@theMiddleBlue Is this related to the anti-evasion work done / false negatives reported in #3311, #3182, #3203?

**Comment by theMiddleBlue** [comment]
it's more about the base64 function already present on those rules before the anti-evasion work you mention I guess

**Comment by RedXanadu** [comment]
But we added Base64 anti-evasion decoding to  934100, 934101, 934130, 934131, and 934160. Is the originally reported false negative no longer considered valid? And we should remove Base64 decoding from all of the rules that were modified?

**Comment by dune73** [comment]
Can we get examples where the decoding fails with the ext version?

**Comment by theMiddleBlue** [comment]
at the moment, on v3, basically every base64 string that contains a `+` fails
that because urldecode convert + into a whitespace and the base64decodeext function on v3 isn't happy with it.

but again, I think that "the base64 decoding approach" used only here doesn't make any sense

**Comment by theMiddleBlue** [comment]
suggested approach: https://github.com/coreruleset/coreruleset/pull/3378

**Comment by M4tteoP** [comment]
Can we close this on? https://github.com/coreruleset/coreruleset/pull/3378 has been merged 🤔

**Comment by dune73** [comment]
Yes.
