### ISSUE TITLE
Monthly Chat Agenda November 2023 (2023-11-20)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3385]
This is the Agenda for the single Monthly CRS Chats in November.

The first chat did not take place since the team was attending the annual CRS developer summit in Budapest.

Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

## Separate 2nd Meeting (Monday, 2023-11-20)

* Looking back onto the CRS dev retreat
* CRS v4.0 False Positives (and the lack of reports)
* CRS v4.0 release plans
* Backport of 3.3.5 to 3.2.x

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
## Decisions November 20th
