### ISSUE TITLE
FP on 920470 PL1 (Illegal Content-Type header)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3386]
### Description

I'm getting the following Content-Type header triggering FPs sporadically:

`application/x-www-form-urlencoded;` 

### How to reproduce the misbehavior (-> curl call)

```
$ curl -H "x-crs-paranoia-level: 1" -H "x-format-output: txt-matched-rules" -H "x-backend: apache" -H "x-crs-version: nightly" https://sandbox.coreruleset.org/ -d "foo=bar" -H "Content-Type: application/x-www-form-urlencoded;"
920470 PL1 Illegal Content-Type header
```
### Logs

```
[2023-11-14 12:50:28.020899] [-:error] 10.86.43.156:37386 ZVNfBAjnMZuX@F3YId1@IgAAAAA [client 10.86.43.156] ModSecurity: Warning. Match of "rx ^[\\\\w/.+*-]+(?:\\\\s?;\\\\s?(?:action|boundary|charset|component|start(?:-info)?|type|version)\\\\s?=\\\\s?['\\"\\\\w.()+,/:=?<>@#*-]+)*$" against "REQUEST_HEADERS:Content-Type" required. [file "/etc/apache2/crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "962"] [id "920470"] [msg "Illegal Content-Type header"] [data "application/x-www-form-urlencoded;"] [severity "CRITICAL"] [ver "OWASP_CRS/4.0.0-rc2"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153"] [tag "PCI/12.1"] [hostname "www.example.com"] [uri "/download.do"] [unique_id "ZVNfBAjnMZuX@F3YId1@IgAAAAA"]

```
### Your Environment

* CRS version (e.g., v3.3.4): 4.0-RC-2

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by Xhoenix** [comment]
The regex operator begins with `!@rx`, thus it catches anything outside of the regex match, which includes above Content-Type value.

**Comment by Xhoenix** [comment]
I'm checking the vuln right now, for further info.

**Comment by dune73** [comment]
Thank you for investigating. I think it's more of an FP, but double checking would be smart.

**Comment by dune73** [comment]
For me, it looks like `application/x-www-form-urlencoded; charset=utf-8` but the `charset` went missing.

**Comment by Xhoenix** [comment]
Just checked mdn docs and it's still valid without the charset:- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

**Comment by Xhoenix** [comment]
> Thank you for investigating. I think it's more of an FP, but double checking would be smart.

That's why I decided to do a double check. :)

**Comment by Xhoenix** [comment]
Not sure, but it seems the semicolon `;` at the end of header creates problem with regex, as the header expects the remaining part

**Comment by dune73** [comment]
Exactly. We may have to make this optional.

I see the following variants:
* naked mime type: OK
* mime type + ";": NOK but should be OK
* mime type + ";" + charset: OK
* mime type + charset: NOK and should remain NOK

**Comment by Xhoenix** [comment]
Btw, why bother? Browsers won't make the mistake of adding a semicolon, unnecessarily.

**Comment by dune73** [comment]
You bet.

6 entries over the course of 30 days with the following UA:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

```

**Comment by Xhoenix** [comment]
```
"!@rx ^[\w/.+*-]+\s?;?\s?(?:(?:action|boundary|charset|component|start(?:-info)?|type|version)\s?=\s?['\"\w.()+,/:=?<>@#*-]+)*$"
```

Well then, I came up with this temp. fixup for rule 920470, if you need it. I still think it's unnecessary, though.

**Comment by Xhoenix** [comment]
> You bet.
> 
> 6 entries over the course of 30 days with the following UA:
> 
> ```
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
> ```
> 
> All different IPs.

This doesn't change anything as using real UAs is *pretty* common amongst hackers, and I myself had used many times.

**Comment by dune73** [comment]
OK. You win.

I thought this was legitimate behavior / expression of a bug in that browser. But your question made me look at the sessions of these IP addresses and they all have a similar pattern (exploring the site very fast, not reading its content). Then they do the submission exactly 3 times. Then they leave (or get banned by fail2ban).

This means, whatever these clients are doing, they are not legitimate users.

I'm closing the isse.
