### ISSUE TITLE
CRS Sandbox: Unable to collect audit log for transaction

### ISSUE THREAD

**Issue by favroom** [coreruleset/coreruleset#3389]
### Describe the bug

When running the examples from the CRS Sandbox documentation page, for each example "Unable to collect audit log for transaction ..." is returned.

### Steps to reproduce

I ran the examples on macOS 14.1.1 with Bash. e.g.:
bash-3.2$ curl -H 'x-format-output: txt-matched-rules-extended' https://sandbox.coreruleset.org/?file=/etc/passwd

### Expected behaviour

Response as described in the documentation

### Actual behaviour

An error is returned. e.g.:
{"error": "Unable to collect audit log for transaction ZWSV7gxvFLLyobMsYX53WAAAAJM"}bash-3.2$

<img width="820" alt="Scherm­afbeelding 2023-11-27 om 14 13 59" src="https://github.com/coreruleset/coreruleset/assets/10923053/291988df-8767-44a6-b796-03de808be776">

### Your Environment

macOS 14.1.1 with Bash.
CRS Sandbox on:
https://sandbox.coreruleset.org

**Comment by fzipi** [comment]
@favroom Should be working now. Can you try and let us know?

**Comment by airween** [comment]
Closed as completed.
