### ISSUE TITLE
Problematic word boundary match in 932* rules

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3401]
The 932* rules, such as 932237 for example, use a word boundary match to ensure that "something" follows a command word. At a word boundary, two adjacent tokens must not both match `\w` and `\W`, i.e., one must be a word token and the other must not. This means that "something" must be a word token if the previous token was a space, redirect, etc. If "something" is not a word token, such as the dash character, then the word boundary match will fail.

Example: `some-command --help` would not match a search for `some-command`.

A possible solution to this problem might be to replace the word boundary match `\b` with `\S`.

This issue was discovered in #3394 by @EsadCetiner.

**Comment by theseion** [comment]
@theMiddleBlue Any thoughts on this one?

**Comment by theseion** [comment]
True, that kind of thing should be caught by other rules though right? So `set --help` would not be blocked but `${IFS}` would be.

**Comment by theMiddleBlue** [comment]
Yes, absolutely! Apologies for the late response!
