### ISSUE TITLE
The http request contains html source code, which is easily detected by waf and triggers multiple CRITICAL rules. Can I just disable them all? Does the official suggest that I modify the rules?

### ISSUE THREAD

**Issue by mamahaha125** [coreruleset/coreruleset#3455]
When I visit some websites related to code work, it is easy to be intercepted by WAF because these behaviors trigger at least 7 or more rules.for example...

-----------------------------22580119949290
Content-Disposition: form-data; name="steps"

<p>
	<br />
</p>
<p style="background-color:#FFFFFF;">
	IP<br />
127.0.0.1
</p>
<p style="background-color:#FFFFFF;">
	<br />
</p>
<p style="background-color:#FFFFFF;">
</p>
<p style="background-color:#FFFFFF;">
	<br />
version<br />
v3.3.15<br />
<br />
code<br />
</p>
<p style="background-color:#FFFFFF;">

</p>
<p style="background-color:#FFFFFF;">
</p>
<p style="background-color:#FFFFFF;">
	<img src="/file/d-26102.png" alt="" />
</p>
<p style="background-color:#FFFFFF;">
	<br />
</p>
<p style="background-color:#FFFFFF;">
	<br />
</p>
<p style="background-color:#FFFFFF;">
	<br />
</p>
-----------------------------22580119949290
Content-Disposition: form-data; name="comment"

**Comment by M4tteoP** [comment]
Hi @mamahaha125,

Please use our false positive issue template in the future (provided by default). This ensures that we have all the required information in a standard format, making the process of triaging issues faster and simpler. In this context, it would be great to know at least the CRS version you are using, the rules that have been triggered, and related payloads to reproduce it.

> Can I just disable them all?

As a general guideline, it is not advisable to just disable rules, but rather write exclusion rules to tune away the false positives such as removing specific arguments from the rule, or disabling the rule also for specific paths.
You can rely on the [False positive and tuning doc](https://coreruleset.org/docs/concepts/false_positives_tuning/) and on this tuning tutorial: https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/.
Also, you might find useful to take a look at this issue: https://github.com/coreruleset/coreruleset/issues/3441. It comes with a multipart request that generates FPs and an example of an exclusion rule to tune away a specific argument 

> Does the official suggest that I modify the rules?

Directly modifying the rules [is discouraged](https://coreruleset.org/docs/concepts/false_positives_tuning/#directly-modifying-crs-rules) compared to writing and maintaining exclusions rules.

**Comment by azurit** [comment]
@mamahaha125 Ping.
