### ISSUE TITLE
Change 932237 to phase 1 

### ISSUE THREAD

**Issue by EsadCetiner** [coreruleset/coreruleset#3458]
### Motivation

932237 is currently set to phase 2, but the rule only inspects the user agent and referrer header and not anything within the request body. Changing this to phase 1 will slightly improve performance,

### Proposed solution

Change the rule to phase 1 for improved performance, just like how 932239 is set to phase 1.

### Alternatives

N/A

### Additional context

I discoverd this issue while working on #3394

**Comment by dune73** [comment]
Thanks for creating this issue.

**Comment by fzipi** [comment]
We didn't address it yet, right? @EsadCetiner do you want to push a PR for this move?

**Comment by EsadCetiner** [comment]
@fzipi if there's nobody that disagrees, I'm happy to open a PR.

**Comment by EsadCetiner** [comment]
I've open a PR here: https://github.com/coreruleset/coreruleset/pull/3570
I noticed a few more rules that inspect only the headers at phase 2 so I've changed those as well

**Comment by fzipi** [comment]
Awesome! 🚀
