### ISSUE TITLE
Regression test badge for older releases can become inactive

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3496]
# Original issue description
The regression test badge for 3.2 (in the readme) is no longer active. To reactivate it, we probably need to add a manual trigger, so that we can run the workflow on demand. GH only supports scheduled builds on the main branch.

# Update
The issue remains the same for supported older versions.

**Comment by fzipi** [comment]
Do we need to solve this now that we are phasing our support for v3.2?

**Comment by dune73** [comment]
I'd say we kick it tomorrow.

**Comment by theseion** [comment]
Agreed. This will still come back for older releases at some point, so let's keep this issue open.

**Comment by theseion** [comment]
Done.

**Comment by fzipi** [comment]
We still want to do this? I can push an update if needed. But probably removing the badge will be the best.

We need to figure this out for v3.3 though

**Comment by theseion** [comment]
TBH, I don't think my original assessment was correct. Let's close this.
