### ISSUE TITLE
Finish updating the changelog file for the v4 release

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#3538]
We need to finish updating the changelog file for the 4.0 release.

### Proposed solution

Everything listed under 'FIXME' needs integrating into the main 4.0 release notes section, using the new style.

**We are also missing release notes for several 3.3.x releases.** This needs to be fixed before the v4 release.

**Comment by dune73** [comment]
I'm happy to do the integrating and the reordering, integrating the pending changes and the missing 3.3.x stuff, if you guys can write the stuff under FIXME following the new style.

**Comment by RedXanadu** [comment]
That makes sense.

@theseion Shall we work on a common branch for this? I'll start work on one shortly (but if you can think of a more sensible approach then just tell me :grinning:)

**Comment by theseion** [comment]
Yes, a common branch should be fine with only two people on it.

**Comment by RedXanadu** [comment]
@dune73 We finished the lines under the FIXME section. Merged!

**Comment by fzipi** [comment]
Closing after merge.
