### ISSUE TITLE
user cannot upload files

### ISSUE THREAD

**Issue by nuroji** [coreruleset/coreruleset#3554]
Please provide a solution, why when I apply the OWASP modsecurity  to the web server, the user cannot upload files

**Comment by airween** [comment]
Hi @nuroji,

please provide more details about your issue. It would be nice to fill [the issue template](https://github.com/coreruleset/coreruleset/issues/new?assignees=&labels=%3Aheavy_plus_sign%3A+False+Positive&projects=&template=01_false-positive.md&title=) (now you should copy the text in the textarea and insert here, then change the content).

Without that, we can help you.

**Comment by dune73** [comment]
Closing this.
