### ISSUE TITLE
False positive? 

### ISSUE THREAD

**Issue by le0np** [coreruleset/coreruleset#3556]
Hello there, 

I'm just contacting you about a potential false positive triggered by one of the ModSecurity rules.

In our logs, we've observed instances where ModSecurity has flagged a rule (Rule ID: 942131) as triggering certain requests. However, upon closer inspection, it appears that the data being flagged does not constitute a security threat, or at least it does not look like SQL injection, but rather JSON in hexadecimal encoding. The rule seems to be incorrectly identifying benign traffic as malicious.
 
Could you please review this detection and provide guidance on how to address it? If it is indeed a false positive, I would appreciate any advice on how to adjust the ruleset to prevent similar occurrences in the future.

Here's a sample log entry for reference:
```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)[\"'`][\s\v]*?(?:x?or|div|like|between|and)[\s\v]*?[\"'`]?[0-9]|\x5cx(?:2[37]|3d)|^(?:.?[\"'`]$|[\"'\x5c`]*?(?:[\"'0-9`]+|[^\"'`]+[\"'`])[\s\v]*?(?:and|n(?:and|ot)|(?:xx?)?or|div|like|between|\|\| (403 characters omitted)' against variable `REQUEST_COOKIES:SL_C_23361dd035530_SID' (Value: `{"b36a7261765f078b10d600dcb700fcd213caf111":{"sessionId":"4rlzi5FBLH_irf2U-Kb-5","visitorId":"JaTXwT (18 characters omitted)' ) [file "/etc/nginx/modsec/conf.d/../owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "970"] [id "942330"] [rev ""] [msg "Detects classic SQL injection probings 1/3"] [data "Matched Data: -5\x22,\x22v found within REQUEST_COOKIES:SL_C_23361dd035530_SID: {\x22b36a7261765f078b10d600dcb700fcd213caf111\x22:{\x22sessionId\x22:\x224rlzi5FBLH_irf2U-Kb-5\x22,\x22visitorId\x22:\x22JaTXwTomDiRgm7PEjI3Aj\x22}}"] [severity "2"] [ver "OWASP_CRS/4.0.0-rc1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [tag "paranoia-level/2"] [hostname "82.2.134.13"] [uri "/online/somefile.php"] [unique_id "170681577249.691781"] [ref "o77,6v221,118t:urlDecodeUni"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:BLOCKING_INBOUND_ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/modsec/conf.d/../owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "176"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "0"] [ver "OWASP_CRS/4.0.0-rc1"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "82.2.134.13"] [uri "/online/somefile.php" [unique_id "170681577249.691781"] [ref ""]
```

* CMS: Drupal v.8.7.1
* Paranoia level setting: PL2
* ModSecurity version: ModSecurity-nginx v1.0.3
* OWASP_CRS: 4.0.0-rc1
* Web server: Nginx/1.20.1
* Operating System and version: Rocky Linux 8.9

**Comment by airween** [comment]
Hi @le0np,

thanks for reporting.

It seems like this is definitely a false positive match.

Coreruleset has a very great documentation about how to handle the false positives, see [this link](https://coreruleset.org/docs/concepts/false_positives_tuning/#rule-exclusions).

I think after you read that part, you will create something similar in your `/etc/nginx/modsec/owasp-modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`:

```
SecRule REQUEST_URI "@beginsWith /online/somefile.php" \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveTargetById=942330;REQUEST_COOKIES"
```
or something similar. Please note that this exclusion contains the URI you given in the log.

Please let me know if we can help anything else.

**Comment by airween** [comment]
> thank you for your quick answer... the question is how safe is to whitelist a double-quotes symbol in the COOKIES?

The problem is not the double quoted symbols.

> Do I understood it correctly, that Drupal (or whatever is using it) SHOULD NOT use double-quotes in the cookies? Or is it a common practice?

I'm not sure about that - see the [regex explanation](https://regex101.com/r/jVRyqw/1). 

I mean using double quoted cookies aren't problematic. In this case the subject (the JSON encoded cookie itself) has a sub-string which triggered the rule. Perhaps we have to analyze it why.

> We can easily whitelist this, thanks.. the question is -- should we? We're not sure.

I should do that. The given example creates the exclusion only against the affected URI, only for the `REQUEST_COOKIES` and excludes only that rule. And it's a Drupal, so if it uses that cookie, I'm almost sure the framework handles it correctly.

The rule is on [PL2](https://coreruleset.org/docs/concepts/paranoia_levels/#description-of-the-four-paranoia-levels), which means is a bit more strict than a "simple" protection.

**Comment by dune73** [comment]
I think you are on good tracks doing a rule exclusions here. Chances are Drupal knows what they are doing with cookies.

**Comment by prghix** [comment]
Thank you both!

Created a whitelisting rule + set-up the monthly contribution to the project.

**Comment by dune73** [comment]
Thank you @prghix.

I do not understand the "monthly contribution". Are we talking financial donation?

**Comment by prghix** [comment]
> Thank you @prghix.
> 
> I do not understand the "monthly contribution". Are we talking financial donation?

Sorry, of course I did mean financial contribution (through that Stripe thing you have on OWASP website).

Also, we'll try to provide debug when possible... but not sure how useful we'll be really :)

**Comment by dune73** [comment]
This is super nice. We rarely hear of people donating to OWASP because of our support. Thank you very much.

Any help is appreciated!
