### ISSUE TITLE
Why use lowercase and (?i) simultaneously in the rules?

### ISSUE THREAD

**Issue by mamahaha125** [coreruleset/coreruleset#3576]
### Describe the bug

942150

### Steps to reproduce

```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i)\b(?:json(?:_[0-9A-Z_a-z]+)?|a(?:bs|(?:cos|sin)h?|tan[2h]?|vg)|c(?:eil(?:ing)?|h(?:a(?:nges|r(?:set)?)|r)|o(?:alesce|sh?|unt)|ast)|d(?:e(?:grees|fault)|a(?:te|y))|exp|f(?:loor(?:avg)?|ormat|ield)|g(?:lob|roup_concat)|h(?:ex|our)|i(?:f(?:null)?|if|n(?:str)?)|l(?:ast(?:_insert_rowid)?|ength|ike(?:l(?:ihood|y))?|n|o(?:ad_extension|g(?:10|2)?|wer(?:pi)?|cal)|trim)|m(?:ax|in(?:ute)?|o(?:d|nth))|n(?:ullif|ow)|p(?:i|ow(?:er)?|rintf|assword)|quote|r(?:a(?:dians|ndom(?:blob)?)|e(?:p(?:lace|eat)|verse)|ound|trim|ight)|s(?:i(?:gn|nh?)|oundex|q(?:lite_(?:compileoption_(?:get|used)|offset|source_id|version)|rt)|u(?:bstr(?:ing)?|m)|econd|leep)|t(?:anh?|otal(?:_changes)?|r(?:im|unc)|ypeof|ime)|u(?:n(?:icode|likely)|(?:pp|s)er)|zeroblob|bin|v(?:alues|ersion)|week|year)[^0-9A-Z_a-z]*\(" \
    "id:**942150**,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni,t:lowercase,\
    msg:'SQL Injection Attack: SQL function name detected',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/152/248/66',\
    tag:'PCI/6.5.2',\
    tag:'paranoia-level/2',\
    ver:'OWASP_CRS/4.0.0-rc2',\
    severity:'CRITICAL',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.inbound_anomaly_score_pl2=+%{tx.critical_anomaly_score}'"
```

### Your Environment

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:

**Comment by theseion** [comment]
While it's certainly not great, why do you think it's a bug?

**Comment by Xhoenix** [comment]
Hello @mamahaha125, the (?i) was added during Regex Assembly transition in CRS. While doing lowercase twice is not a bug, this do need to be fixed.

**Comment by azurit** [comment]
Doing the same thing twice (for no reason) would I, personally, call a bug. It's a thing affecting performance and it needs to be fixed.

**Comment by theseion** [comment]
I agree that it needs to be fixed. I would consider this a "bug" if it would alter the expected behaviour, which is not the case. My suggestion: we close this issue and open a new one to implement a new lint rule that detects this situation. Then we clean up all the rules in one sweep.

**Comment by mamahaha125** [comment]
> I agree that it needs to be fixed. I would consider this a "bug" if it would alter the expected behaviour, which is not the case. My suggestion: we close this issue and open a new one to implement a new lint rule that detects this situation. Then we clean up all the rules in one sweep.

I agree close this issue, but I believe that this behavior will affect performance, so it still needs to be addressed

**Comment by theseion** [comment]
You are not wrong, it does have an impact on performance. However, there are many other things in CRS that affect performance and have a much bigger impact. You would probably not even be able to measure the difference if you removed `lowercase` from a single rule.

**Comment by airween** [comment]
Just for the record, the mentioned rules were modified, the `t:lowercase` actions were removed in #3585. @franbuehler extended the `rules-check.py` script, we do not allow any rule which uses `@rx` with `(?i)` modifier, and has `t:lowercase`, see #3584.
