### ISSUE TITLE
Lint rule to check for unnecessary `lowercase` transformations

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3579]
Most of our regular expressions use the case flag to make the expression case insensitive (`(?i)`). As reported in #3576, some rules also use a `lowercase` transformation, which is unnecessary if the regular expression ignores case anyway.

I think we could benefit from a new lint rule that checks for this. Then we could clean up all affected rules.

**Comment by fzipi** [comment]
Can we do something at generation time using crs-toolchain?

**Comment by airween** [comment]
It's easy to add to [crs-rule-check](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check) - which is already part of CI workflow.

**Comment by theseion** [comment]
@franbuehler is already working on it.

**Comment by franbuehler** [comment]
I was thinking of fixing this in https://github.com/coreruleset/coreruleset/blob/main/util/crs-rules-check/rules-check.py.
Then it would be added in this linting step: https://github.com/coreruleset/coreruleset/blob/main/.github/workflows/lint.yaml#L34

Why `crs-toolchain`?

**Comment by airween** [comment]
I don't know that `crs-toolchain` is able to process the operators, their arguments and/or rule actions. `crs-rule-check` is able.

**Comment by fzipi** [comment]
These are two different things:
- crs-rule-check will prevent rules to be committed with failing checks. This is this work.
- crs-toolchain should be able to warn when generating regexes. crs-toolchain doesn't care about operators arguments or rule actions. But can tell when you are using the `i` flag, and when a line has a group like `[A-Z]`.

**Comment by theseion** [comment]
@fzipi https://github.com/coreruleset/crs-toolchain/issues/113
