### ISSUE TITLE
 Monthly Chat Agenda April 2024 (2024-03-01 and 2024-04-15)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3636]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2024-04-01, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2024-04-15. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* [FIXME](FIXME)

#### Rules

* FIXME: Please fill in

#### CRS Sandbox

* #3609 - A fix is working locally but haven't been pushed because of container hiccups.

#### Security

* No news on this front.

#### Plugins

* FIXME: Please fill in

#### Documentation and Public Relations

* We are working on a new version for the website.

#### Project Administration and Sponsor relationships

* FIXME: Please fill in

#### Tools

* crs-toolchain version 2.2.0 with fixes available.

#### Testing incl. Seaweed and many future plans

* No updates on this front.

#### Containers

* We are testing the Alpine Apache image using the CIS Benchmark for Apache
* Now apache and nginx images run using unprivileged users

#### CRS Status Page

* No progress

## Project discussions and decisions

* [#3623](https://github.com/coreruleset/coreruleset/issues/3623) -> do we want to handle this long accept-encoding header in CRS and allow a value of 100 instead of 50 OR do we say that the user has to write an exclusion rule for this exotic use-case?
* release policy - we need to update the existing policy to reflect what we are pushing now.
* Azurit has a series of additional plugins he wants to bet listed or made official. How do we go about this in an effective manner?
* Hardening of the Apache Alpine docker container according to CIS benchmark (see https://docs.google.com/document/d/1Li2LNSWXSAKOHr5VmO0UgEyMsFQO-Cb915S69GiJ1Lo/edit) 

### PRs that have been merged since the last meeting

* #3626
* #3627
* #3625
* #3621
* #3622
* #3617
* #3620
* #3618
* #3619
* #3615
* #3614
* #3613
* #3612
* #3601
* #3606
* #3604
* #3600
* #3599
* #3602
* #3598
* #3485

We merged 21 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2637
* #3292
* #3635
* #3595
* #3450

* As of Monday, we have FIXME open issues.
* As of Monday, we have FIXME open pull requests.

## Separate 2nd Meeting (Monday, 2024-FIXME)

* https://github.com/coreruleset/coreruleset/pull/3646
* https://github.com/coreruleset/coreruleset/pull/3650
* https://github.com/coreruleset/coreruleset/issues/3644
* CIS Benchmark for Apache Docker Container

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by fzipi** [comment]
## Decisions April 1

Accept-encoding length
🔵 Decision: looks like going up to 100 will solve the problem reported, and won't break anything. So we decided to go 100.

Release Policy
🔵 Decision: @fzipi will create a new drive document so we can start collaborating on a policy document.

**Comment by franbuehler** [comment]
## Decisions April 15

**OWASP summit / CRS retreat**
🔵 Decision: CRS would participate the official OWASP summit as a project. We hope for some exchange with other projects, but we really want to work on CRS as productively as possible.

**Mozlila User Agent**
🔵 Decision: We want to block this. We don't see it as legitimate.

x
🔵 Decision: y
