### ISSUE TITLE
Rule #942100 PL1 SQL Injection Attack Detected via libinjection

### ISSUE THREAD

**Issue by rahulthackkar** [coreruleset/coreruleset#3672]
### Description
I have one feature that allows search in products, I tried with my actual product url which my client uses, I got SQL injection error. 

### How to reproduce the misbehavior (-> curl call)
`curl -H "x-format-output: txt-matched-rules" 'https://sandbox.coreruleset.org?q=bunting-(epson-10-color-quality-print)/'
`

### Your Environment

* CRS version (e.g., v3.3.4): v3.3.2
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6): 2.9.5
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): Apache 2.4.52
* Operating System and version: Ubuntu 22.04

### Confirmation

- [x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by Xhoenix** [comment]
Hi @rahulthackkar,

Thanks for submitting and sorry for your inconvenience.

Unfortunately, you are facing a false positive in the LibInjection library that we are leveraging. You are not the first to report such an issue and we are also aware that LibInjection has become largely unmaintained, so you are a bit at a loss here.

Instead, you need to help yourself by writing one or more rule exclusions that are specific to your setup.

If you are not familiar with this technique then take a look at the [tutorial at netnea](https://www.netnea.com/cms/apache-tutorials/), specifically [this tutorial](https://www.netnea.com/cms/apache-tutorials/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/) that covers handling false positives.

Please note that we also provide rule exclusion packages for selected off-the-shelf software at Paranoia Level 1 and Paranoia Level 2. These can be activated by editing `crs-setup.conf` or by enabling them on the platform you are using.

CRS Dev-on-Duty

**Comment by rahulthackkar** [comment]
Hi @Xhoenix ,

Thanks for your response.

I know I can exclude rules, but here what should I do? as this is one example case where I need to disable this rule, but there may be lots of places where I should allow such pattern(even I don't have all those listed), as solution is big one, and I don't know from where that type of data can be sent in request (get / post).

So disabling that rule will compromise security, and writing exclusions based on URI/parameter is difficult for me as I am not sure from where and in which param, I will get these data.

I am stuck here, as only enabling minimum configuration (PL 1) won't be sufficient.

Your views / suggestions are appriciable.

**Comment by azurit** [comment]
@rahulthackkar You need to write an exclusion rule based on your logs and exclude that rule everywhere, where it is doing problems.

**Comment by renepupil** [comment]
@Xhoenix Is there a plan to get rid of "client9/libinjection" ?

**Comment by dune73** [comment]
No, there is no such plan. But a desire.

With so many other false positives solved, the libinjection rules in CRS now amount to one of the largest sources of false positives at PL1 and since we can not do anything about it, we would love to replace it since it is not actively maintained and we do not have the resources to take it under our wings.
