### ISSUE TITLE
Rule 930110 block FormData request uploading image.

### ISSUE THREAD

**Issue by swotiendang** [coreruleset/coreruleset#3710]
![2024-05-21_161453](https://github.com/coreruleset/coreruleset/assets/147467559/bf467e3a-6a85-45d1-b8c1-5bcd51bea1ad)
![2024-05-21_153415](https://github.com/coreruleset/coreruleset/assets/147467559/7716cf0a-429a-4649-99b3-5f06c6bddf52)
![2024-05-22_090427](https://github.com/coreruleset/coreruleset/assets/147467559/e4557736-d73e-4bec-b2c8-06b52055385b)

Image with error:
![abc](https://github.com/coreruleset/coreruleset/assets/147467559/a124f120-f3a3-4936-b6df-138fe2deee16)

**Comment by theseion** [comment]
Thanks for the report @swotiendang. Unfortunately, I don't see any reason for why the rule triggered. The matched value appears to be in the multipart boundary / `Content-Disposition` header, but I don't see any `..`, which are required to trigger the rule.
Could you provide the output from Azure in textual format? And it would also help so see the exact request that you're sending (including image data, if it works for a very small image).

Which version of CRS are you using?

**Comment by swotiendang** [comment]
Hi @theseion  I think it's issue with Azure default ruleset, I check this repo latest version and microsoft version, they're mismatch, microsoft is using owasp 3.1. 

You can close this issue since it's Azure concern.

**Comment by theseion** [comment]
I'm aware that Azure uses an older version, but even in 3.1, the rule should only trigger when it sees `..`.

Feel free to reopen the issue if you want me to look into this further.
