### ISSUE TITLE
Rule 933120 FP on various SAML software products

### ISSUE THREAD

**Issue by tvdijen** [coreruleset/coreruleset#3723]
I'm not sure if this is a case of 'works as designed', but I work a lot with SAML-related software and I see two clear cases for rule `933120` that _to me_ are FPs:

1.  URLs containing `SAMLRequest=hVLLTiNBDPyVUd8n88**sMtP**...vBoUORLU%2BS%2F%2F%2Fd8h8%3` where the value is a base64 encoded string.

[SAML 2.0 standard](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) defines a fixed set of HTTP params that contain base64-encoded strings:
- SAMLRequest
- SAMLResponse
- Signature

Regardless of the product being used, the contents of these parameters would trigger this rule if a common word would occur in the base64-encoded string.

2.  One [SAML product](https://github.com/simplesamlphp/simplesamlphp) also defines a HTTP param called `AuthState`, which contains an encoded url from the SAML SP. One [commonly used SAML-product](https://github.com/openconext/openconext-engineblock) for such an SP standardizes their hostname on `engine`, leading to a HTTP param like `AuthState=https%3A%2F%2Fengine.example.org%2F`

This one is product-specific, but still very annoying. I'm hoping that with a better regexp this case could be fixed.

_Originally posted by @tvdijen in https://github.com/coreruleset/coreruleset/issues/3637#issuecomment-2133585381_

**Comment by franbuehler** [comment]
Thanks for submitting and sorry for your inconvenience.

I'd like to support you here, but unfortunately, you did not include enough information for us to actually help you.
Ideally, you would fill out the False Positive template. You can choose this template when creating a new issue.

Please provide the following if possible:

* Full alert message (ideally send us the full audit log of the request)
* Web server and version or the platform you are using
* ModSecurity version
* CRS version

ATTENTION: When submitting logs, please remove all personal information like IP addresses, hostnames, passwords, etc.

We'll be happy to have a look afterwards.

CRS Dev-on-Duty

**Comment by tvdijen** [comment]
Ah, I think I wasn't given the FP-template option because I created the issue from a comment.
Will provide all the necessary details ASAP.

**Comment by franbuehler** [comment]
Oh, maybe. That's possible.
Thank you very much for providing the details.

**Comment by tvdijen** [comment]
Platform: Red Hat v8.9
Webserver: Apache 2.4.37
ModSecurity: 2.9.6
CRS: 4.3.0

**Comment by tvdijen** [comment]
[case_1.txt](https://github.com/coreruleset/coreruleset/files/15496545/case_1.txt)
[case_2.txt](https://github.com/coreruleset/coreruleset/files/15496546/case_2.txt)

**Comment by franbuehler** [comment]
Thank you for the details. I have to investigate.

1st curl call (`SAMLRequest=mhXNy9pMlFhTjBlRkkzSkpia1Y2cSMtPEE9PTwvc2FtbDpBdHRyaWJ1dGVWYWx1ZT48L3NhbWw6QXR0cmlidXRlPjwvc2FtbDpBdHRyaWJ1dGVTdGF0ZW1lbnQ%2BPC9zYW1sOkFzc2VydGlvbj48L3NhbWxwOlJlc3BvbnNlPg%3D%3D`) leads to:


`"Warning. Matched phrase \"=\" at ARGS:SAMLRequest. [file \"/etc/modsecurity.d/owasp-crs/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf\"] [line \"130\"] [id \"933120\"] [msg \"PHP Injection Attack: Configuration Directive Found\"] [data \"Matched Data: smtp found within ARGS:SAMLRequest: mhXNy9pMlFhTjBlRkkzSkpia1Y2cSMtPEE9PTwvc2FtbDpBdHRyaWJ1dGVWYWx1ZT48L3NhbWw6QXR0cmlidXRlPjwvc2FtbDpBdHRyaWJ1dGVTdGF0ZW1lbnQ+PC9zYW1sOkFzc2VydGlvbj48L3NhbWxwOlJlc3BvbnNlPg==\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/4.3.0-dev\"] [tag \"modsecurity\"] [tag \"application-multi\"] [tag \"language-php\"] [tag \"platform-multi\"] [tag \"attack-injection-php\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/152/242\"]"`

2nd curl call:

`"Warning. Matched phrase \"=\" at ARGS:AuthState. [file \"/etc/modsecurity.d/owasp-crs/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf\"] [line \"130\"] [id \"933120\"] [msg \"PHP Injection Attack: Configuration Directive Found\"] [data \"Matched Data: engine found within ARGS:AuthState: _9aec1cb5c8b8d47bbd5bd0766b57cd7f7eca4919f2:https:/idp.example.org/module.php/saml/idp/singleSignOnService?spentityid=https%3A%2F%2Fengine.example.org%2Fauthentication%2Fsp%2Fmetadata&cookieTime=1716812552\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/4.3.0-dev\"] [tag \"modsecurity\"] [tag \"application-multi\"] [tag \"language-php\"] [tag \"platform-multi\"] [tag \"attack-injection-php\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/152/242\"]"`

**Comment by fzipi** [comment]
@franbuehler Any news on this one?

**Comment by franbuehler** [comment]
While investigating these false positive, I found this PR https://github.com/coreruleset/coreruleset/pull/3638 that should resolve at least the first false positive with smtp by adding a [word boundary to start of the directives](https://github.com/coreruleset/coreruleset/pull/3638/files#diff-1ebac01c66b07d1720aacf097183c796bcde107c177c55bbeb75bafde7e742ceR132).

@tvdijen: could you please confirm that you still have these false positives with the latest CRS release?

If yes, the linked PR is maybe not workind as intended and I have to investigate further.

**Comment by tvdijen** [comment]
#3638 was released in v4.3.0 and that's the version that I have tested with. It's still an issue.

**Comment by Xhoenix** [comment]
@fzipi in PR #3638 certain keywords causing FPs were added, which were earlier removed as can be seen [here](https://github.com/coreruleset/coreruleset/pull/3638/files#diff-e08f25b74f02a4dfc08f6dbba996d2d811c0d67324c72c63ea97dd57e10f5af5). We need to remove those words alongwith the word 'smtp' to fix this.

**Comment by fzipi** [comment]
@Xhoenix Can we do better than `@rx \b([^\s]+)\s*=` in that rule?

**Comment by Xhoenix** [comment]
I think it's okay.

**Comment by fzipi** [comment]
@tvdijen Fix #3863 should prevent to match base64 encoded strings, preventing these kind of FPs.

**Comment by tvdijen** [comment]
Ohh awesome! I will give it a try tomorrow!

**Comment by fzipi** [comment]
Excellent. This should make the 4.9.0 release in a couple of weeks.
