### ISSUE TITLE
932239 blocking Mozilla user-agents | Matched Data: ; PG found

### ISSUE THREAD

**Issue by isniukArte** [coreruleset/coreruleset#3725]
### Description
We have a lot of absolutely legal requests from real users with User-Agent like this:
`Mozilla/5.0 (Linux; Android 14; PGT-N19 Build/HONORPGT-N49; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36`

These requests are blocked by 932239 with reason:
`Matched Data: ; PG found within REQUEST_HEADERS:user-agent: Mozilla/5.0 (Linux; Android 14; PGT-N19 Build/HONORPGT-N49; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36`

### How to reproduce the misbehavior (-> curl call)
```
curl -X GET host.with.pl2.enabled -kL \
-H "User-Agent: Mozilla/5.0 (Linux; Android 14; PGT-N19 Build/HONORPGT-N49; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36" \
-H "Host: host.with.pl2.enabled"
```

### Your Environment

* CRS version (e.g., v3.3.4):4.3.0
* Paranoia level setting (e.g. PL1) :PL2
* ModSecurity version (e.g., 2.9.6): ModSecurity v3.0.12 (Linux)
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): ingress-nginx controller v1.10.0
* Operating System and version: n/a

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by franbuehler** [comment]
Thank you for your report and sorry for the inconvenience.
 
Indeed, this user-agent seems to be legit. I don't find an exact match, but two (or more) close examples, where we also find this `; PG` as part of the user-agent string:
* https://user-agents.net/string/mozilla-5-0-linux-android-13-pgt-n19-build-honorpgt-n49-wv-applewebkit-537-36-khtml-like-gecko-version-4-0-chrome-114-0-5735-196-mobile-safari-537-36-fb-iab-fb4a-fbav-422-0-0-26-76
* https://user-agents.net/string/mozilla-5-0-linux-android-13-pgt-n19-build-honorpgt-n49-wv-applewebkit-537-36-khtml-like-gecko-version-4-0-chrome-120-0-6099-144-mobile-safari-537-36-home-assistant-2023-12-4-11898-android-13-pgt-n19

I think this false positive could be resolved by adding `pg` or `pgt` (I'll have to find out) to the [file that handles user-agent exclusions](https://github.com/coreruleset/coreruleset/blob/main/regex-assembly/exclude/unix-shell-fps-useragents.ra) for rule 932230.
