### ISSUE TITLE
Monthly Chat Agenda June 2024 (2024‐06‐03 and 2024‐06‐17)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#3728]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2024-06-03, at 20:30 CEST. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2024-06-17. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

- Registration for the CRS Community Summit (June 24) open at https://pretix.eu/owasp-crs/community-summit-2024/

Blog posts that mention OWASP CRS  found by dev-on-duty, to be added for the next meeting (external references):

- https://twitter.com/20iUnlimited/status/1795804063444910383 (Link to https://www.20i.com/blog/modsec/): Rough overview, does not go into depth. Explains how to write a SecRule using an example.
- https://twitter.com/prod42net/status/1795272715131138419 - Link to https://dev.to/henri_sekeladi/whitelisting-specific-paths-on-modsecurity-3-with-owasp-rules-39d5 (rule exclusion example with a path)
- https://twitter.com/prod42net/status/1795272708898333151 -> Link to https://dev.to/henri_sekeladi/install-modsecurity-owasp-crs-for-nginx-webserver-on-centos-7-4fgo 
- https://twitter.com/prod42net/status/1795272706331406484 -> Link to https://dev.to/henri_sekeladi/install-nginx-with-modsecurity-3-owasp-crs-on-ubuntu-2204-5d6l (I think they use the bad NGINX by Ondrej PPA here -> should we say something? Also see https://owasp.slack.com/archives/CBKGH8A5P/p1706108836492279. Not entirely sure if I got this right)

#### Rules

* FIXME: Please fill in

#### CRS Sandbox

* A lot of work have been done to restore the Sandbox using the latest container versions
  - now it should be blocking using 403 back again
  - started the effort to bring back Coraza to the sandbox

#### Security

* New report by @azurit (R9V in the security tracker)

#### Plugins

* Finally we finished https://github.com/coreruleset/coreruleset/issues/3051
  * Official plugins are tested now.
* [Fake Bot Plugin](https://github.com/coreruleset/fake-bot-plugin)
  * marked as 'tested'
  * version 1.0.0 released
* [Google OAuth2 Plugin](https://github.com/coreruleset/google-oauth2-plugin)
  * version 1.0.0 released

#### Documentation and Public Relations

* FIXME: Please fill in

#### Project Administration and Sponsor relationships

* FIXME: Please fill in

#### Tools

* Nearly done with platform overrides
* Moved to Albedo in CRS and plugin tests
* Released v1.0.1 of go-ftw with support for the newest ftw-tests-schema
* Discussion to rename go-ftw

#### Testing incl. Seaweed and many future plans

* Seaweed is back reporting
  - need to fix multiple steps tests
  - waf must always return 200 OK to receive some attacks

#### Containers

* New version out with updated CRS v4.3.0

#### CRS Status Page

* Azure run failed and should be checked.

## Project discussions and decisions

* What will happen if we merge lfi-os-files.data and restricted-files.data into one file?
* https://github.com/coreruleset/coreruleset/issues/2127
* https://github.com/coreruleset/coreruleset/issues/3297
* https://github.com/coreruleset/coreruleset/issues/3239 Looks like we never got into the next steps needed here.
* Idea to rename go-ftw to Waft, Westy, Wtf ... 

### PRs that have been merged since the last meeting

* #3714
* #3719
* #3718
* #3706
* #3717
* #3716
* #3705
* #3687
* #3638
* #3699
* #3703
* #3646
* #3700
* #3645
* #3701
* #3707
* #3709
* #3708
* #3702

We merged 19 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #3727
* #3720
* #3713
* #3715
* #3712
* #3650

## Separate 2nd Meeting (Monday, 2024-06-17)

* #3733 
* #3721 - The string `Reserve Space (Room A)` triggers a FP on 942151. This rule checks for `function_name (`. Idea: to match `function_name (\d+`. BUT: is this common or do we say, you have to tune this in your installation.
* https://github.com/coreruleset/coreruleset/issues/2751
* https://github.com/coreruleset/coreruleset/issues/2686
* https://github.com/coreruleset/coreruleset/issues/2502
* https://github.com/coreruleset/coreruleset/pull/3713

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
## Decisions June 3rd

Blog post with NGINX by Ondrej PPA
🔵 CRS will write a blog post explaining the situation. We can then link this blog post when we get reports.

**Comment by franbuehler** [comment]
## Decisions June 17th

**mysql injection easy bypass with #**
🔵 already closed, was catched at PL2

**Rule 942151 "space (word)" false positive**
🔵 We'll wait for more fp reports here. Not common enough

**FPs with rule 953120 for gzip data**
🔵 Fzipi will help here

**Detect `$ {` PHP injection**
🔵

* https://github.com/coreruleset/coreruleset/issues/2502
* https://github.com/coreruleset/coreruleset/pull/3713
