### ISSUE TITLE
mysql injection easy bypass with #

### ISSUE THREAD

**Issue by filoips** [coreruleset/coreruleset#3733]
### Description

mysql use # as comment markup 

### How to reproduce the misbehavior (-> curl call)
on mutillidae buggy application on login screen
insert as username  : admin' # 
it will bypass rule : 942500

### Logs
```
---qTKOePCH---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:^([\d.]+|\[[\da-f:]+\]|[\da-f:]+)(:[\d]+)?$)' against variable `REQUEST_HEADERS:Host' (Value: `172.30.1.25:8080' ) [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "772"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "172.30.1.25:8080"] [severity "4"] [ver "OWASP_CRS/4.4.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "172.30.1.25"] [uri "/index.php"] [unique_id "171776332725.473114"] [ref "o0,16o0,11o11,5v56,16"]
```

### Your Environment
Mutillidae running on  linux server
reverse proxy nginx with modsecurity  
 

* CRS version : 4.4.0 
* Paranoia level setting  : PL2
* ModSecurity version (e.g., 2.9.6): 3.0.9-1+deb12u1
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): 1.22.1-9
* Operating System and version: debian 12

### Workaround
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i:'\s*(?:#\s*|--\s*))" \
    "id:942501,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni,\
    msg:'MySQL in-line comment detected',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'paranoia-level/1',\
    tag:'OWASP_CRS',\
    tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',\
    tag:'WASCTC/WASC-19',\
    tag:'OWASP_TOP_10/A1',\
    tag:'OWASP_AppSensor/CIE1',\
    tag:'PCI/6.5.2',\
    ver:'OWASP_CRS/3.2.0',\
    severity:'CRITICAL',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"
```

### Confirmation

[ X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by filoips** [comment]
OK thank you, I'll check my setup.

**Comment by filoips** [comment]
on github repository pattern is :
(?i)\)[\s\x0b]*?when[\s\x0b]*?[0-9]+[\s\x0b]*?then|[\"'`][\s\x0b]*?(?:[#\{]|--)|/\*![\s\x0b]?[0-9]+|\b(?:(?:binary|cha?r)[\s\x0b]*?\([\s\x0b]*?[0-9]|(?:and|n(?:and|ot)|(?:xx?)?or|div|like|between|r(?:egexp|like))[\s\x0b]+[0-9A-Z_a-z]+\()|(?:\|\||&&)[\s\x0b]*?[0-9A-Z_a-z]+\(

but it contains an error

[image: image.png]

I'm going to test in next days

**Comment by filoips** [comment]
Hello,
I Found the problem on my setup , I'm using old crs setup  with new rules
where some variables have different name.

Sorry for the misunderstood.

Regards

**Comment by airween** [comment]
Glad to see you could solve the problem - can we close this issue?

**Comment by filoips** [comment]
Yes, everything is fine.

Il Lun 10 Giu 2024, 13:19 Ervin Hegedus ***@***.***> ha
scritto:
