### ISSUE TITLE
Fix test 920370-1

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3745]
The comment on test 920370-1 says that it should trigger the rule but it doesn't. The comment also says that the PCRE limit is too low, which is wrong, the rule looks at the length of ARGS and doesn't use `@rx`.

- The test needs to be rewritten to trigger the rule
- The platform overrides for this rule can probably be removed

**Comment by azurit** [comment]
Problem with this test is that `ARG_LENGTH` is not set by default, so rule `920370` is not executed by default. This test needs modified `crs-setup.conf` to work.

**Comment by azurit** [comment]
Maybe it won't hurt if we use such crs-setup for all tests (rule `900320` needs to be uncommented).

**Comment by fzipi** [comment]
JFYI: we already have a way of enabling CRS variables at will by defining the variable to `1`, `true` or anything that is not empty. 

You can see an example here: https://github.com/coreruleset/modsecurity-crs-docker/blob/7e13621daf45689622ae598cefdc962273d9585f/src/opt/modsecurity/activate-rules.sh#L88

This same process can be used to check for additional rules that are similar to this case, so we don't need to exclude them from the tests.
