### ISSUE TITLE
 Monthly Chat Agenda July 2024 (2024‐07‐01 and 2024‐07‐15) #3728 

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#3753]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2024-07-01, at 20:30 CEST. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2024-07-15. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

Blog posts that mention OWASP CRS found by dev-on-duty, to be added for the next meeting (external references):

* [ModSec-Learn: Boosting ModSecurity with Machine Learning](https://arxiv.org/abs/2406.13547)
   * I did not check the linked [open source code](https://github.com/pralab/modsec-learn) and the [dataset ](https://github.com/pralab/http-traffic-dataset) yet. 
   * Direct link to [pdf](https://arxiv.org/pdf/2406.13547). 
   * Link to [tweet](https://twitter.com/realmofresearch/status/1806920302531871076).

#### Rules

* FIXME: Please fill in

#### CRS Sandbox

* FIXME: Please fill in

#### Security

* FIXME: Please fill in

#### Plugins

* FIXME: Please fill in

#### Documentation and Public Relations

* v4.4 release was deemed too small to require a blog post + announcements, social media, etc.
  * Probably requires a new policy, as the current release procedure document asks for publication of a blog post + mailing list announcements etc. for a release

#### Project Administration and Sponsor relationships

* FIXME: Please fill in

#### Tools

* go-ftw v1.0.3 released

#### Testing incl. Seaweed and many future plans

* Updates on Seaweed were presented at the CRS Summit
  - new version based on docker-compose and Golang for parsing results
* Support for platform platform specific tests using platform overrides has arrived. Includes improved schema for writing tests

#### Containers

* Issue with running Docker test containers in vanilla CRS repo following changes to make containers root-less. A solution has been found and is pending.

#### CRS Status Page

* Azure run failed and should be checked.

## Project discussions and decisions

* CRS November Developer summit updates
* Who wants to take on https://github.com/coreruleset/coreruleset/issues/3415 ?
* Should CRS get involved with a new edition of the OWASP WAF Evaluation Criteria (-> https://owasp.org/www-project-wafec/)

### PRs that have been merged since the last meeting

* #3740
* #3748
* #3747
* #3742
* #3739
* #3713
* #3712
* #3731

We merged 8 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #3735
* #3369
* #3720
* #3715
* #3650
* #3741
* #3734
* #3727

## Separate 2nd Meeting (Monday, 2024-07-15)

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

- Issue slot 1: #2841
- Issue slot 2: #3770
- Issue slot 3: Proposal to close security issue KK4
- 

### Other topics

- simplified support for schemas by using dedicated file extensions for tests and override files? (https://github.com/SchemaStore/schemastore/pull/3904)

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
## Decisions / discussions July 1st

#### CRS November Developer summit updates 
🔵 Information:
* Details will be published in the next few weeks. But it's best to reserve first full week in November.
* The place will be London and we will try to maximize the amount of days we spend together, as usual.
* This summit might bring together, for the first time, CRS, ModSecurity, and Coraza developers in a unique way
* No naming discussions ;-) 

#### Implement JavaScript prototype pollution detection
🔵

**Comment by fzipi** [comment]
In the meantime, there are news in the #project-wafec slack channel and has been reactivated primary by the lead of Manuel Welder and Sam Stepanyan.

**Comment by fzipi** [comment]
All relevant notes have been taken in the issues, closing.
