### ISSUE TITLE
Add lint rule to ensure use of `capture` action when numerical transaction registers are used

### ISSUE THREAD

**Issue by theseion** [coreruleset/coreruleset#3764]
The numerical transaction registers (`TX.0` through `TX.9`) are only filled when the `capture` action is used. If a rule uses any of the numerical transaction registers but does not use the `capture` action, it will see values set by other rules.

We should have a lint rule that prevents this situation from occurring.

**Comment by theseion** [comment]
@airween? ;)

**Comment by airween** [comment]
> @airween? ;)

Sure! :)

You mean something like this:

```
SecRule REQUEST_HEADERS:Referer "@rx ^[^#]+" \
   "id:932205,\
    ...
    capture,\
    ...
    chain"
    SecRule TX:0 "@rx ^..." \
        "capture,\
        t:none,\
        chain"
        SecRule TX:1 "@rx /" \
            ...
                "
```
so in this case the chained rule **before** uses `TX:N` **must** contain `capture`, right?

What if the rule is not chained, but uses `TX.0`, for example in `logdata`? I think the `capture` needs in that case too.

```
   ...
   logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
   ...
```

**Comment by theseion** [comment]
Yes. The `capture` action is **always** required. It can be misleading to look at the log because sometimes the desired information ends up in the variable by accident, simply because a different rule set the value previously.

**Comment by fzipi** [comment]
@airween Any progress here?

**Comment by airween** [comment]
Yes, I already made it. I need to test it and make a last check - I can send that soon.

**Comment by airween** [comment]
See #3825.

**Comment by airween** [comment]
Closing via #3825.
