### ISSUE TITLE
New rules cause response body inspection to be skipped even when SecDisableBackendCompression is On

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#3769]
### Describe the bug

In https://github.com/coreruleset/coreruleset/pull/3742 a handful of new rules have been introduced to skip response body inspection if the response is compressed. For responses with compression, this is done unconditionally. These new rules were part of the newest release `4.4.0`.

From what I can tell this does not take into account that [SecDisableBackendCompression](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v2.x%29#user-content-SecDisableBackendCompression) might be set to `On` to decompress and inspect response bodies.

### Steps to reproduce

Change `nolog` to `log` for the rules in question (e.g. `951010`) and access an endpoint where the response is sent with compression (e.g. httpbin endpoints `/deflate`, `/gzip`, or `/brotli`).

### Expected behaviour

When `SecDisableBackendCompression` is `Off` the rules should match and skip response body inspection.

When `SecDisableBackendCompression` is `On` the rules should _not_ match and inspect the response.

### Actual behaviour

The rules match for both `SecDisableBackendCompression` `Off` and `On`.

### Your Environment

* CRS version (e.g., v3.2.0): `4.4.0`
* Paranoia level setting: `all`

**Comment by fzipi** [comment]
@studersi Can you followup here?

**Comment by studersi** [comment]
Oh, I see what is going on now. I misunderstood the way `SecDisableBackendCompression` is working.

@azurit: You are correct, the body is not actually being decompressed.

Decompressing the response body is _not_ something `SecDisableBackendCompression` is intended to do, at all. The directive only removes the `Accept-Encoding` header from the request, such that the backend never compresses the response in the first place.

In my testing, I used endpoints that are specifically intended to test compressed responses. On these endpoints, the response is always compressed, independently of any `Accept-Encoding` request header. In other words, the directive `SecDisableBackendCompression` has no effect in these tests.

My bad, sorry for the confusion. I'll close this as there is nothing else to do :-)
