### ISSUE TITLE
Monthly Chat Agenda August 2024 (2024-08-05 and 2024-08-19)

### ISSUE THREAD

**Issue by airween** [coreruleset/coreruleset#3785]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2024-08-05, at 20:30 CEST. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2024-08-19. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

#### Blog Posts that mention CRS

* https://dev.to/motorbuy6/why-safeline-might-be-the-best-free-waf-23o7 (Twitter Post: https://x.com/prod42net/status/1822962701485662508)

#### Rules

* FIXME: Please fill in

#### CRS Sandbox

* FIXME: Please fill in

#### Security

* FIXME: Please fill in

#### Plugins

* FIXME: Please fill in

#### Documentation and Public Relations

* FIXME: Please fill in

#### Project Administration and Sponsor relationships

* We are in the process of getting new important sponsorship 🎉 More news in the next meeting.

#### Tools

* FIXME: Please fill in

#### Testing incl. Seaweed and many future plans

* No news on this area

#### Containers

* We released a new version with updated CRS version to 4.5.0 and apache to 2.4.62.

#### CRS Status Page

* There are some internal failures while running the Azure tests, need to review.

## Project discussions and decisions

* LTS release when?
  * We want integrators to be able to get on board with v4 so that v4 sees widespread use: currently they're all sticking with v3
* There was a survey internally about what leaders think about a Contributor License Agreement (CLA). CLA is a legal document that defines the terms under which a license is granted by a contributor to an open source project. It is used to protect a project from future legal issues. Please review the [Individual Contributor License Agreement (ICLA)](https://apache.org/licenses/icla.pdf) or, if applicable, the [Corporate Contributor License Agreement (CCLA)](https://apache.org/licenses/cla-corporate.pdf) from the Apache Foundation. Additional information related to open source contributor and/or copyright agreements can be found [here](https://yahoo.github.io/oss-guide/docs/resources/what-is-cla.html)  
* #3770: how much HTML do we want to detect?
* #3780: new rule or add to existing rule? -> performance overhead vs. rule complexity (and ReDos)
* #3573 

### PRs that have been merged since the last meeting

* #3784
* #3783 
* #3778 
* #3777 
* #3776 
* #3773 
* #3772 
* #3771 
* #3766 
* #3765 
* #3763 
* #3762 
* #3760 

## Separate 2nd Meeting (Monday, 2024-08-19)

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

- Issue slot 1: ...
- Issue slot 2: ...
- Issue slot 3: ...
- Brainstorm: if and which rule we would like a friendly CDN to test for us in terms of false positives. Ideally something that gets triggered by attacks from time to time (so not a super exotic rule that is never triggering, because attacks are so rare).

### Other topics

* FIXME: Please fill in

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by fzipi** [comment]
## Decisions July 5th

#### LTS Release
🔵 We will start adding issues with the things we think v4 LTS should have. A new label `v4 LTS` will be added to track them.
🔵 Regarding CLA, we don't have a clear position, as it is not a requirement now.

**Comment by franbuehler** [comment]
## Decisions Aug 19th

#### PR Jit https://github.com/coreruleset/coreruleset/pull/3780
🔵 @Xhoenix will test @theseion's extension to the cmdline processor as proposed in the PR.

#### Which rule do we want to test?
🔵 @fzipi will start a wiki page where we add our suggestions and comments to a list of rules

#### Info dev retreat
🔵 @fzipi just let us know that he'w working on getting all set for the developer retreat asap.
