### ISSUE TITLE
Windows 10 Defender detecting virus Backdoor:PHP/Dirteli.MTJ & Backdoor:PHP/Chopper.E!dha when downloading source v4.5.0.zip

### ISSUE THREAD

**Issue by MMirabito** [coreruleset/coreruleset#3791]
Dear all, is anyone else getting this when downloading [https://github.com/coreruleset/coreruleset/archive/refs/tags/v4.5.0.zip]
Could any of you let me know if this is real or a false positive, and what should I tell my IT security department?

Detected: **Backdoor:PHP/Dirteli.MTJ**  & **Backdoor:PHP/Chopper.E!dha**

### Describe the bug
Downloaded 
https://github.com/coreruleset/coreruleset/archive/refs/tags/v4.5.0.zip

### Steps to reproduce
When the download finished Win 10 Defender detected a virus 

### Expected behavior
Antivirus should not be triggered

### Actual behavior
![image](https://github.com/user-attachments/assets/a4998f9c-54ab-4c89-85fe-521c57f20df3)

of antivirus detection

### Your Environment
Win 10 Enterprise desktop

**Comment by MMirabito** [comment]
Quick update: **Defender** is flagging he following **YAML** text files:

- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933190.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933111.yaml
- tests/regression/tests/RESPONSE-955-WEB-SHELLS/955260.yaml
 
Thanks in advance for any guidance
max

![image](https://github.com/user-attachments/assets/851dcfdd-2b55-41f3-bb19-dd884ec8d5e1)

**Comment by theseion** [comment]
I see. @fzipi, could you create a new artefact for the current release called `coreruleset-rules-only-4.5.0.zip` with only the top level, "rules", and "plugins" directories and sign that?
We'll want to automate that for the next release, of course.

**Comment by RedXanadu** [comment]
How much burden would this be to maintain going forwards / indefinitely?

If it's a non-zero burden, I question whether we want to take it upon ourselves to work around faulty Microsoft software / a Microsoft false positive.

**Comment by theseion** [comment]
> - MS user reports issue to MS as a support problem, requests resolution
> There is no way that MS cannot handle security software that contains signatures of malicious traffic/code…
Not realistic, IMO.

> User self-serves and creates sanitised archive file for their own use, burden is not on CRS
Won't work, because the user cannot download any of our files

I don't think that it's a big deal to create these extra artefacts. We can easily automated that.

**Comment by fzipi** [comment]
I think it could be good to start having a rules only distribution, in contrast of a full "source" dist.

As Max said, it is easy to automate and will give some benefits.

We can try targeting 4.6.0 maybe.

**Comment by theseion** [comment]
@MMirabito, is 4.6.0 early enough for you? That should be next week, I guess @fzipi?

**Comment by fzipi** [comment]
Next week, exactly. Mon/Tue.

**Comment by RedXanadu** [comment]
For the record, I still think this is not a good idea. I do not believe Microsoft _cannot_ fix this issue, otherwise how can software like antivirus operate? :shrug: I do not think CRS should shoulder this responsibility.

**Comment by theseion** [comment]
These kinds of false positives by AV software are an age old problem. Yes, the issue lies with the AV software / OS vendor, but we also want our users to have access to our rules. Supplying this minimal package in addition isn't a big deal.

**Comment by theseion** [comment]
We haven't heard from OP since they opened the issue. I assume we've addressed the issue, so let's close this.

**Comment by mariosdimitradis** [comment]
@theseion 
I'm using also the coreruleset on a Ubuntu 20.04 Server and last week Microsoft Defender reports Virus on two files in this repository. Could you check that please? I'm using the latest release v4.6.0

Microsoft reports also that the files are not signed.

**Software: Backdoor:PHP/Dirtelti.MTJ**
SHA1: b42460e12e19f904858568037b9c6fbba4af60c5
SHA256: 829ac2ad20233fad47c056436bd528807e7dd200d30419fd64b97862e2aa7214
MD5: ada23138c1d27cbf010cba685f56a7a3
File: tests/regression/tests/RESPONSE-955-WEB-SHELLS/955260.yaml
 
**Software: Backdoor:PHP/Chopper.E!dha**
SHA1: 0be0ac6cda3602f4d9b1c69b7c0154078cd03061
SHA256: 4a8d05c406d87672d2129f530739e44098cd53e14707730dd337f23015338552
MD5: c444b5d9a6edba50d9df630a577d0730
File: tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933111.yaml

**Comment by fzipi** [comment]
Are you using the _minimal_ release? Because that is what the release is for.

**Comment by mariosdimitradis** [comment]
@fzipi No, I clone the repo, but switch now to the minimal release.

**Comment by fzipi** [comment]
Cloning won't help, sadly, as you will get the thing that's matching. Maybe report this to Microsoft also?

**Comment by HackingRepo** [comment]
I think the rules contain signature for the malware, I think i will open a pr for i test it since i use actually windows and see what is actually flagged when i have time

**Comment by HackingRepo** [comment]
i see 955260, Cannot be solved for others, patterns like eval and hacker and keep them just simple

**Comment by HackingRepo** [comment]
for 955260 cannot be fixed
