### ISSUE TITLE
Update security policy doc to reflect 4.6.0 release

### ISSUE THREAD

**Issue by gene1wood** [coreruleset/coreruleset#3804]
### Describe the bug

The security policy page in the GitHub repo : https://github.com/coreruleset/coreruleset/security/policy

should be updated to reflect the 4.6.0 CRS release today. I imagine by adding 4.6.0 and deprecating suport for 4.4.0

### Steps to reproduce

Visit https://github.com/coreruleset/coreruleset/security/

### Expected behaviour

It should list the 4.6.0 release and whether or not it's supported

### Actual behaviour

The most recent release listed is 4.5.0

**Comment by airween** [comment]
hi @gene1wood,

thanks for reporting, we will fix that soon.

Thanks again!

**Comment by airween** [comment]
Closing as completed via #3805.

Thank you again!
