### ISSUE TITLE
ModSecurity warns about 980170

### ISSUE THREAD

**Issue by KramNamez** [coreruleset/coreruleset#3820]
### Describe the bug

Rule 980170 always triggers a ModSecurity Warning about an unconditional match. The rule works as it is clearly intended to, so the warning is pointless.

### Steps to reproduce
Trigger the reporting rule, whether by setting a high reporting level or satisfying the conditions at lower levels.

### Expected behaviour

The rule triggers and reports the scores.

### Actual behaviour

ModSecurity warns about an unconditional match:
`ModSecurity: Warning. Unconditional match in SecAction.`

**Comment by RedXanadu** [comment]
Hi @KramNamez,

I was partly involved in implementing the new reporting logic. Please allow me to explain (if I can remember!) the rationale behind it.

Assuming you have a deployment with `tx.reporting_level` set however you like (see `crs-setup.conf` for the variable setting rule and the documentation for this config option) then rule 980170 will either trigger or not as needed.

We use a series of SecRules in `RESPONSE-980-CORRELATION.conf` to determine whether or not the reporting rule 980170 should be skipped.

If you set `tx.reporting_level` to **0** then the reporting rule should never trigger and will not write to the log (if that is what you want).

If your request is simply that the engine should not write the string "Warning." (as opposed to, maybe, "Info." or something similar) then you may want to raise that as a feature request on the [ModSecurity GitHub page](https://github.com/owasp-modsecurity/ModSecurity/). It is hardcoded into the engine via the `msc_alert` function that "Warning." is prepended to every log message by default, as far as I can see. That is simply how the engine functions.

Feel free to follow up if you have any further questions.

**Comment by KramNamez** [comment]
Ah, yes, then I will have to go to the ModSecurity Github.

I understand the logic of the rule and that's fine - we're using it and it contains the info we want, perfect. It is about the Warning, because technically, it's a rule that doesn't have a condition _itself_. That's ugly for logging, and I was hoping that CRS could suppress that warning for this rule, for example.

**Comment by dune73** [comment]
That's unfortunately entirely in the hand of the engine.
