### ISSUE TITLE
v3.3.6 release missing in v4 CHANGES.MD

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#3831]
### Describe the bug

v3.3.6 release notes are missing in the v4 version of `CHANGES.MD`.

### Actual behaviour

The v3 and v4 versions of `CHANGES.MD` have drifted slightly over the past releases (e.g. updated release notes in both the v3 and v4 branches, due to backports to v3 on the separate v3 branch.)

### What we should do to fix

1. Make sure that the v4 version has all the info of all releases (I think it's just 3.3.6 that's missing.)
2. Double/triple-check that nothing else is missing / no other drift with the v4 version of `CHANGES.MD`.

**Comment by LuckyyS0da** [comment]
Hello! I would like to work on this.

**Comment by dune73** [comment]
Thank you @LuckyyS0da

**Comment by fzipi** [comment]
Hi @LuckyyS0da ! Do you need anything for pushing this one?

**Comment by LuckyyS0da** [comment]
To be honest, I am new to open contributions and wanted to explore a bit and then landed on this. I somewhat understood the issue but don't know how to implement it.

**Comment by fzipi** [comment]
@LuckyyS0da No problem. You should take the text from the [changes file for v3.3.6](https://github.com/coreruleset/coreruleset/blob/v3.3/master/CHANGES.md#version-336---2024-08-27) and add them [here](https://github.com/coreruleset/coreruleset/blob/main/CHANGES.md#version-335---2023-07-18). You can do it just by pressing [here](https://github.com/coreruleset/coreruleset/edit/main/CHANGES.md) and then saving the changes. It will create a new branch for you, and then you create a new pull request. Easy!

**Comment by LuckyyS0da** [comment]
Thank you @fzipi 
I did like what you told me and created a pull request after adding the text to v4.0
