### ISSUE TITLE
Drop Apple resource forks from CRS 4 tarball

### ISSUE THREAD

**Issue by rainerjung** [coreruleset/coreruleset#3839]
THE CRS 4 Tarballs - at least the minimal ones for 4.4.6 and 4.4.7 - contain Apple resource fork files. On normal Unixes those appear as dot files, e.g. "._LICENSE". Each file and directory has such a shadow object. In addition unpacking teh tarballs produces a lot of warnings "tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'", probably one line for each resource fork.

I assume the tarballs have been created on MacOSX. Apple systems have a tendency to fill all file systems they can grab with such garbage files. They should not get distributed in the release artefacts. The artefacts for CRS 3 seem to not (yet?) contain the resource fork files.

Thanks!

Rainer

**Comment by dune73** [comment]
Thank you @rainerjung. And greetings. It's been a while.

**Comment by fzipi** [comment]
🤦 That was me, probably. Weird, I'm just using gnu tools. I'll clear those up.

Thanks for reporting!

**Comment by rainerjung** [comment]
Looks good to me, many thanks.
