### ISSUE TITLE
SQL operators can be one or more characters

### ISSUE THREAD

**Issue by Xhoenix** [coreruleset/coreruleset#3842]
Is there a reason for not using `[|&<>*\/%=^+-]+` in the following regex?

https://github.com/coreruleset/coreruleset/blob/a6036b984405798f5accec6a1fc5caaa90de46ac/regex-assembly/942520.ra#L15

**Comment by fzipi** [comment]
If it is an operator, w probably don't need more than three of these. Also, as we are using it in more than one place, probably it is better to extract them and use it in an include file, so at least we use the same everywhere.

Good find.

**Comment by fzipi** [comment]
I meant this rule and 942120, for example.

**Comment by Xhoenix** [comment]
@fzipi should I replace the corresponding PR for this with `{1,3}` instead of a `+`?

**Comment by fzipi** [comment]
Yes sounds more reasonable. But then the real refactor should come from the inclusion, right? 

Meaning: it doesn't matter too much because if we change it for all the operators in their right form, there is no need for "counting" 1..3 😄
