### ISSUE TITLE
No regression testing for `modsec3-nginx` ?

### ISSUE THREAD

**Issue by s3rj1k** [coreruleset/coreruleset#3843]
It seems that there is no regression testing for modsec3-nginx variant, is it intentional?

https://github.com/coreruleset/coreruleset/blob/main/.github/workflows/test.yml#L26

**Comment by airween** [comment]
Yes, it's intentional. We are working on overrides, because there are few differences in behavior of two engines (mod_security2 - which is the reference system of CRS - and libmodsecurity3). See #3369.

**Comment by s3rj1k** [comment]
@airween I see, thank you

**Comment by airween** [comment]
Sorry, it's already merged - then may be we should think it through again. Thanks for bringing it up!

**Comment by s3rj1k** [comment]
> Thanks for bringing it up!

No problem, running manually I still saw some failures for nginx

**Comment by airween** [comment]
> No problem, running manually I still saw some failures for nginx

Unfortunately I have to say that's normal.
 
> (please reopen if needed for tracking)

It would be a great help if you could share your experiences, eg: used versions (libmodsecurity3, Nginx, Nginx-connector, CRS and go-ftw version). And list of the failed tests.

You can share those here, next Monday we can discuss it.

And thanks again!

**Comment by airween** [comment]
And which rules were failed?

**Comment by s3rj1k** [comment]
> And which rules were failed?

(did not save test coverage output)

**Comment by airween** [comment]
Okay, no problem - thanks again for noticing!
