### ISSUE TITLE
Unnecessary use of `\d` in 942130 and 942131

### ISSUE THREAD

**Issue by Xhoenix** [coreruleset/coreruleset#3846]
Is there any reason why `[\d\w]` is used throughout the file, when `\w` is sufficient?

https://github.com/coreruleset/coreruleset/blob/0a2588e38bd75e26000c155cd788040f6411d4ab/regex-assembly/942130.ra#L27

**Comment by fzipi** [comment]
Probably not, and it can be removed. Also, that file can be rewritten to be way more succinct using regex-assembly constructs.

**Comment by fzipi** [comment]
@Xhoenix You can create a PR to solve this one if you want!

**Comment by Xhoenix** [comment]
Opened PR #3862.
