### ISSUE TITLE
rule id 942100 mark query separator as positive

### ISSUE THREAD

**Issue by abudawud** [coreruleset/coreruleset#3900]
### Description

Why this pattern  [Query Separator](https://sandbox.coreruleset.org/?ids=89--123--11) mark as SQLi ? or is there any way to tune this rule ?

### How to reproduce the misbehavior (-> curl call)

Use browser and visit `https://sandbox.coreruleset.org/?ids=89--123--11`

### Your Environment

Modsec sandbox

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses, passwords, domain names) from any logs posted.

**Comment by Xhoenix** [comment]
Hi @abudawud,

Thanks for reporting this. 
Unfortunately, you are facing a false positive in the LibInjection library that we are leveraging. You are not the first to report such an issue and we are also aware that LibInjection has become largely unmaintained, so you are a bit at a loss here. https://github.com/libinjection/libinjection

You can write an rule exclusion for your scenario, you can learn how to do so from here: https://coreruleset.org/docs/concepts/false_positives_tuning/

CRS Dev on Duty

**Comment by abudawud** [comment]
ok thanks @Xhoenix

**Comment by abudawud** [comment]
I have read the rule exclusion doc, but i still have no idea how to exlude this false positive without exluding all libinjection detection. Would you like to give me an idea to exlude all request match rule id 942100 that contain `--` separator ?

```ModSecurity: Warning. detected SQLi using libinjection. [file "/etc/nginx/modsec/crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "46"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: 1c found within ARGS:search[value]: 24--"] [severity "2"] [ver "OWASP_CRS/4.8.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [hostname "10.240.20.81"] [uri "/pembelian/saprotan_json"] [unique_id "173044172037.861498"] [ref "v3888,4"]```

i want to exlude by looking at data attribute: `data "Matched Data: 1c found within ARGS:search[value]: 24--`
May be like @rx data "Matched Data: 1c found.*--` or any other idea to exlude correctly ?

Thanks for your help

**Comment by Xhoenix** [comment]
You can adapt [this rule](https://coreruleset.org/docs/concepts/false_positives_tuning/#example-7-ctlruleremovetargetbyid) for your purpose, from the same link I gave you earlier.

**Comment by abudawud** [comment]
thanks, i got it.
i solved this false positive using above doc with regex match `^[0-9-]+$`
