### ISSUE TITLE
Update response rules settings and documentation to make it easier to switch off for preventing RFDoS

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#3943]
While at the developer retreat, we discussed the likelihood of RFDoS.

We decided to make it easier on the user by adding a variable to the `crs-setup.conf.example` to easily disable response rules.

👉 This variable will be kept *On* by default for the time being.

We must also add links to RFDoS and a better description.

**Comment by dune73** [comment]
Absolutely. And thanks for driving this.
