### ISSUE TITLE
Monthly Chat Agenda December 2024 (2024-12-02 and 2024-12-16)

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#3950]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2024-12-02, at 20:30 CET (CEST during summer in the Northern Hemisphere). That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2024-12-16. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* [OWASP announced](https://infosec.exchange/@owasp/113436841820652063) that load balancer vendor and [CRS integrator](https://www.skudonet.com/knowledge-base/howtos/waf-logs/) SKUDONET are now an OWASP "Silver Start-Up Corporate Supporter". We will reach them to say thank you!

* Blog post mentioning ModSecurity and the CRS: https://www.linuxjournal.com/content/fortifying-linux-web-applications-mastering-owasp-zap-and-modsecurity-optimal-security

#### Rules

* New release [v4.9.0](https://github.com/coreruleset/coreruleset/releases/tag/v4.9.0) brings a new variable for disabling response rules.

#### CRS Sandbox

* A new check for availability has been setup using cronitor.io

#### Security

* We have some new reports to address, in particular TR7-241111.

#### Plugins

* Dune73 is working on a new plugin named [Chaos Fortress](https://github.com/dune73/chaos-fortress-plugin) that can be used to slow down attackers by sending consistently random status codes and by delaying the response. It seems this makes automatic security scanners almost useless.

#### Documentation and Public Relations

* There is an open PR to update the documentation: https://github.com/coreruleset/documentation/pull/137

#### Project Administration and Sponsor relationships

* Google renewed their support! 🎉

#### Tools

* Go-ftw comes now with quantitative testing support! We have fun and interesting results in the developer retreat around this.
* We removed and will migrate useful tools that were part of the utils subdirectory.

#### Containers

* Updated to latest v4.9.0 release.

## Project discussions and decisions

* Release cadence (again). How impactful is to make monthly releases, now that we don't commit too many PRs? Does it make sense to switch to Quarterly releases, as it was proposed? _(AH: As was proposed by who? This was sold to the group as the way forwards, why the proposed turn-around? Why was this not discussed at Woburn?)_ FZ: this was questioned again by Jose Carlos Chávez in https://owasp.slack.com/archives/CBKGH8A5P/p1731943800556089, after Woburn.
* Do we need to have two meetings per month now that we don't have the bandwidth?

### PRs that have been merged since the last meeting

* #3949
* #3948
* #3947
* #3946
* #3945
* #3941
* #3944
* #3942
* #3927

We merged 9 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #3735
* #3925
* #3840
* #3813
* #3917
* #3901
* #3881
* #3720
* #3815
* #3780
* #3730

## Separate 2nd Meeting (Monday, 2024-12-16)

* We are cancelling the issues chat meeting and moving on to a new format.

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
# Decisions
- 🔵 #3926: theseion, dune73 and franbuehler will meet after xmas and talk about this topic
- 🔵
